/**
 * @file c2000_launchpad_boostxl.h
 * @brief SDPE hardware preset for Portable C2000 LaunchPad BOOSTXL Contract.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _MCU_BOARD_C2000_LAUNCHPAD_BOOSTXL_H_
#define _MCU_BOARD_C2000_LAUNCHPAD_BOOSTXL_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_c2000_launchpad_boostxl Portable C2000 LaunchPad BOOSTXL Contract
 * @{
 */

// Identification
#define C2000_LAUNCHPAD_BOOSTXL_ID "c2000_launchpad_boostxl"
#define C2000_LAUNCHPAD_BOOSTXL_SCHEMA "c2000_launchpad_boostxl_board"
#define C2000_LAUNCHPAD_BOOSTXL_NAME "Portable C2000 LaunchPad BOOSTXL Contract"

// Tags: boostxl, c2000, launchpad, portable

/*
 * Schema: Portable dual-site BOOSTXL resource contract used by the GMP C2000 LaunchPad reference application.
 */

// Parameter macros
/**
 * @brief Physical connector naming convention used by portable aliases.
 */
#define C2000_LAUNCHPAD_BOOSTXL_CONNECTOR_STANDARD "BOOSTXL physical pin aliases"

/**
 * @brief Nominal analog positions across the two BOOSTXL sites before board conflicts.
 */
#define C2000_LAUNCHPAD_BOOSTXL_ANALOG_INPUT_COUNT (16U)

/**
 * @brief Portable BOOSTXL PWM pair contract.
 */
#define C2000_LAUNCHPAD_BOOSTXL_PWM_PAIR_COUNT (6U)

/**
 * @brief Nominal J12/J13 encoder-header contract.
 */
#define C2000_LAUNCHPAD_BOOSTXL_EQEP_HEADER_COUNT (2U)

/**
 * @brief Common ADC trigger contract implemented by each board SysConfig.
 */
#define C2000_LAUNCHPAD_BOOSTXL_ADC_TRIGGER "EPWM1_SOCA"

/**
 * @brief Common control interrupt symbol implemented by the shared application.
 */
#define C2000_LAUNCHPAD_BOOSTXL_CONTROL_ISR "MainISR"

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _MCU_BOARD_C2000_LAUNCHPAD_BOOSTXL_H_
