/**
 * @file dioscuri_f280025c.h
 * @brief SDPE hardware preset for Dioscuri F280025C Six-Pair PWM Board.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _MCU_BOARD_DIOSCURI_F280025C_H_
#define _MCU_BOARD_DIOSCURI_F280025C_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_dioscuri_f280025c Dioscuri F280025C Six-Pair PWM Board
 * @{
 */

// Identification
#define DIOSCURI_ID "dioscuri_f280025c"
#define DIOSCURI_SCHEMA "dioscuri_f280025c_board"
#define DIOSCURI_NAME "Dioscuri F280025C Six-Pair PWM Board"

// Tags: c2000, clllc, dab, dioscuri, f280025c, six_pwm_pairs

/*
 * Schema: Dioscuri six-pair PWM, ADC, UART, timer and active-low gate-buffer resource model.
 * Vendor: GMP
 * Document: ctl/suite/dps_clllc/project/hw/LLC_Debug_Kit.pdf
 */

// Parameter macros
/**
 * @brief C2000 device name.
 */
#define DIOSCURI_CHIP "TMS320F280025C"

/**
 * @brief SysConfig source file.
 */
#define DIOSCURI_SYSCFG_FILE "ctl/suite/dps_clllc/project/f280025c_dioscuri/LLC_Kit_F280025.syscfg"

/**
 * @brief PWM outputs 1/2.
 */
#define DIOSCURI_PWM_PAIR1_BASE DIOSCURI_HW_PWM_PAIR1_BASE

/**
 * @brief PWM outputs 3/4.
 */
#define DIOSCURI_PWM_PAIR2_BASE DIOSCURI_HW_PWM_PAIR2_BASE

/**
 * @brief Reserved FSBB PWM outputs 5/6 (ePWM3).
 */
#define DIOSCURI_PWM_PAIR3_BASE DIOSCURI_HW_PWM_PAIR3_BASE

/**
 * @brief Primary PRI_P PWM outputs 7/8 (ePWM4).
 */
#define DIOSCURI_PWM_PAIR4_BASE DIOSCURI_HW_PWM_PAIR4_BASE

/**
 * @brief Reserved FSBB PWM outputs 9/10 (ePWM5).
 */
#define DIOSCURI_PWM_PAIR5_BASE DIOSCURI_HW_PWM_PAIR5_BASE

/**
 * @brief Primary PRI_N PWM outputs 11/12 (ePWM7).
 */
#define DIOSCURI_PWM_PAIR6_BASE DIOSCURI_HW_PWM_PAIR6_BASE

/**
 * @brief SN74LVC8T245 OE# GPIO.
 */
#define DIOSCURI_GATE_ENABLE_GPIO GPIO_ENABLE

/**
 * @brief OE# active level.
 */
#define DIOSCURI_GATE_ENABLE_LEVEL (0U)

/**
 * @brief OE# safe level.
 */
#define DIOSCURI_GATE_DISABLE_LEVEL (1U)

/**
 * @brief PWM-independent scheduler timer.
 */
#define DIOSCURI_TICK_TIMER_BASE CLLLC_TICK_TIMER_BASE

/**
 * @brief Datalink UART.
 */
#define DIOSCURI_UART_BASE UART_USB_BASE

/**
 * @brief Primary voltage ADC result base.
 */
#define DIOSCURI_PRIMARY_VOLTAGE_RESULT_BASE PRIMARY_VOLTAGE_RESULT_BASE

/**
 * @brief Primary voltage ADC SOC.
 */
#define DIOSCURI_PRIMARY_VOLTAGE_SOC PRIMARY_VOLTAGE

/**
 * @brief Primary current ADC result base.
 */
#define DIOSCURI_PRIMARY_CURRENT_RESULT_BASE PRIMARY_CURRENT_RESULT_BASE

/**
 * @brief Primary current ADC SOC.
 */
#define DIOSCURI_PRIMARY_CURRENT_SOC PRIMARY_CURRENT

/**
 * @brief Secondary voltage ADC result base.
 */
#define DIOSCURI_SECONDARY_VOLTAGE_RESULT_BASE SECONDARY_VOLTAGE_RESULT_BASE

/**
 * @brief Secondary voltage ADC SOC.
 */
#define DIOSCURI_SECONDARY_VOLTAGE_SOC SECONDARY_VOLTAGE

/**
 * @brief Secondary current ADC result base.
 */
#define DIOSCURI_SECONDARY_CURRENT_RESULT_BASE SECONDARY_CURRENT_RESULT_BASE

/**
 * @brief Secondary current ADC SOC.
 */
#define DIOSCURI_SECONDARY_CURRENT_SOC SECONDARY_CURRENT

// Logical exports
// pwm_pair1_base: DIOSCURI_PWM_PAIR1_BASE
// pwm_pair2_base: DIOSCURI_PWM_PAIR2_BASE
// pwm_pair3_base: DIOSCURI_PWM_PAIR3_BASE
// pwm_pair4_base: DIOSCURI_PWM_PAIR4_BASE
// pwm_pair5_base: DIOSCURI_PWM_PAIR5_BASE
// pwm_pair6_base: DIOSCURI_PWM_PAIR6_BASE
// gate_enable_gpio: DIOSCURI_GATE_ENABLE_GPIO
// tick_timer_base: DIOSCURI_TICK_TIMER_BASE
// uart_base: DIOSCURI_UART_BASE

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _MCU_BOARD_DIOSCURI_F280025C_H_
