/**
 * @file launchxl_f280049c.h
 * @brief SDPE hardware preset for LaunchXL-F280049C LaunchPad.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _MCU_BOARD_LAUNCHXL_F280049C_H_
#define _MCU_BOARD_LAUNCHXL_F280049C_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_launchxl_f280049c LaunchXL-F280049C LaunchPad
 * @{
 */

// Identification
#define LAUNCHXL_F280049C_ID "launchxl_f280049c"
#define LAUNCHXL_F280049C_SCHEMA "launchxl_f280049c_board"
#define LAUNCHXL_F280049C_NAME "LaunchXL-F280049C LaunchPad"

/*
 * Schema: LaunchXL-F280049C board resource model with both BOOSTXL sites, all six ePWM pairs, three ADC modules, two eQEP connectors and board service peripherals.
 */

// Parameter macros
/**
 * @brief C2000 device name.
 */
#define LAUNCHXL_F280049C_CHIP "TMS320F280049C"

/**
 * @brief SysConfig source file implementing this resource map.
 */
#define LAUNCHXL_F280049C_SYSCFG_FILE "ctl/suite/mcs_pmsm_nt/project/f280049c/280049C_LaunchPad.syscfg"

/**
 * @brief Device system clock in hertz.
 */
#define LAUNCHXL_F280049C_SYSTEM_CLOCK_HZ (100000000UL)

/**
 * @brief BOOSTXL analog inputs assigned to ADCA.
 */
#define LAUNCHXL_F280049C_ADCA_SOC_COUNT (7U)

/**
 * @brief BOOSTXL analog inputs assigned to ADCB.
 */
#define LAUNCHXL_F280049C_ADCB_SOC_COUNT (3U)

/**
 * @brief BOOSTXL analog inputs assigned to ADCC.
 */
#define LAUNCHXL_F280049C_ADCC_SOC_COUNT (6U)

/**
 * @brief J3 pin 23, ADCINA5, ADCA SOC0.
 */
#define LAUNCHXL_F280049C_J3_AIN1 BOOSTXL_J3_AIN1

/**
 * @brief J3 pin 24, ADCINB0, ADCB SOC0.
 */
#define LAUNCHXL_F280049C_J3_AIN2 BOOSTXL_J3_AIN2

/**
 * @brief J3 pin 25, ADCINC2, ADCC SOC0.
 */
#define LAUNCHXL_F280049C_J3_AIN3 BOOSTXL_J3_AIN3

/**
 * @brief J3 pin 26, ADCINB1, ADCB SOC1.
 */
#define LAUNCHXL_F280049C_J3_AIN4 BOOSTXL_J3_AIN4

/**
 * @brief J3 pin 27, ADCINB2, ADCB SOC2.
 */
#define LAUNCHXL_F280049C_J3_AIN5 BOOSTXL_J3_AIN5

/**
 * @brief J3 pin 28, ADCINC0, ADCC SOC1.
 */
#define LAUNCHXL_F280049C_J3_AIN6 BOOSTXL_J3_AIN6

/**
 * @brief J3 pin 29, ADCINA9, ADCA SOC1.
 */
#define LAUNCHXL_F280049C_J3_AIN7 BOOSTXL_J3_AIN7

/**
 * @brief J3 pin 30, ADCINA1/DACB, ADCA SOC2; mutually exclusive with DACB output.
 */
#define LAUNCHXL_F280049C_J3_AIN8 BOOSTXL_J3_AIN8

/**
 * @brief J7 pin 23, ADCINA6, ADCA SOC3.
 */
#define LAUNCHXL_F280049C_J7_AIN1 BOOSTXL_J7_AIN1

/**
 * @brief J7 pin 24, ADCINA2, ADCA SOC4.
 */
#define LAUNCHXL_F280049C_J7_AIN2 BOOSTXL_J7_AIN2

/**
 * @brief J7 pin 25, ADCINC14, ADCC SOC2.
 */
#define LAUNCHXL_F280049C_J7_AIN3 BOOSTXL_J7_AIN3

/**
 * @brief J7 pin 26, ADCINC1, ADCC SOC3.
 */
#define LAUNCHXL_F280049C_J7_AIN4 BOOSTXL_J7_AIN4

/**
 * @brief J7 pin 27, ADCINC3, ADCC SOC4.
 */
#define LAUNCHXL_F280049C_J7_AIN5 BOOSTXL_J7_AIN5

/**
 * @brief J7 pin 28, ADCINC5, ADCC SOC5.
 */
#define LAUNCHXL_F280049C_J7_AIN6 BOOSTXL_J7_AIN6

/**
 * @brief J7 pin 29, ADCINA3, ADCA SOC5.
 */
#define LAUNCHXL_F280049C_J7_AIN7 BOOSTXL_J7_AIN7

/**
 * @brief J7 pin 30, ADCINA0/DACA, ADCA SOC6; mutually exclusive with DACA output.
 */
#define LAUNCHXL_F280049C_J7_AIN8 BOOSTXL_J7_AIN8

/**
 * @brief BOOSTXL site 1 J4 PWM pair 1, GPIO10/11, ePWM6.
 */
#define LAUNCHXL_F280049C_J4_PWM1_BASE BOOSTXL_J4_PWM1_BASE

/**
 * @brief BOOSTXL site 1 J4 PWM pair 2, GPIO8/9, ePWM5.
 */
#define LAUNCHXL_F280049C_J4_PWM2_BASE BOOSTXL_J4_PWM2_BASE

/**
 * @brief BOOSTXL site 1 J4 PWM pair 3, GPIO4/5, ePWM3.
 */
#define LAUNCHXL_F280049C_J4_PWM3_BASE BOOSTXL_J4_PWM3_BASE

/**
 * @brief BOOSTXL site 2 J8 PWM pair 1, GPIO0/1, ePWM1.
 */
#define LAUNCHXL_F280049C_J8_PWM1_BASE BOOSTXL_J8_PWM1_BASE

/**
 * @brief BOOSTXL site 2 J8 PWM pair 2, GPIO6/7, ePWM4.
 */
#define LAUNCHXL_F280049C_J8_PWM2_BASE BOOSTXL_J8_PWM2_BASE

/**
 * @brief BOOSTXL site 2 J8 PWM pair 3, GPIO2/3, ePWM2.
 */
#define LAUNCHXL_F280049C_J8_PWM3_BASE BOOSTXL_J8_PWM3_BASE

/**
 * @brief J12 encoder connector eQEP1 base.
 */
#define LAUNCHXL_F280049C_EQEP_J12_BASE EQEP1_J12_BASE

/**
 * @brief J13 encoder connector eQEP2 base.
 */
#define LAUNCHXL_F280049C_EQEP_J13_BASE EQEP2_J13_BASE

/**
 * @brief On-board red LED GPIO resource.
 */
#define LAUNCHXL_F280049C_LED_RED LED_R

/**
 * @brief On-board green LED GPIO resource.
 */
#define LAUNCHXL_F280049C_LED_GREEN LED_G

/**
 * @brief BOOSTXL gate-enable GPIO resource.
 */
#define LAUNCHXL_F280049C_GATE_ENABLE ENABLE_GATE

/**
 * @brief BOOSTXL gate-reset GPIO resource.
 */
#define LAUNCHXL_F280049C_GATE_RESET RESET_GATE

/**
 * @brief Board monitor/test GPIO resource.
 */
#define LAUNCHXL_F280049C_MONITOR_GPIO MONITOR_IO

/**
 * @brief LaunchPad CAN peripheral base.
 */
#define LAUNCHXL_F280049C_CAN_BASE LAUNCHXL_CAN_BASE

/**
 * @brief XDS110 back-channel UART base.
 */
#define LAUNCHXL_F280049C_UART_USB_BASE LAUNCHXL_UART_USB_BASE

/**
 * @brief DAC A base.
 */
#define LAUNCHXL_F280049C_DACA_BASE LAUNCHXL_DACA_BASE

/**
 * @brief DAC B base.
 */
#define LAUNCHXL_F280049C_DACB_BASE LAUNCHXL_DACB_BASE

// Logical exports
// j4_pwm1_base: LAUNCHXL_F280049C_J4_PWM1_BASE
// j4_pwm2_base: LAUNCHXL_F280049C_J4_PWM2_BASE
// j4_pwm3_base: LAUNCHXL_F280049C_J4_PWM3_BASE
// j8_pwm1_base: LAUNCHXL_F280049C_J8_PWM1_BASE
// j8_pwm2_base: LAUNCHXL_F280049C_J8_PWM2_BASE
// j8_pwm3_base: LAUNCHXL_F280049C_J8_PWM3_BASE
// eqep_j12_base: LAUNCHXL_F280049C_EQEP_J12_BASE
// eqep_j13_base: LAUNCHXL_F280049C_EQEP_J13_BASE

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _MCU_BOARD_LAUNCHXL_F280049C_H_
