/**
 * @file nucleo_u083rc.h
 * @brief SDPE hardware preset for NUCLEO-U083RC GMP Base Board.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _MCU_BOARD_NUCLEO_U083RC_H_
#define _MCU_BOARD_NUCLEO_U083RC_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_nucleo_u083rc NUCLEO-U083RC GMP Base Board
 * @{
 */

// Identification
#define NUCLEO_U083RC_ID "nucleo_u083rc"
#define NUCLEO_U083RC_SCHEMA "stm32_nucleo_64_board"
#define NUCLEO_U083RC_NAME "NUCLEO-U083RC GMP Base Board"

/*
 * Schema: Board-level resource contract for reusable GMP Nucleo-64 control targets.
 */

// Parameter macros
/**
 * @brief STM32 device name.
 */
#define NUCLEO_U083RC_CHIP "STM32U083RCTx"

/**
 * @brief Nucleo board name.
 */
#define NUCLEO_U083RC_BOARD "NUCLEO-U083RC"

/**
 * @brief Repository-relative CubeMX IOC path.
 */
#define NUCLEO_U083RC_IOC_FILE "csp/stm32/Nucleo_64/stm32u083rc_nucleo/stm32u083rc_nucleo.ioc"

/**
 * @brief System clock in hertz.
 */
#define NUCLEO_U083RC_SYSTEM_CLOCK_HZ (48000000UL)

/**
 * @brief HAL system tick rate in hertz.
 */
#define NUCLEO_U083RC_SYSTEM_TICK_HZ (1000UL)

/**
 * @brief TIM1 HAL handle.
 */
#define NUCLEO_U083RC_PWM_TIM1_HANDLE (&htim1)

/**
 * @brief TIM1 CubeMX handle symbol.
 */
#define NUCLEO_U083RC_PWM_TIM1_SYMBOL htim1

/**
 * @brief TIM1 peripheral instance.
 */
#define NUCLEO_U083RC_PWM_TIM1_INSTANCE TIM1

/**
 * @brief TIM1 ADC trigger selection.
 */
#define NUCLEO_U083RC_PWM_TIM1_ADC_TRIGGER ADC_EXTERNALTRIG_T1_TRGO2

/**
 * @brief TIM8 HAL handle.
 */
#define NUCLEO_U083RC_PWM_TIM8_HANDLE (&htim1)

/**
 * @brief TIM8 CubeMX handle symbol.
 */
#define NUCLEO_U083RC_PWM_TIM8_SYMBOL htim1

/**
 * @brief TIM8 peripheral instance.
 */
#define NUCLEO_U083RC_PWM_TIM8_INSTANCE TIM1

/**
 * @brief TIM8 ADC trigger selection.
 */
#define NUCLEO_U083RC_PWM_TIM8_ADC_TRIGGER ADC_EXTERNALTRIG_T1_TRGO2

/**
 * @brief One when a usable hardware break input is routed.
 */
#define NUCLEO_U083RC_PWM_HAS_BREAK (0U)

/**
 * @brief TIM3 encoder handle.
 */
#define NUCLEO_U083RC_QEP_TIM3_HANDLE (&htim3)

/**
 * @brief TIM3 CubeMX handle symbol.
 */
#define NUCLEO_U083RC_QEP_TIM3_SYMBOL htim3

/**
 * @brief TIM3 peripheral instance.
 */
#define NUCLEO_U083RC_QEP_TIM3_INSTANCE TIM3

/**
 * @brief TIM4 encoder handle.
 */
#define NUCLEO_U083RC_QEP_TIM4_HANDLE (&htim3)

/**
 * @brief TIM4 CubeMX handle symbol.
 */
#define NUCLEO_U083RC_QEP_TIM4_SYMBOL htim3

/**
 * @brief TIM4 peripheral instance.
 */
#define NUCLEO_U083RC_QEP_TIM4_INSTANCE TIM3

/**
 * @brief TIM3 index GPIO port.
 */
#define NUCLEO_U083RC_QEP_TIM3_Z_PORT GPIOC

/**
 * @brief TIM3 index GPIO pin.
 */
#define NUCLEO_U083RC_QEP_TIM3_Z_PIN GPIO_PIN_10

/**
 * @brief TIM4 index GPIO port.
 */
#define NUCLEO_U083RC_QEP_TIM4_Z_PORT GPIOC

/**
 * @brief TIM4 index GPIO pin.
 */
#define NUCLEO_U083RC_QEP_TIM4_Z_PIN GPIO_PIN_10

/**
 * @brief One when the selected QEP index is implemented by a GPIO interrupt.
 */
#define NUCLEO_U083RC_QEP_SOFTWARE_INDEX (1U)

/**
 * @brief One when the target HAL reports GPIO interrupts through HAL_GPIO_EXTI_Callback.
 */
#define NUCLEO_U083RC_QEP_LEGACY_EXTI_CALLBACK (0U)

/**
 * @brief One when a timer-triggered regular ADC scan with circular DMA drives the control step.
 */
#define NUCLEO_U083RC_ADC_REGULAR_DMA (1U)

/**
 * @brief One when the target HAL exposes an ADC self-calibration operation.
 */
#define NUCLEO_U083RC_ADC_HAS_CALIBRATION (1U)

/**
 * @brief One when an internal timer relays the PWM timer trigger to the ADC.
 */
#define NUCLEO_U083RC_ADC_TRIGGER_BRIDGE (0U)

/**
 * @brief HAL handle for the internal ADC trigger bridge timer.
 */
#define NUCLEO_U083RC_ADC_TRIGGER_TIMER_HANDLE NULL

/**
 * @brief CubeMX symbol for the internal ADC trigger bridge timer.
 */
#define NUCLEO_U083RC_ADC_TRIGGER_TIMER_SYMBOL unused_adc_trigger_timer

/**
 * @brief Peripheral instance for the internal ADC trigger bridge timer.
 */
#define NUCLEO_U083RC_ADC_TRIGGER_TIMER_INSTANCE 0U

/**
 * @brief ADC handle whose conversion completion drives the control step.
 */
#define NUCLEO_U083RC_ADC_PRIMARY_HANDLE (&hadc1)

/**
 * @brief Primary ADC CubeMX handle symbol.
 */
#define NUCLEO_U083RC_ADC_PRIMARY_SYMBOL hadc1

/**
 * @brief Second synchronized ADC handle.
 */
#define NUCLEO_U083RC_ADC_SECONDARY_HANDLE (&hadc1)

/**
 * @brief Secondary ADC CubeMX handle symbol.
 */
#define NUCLEO_U083RC_ADC_SECONDARY_SYMBOL hadc1

/**
 * @brief Family-specific ADC JSQR trigger-field mask.
 */
#define NUCLEO_U083RC_ADC_TRIGGER_MASK 0U

/**
 * @brief Family-specific ADC trigger edge.
 */
#define NUCLEO_U083RC_ADC_TRIGGER_EDGE 0U

/**
 * @brief Number of fixed external feedback channels.
 */
#define NUCLEO_U083RC_ADC_FB_COUNT (6U)

/**
 * @brief FB0 ADC handle.
 */
#define NUCLEO_U083RC_ADC_FB0_HANDLE (&hadc1)

/**
 * @brief FB0 injected rank or regular-DMA buffer index.
 */
#define NUCLEO_U083RC_ADC_FB0_RANK 0

/**
 * @brief FB0 physical MCU pin.
 */
#define NUCLEO_U083RC_ADC_FB0_PIN "PC0"

/**
 * @brief FB1 ADC handle.
 */
#define NUCLEO_U083RC_ADC_FB1_HANDLE (&hadc1)

/**
 * @brief FB1 injected rank or regular-DMA buffer index.
 */
#define NUCLEO_U083RC_ADC_FB1_RANK 1

/**
 * @brief FB1 physical MCU pin.
 */
#define NUCLEO_U083RC_ADC_FB1_PIN "PC1"

/**
 * @brief FB2 ADC handle.
 */
#define NUCLEO_U083RC_ADC_FB2_HANDLE (&hadc1)

/**
 * @brief FB2 injected rank or regular-DMA buffer index.
 */
#define NUCLEO_U083RC_ADC_FB2_RANK 2

/**
 * @brief FB2 physical MCU pin.
 */
#define NUCLEO_U083RC_ADC_FB2_PIN "PC2"

/**
 * @brief FB3 ADC handle.
 */
#define NUCLEO_U083RC_ADC_FB3_HANDLE (&hadc1)

/**
 * @brief FB3 injected rank or regular-DMA buffer index.
 */
#define NUCLEO_U083RC_ADC_FB3_RANK 3

/**
 * @brief FB3 physical MCU pin.
 */
#define NUCLEO_U083RC_ADC_FB3_PIN "PC3"

/**
 * @brief FB4 ADC handle.
 */
#define NUCLEO_U083RC_ADC_FB4_HANDLE (&hadc1)

/**
 * @brief FB4 injected rank or regular-DMA buffer index.
 */
#define NUCLEO_U083RC_ADC_FB4_RANK 4

/**
 * @brief FB4 physical MCU pin.
 */
#define NUCLEO_U083RC_ADC_FB4_PIN "PA0"

/**
 * @brief FB5 ADC handle.
 */
#define NUCLEO_U083RC_ADC_FB5_HANDLE (&hadc1)

/**
 * @brief FB5 injected rank or regular-DMA buffer index.
 */
#define NUCLEO_U083RC_ADC_FB5_RANK 5

/**
 * @brief FB5 physical MCU pin.
 */
#define NUCLEO_U083RC_ADC_FB5_PIN "PA1"

/**
 * @brief ST-Link VCP UART handle.
 */
#define NUCLEO_U083RC_DL_UART_HANDLE (&huart2)

/**
 * @brief ST-Link VCP CubeMX handle symbol.
 */
#define NUCLEO_U083RC_DL_UART_SYMBOL huart2

/**
 * @brief ST-Link VCP UART instance.
 */
#define NUCLEO_U083RC_DL_UART_INSTANCE USART2

/**
 * @brief Circular RX DMA handle.
 */
#define NUCLEO_U083RC_DL_RX_DMA_HANDLE (&hdma_usart2_rx)

/**
 * @brief VCP TX physical MCU pin.
 */
#define NUCLEO_U083RC_DL_TX_PIN "PA2"

/**
 * @brief VCP RX physical MCU pin.
 */
#define NUCLEO_U083RC_DL_RX_PIN "PA3"

/**
 * @brief User LED GPIO port.
 */
#define NUCLEO_U083RC_STATUS_LED_PORT GPIOA

/**
 * @brief User LED GPIO pin mask.
 */
#define NUCLEO_U083RC_STATUS_LED_PIN GPIO_PIN_5

/**
 * @brief GPIO state that lights the LED.
 */
#define NUCLEO_U083RC_STATUS_LED_ON GPIO_PIN_SET

/**
 * @brief GPIO state that turns the LED off.
 */
#define NUCLEO_U083RC_STATUS_LED_OFF GPIO_PIN_RESET

/**
 * @brief Arduino I2C HAL handle.
 */
#define NUCLEO_U083RC_I2C_HANDLE (&hi2c1)

/**
 * @brief Arduino I2C peripheral instance.
 */
#define NUCLEO_U083RC_I2C_INSTANCE I2C1

/**
 * @brief I2C SCL physical MCU pin.
 */
#define NUCLEO_U083RC_I2C_SCL_PIN "PB8"

/**
 * @brief I2C SDA physical MCU pin.
 */
#define NUCLEO_U083RC_I2C_SDA_PIN "PB9"

/**
 * @brief One when an internal DAC is routed externally.
 */
#define NUCLEO_U083RC_HAS_DAC (1U)

/**
 * @brief DAC HAL handle, valid when HAS_DAC is one.
 */
#define NUCLEO_U083RC_DAC_HANDLE (&hdac1)

/**
 * @brief DAC CubeMX handle symbol.
 */
#define NUCLEO_U083RC_DAC_SYMBOL hdac1

/**
 * @brief DAC channel, valid when HAS_DAC is one.
 */
#define NUCLEO_U083RC_DAC_CHANNEL DAC_CHANNEL_1

/**
 * @brief DAC physical MCU pin.
 */
#define NUCLEO_U083RC_DAC_PIN "PA4"

/**
 * @brief One when CAN/FDCAN pins are routed externally.
 */
#define NUCLEO_U083RC_HAS_CAN (0U)

/**
 * @brief CAN peripheral type string.
 */
#define NUCLEO_U083RC_CAN_TYPE "NONE"

/**
 * @brief CAN/FDCAN HAL handle.
 */
#define NUCLEO_U083RC_CAN_HANDLE NULL

/**
 * @brief CAN/FDCAN instance.
 */
#define NUCLEO_U083RC_CAN_INSTANCE 0U

/**
 * @brief CAN TX physical MCU pin.
 */
#define NUCLEO_U083RC_CAN_TX_PIN "NC"

/**
 * @brief CAN RX physical MCU pin.
 */
#define NUCLEO_U083RC_CAN_RX_PIN "NC"

/**
 * @brief One when the board CAN transceiver exposes a standby GPIO.
 */
#define NUCLEO_U083RC_CAN_HAS_STBY (0U)

/**
 * @brief CAN transceiver standby GPIO port.
 */
#define NUCLEO_U083RC_CAN_STBY_PORT GPIOA

/**
 * @brief CAN transceiver standby GPIO pin.
 */
#define NUCLEO_U083RC_CAN_STBY_PIN GPIO_PIN_0

/**
 * @brief GPIO state that places the CAN transceiver in standby.
 */
#define NUCLEO_U083RC_CAN_STBY_ON GPIO_PIN_SET

/**
 * @brief GPIO state that enables the CAN transceiver.
 */
#define NUCLEO_U083RC_CAN_STBY_OFF GPIO_PIN_RESET

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _MCU_BOARD_NUCLEO_U083RC_H_
