/**
 * @file nucleo_h753zi.h
 * @brief SDPE hardware preset for NUCLEO-H753ZI GMP Ethernet Control Board.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _MCU_BOARD_NUCLEO_H753ZI_H_
#define _MCU_BOARD_NUCLEO_H753ZI_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_nucleo_h753zi NUCLEO-H753ZI GMP Ethernet Control Board
 * @{
 */

// Identification
#define NUCLEO_H753ZI_ID "nucleo_h753zi"
#define NUCLEO_H753ZI_SCHEMA "stm32_nucleo_144_board"
#define NUCLEO_H753ZI_NAME "NUCLEO-H753ZI GMP Ethernet Control Board"

/*
 * Schema: Board-level resource contract for reusable GMP Nucleo-144 control targets.
 */

// Parameter macros
/**
 * @brief STM32 device name.
 */
#define NUCLEO_H753ZI_CHIP "STM32H753ZITx"

/**
 * @brief Nucleo board name.
 */
#define NUCLEO_H753ZI_BOARD "NUCLEO-H753ZI"

/**
 * @brief Repository-relative CubeMX IOC path.
 */
#define NUCLEO_H753ZI_IOC_FILE "csp/stm32/Nucleo_144/stm32h753zi_nucleo/stm32h753zi_nucleo.ioc"

/**
 * @brief System clock in hertz.
 */
#define NUCLEO_H753ZI_SYSTEM_CLOCK_HZ (400000000UL)

/**
 * @brief HAL system tick rate in hertz.
 */
#define NUCLEO_H753ZI_SYSTEM_TICK_HZ (1000UL)

/**
 * @brief TIM1 HAL handle.
 */
#define NUCLEO_H753ZI_PWM_TIM1_HANDLE (&htim1)

/**
 * @brief TIM1 CubeMX handle symbol.
 */
#define NUCLEO_H753ZI_PWM_TIM1_SYMBOL htim1

/**
 * @brief TIM1 peripheral instance.
 */
#define NUCLEO_H753ZI_PWM_TIM1_INSTANCE TIM1

/**
 * @brief TIM1 ADC trigger selection.
 */
#define NUCLEO_H753ZI_PWM_TIM1_ADC_TRIGGER ADC_EXTERNALTRIG_T1_TRGO2

/**
 * @brief TIM8 HAL handle.
 */
#define NUCLEO_H753ZI_PWM_TIM8_HANDLE (&htim1)

/**
 * @brief TIM8 CubeMX handle symbol.
 */
#define NUCLEO_H753ZI_PWM_TIM8_SYMBOL htim1

/**
 * @brief TIM8 peripheral instance.
 */
#define NUCLEO_H753ZI_PWM_TIM8_INSTANCE TIM1

/**
 * @brief TIM8 ADC trigger selection.
 */
#define NUCLEO_H753ZI_PWM_TIM8_ADC_TRIGGER ADC_EXTERNALTRIG_T1_TRGO2

/**
 * @brief One when a usable hardware break input is routed.
 */
#define NUCLEO_H753ZI_PWM_HAS_BREAK (0U)

/**
 * @brief TIM3 encoder handle.
 */
#define NUCLEO_H753ZI_QEP_TIM3_HANDLE (&htim3)

/**
 * @brief TIM3 CubeMX handle symbol.
 */
#define NUCLEO_H753ZI_QEP_TIM3_SYMBOL htim3

/**
 * @brief TIM3 peripheral instance.
 */
#define NUCLEO_H753ZI_QEP_TIM3_INSTANCE TIM3

/**
 * @brief TIM4 encoder handle.
 */
#define NUCLEO_H753ZI_QEP_TIM4_HANDLE (&htim3)

/**
 * @brief TIM4 CubeMX handle symbol.
 */
#define NUCLEO_H753ZI_QEP_TIM4_SYMBOL htim3

/**
 * @brief TIM4 peripheral instance.
 */
#define NUCLEO_H753ZI_QEP_TIM4_INSTANCE TIM3

/**
 * @brief TIM3 index GPIO port.
 */
#define NUCLEO_H753ZI_QEP_TIM3_Z_PORT GPIOG

/**
 * @brief TIM3 index GPIO pin.
 */
#define NUCLEO_H753ZI_QEP_TIM3_Z_PIN GPIO_PIN_2

/**
 * @brief TIM4 index GPIO port.
 */
#define NUCLEO_H753ZI_QEP_TIM4_Z_PORT GPIOG

/**
 * @brief TIM4 index GPIO pin.
 */
#define NUCLEO_H753ZI_QEP_TIM4_Z_PIN GPIO_PIN_2

/**
 * @brief One when the selected QEP index is implemented by a GPIO interrupt.
 */
#define NUCLEO_H753ZI_QEP_SOFTWARE_INDEX (1U)

/**
 * @brief One when the target HAL reports GPIO interrupts through HAL_GPIO_EXTI_Callback.
 */
#define NUCLEO_H753ZI_QEP_LEGACY_EXTI_CALLBACK (1U)

/**
 * @brief One when a timer-triggered regular ADC scan with circular DMA drives the control step.
 */
#define NUCLEO_H753ZI_ADC_REGULAR_DMA (1U)

/**
 * @brief One when the target HAL exposes an ADC self-calibration operation.
 */
#define NUCLEO_H753ZI_ADC_HAS_CALIBRATION (1U)

/**
 * @brief HAL ADC calibration signature: 0 none, 1 handle, 2 handle plus input mode, 3 H7 offset-linearity plus input mode.
 */
#define NUCLEO_H753ZI_ADC_CALIBRATION_STYLE (3U)

/**
 * @brief One when an internal timer relays the PWM timer trigger to the ADC.
 */
#define NUCLEO_H753ZI_ADC_TRIGGER_BRIDGE (0U)

/**
 * @brief HAL handle for the internal ADC trigger bridge timer.
 */
#define NUCLEO_H753ZI_ADC_TRIGGER_TIMER_HANDLE NULL

/**
 * @brief CubeMX symbol for the internal ADC trigger bridge timer.
 */
#define NUCLEO_H753ZI_ADC_TRIGGER_TIMER_SYMBOL unused_adc_trigger_timer

/**
 * @brief Peripheral instance for the internal ADC trigger bridge timer.
 */
#define NUCLEO_H753ZI_ADC_TRIGGER_TIMER_INSTANCE 0U

/**
 * @brief ADC handle whose conversion completion drives the control step.
 */
#define NUCLEO_H753ZI_ADC_PRIMARY_HANDLE (&hadc1)

/**
 * @brief Primary ADC CubeMX handle symbol.
 */
#define NUCLEO_H753ZI_ADC_PRIMARY_SYMBOL hadc1

/**
 * @brief Second synchronized ADC handle.
 */
#define NUCLEO_H753ZI_ADC_SECONDARY_HANDLE (&hadc1)

/**
 * @brief Secondary ADC CubeMX handle symbol.
 */
#define NUCLEO_H753ZI_ADC_SECONDARY_SYMBOL hadc1

/**
 * @brief Family-specific ADC JSQR trigger-field mask.
 */
#define NUCLEO_H753ZI_ADC_TRIGGER_MASK 0U

/**
 * @brief Family-specific ADC trigger edge.
 */
#define NUCLEO_H753ZI_ADC_TRIGGER_EDGE 0U

/**
 * @brief Number of fixed external feedback channels.
 */
#define NUCLEO_H753ZI_ADC_FB_COUNT (6U)

/**
 * @brief FB0 ADC handle.
 */
#define NUCLEO_H753ZI_ADC_FB0_HANDLE (&hadc1)

/**
 * @brief FB0 injected rank or regular-DMA buffer index.
 */
#define NUCLEO_H753ZI_ADC_FB0_RANK 5

/**
 * @brief FB0 physical MCU pin.
 */
#define NUCLEO_H753ZI_ADC_FB0_PIN "PA3"

/**
 * @brief FB1 ADC handle.
 */
#define NUCLEO_H753ZI_ADC_FB1_HANDLE (&hadc1)

/**
 * @brief FB1 injected rank or regular-DMA buffer index.
 */
#define NUCLEO_H753ZI_ADC_FB1_RANK 1

/**
 * @brief FB1 physical MCU pin.
 */
#define NUCLEO_H753ZI_ADC_FB1_PIN "PC0"

/**
 * @brief FB2 ADC handle.
 */
#define NUCLEO_H753ZI_ADC_FB2_HANDLE (&hadc1)

/**
 * @brief FB2 injected rank or regular-DMA buffer index.
 */
#define NUCLEO_H753ZI_ADC_FB2_RANK 0

/**
 * @brief FB2 physical MCU pin.
 */
#define NUCLEO_H753ZI_ADC_FB2_PIN "PB1"

/**
 * @brief FB3 ADC handle.
 */
#define NUCLEO_H753ZI_ADC_FB3_HANDLE (&hadc1)

/**
 * @brief FB3 injected rank or regular-DMA buffer index.
 */
#define NUCLEO_H753ZI_ADC_FB3_RANK 3

/**
 * @brief FB3 physical MCU pin.
 */
#define NUCLEO_H753ZI_ADC_FB3_PIN "PA4"

/**
 * @brief FB4 ADC handle.
 */
#define NUCLEO_H753ZI_ADC_FB4_HANDLE (&hadc1)

/**
 * @brief FB4 injected rank or regular-DMA buffer index.
 */
#define NUCLEO_H753ZI_ADC_FB4_RANK 4

/**
 * @brief FB4 physical MCU pin.
 */
#define NUCLEO_H753ZI_ADC_FB4_PIN "PA5"

/**
 * @brief FB5 ADC handle.
 */
#define NUCLEO_H753ZI_ADC_FB5_HANDLE (&hadc1)

/**
 * @brief FB5 injected rank or regular-DMA buffer index.
 */
#define NUCLEO_H753ZI_ADC_FB5_RANK 2

/**
 * @brief FB5 physical MCU pin.
 */
#define NUCLEO_H753ZI_ADC_FB5_PIN "PA0"

/**
 * @brief ST-Link VCP UART handle.
 */
#define NUCLEO_H753ZI_DL_UART_HANDLE (&huart3)

/**
 * @brief ST-Link VCP CubeMX handle symbol.
 */
#define NUCLEO_H753ZI_DL_UART_SYMBOL huart3

/**
 * @brief ST-Link VCP UART instance.
 */
#define NUCLEO_H753ZI_DL_UART_INSTANCE USART3

/**
 * @brief Circular RX DMA handle.
 */
#define NUCLEO_H753ZI_DL_RX_DMA_HANDLE (&hdma_usart3_rx)

/**
 * @brief VCP TX physical MCU pin.
 */
#define NUCLEO_H753ZI_DL_TX_PIN "PD8"

/**
 * @brief VCP RX physical MCU pin.
 */
#define NUCLEO_H753ZI_DL_RX_PIN "PD9"

/**
 * @brief User LED GPIO port.
 */
#define NUCLEO_H753ZI_STATUS_LED_PORT GPIOB

/**
 * @brief User LED GPIO pin mask.
 */
#define NUCLEO_H753ZI_STATUS_LED_PIN GPIO_PIN_0

/**
 * @brief GPIO state that lights the LED.
 */
#define NUCLEO_H753ZI_STATUS_LED_ON GPIO_PIN_SET

/**
 * @brief GPIO state that turns the LED off.
 */
#define NUCLEO_H753ZI_STATUS_LED_OFF GPIO_PIN_RESET

/**
 * @brief Number of onboard user status LEDs.
 */
#define NUCLEO_H753ZI_STATUS_LED_COUNT (3U)

/**
 * @brief Second user LED GPIO port.
 */
#define NUCLEO_H753ZI_STATUS_LED2_PORT GPIOB

/**
 * @brief Second user LED GPIO pin mask.
 */
#define NUCLEO_H753ZI_STATUS_LED2_PIN GPIO_PIN_7

/**
 * @brief GPIO state that lights the second LED.
 */
#define NUCLEO_H753ZI_STATUS_LED2_ON GPIO_PIN_SET

/**
 * @brief GPIO state that turns the second LED off.
 */
#define NUCLEO_H753ZI_STATUS_LED2_OFF GPIO_PIN_RESET

/**
 * @brief Third user LED GPIO port.
 */
#define NUCLEO_H753ZI_STATUS_LED3_PORT GPIOB

/**
 * @brief Third user LED GPIO pin mask.
 */
#define NUCLEO_H753ZI_STATUS_LED3_PIN GPIO_PIN_14

/**
 * @brief GPIO state that lights the third LED.
 */
#define NUCLEO_H753ZI_STATUS_LED3_ON GPIO_PIN_SET

/**
 * @brief GPIO state that turns the third LED off.
 */
#define NUCLEO_H753ZI_STATUS_LED3_OFF GPIO_PIN_RESET

/**
 * @brief Arduino I2C HAL handle.
 */
#define NUCLEO_H753ZI_I2C_HANDLE (&hi2c1)

/**
 * @brief Arduino I2C peripheral instance.
 */
#define NUCLEO_H753ZI_I2C_INSTANCE I2C1

/**
 * @brief I2C SCL physical MCU pin.
 */
#define NUCLEO_H753ZI_I2C_SCL_PIN "PB8"

/**
 * @brief I2C SDA physical MCU pin.
 */
#define NUCLEO_H753ZI_I2C_SDA_PIN "PB9"

/**
 * @brief Ethernet HAL handle.
 */
#define NUCLEO_H753ZI_ETH_HANDLE (&heth)

/**
 * @brief Ethernet CubeMX handle symbol.
 */
#define NUCLEO_H753ZI_ETH_SYMBOL heth

/**
 * @brief Ethernet MAC peripheral instance.
 */
#define NUCLEO_H753ZI_ETH_INSTANCE ETH

/**
 * @brief HAL Ethernet media-interface selection.
 */
#define NUCLEO_H753ZI_ETH_MEDIA_INTERFACE HAL_ETH_RMII_MODE

/**
 * @brief Board Ethernet PHY driver family.
 */
#define NUCLEO_H753ZI_ETH_PHY_DRIVER "LAN8742"

/**
 * @brief MDIO PHY address.
 */
#define NUCLEO_H753ZI_ETH_PHY_ADDRESS (0U)

/**
 * @brief RMII reference-clock physical MCU pin.
 */
#define NUCLEO_H753ZI_ETH_REF_CLK_PIN "PA1"

/**
 * @brief RMII MDIO physical MCU pin.
 */
#define NUCLEO_H753ZI_ETH_MDIO_PIN "PA2"

/**
 * @brief RMII carrier/data-valid physical MCU pin.
 */
#define NUCLEO_H753ZI_ETH_CRS_DV_PIN "PA7"

/**
 * @brief RMII MDC physical MCU pin.
 */
#define NUCLEO_H753ZI_ETH_MDC_PIN "PC1"

/**
 * @brief RMII receive-data 0 physical MCU pin.
 */
#define NUCLEO_H753ZI_ETH_RXD0_PIN "PC4"

/**
 * @brief RMII receive-data 1 physical MCU pin.
 */
#define NUCLEO_H753ZI_ETH_RXD1_PIN "PC5"

/**
 * @brief RMII transmit-enable physical MCU pin.
 */
#define NUCLEO_H753ZI_ETH_TX_EN_PIN "PG11"

/**
 * @brief RMII transmit-data 0 physical MCU pin.
 */
#define NUCLEO_H753ZI_ETH_TXD0_PIN "PG13"

/**
 * @brief RMII transmit-data 1 physical MCU pin.
 */
#define NUCLEO_H753ZI_ETH_TXD1_PIN "PB13"

/**
 * @brief Locally administered MAC byte 0.
 */
#define NUCLEO_H753ZI_ETH_MAC0 (0x02U)

/**
 * @brief Locally administered MAC byte 1.
 */
#define NUCLEO_H753ZI_ETH_MAC1 (0x47U)

/**
 * @brief Locally administered MAC byte 2.
 */
#define NUCLEO_H753ZI_ETH_MAC2 (0x4DU)

/**
 * @brief Locally administered MAC byte 3.
 */
#define NUCLEO_H753ZI_ETH_MAC3 (0x50U)

/**
 * @brief Locally administered MAC byte 4.
 */
#define NUCLEO_H753ZI_ETH_MAC4 (0x14U)

/**
 * @brief Locally administered MAC byte 5.
 */
#define NUCLEO_H753ZI_ETH_MAC5 (0x01U)

/**
 * @brief Static IPv4 address octet 0.
 */
#define NUCLEO_H753ZI_ETH_IPV4_0 (192U)

/**
 * @brief Static IPv4 address octet 1.
 */
#define NUCLEO_H753ZI_ETH_IPV4_1 (168U)

/**
 * @brief Static IPv4 address octet 2.
 */
#define NUCLEO_H753ZI_ETH_IPV4_2 (137U)

/**
 * @brief Static IPv4 address octet 3.
 */
#define NUCLEO_H753ZI_ETH_IPV4_3 (2U)

/**
 * @brief IPv4 netmask octet 0.
 */
#define NUCLEO_H753ZI_ETH_NETMASK_0 (255U)

/**
 * @brief IPv4 netmask octet 1.
 */
#define NUCLEO_H753ZI_ETH_NETMASK_1 (255U)

/**
 * @brief IPv4 netmask octet 2.
 */
#define NUCLEO_H753ZI_ETH_NETMASK_2 (255U)

/**
 * @brief IPv4 netmask octet 3.
 */
#define NUCLEO_H753ZI_ETH_NETMASK_3 (0U)

/**
 * @brief IPv4 gateway octet 0.
 */
#define NUCLEO_H753ZI_ETH_GATEWAY_0 (192U)

/**
 * @brief IPv4 gateway octet 1.
 */
#define NUCLEO_H753ZI_ETH_GATEWAY_1 (168U)

/**
 * @brief IPv4 gateway octet 2.
 */
#define NUCLEO_H753ZI_ETH_GATEWAY_2 (137U)

/**
 * @brief IPv4 gateway octet 3.
 */
#define NUCLEO_H753ZI_ETH_GATEWAY_3 (1U)

/**
 * @brief UDP acceptance-test echo port.
 */
#define NUCLEO_H753ZI_ETH_UDP_ECHO_PORT (50000U)

/**
 * @brief GMP Data Link TCP service port.
 */
#define NUCLEO_H753ZI_ETH_DL_TCP_PORT (50001U)

/**
 * @brief GMP Data Link UDP service port.
 */
#define NUCLEO_H753ZI_ETH_DL_UDP_PORT (50002U)

/**
 * @brief One when an internal DAC is routed externally.
 */
#define NUCLEO_H753ZI_HAS_DAC (0U)

/**
 * @brief DAC HAL handle, valid when HAS_DAC is one.
 */
#define NUCLEO_H753ZI_DAC_HANDLE NULL

/**
 * @brief DAC CubeMX handle symbol.
 */
#define NUCLEO_H753ZI_DAC_SYMBOL unused_dac

/**
 * @brief DAC channel, valid when HAS_DAC is one.
 */
#define NUCLEO_H753ZI_DAC_CHANNEL 0U

/**
 * @brief DAC physical MCU pin.
 */
#define NUCLEO_H753ZI_DAC_PIN "NC"

/**
 * @brief One when CAN/FDCAN pins are routed externally.
 */
#define NUCLEO_H753ZI_HAS_CAN (0U)

/**
 * @brief CAN peripheral type string.
 */
#define NUCLEO_H753ZI_CAN_TYPE "FDCAN"

/**
 * @brief CAN/FDCAN HAL handle.
 */
#define NUCLEO_H753ZI_CAN_HANDLE NULL

/**
 * @brief CAN/FDCAN instance.
 */
#define NUCLEO_H753ZI_CAN_INSTANCE FDCAN1

/**
 * @brief CAN TX physical MCU pin.
 */
#define NUCLEO_H753ZI_CAN_TX_PIN "PD1"

/**
 * @brief CAN RX physical MCU pin.
 */
#define NUCLEO_H753ZI_CAN_RX_PIN "PD0"

/**
 * @brief One when the board CAN transceiver exposes a standby GPIO.
 */
#define NUCLEO_H753ZI_CAN_HAS_STBY (0U)

/**
 * @brief CAN transceiver standby GPIO port.
 */
#define NUCLEO_H753ZI_CAN_STBY_PORT GPIOA

/**
 * @brief CAN transceiver standby GPIO pin.
 */
#define NUCLEO_H753ZI_CAN_STBY_PIN GPIO_PIN_0

/**
 * @brief GPIO state that places the CAN transceiver in standby.
 */
#define NUCLEO_H753ZI_CAN_STBY_ON GPIO_PIN_SET

/**
 * @brief GPIO state that enables the CAN transceiver.
 */
#define NUCLEO_H753ZI_CAN_STBY_OFF GPIO_PIN_RESET

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _MCU_BOARD_NUCLEO_H753ZI_H_
