/**
 * @file l6230.h
 * @brief SDPE hardware preset for L6230 Three-Phase DMOS Driver.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _INTEGRATED_POWER_STAGE_L6230_H_
#define _INTEGRATED_POWER_STAGE_L6230_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_l6230 L6230 Three-Phase DMOS Driver
 * @{
 */

// Identification
#define L6230_ID "l6230"
#define L6230_SCHEMA "integrated_power_stage"
#define L6230_NAME "L6230 Three-Phase DMOS Driver"

// Tags: integrated_driver, integrated_power_stage, mosfet, power_device, st, three_phase

/*
 * Schema: Integrated half-bridge or three-phase power stage that is not classified as an IPM.
 * Vendor: STMicroelectronics
 * Datasheet: https://www.st.com/resource/en/datasheet/l6230.pdf
 */

// Parameter macros
/**
 * @brief Manufacturer part number.
 */
#define L6230_PART_NUMBER "L6230"

/**
 * @brief Integrated switch technology.
 */
#define L6230_SWITCH_TECHNOLOGY "DMOS"

/**
 * @brief Half bridge or three-phase bridge.
 */
#define L6230_CONFIGURATION "three_phase_bridge"

/**
 * @brief Number of integrated phases.
 */
#define L6230_PHASE_COUNT (3U)

/**
 * @brief Maximum switch or operating voltage.
 * @unit V
 */
#define L6230_VOLTAGE_RATING_V (52.0f)

/**
 * @brief Continuous/RMS output current under datasheet conditions.
 * @unit A
 */
#define L6230_CURRENT_RATING_A (1.4f)

/**
 * @brief Peak output current.
 * @unit A
 */
#define L6230_PEAK_CURRENT_A (2.8f)

/**
 * @brief Documented on resistance; for a bridge this may be HS+LS.
 * @unit ohm
 */
#define L6230_RDSON_OHM (0.73f)

/**
 * @brief Whether the gate driver is integrated.
 */
#define L6230_DRIVER_INTEGRATED (1U)

/**
 * @brief One for active-high logic, zero for active-low.
 */
#define L6230_INPUT_ACTIVE_LEVEL (1U)

/**
 * @brief Manufacturer package.
 */
#define L6230_PACKAGE "PowerSO36 or VFQFPN32"

// Logical exports
// voltage_rating: L6230_VOLTAGE_RATING_V
// current_rating: L6230_CURRENT_RATING_A

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _INTEGRATED_POWER_STAGE_L6230_H_
