%% SDPE MATLAB initialization script
% Project: DPS CLLLC / DAB Common Control
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

%% GMP numeric-domain conversion contract
if ~exist('GMP_SDPE_REAL_TYPE', 'var'); GMP_SDPE_REAL_TYPE = 'double'; end
if ~exist('GMP_SDPE_PARAMETER_TYPE', 'var'); GMP_SDPE_PARAMETER_TYPE = 'double'; end
if ~exist('GMP_SDPE_CTRL_TYPE', 'var'); GMP_SDPE_CTRL_TYPE = 'double'; end
if ~exist('GMP_SDPE_REAL_TO_CTRL', 'var')
    GMP_SDPE_REAL_TO_CTRL = @(value) cast(value, GMP_SDPE_CTRL_TYPE);
end
if ~exist('GMP_SDPE_CTRL_TO_REAL', 'var')
    GMP_SDPE_CTRL_TO_REAL = @(value) cast(value, GMP_SDPE_REAL_TYPE);
end
real2param = @(value) cast(cast(value, GMP_SDPE_REAL_TYPE), GMP_SDPE_PARAMETER_TYPE);
real2ctrl = @(value) GMP_SDPE_REAL_TO_CTRL(cast(value, GMP_SDPE_REAL_TYPE));
param2ctrl = @(value) GMP_SDPE_REAL_TO_CTRL(cast(value, GMP_SDPE_PARAMETER_TYPE));
ctrl2param = @(value) cast(GMP_SDPE_CTRL_TO_REAL(value), GMP_SDPE_PARAMETER_TYPE);

% Notes:
%   Platform-independent Dioscuri CLLLC/DAB tank, sensing, modulation and control-loop contract.

%% Project metadata
DPS_CLLLC_COMMON_SDPE_PROJECT_ID = 'dps_clllc_common';

DPS_CLLLC_COMMON_SDPE_PROJECT_SUITE = 'dps_clllc';

DPS_CLLLC_COMMON_SDPE_PROJECT_VERSION = '1.0.0';

DPS_CLLLC_COMMON_SDPE_PROJECT_UPDATED_AT = '2026-08-15';

%% Hardware macros
TMCS1133_B5A_ID = 'tmcs1133_b5a';

TMCS1133_B5A_SCHEMA = 'current_sensor';

TMCS1133_B5A_NAME = 'TMCS1133 B5A Hall Current Sensor';

% Main sensing IC or technology name.
TMCS1133_B5A_CHIP = 'TMCS1133B5A';

% Current sensing technology, such as Hall, shunt, or fluxgate.
TMCS1133_B5A_SENSOR_TYPE = 'Hall';

% Nominal measurable current range.
TMCS1133_B5A_RANGE_A = real2param(10.3);

% Minimum output voltage.
TMCS1133_B5A_OUTPUT_MIN_V = real2param(0.0);

% Maximum output voltage.
TMCS1133_B5A_OUTPUT_MAX_V = real2param(3.3);

% Zero-current output bias.
TMCS1133_B5A_BIAS_V = real2param(1.65);

% Current sensor sensitivity.
TMCS1133_B5A_SENSITIVITY_MV_PER_A = real2param(150.0);

% Typical small-signal bandwidth.
TMCS1133_B5A_BANDWIDTH_HZ = real2param(300000.0);

% Sensor internal series resistance.
TMCS1133_B5A_INTERNAL_RESISTANCE_OHM = real2param(0.0018);

% Current sensor sensitivity converted to V/A.
TMCS1133_B5A_SENSITIVITY_V_PER_A = TMCS1133_B5A_SENSITIVITY_MV_PER_A / 1000.0;

% Positive current range implied by bias and sensitivity.
TMCS1133_B5A_MAX_CURRENT_FROM_BIAS_A = TMCS1133_B5A_BIAS_V / TMCS1133_B5A_SENSITIVITY_V_PER_A;

DIOSCURI_VOLTAGE_SENSOR_ID = 'dioscuri_voltage_sensor';

DIOSCURI_VOLTAGE_SENSOR_SCHEMA = 'voltage_sensor';

DIOSCURI_VOLTAGE_SENSOR_NAME = 'Dioscuri AMC1311 Unidirectional Voltage Sensor';

% Main sensing IC or front-end topology.
DIOSCURI_VOLTAGE_SENSOR_CHIP = 'AMC1311BDWVR + 3x300k/15k divider + 1.65 differential stage';

% Nominal measurable voltage.
DIOSCURI_VOLTAGE_SENSOR_RATED_VOLTAGE_V = real2param(122.0);

% Output bias voltage.
DIOSCURI_VOLTAGE_SENSOR_BIAS_V = real2param(0.0);

% Voltage sensor sensitivity.
DIOSCURI_VOLTAGE_SENSOR_SENSITIVITY_V_PER_V = real2param(0.02705);

% Equivalent input resistance.
DIOSCURI_VOLTAGE_SENSOR_INPUT_RESISTANCE_OHM = real2param(915000.0);

% Small-signal sensing bandwidth.
DIOSCURI_VOLTAGE_SENSOR_BANDWIDTH_HZ = real2param(100000.0);

% Approximate positive full scale voltage when biased at mid-supply.
DIOSCURI_VOLTAGE_SENSOR_MAX_BY_BIAS_V = sdpe_select(DIOSCURI_VOLTAGE_SENSOR_BIAS_V > 0.0, DIOSCURI_VOLTAGE_SENSOR_BIAS_V / DIOSCURI_VOLTAGE_SENSOR_SENSITIVITY_V_PER_V, DIOSCURI_VOLTAGE_SENSOR_RATED_VOLTAGE_V);

DIOSCURI_CLLLC_TANK_ID = 'dioscuri_clllc_resonant_tank';

DIOSCURI_CLLLC_TANK_SCHEMA = 'clllc_resonant_tank';

DIOSCURI_CLLLC_TANK_NAME = 'Dioscuri CLLLC Debug-Kit Resonant Tank';

% Nominal tank resonant frequency.
DIOSCURI_CLLLC_TANK_RESONANT_FREQUENCY_HZ = real2param(100000.0);

% Transformer magnetizing inductance.
DIOSCURI_CLLLC_TANK_MAGNETIZING_INDUCTANCE_H = real2param(120e-6);

% Primary-side resonant inductance.
DIOSCURI_CLLLC_TANK_PRIMARY_RESONANT_INDUCTANCE_H = real2param(20e-6);

% Secondary-side resonant inductance.
DIOSCURI_CLLLC_TANK_SECONDARY_RESONANT_INDUCTANCE_H = real2param(20e-6);

% Primary-side resonant capacitance.
DIOSCURI_CLLLC_TANK_PRIMARY_RESONANT_CAPACITANCE_F = real2param(120e-9);

% Secondary-side resonant capacitance.
DIOSCURI_CLLLC_TANK_SECONDARY_RESONANT_CAPACITANCE_F = real2param(120e-9);

% Transformer secondary-to-primary turns ratio.
DIOSCURI_CLLLC_TANK_TRANSFORMER_RATIO_NS_NP = real2param(1.0);

% Output capacitance.
DIOSCURI_CLLLC_TANK_OUTPUT_CAPACITANCE_F = real2param(440e-6);

% Minimum supported load resistance.
DIOSCURI_CLLLC_TANK_MINIMUM_LOAD_RESISTANCE_OHM = real2param(10.0);

% Aggregate resonant-tank series resistance used by the plant model.
DIOSCURI_CLLLC_TANK_TANK_ESR_OHM = real2param(0.1);

%% Sensing
% Calibrate the TMCS1133B5A zero-current bias while all PWM outputs are disabled.
SPECIFY_ENABLE_ADC_CALIBRATE = true;

%% Requirement bindings
% Enable the five ADC slots used by the CLLLC SIL input ABI.
GMP_PIL_RX_MASK = 31;

% Enable eight modulation slots and seven monitor slots used by the CLLLC SIL output ABI.
GMP_PIL_TX_MASK = 8323327;

% Nominal tank resonant frequency.
CLLLC_F_RESONANT_HZ = DIOSCURI_CLLLC_TANK_RESONANT_FREQUENCY_HZ;

% Lowest allowed hybrid modulation frequency.
CLLLC_F_MIN_HZ = real2param(75000.0);

% Highest allowed hybrid modulation frequency.
CLLLC_F_MAX_HZ = real2param(150000.0);

% Absolute complementary-switch dead time.
CLLLC_DEADBAND_S = real2param(200e-9);

% Maximum signed primary-to-secondary bridge phase displacement, where 1 pu is 360 degrees.
CLLLC_MAX_PHASE_SHIFT_PU = real2param(0.25);

% Transformer magnetizing inductance.
CLLLC_LM_H = DIOSCURI_CLLLC_TANK_MAGNETIZING_INDUCTANCE_H;

% Primary resonant inductance.
CLLLC_LR_PRIMARY_H = DIOSCURI_CLLLC_TANK_PRIMARY_RESONANT_INDUCTANCE_H;

% Secondary resonant inductance.
CLLLC_LR_SECONDARY_H = DIOSCURI_CLLLC_TANK_SECONDARY_RESONANT_INDUCTANCE_H;

% Primary resonant capacitance.
CLLLC_CR_PRIMARY_F = DIOSCURI_CLLLC_TANK_PRIMARY_RESONANT_CAPACITANCE_F;

% Secondary resonant capacitance.
CLLLC_CR_SECONDARY_F = DIOSCURI_CLLLC_TANK_SECONDARY_RESONANT_CAPACITANCE_F;

% Secondary-to-primary turns ratio.
CLLLC_TRANSFORMER_NS_NP = DIOSCURI_CLLLC_TANK_TRANSFORMER_RATIO_NS_NP;

% Equivalent output capacitance.
CLLLC_COUT_F = DIOSCURI_CLLLC_TANK_OUTPUT_CAPACITANCE_F;

% Minimum resistive load used for conservative tuning.
CLLLC_RLOAD_MIN_OHM = DIOSCURI_CLLLC_TANK_MINIMUM_LOAD_RESISTANCE_OHM;

% Equivalent resonant-tank series resistance.
CLLLC_TANK_ESR_OHM = DIOSCURI_CLLLC_TANK_TANK_ESR_OHM;

% Voltage per-unit base.
CTRL_VOLTAGE_BASE = real2param(120.0);

% Current per-unit base, kept within the TMCS1133B5A rated measurement range.
CTRL_CURRENT_BASE = real2param(10.0);

% AMC1311 board-level ADC sensitivity.
CLLLC_VOLTAGE_SENSITIVITY_V_PER_V = DIOSCURI_VOLTAGE_SENSOR_SENSITIVITY_V_PER_V;

% Unidirectional AMC1311 board-level ADC bias.
CLLLC_VOLTAGE_BIAS_V = DIOSCURI_VOLTAGE_SENSOR_BIAS_V;

% AMC1311 front-end full-scale voltage.
CLLLC_VOLTAGE_SENSOR_RANGE_V = DIOSCURI_VOLTAGE_SENSOR_RATED_VOLTAGE_V;

% TMCS1133B5A sensitivity.
CLLLC_CURRENT_SENSITIVITY_V_PER_A = TMCS1133_B5A_SENSITIVITY_V_PER_A;

% TMCS1133B5A zero-current output bias.
CLLLC_CURRENT_BIAS_V = TMCS1133_B5A_BIAS_V;

% TMCS1133B5A rated current range.
CLLLC_CURRENT_SENSOR_RANGE_A = TMCS1133_B5A_RANGE_A;

% Default secondary voltage reference.
CLLLC_VOLTAGE_TARGET_PU = real2param(0.40);

% Current-loop reference and parallel current limit.
CLLLC_CURRENT_TARGET_PU = real2param(0.50);

% Requested current-loop bandwidth, constrained by CLLLC auto tuning.
CLLLC_CURRENT_LOOP_BW_HZ = real2param(5000.0);

% Requested voltage-loop bandwidth, constrained below the current loop.
CLLLC_VOLTAGE_LOOP_BW_HZ = real2param(400.0);

% Voltage-reference slew rate.
CLLLC_VOLTAGE_SLOPE_PU_S = real2param(0.5);

% Current-reference slew rate.
CLLLC_CURRENT_SLOPE_PU_S = real2param(1.0);

% Maximum current-sensor offset calibration time.
TIMEOUT_ADC_CALIB_MS = 3000;

%% SDPE project summary
fprintf('\n============================================================\n');
fprintf('SDPE Project : %s\n', 'DPS CLLLC / DAB Common Control');
fprintf('Project ID   : %s\n', 'dps_clllc_common');
fprintf('Suite        : %s\n', 'dps_clllc');
fprintf('Version      : %s\n', '1.0.0');
fprintf('Hardware (3):\n');
fprintf('  - %s\n', 'tmcs1133_b5a');
fprintf('  - %s\n', 'dioscuri_voltage_sensor');
fprintf('  - %s\n', 'dioscuri_clllc_resonant_tank');
fprintf('Common requirements (0):\n');
fprintf('Enabled variables (73):\n');
fprintf('  CLLLC_COUT_F = '); disp(CLLLC_COUT_F);
fprintf('  CLLLC_CR_PRIMARY_F = '); disp(CLLLC_CR_PRIMARY_F);
fprintf('  CLLLC_CR_SECONDARY_F = '); disp(CLLLC_CR_SECONDARY_F);
fprintf('  CLLLC_CURRENT_BIAS_V = '); disp(CLLLC_CURRENT_BIAS_V);
fprintf('  CLLLC_CURRENT_LOOP_BW_HZ = '); disp(CLLLC_CURRENT_LOOP_BW_HZ);
fprintf('  CLLLC_CURRENT_SENSITIVITY_V_PER_A = '); disp(CLLLC_CURRENT_SENSITIVITY_V_PER_A);
fprintf('  CLLLC_CURRENT_SENSOR_RANGE_A = '); disp(CLLLC_CURRENT_SENSOR_RANGE_A);
fprintf('  CLLLC_CURRENT_SLOPE_PU_S = '); disp(CLLLC_CURRENT_SLOPE_PU_S);
fprintf('  CLLLC_CURRENT_TARGET_PU = '); disp(CLLLC_CURRENT_TARGET_PU);
fprintf('  CLLLC_DEADBAND_S = '); disp(CLLLC_DEADBAND_S);
fprintf('  CLLLC_F_MAX_HZ = '); disp(CLLLC_F_MAX_HZ);
fprintf('  CLLLC_F_MIN_HZ = '); disp(CLLLC_F_MIN_HZ);
fprintf('  CLLLC_F_RESONANT_HZ = '); disp(CLLLC_F_RESONANT_HZ);
fprintf('  CLLLC_LM_H = '); disp(CLLLC_LM_H);
fprintf('  CLLLC_LR_PRIMARY_H = '); disp(CLLLC_LR_PRIMARY_H);
fprintf('  CLLLC_LR_SECONDARY_H = '); disp(CLLLC_LR_SECONDARY_H);
fprintf('  CLLLC_MAX_PHASE_SHIFT_PU = '); disp(CLLLC_MAX_PHASE_SHIFT_PU);
fprintf('  CLLLC_RLOAD_MIN_OHM = '); disp(CLLLC_RLOAD_MIN_OHM);
fprintf('  CLLLC_TANK_ESR_OHM = '); disp(CLLLC_TANK_ESR_OHM);
fprintf('  CLLLC_TRANSFORMER_NS_NP = '); disp(CLLLC_TRANSFORMER_NS_NP);
fprintf('  CLLLC_VOLTAGE_BIAS_V = '); disp(CLLLC_VOLTAGE_BIAS_V);
fprintf('  CLLLC_VOLTAGE_LOOP_BW_HZ = '); disp(CLLLC_VOLTAGE_LOOP_BW_HZ);
fprintf('  CLLLC_VOLTAGE_SENSITIVITY_V_PER_V = '); disp(CLLLC_VOLTAGE_SENSITIVITY_V_PER_V);
fprintf('  CLLLC_VOLTAGE_SENSOR_RANGE_V = '); disp(CLLLC_VOLTAGE_SENSOR_RANGE_V);
fprintf('  CLLLC_VOLTAGE_SLOPE_PU_S = '); disp(CLLLC_VOLTAGE_SLOPE_PU_S);
fprintf('  CLLLC_VOLTAGE_TARGET_PU = '); disp(CLLLC_VOLTAGE_TARGET_PU);
fprintf('  CTRL_CURRENT_BASE = '); disp(CTRL_CURRENT_BASE);
fprintf('  CTRL_VOLTAGE_BASE = '); disp(CTRL_VOLTAGE_BASE);
fprintf('  DIOSCURI_CLLLC_TANK_ID = '); disp(DIOSCURI_CLLLC_TANK_ID);
fprintf('  DIOSCURI_CLLLC_TANK_MAGNETIZING_INDUCTANCE_H = '); disp(DIOSCURI_CLLLC_TANK_MAGNETIZING_INDUCTANCE_H);
fprintf('  DIOSCURI_CLLLC_TANK_MINIMUM_LOAD_RESISTANCE_OHM = '); disp(DIOSCURI_CLLLC_TANK_MINIMUM_LOAD_RESISTANCE_OHM);
fprintf('  DIOSCURI_CLLLC_TANK_NAME = '); disp(DIOSCURI_CLLLC_TANK_NAME);
fprintf('  DIOSCURI_CLLLC_TANK_OUTPUT_CAPACITANCE_F = '); disp(DIOSCURI_CLLLC_TANK_OUTPUT_CAPACITANCE_F);
fprintf('  DIOSCURI_CLLLC_TANK_PRIMARY_RESONANT_CAPACITANCE_F = '); disp(DIOSCURI_CLLLC_TANK_PRIMARY_RESONANT_CAPACITANCE_F);
fprintf('  DIOSCURI_CLLLC_TANK_PRIMARY_RESONANT_INDUCTANCE_H = '); disp(DIOSCURI_CLLLC_TANK_PRIMARY_RESONANT_INDUCTANCE_H);
fprintf('  DIOSCURI_CLLLC_TANK_RESONANT_FREQUENCY_HZ = '); disp(DIOSCURI_CLLLC_TANK_RESONANT_FREQUENCY_HZ);
fprintf('  DIOSCURI_CLLLC_TANK_SCHEMA = '); disp(DIOSCURI_CLLLC_TANK_SCHEMA);
fprintf('  DIOSCURI_CLLLC_TANK_SECONDARY_RESONANT_CAPACITANCE_F = '); disp(DIOSCURI_CLLLC_TANK_SECONDARY_RESONANT_CAPACITANCE_F);
fprintf('  DIOSCURI_CLLLC_TANK_SECONDARY_RESONANT_INDUCTANCE_H = '); disp(DIOSCURI_CLLLC_TANK_SECONDARY_RESONANT_INDUCTANCE_H);
fprintf('  DIOSCURI_CLLLC_TANK_TANK_ESR_OHM = '); disp(DIOSCURI_CLLLC_TANK_TANK_ESR_OHM);
fprintf('  DIOSCURI_CLLLC_TANK_TRANSFORMER_RATIO_NS_NP = '); disp(DIOSCURI_CLLLC_TANK_TRANSFORMER_RATIO_NS_NP);
fprintf('  DIOSCURI_VOLTAGE_SENSOR_BANDWIDTH_HZ = '); disp(DIOSCURI_VOLTAGE_SENSOR_BANDWIDTH_HZ);
fprintf('  DIOSCURI_VOLTAGE_SENSOR_BIAS_V = '); disp(DIOSCURI_VOLTAGE_SENSOR_BIAS_V);
fprintf('  DIOSCURI_VOLTAGE_SENSOR_CHIP = '); disp(DIOSCURI_VOLTAGE_SENSOR_CHIP);
fprintf('  DIOSCURI_VOLTAGE_SENSOR_ID = '); disp(DIOSCURI_VOLTAGE_SENSOR_ID);
fprintf('  DIOSCURI_VOLTAGE_SENSOR_INPUT_RESISTANCE_OHM = '); disp(DIOSCURI_VOLTAGE_SENSOR_INPUT_RESISTANCE_OHM);
fprintf('  DIOSCURI_VOLTAGE_SENSOR_MAX_BY_BIAS_V = '); disp(DIOSCURI_VOLTAGE_SENSOR_MAX_BY_BIAS_V);
fprintf('  DIOSCURI_VOLTAGE_SENSOR_NAME = '); disp(DIOSCURI_VOLTAGE_SENSOR_NAME);
fprintf('  DIOSCURI_VOLTAGE_SENSOR_RATED_VOLTAGE_V = '); disp(DIOSCURI_VOLTAGE_SENSOR_RATED_VOLTAGE_V);
fprintf('  DIOSCURI_VOLTAGE_SENSOR_SCHEMA = '); disp(DIOSCURI_VOLTAGE_SENSOR_SCHEMA);
fprintf('  DIOSCURI_VOLTAGE_SENSOR_SENSITIVITY_V_PER_V = '); disp(DIOSCURI_VOLTAGE_SENSOR_SENSITIVITY_V_PER_V);
fprintf('  DPS_CLLLC_COMMON_SDPE_PROJECT_ID = '); disp(DPS_CLLLC_COMMON_SDPE_PROJECT_ID);
fprintf('  DPS_CLLLC_COMMON_SDPE_PROJECT_SUITE = '); disp(DPS_CLLLC_COMMON_SDPE_PROJECT_SUITE);
fprintf('  DPS_CLLLC_COMMON_SDPE_PROJECT_UPDATED_AT = '); disp(DPS_CLLLC_COMMON_SDPE_PROJECT_UPDATED_AT);
fprintf('  DPS_CLLLC_COMMON_SDPE_PROJECT_VERSION = '); disp(DPS_CLLLC_COMMON_SDPE_PROJECT_VERSION);
fprintf('  GMP_PIL_RX_MASK = '); disp(GMP_PIL_RX_MASK);
fprintf('  GMP_PIL_TX_MASK = '); disp(GMP_PIL_TX_MASK);
fprintf('  SPECIFY_ENABLE_ADC_CALIBRATE = '); disp(SPECIFY_ENABLE_ADC_CALIBRATE);
fprintf('  TIMEOUT_ADC_CALIB_MS = '); disp(TIMEOUT_ADC_CALIB_MS);
fprintf('  TMCS1133_B5A_BANDWIDTH_HZ = '); disp(TMCS1133_B5A_BANDWIDTH_HZ);
fprintf('  TMCS1133_B5A_BIAS_V = '); disp(TMCS1133_B5A_BIAS_V);
fprintf('  TMCS1133_B5A_CHIP = '); disp(TMCS1133_B5A_CHIP);
fprintf('  TMCS1133_B5A_ID = '); disp(TMCS1133_B5A_ID);
fprintf('  TMCS1133_B5A_INTERNAL_RESISTANCE_OHM = '); disp(TMCS1133_B5A_INTERNAL_RESISTANCE_OHM);
fprintf('  TMCS1133_B5A_MAX_CURRENT_FROM_BIAS_A = '); disp(TMCS1133_B5A_MAX_CURRENT_FROM_BIAS_A);
fprintf('  TMCS1133_B5A_NAME = '); disp(TMCS1133_B5A_NAME);
fprintf('  TMCS1133_B5A_OUTPUT_MAX_V = '); disp(TMCS1133_B5A_OUTPUT_MAX_V);
fprintf('  TMCS1133_B5A_OUTPUT_MIN_V = '); disp(TMCS1133_B5A_OUTPUT_MIN_V);
fprintf('  TMCS1133_B5A_RANGE_A = '); disp(TMCS1133_B5A_RANGE_A);
fprintf('  TMCS1133_B5A_SCHEMA = '); disp(TMCS1133_B5A_SCHEMA);
fprintf('  TMCS1133_B5A_SENSITIVITY_MV_PER_A = '); disp(TMCS1133_B5A_SENSITIVITY_MV_PER_A);
fprintf('  TMCS1133_B5A_SENSITIVITY_V_PER_A = '); disp(TMCS1133_B5A_SENSITIVITY_V_PER_A);
fprintf('  TMCS1133_B5A_SENSOR_TYPE = '); disp(TMCS1133_B5A_SENSOR_TYPE);
fprintf('Disabled macros (0):\n');
fprintf('============================================================\n');

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
