# This file is generated by the GMP source manager. Do not edit it manually.

if(NOT DEFINED ENV{GMP_PRO_LOCATION})
    message(FATAL_ERROR "GMP_PRO_LOCATION is not defined. Install or activate GMP first.")
endif()
file(TO_CMAKE_PATH "$ENV{GMP_PRO_LOCATION}" GMP_PRO_ROOT)

if(NOT DEFINED GMP_CMAKE_TARGET)
    set(GMP_CMAKE_TARGET "${CMAKE_PROJECT_NAME}")
endif()
if(NOT TARGET ${GMP_CMAKE_TARGET})
    message(FATAL_ERROR "GMP target '${GMP_CMAKE_TARGET}' does not exist. Include this file after add_executable/add_library.")
endif()

set(GMP_GENERATED_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/gmp_src/crc16.c"
    "${CMAKE_CURRENT_LIST_DIR}/gmp_src/gmp_can_service.c"
    "${CMAKE_CURRENT_LIST_DIR}/gmp_src/gmp_dev_util.c"
    "${CMAKE_CURRENT_LIST_DIR}/gmp_src/gmp_process_mgr.c"
    "${CMAKE_CURRENT_LIST_DIR}/gmp_src/gmp_std_error_code.c"
    "${CMAKE_CURRENT_LIST_DIR}/gmp_src/gmp_std_port.c"
    "${CMAKE_CURRENT_LIST_DIR}/gmp_src/rpi_pico_common.c"
    "${CMAKE_CURRENT_LIST_DIR}/gmp_src/rpi_pico_peripheral.c"
    "${CMAKE_CURRENT_LIST_DIR}/../user/ctl_main.c"
    "${CMAKE_CURRENT_LIST_DIR}/../user/user_main.c"
    "${CMAKE_CURRENT_LIST_DIR}/../xplt/xplt.peripheral.c"
)
target_sources(${GMP_CMAKE_TARGET} PRIVATE ${GMP_GENERATED_SOURCES})

target_include_directories(${GMP_CMAKE_TARGET} PRIVATE
    "${CMAKE_CURRENT_LIST_DIR}/../user"
    "${CMAKE_CURRENT_LIST_DIR}/../xplt"
    "${GMP_PRO_ROOT}"
    "${GMP_PRO_ROOT}/csp/rpi_pico"
)

target_link_libraries(${GMP_CMAKE_TARGET} PRIVATE
    "hardware_gpio"
    "hardware_i2c"
    "hardware_spi"
    "hardware_uart"
    "hardware_watchdog"
    "pico_stdlib"
)
