# CMake generated Testfile for 
# Source directory: E:/lib/gmp_pro/ctl/math_block/tests
# Build directory: E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[gmp_numeric_float_float]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/Debug/gmp_numeric_float_float.exe")
  set_tests_properties([=[gmp_numeric_float_float]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;37;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;40;add_gmp_numeric_contract;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[gmp_numeric_float_float]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/Release/gmp_numeric_float_float.exe")
  set_tests_properties([=[gmp_numeric_float_float]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;37;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;40;add_gmp_numeric_contract;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[gmp_numeric_float_float]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/MinSizeRel/gmp_numeric_float_float.exe")
  set_tests_properties([=[gmp_numeric_float_float]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;37;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;40;add_gmp_numeric_contract;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[gmp_numeric_float_float]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/RelWithDebInfo/gmp_numeric_float_float.exe")
  set_tests_properties([=[gmp_numeric_float_float]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;37;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;40;add_gmp_numeric_contract;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
else()
  add_test([=[gmp_numeric_float_float]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[gmp_numeric_float_double]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/Debug/gmp_numeric_float_double.exe")
  set_tests_properties([=[gmp_numeric_float_double]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;37;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;41;add_gmp_numeric_contract;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[gmp_numeric_float_double]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/Release/gmp_numeric_float_double.exe")
  set_tests_properties([=[gmp_numeric_float_double]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;37;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;41;add_gmp_numeric_contract;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[gmp_numeric_float_double]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/MinSizeRel/gmp_numeric_float_double.exe")
  set_tests_properties([=[gmp_numeric_float_double]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;37;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;41;add_gmp_numeric_contract;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[gmp_numeric_float_double]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/RelWithDebInfo/gmp_numeric_float_double.exe")
  set_tests_properties([=[gmp_numeric_float_double]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;37;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;41;add_gmp_numeric_contract;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
else()
  add_test([=[gmp_numeric_float_double]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[gmp_numeric_double_double]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/Debug/gmp_numeric_double_double.exe")
  set_tests_properties([=[gmp_numeric_double_double]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;37;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;42;add_gmp_numeric_contract;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[gmp_numeric_double_double]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/Release/gmp_numeric_double_double.exe")
  set_tests_properties([=[gmp_numeric_double_double]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;37;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;42;add_gmp_numeric_contract;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[gmp_numeric_double_double]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/MinSizeRel/gmp_numeric_double_double.exe")
  set_tests_properties([=[gmp_numeric_double_double]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;37;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;42;add_gmp_numeric_contract;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[gmp_numeric_double_double]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/RelWithDebInfo/gmp_numeric_double_double.exe")
  set_tests_properties([=[gmp_numeric_double_double]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;37;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;42;add_gmp_numeric_contract;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
else()
  add_test([=[gmp_numeric_double_double]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[gmp_numeric_iq24_float]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/Debug/gmp_numeric_iq24_float.exe")
  set_tests_properties([=[gmp_numeric_iq24_float]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;68;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[gmp_numeric_iq24_float]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/Release/gmp_numeric_iq24_float.exe")
  set_tests_properties([=[gmp_numeric_iq24_float]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;68;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[gmp_numeric_iq24_float]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/MinSizeRel/gmp_numeric_iq24_float.exe")
  set_tests_properties([=[gmp_numeric_iq24_float]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;68;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[gmp_numeric_iq24_float]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/RelWithDebInfo/gmp_numeric_iq24_float.exe")
  set_tests_properties([=[gmp_numeric_iq24_float]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;68;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
else()
  add_test([=[gmp_numeric_iq24_float]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[gmp_numeric_iq24_double]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/Debug/gmp_numeric_iq24_double.exe")
  set_tests_properties([=[gmp_numeric_iq24_double]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;68;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[gmp_numeric_iq24_double]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/Release/gmp_numeric_iq24_double.exe")
  set_tests_properties([=[gmp_numeric_iq24_double]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;68;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[gmp_numeric_iq24_double]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/MinSizeRel/gmp_numeric_iq24_double.exe")
  set_tests_properties([=[gmp_numeric_iq24_double]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;68;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[gmp_numeric_iq24_double]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/RelWithDebInfo/gmp_numeric_iq24_double.exe")
  set_tests_properties([=[gmp_numeric_iq24_double]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;68;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
else()
  add_test([=[gmp_numeric_iq24_double]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[gmp_lite_algebra]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/Debug/gmp_lite_algebra.exe")
  set_tests_properties([=[gmp_lite_algebra]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;73;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[gmp_lite_algebra]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/Release/gmp_lite_algebra.exe")
  set_tests_properties([=[gmp_lite_algebra]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;73;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[gmp_lite_algebra]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/MinSizeRel/gmp_lite_algebra.exe")
  set_tests_properties([=[gmp_lite_algebra]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;73;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[gmp_lite_algebra]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/RelWithDebInfo/gmp_lite_algebra.exe")
  set_tests_properties([=[gmp_lite_algebra]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;73;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
else()
  add_test([=[gmp_lite_algebra]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[gmp_sinv_qr_contract]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/Debug/gmp_sinv_qr_contract.exe")
  set_tests_properties([=[gmp_sinv_qr_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;84;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[gmp_sinv_qr_contract]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/Release/gmp_sinv_qr_contract.exe")
  set_tests_properties([=[gmp_sinv_qr_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;84;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[gmp_sinv_qr_contract]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/MinSizeRel/gmp_sinv_qr_contract.exe")
  set_tests_properties([=[gmp_sinv_qr_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;84;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[gmp_sinv_qr_contract]=] "E:/lib/gmp_pro/ctl/math_block/tests/.build/cmake/RelWithDebInfo/gmp_sinv_qr_contract.exe")
  set_tests_properties([=[gmp_sinv_qr_contract]=] PROPERTIES  _BACKTRACE_TRIPLES "E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;84;add_test;E:/lib/gmp_pro/ctl/math_block/tests/CMakeLists.txt;0;")
else()
  add_test([=[gmp_sinv_qr_contract]=] NOT_AVAILABLE)
endif()
