/**
 * @file tle4971a025.h
 * @brief SDPE hardware preset for TLE4971A025 Coreless Hall Current Sensor.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _CURRENT_SENSOR_TLE4971A025_H_
#define _CURRENT_SENSOR_TLE4971A025_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_tle4971a025 TLE4971A025 Coreless Hall Current Sensor
 * @{
 */

// Identification
#define TLE4971A025_ID "tle4971a025"
#define TLE4971A025_SCHEMA "current_sensor"
#define TLE4971A025_NAME "TLE4971A025 Coreless Hall Current Sensor"

// Tags: coreless, current_sensor, hall, sensor, tle4971

/*
 * Schema: Basic current sensor model used to scale ADC voltage into current.
 * Vendor: Infineon
 * Datasheet: https://www.infineon.com/cms/en/product/sensor/current-sensors/tle4971/
 * Document: ctl/component/hardware_preset/current_sensor/TLE4971A.h
 */

// Parameter macros
/**
 * @brief Main sensing IC or technology name.
 */
#define TLE4971A025_CHIP "TLE4971A025"

/**
 * @brief Current sensing technology, such as Hall, shunt, or fluxgate.
 */
#define TLE4971A025_SENSOR_TYPE "Coreless Hall"

/**
 * @brief Nominal measurable current range.
 * @unit A
 */
#define TLE4971A025_RANGE_A (25.0f)

/**
 * @brief Minimum output voltage.
 * @unit V
 */
#define TLE4971A025_OUTPUT_MIN_V (0.0f)

/**
 * @brief Maximum output voltage.
 * @unit V
 */
#define TLE4971A025_OUTPUT_MAX_V (3.3f)

/**
 * @brief Zero-current output bias.
 * @unit V
 */
#define TLE4971A025_BIAS_V (1.65f)

/**
 * @brief Current sensor sensitivity.
 * @unit mV/A
 */
#define TLE4971A025_SENSITIVITY_MV_PER_A (48.0f)

/**
 * @brief Typical small-signal bandwidth.
 * @unit Hz
 */
#define TLE4971A025_BANDWIDTH_HZ (210000.0f)

/**
 * @brief Sensor internal series resistance.
 * @unit ohm
 */
#define TLE4971A025_INTERNAL_RESISTANCE_OHM (0.0f)

// Derived macros
/**
 * @brief Current sensor sensitivity converted to V/A.
 * @unit V/A
 */
#define TLE4971A025_SENSITIVITY_V_PER_A (TLE4971A025_SENSITIVITY_MV_PER_A / 1000.0f)

/**
 * @brief Positive current range implied by bias and sensitivity.
 * @unit A
 */
#define TLE4971A025_MAX_CURRENT_FROM_BIAS_A (TLE4971A025_BIAS_V / TLE4971A025_SENSITIVITY_V_PER_A)

// Logical exports
// sensitivity: TLE4971A025_SENSITIVITY_V_PER_A
// bias: TLE4971A025_BIAS_V
// range: TLE4971A025_RANGE_A

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _CURRENT_SENSOR_TLE4971A025_H_
