/**
 * @file controlcard_f28388d.h
 * @brief SDPE hardware preset for TMDSCNCD28388D ControlCARD.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _MCU_BOARD_CONTROLCARD_F28388D_H_
#define _MCU_BOARD_CONTROLCARD_F28388D_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_controlcard_f28388d TMDSCNCD28388D ControlCARD
 * @{
 */

// Identification
#define CONTROLCARD_F28388D_ID "controlcard_f28388d"
#define CONTROLCARD_F28388D_SCHEMA "controlcard_f28388d_board"
#define CONTROLCARD_F28388D_NAME "TMDSCNCD28388D ControlCARD"

// Tags: c2000, communication-manager, controlcard, f28388d, tricore

/*
 * Schema: Three-core control and communication resource contract for the F28388D ControlCARD.
 */

// Parameter macros
/**
 * @brief ControlCARD board name.
 */
#define CONTROLCARD_F28388D_BOARD_NAME "TMDSCNCD28388D"

/**
 * @brief C2000 device.
 */
#define CONTROLCARD_F28388D_CHIP "TMS320F28388D"

/**
 * @brief CPU1 and CPU2 clock contract.
 * @unit Hz
 */
#define CONTROLCARD_F28388D_CPU_CLOCK_HZ (200000000UL)

/**
 * @brief Communication Manager clock contract.
 * @unit Hz
 */
#define CONTROLCARD_F28388D_CM_CLOCK_HZ (125000000UL)

/**
 * @brief GMP byte/data_gt width shared by all three cores.
 * @unit bit
 */
#define CONTROLCARD_F28388D_DATA_UNIT_BITS (16U)

/**
 * @brief CPU1 runtime responsibility.
 */
#define CONTROLCARD_F28388D_CPU1_ROLE "control and serial DL"

/**
 * @brief CPU2 runtime responsibility.
 */
#define CONTROLCARD_F28388D_CPU2_ROLE "deterministic computation"

/**
 * @brief CM runtime responsibility.
 */
#define CONTROLCARD_F28388D_CM_ROLE "USB Ethernet EtherCAT communication"

/**
 * @brief XDS virtual COM SCI base.
 */
#define CONTROLCARD_F28388D_SERIAL_BASE SCIA_BASE

/**
 * @brief GMP serial Data Link baud rate.
 * @unit baud
 */
#define CONTROLCARD_F28388D_SERIAL_BAUDRATE (115200UL)

/**
 * @brief Three-phase complementary PWM frequency.
 * @unit Hz
 */
#define CONTROLCARD_F28388D_PWM_FREQUENCY_HZ (20000UL)

/**
 * @brief Number of complementary ePWM pairs.
 */
#define CONTROLCARD_F28388D_PWM_PHASE_COUNT (3U)

/**
 * @brief ABZ encoder interface.
 */
#define CONTROLCARD_F28388D_QEP_BASE EQEP1_BASE

/**
 * @brief ePWM-triggered external feedback channels.
 */
#define CONTROLCARD_F28388D_ADC_CHANNEL_COUNT (6U)

/**
 * @brief Initialized user LEDs.
 */
#define CONTROLCARD_F28388D_LED_COUNT (2U)

/**
 * @brief Board control I2C interface.
 */
#define CONTROLCARD_F28388D_I2C_BASE I2CA_BASE

/**
 * @brief ControlCARD SD socket SPI interface.
 */
#define CONTROLCARD_F28388D_SD_SPI_BASE SPIC_BASE

/**
 * @brief Available debug DAC outputs.
 */
#define CONTROLCARD_F28388D_DAC_COUNT (3U)

/**
 * @brief CM-owned USB controller is enabled.
 */
#define CONTROLCARD_F28388D_HAS_USB (1U)

/**
 * @brief CM-owned Ethernet MAC is enabled.
 */
#define CONTROLCARD_F28388D_HAS_ETHERNET (1U)

/**
 * @brief CM-owned EtherCAT subsystem is enabled.
 */
#define CONTROLCARD_F28388D_HAS_ETHERCAT (1U)

/**
 * @brief Static IPv4 address in network byte order.
 */
#define CONTROLCARD_F28388D_ETHERNET_IPV4 (0xC0A88902UL)

/**
 * @brief GMP DL TCP service port.
 */
#define CONTROLCARD_F28388D_TCP_PORT (50001U)

/**
 * @brief GMP DL UDP service port.
 */
#define CONTROLCARD_F28388D_UDP_PORT (50002U)

// Logical exports
// board_name: CONTROLCARD_F28388D_BOARD_NAME
// cpu_clock_hz: CONTROLCARD_F28388D_CPU_CLOCK_HZ
// data_unit_bits: CONTROLCARD_F28388D_DATA_UNIT_BITS
// serial_base: CONTROLCARD_F28388D_SERIAL_BASE
// serial_baudrate: CONTROLCARD_F28388D_SERIAL_BAUDRATE
// pwm_frequency_hz: CONTROLCARD_F28388D_PWM_FREQUENCY_HZ
// qep_base: CONTROLCARD_F28388D_QEP_BASE
// adc_channel_count: CONTROLCARD_F28388D_ADC_CHANNEL_COUNT
// has_usb: CONTROLCARD_F28388D_HAS_USB
// has_ethernet: CONTROLCARD_F28388D_HAS_ETHERNET
// has_ethercat: CONTROLCARD_F28388D_HAS_ETHERCAT
// ethernet_ipv4: CONTROLCARD_F28388D_ETHERNET_IPV4
// tcp_port: CONTROLCARD_F28388D_TCP_PORT
// udp_port: CONTROLCARD_F28388D_UDP_PORT

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _MCU_BOARD_CONTROLCARD_F28388D_H_
