/**
 * @file stgib20m60ts_l.h
 * @brief SDPE hardware preset for STGIB20M60TS-L SLLIMM 2nd Series IPM.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _INTEGRATED_POWER_MODULE_STGIB20M60TS_L_H_
#define _INTEGRATED_POWER_MODULE_STGIB20M60TS_L_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_stgib20m60ts_l STGIB20M60TS-L SLLIMM 2nd Series IPM
 * @{
 */

// Identification
#define STGIB20M60TS_L_ID "stgib20m60ts_l"
#define STGIB20M60TS_L_SCHEMA "integrated_power_module"
#define STGIB20M60TS_L_NAME "STGIB20M60TS-L SLLIMM 2nd Series IPM"

// Tags: igbt, ipm, power_device, st, three_phase

/*
 * Schema: Three-phase intelligent power module containing switches, drivers and protection.
 * Vendor: STMicroelectronics
 * Datasheet: https://www.st.com/resource/en/datasheet/stgib20m60ts-l.pdf
 */

// Parameter macros
/**
 * @brief Manufacturer part number.
 */
#define STGIB20M60TS_L_PART_NUMBER "STGIB20M60TS-L"

/**
 * @brief IGBT, MOSFET, GaN, etc.
 */
#define STGIB20M60TS_L_SWITCH_TECHNOLOGY "IGBT"

/**
 * @brief Integrated inverter phase count.
 */
#define STGIB20M60TS_L_PHASE_COUNT (3U)

/**
 * @brief Switch blocking voltage.
 * @unit V
 */
#define STGIB20M60TS_L_VOLTAGE_RATING_V (600.0f)

/**
 * @brief Continuous current per switch under datasheet conditions.
 * @unit A
 */
#define STGIB20M60TS_L_CURRENT_RATING_A (25.0f)

/**
 * @brief Peak current per switch.
 * @unit A
 */
#define STGIB20M60TS_L_PEAK_CURRENT_A (50.0f)

/**
 * @brief One for active-high logic, zero for active-low.
 */
#define STGIB20M60TS_L_INPUT_ACTIVE_LEVEL (1U)

/**
 * @brief Integrated current-sense op amp availability.
 */
#define STGIB20M60TS_L_HAS_CURRENT_OPAMP (1U)

/**
 * @brief Temperature signal availability.
 */
#define STGIB20M60TS_L_HAS_TEMPERATURE_OUTPUT (1U)

/**
 * @brief Manufacturer package.
 */
#define STGIB20M60TS_L_PACKAGE "SDIP2B-26L"

// Logical exports
// voltage_rating: STGIB20M60TS_L_VOLTAGE_RATING_V
// current_rating: STGIB20M60TS_L_CURRENT_RATING_A

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _INTEGRATED_POWER_MODULE_STGIB20M60TS_L_H_
