/**
 * @file stgipq8c60t_hz.h
 * @brief SDPE hardware preset for STGIPQ8C60T-HZ SLLIMM-nano 2 IPM.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _INTEGRATED_POWER_MODULE_STGIPQ8C60T_HZ_H_
#define _INTEGRATED_POWER_MODULE_STGIPQ8C60T_HZ_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_stgipq8c60t_hz STGIPQ8C60T-HZ SLLIMM-nano 2 IPM
 * @{
 */

// Identification
#define STGIPQ8C60T_HZ_ID "stgipq8c60t_hz"
#define STGIPQ8C60T_HZ_SCHEMA "integrated_power_module"
#define STGIPQ8C60T_HZ_NAME "STGIPQ8C60T-HZ SLLIMM-nano 2 IPM"

// Tags: igbt, ipm, power_device, st, three_phase

/*
 * Schema: Three-phase intelligent power module containing switches, drivers and protection.
 * Vendor: STMicroelectronics
 * Datasheet: https://www.st.com/resource/en/datasheet/stgipq8c60t-hz.pdf
 */

// Parameter macros
/**
 * @brief Manufacturer part number.
 */
#define STGIPQ8C60T_HZ_PART_NUMBER "STGIPQ8C60T-HZ"

/**
 * @brief IGBT, MOSFET, GaN, etc.
 */
#define STGIPQ8C60T_HZ_SWITCH_TECHNOLOGY "IGBT"

/**
 * @brief Integrated inverter phase count.
 */
#define STGIPQ8C60T_HZ_PHASE_COUNT (3U)

/**
 * @brief Switch blocking voltage.
 * @unit V
 */
#define STGIPQ8C60T_HZ_VOLTAGE_RATING_V (600.0f)

/**
 * @brief Continuous current per switch under datasheet conditions.
 * @unit A
 */
#define STGIPQ8C60T_HZ_CURRENT_RATING_A (8.0f)

/**
 * @brief Peak current per switch.
 * @unit A
 */
#define STGIPQ8C60T_HZ_PEAK_CURRENT_A (10.2f)

/**
 * @brief One for active-high logic, zero for active-low.
 */
#define STGIPQ8C60T_HZ_INPUT_ACTIVE_LEVEL (1U)

/**
 * @brief Integrated current-sense op amp availability.
 */
#define STGIPQ8C60T_HZ_HAS_CURRENT_OPAMP (1U)

/**
 * @brief Temperature signal availability.
 */
#define STGIPQ8C60T_HZ_HAS_TEMPERATURE_OUTPUT (1U)

/**
 * @brief Manufacturer package.
 */
#define STGIPQ8C60T_HZ_PACKAGE "N2DIP-26L type Z"

// Logical exports
// voltage_rating: STGIPQ8C60T_HZ_VOLTAGE_RATING_V
// current_rating: STGIPQ8C60T_HZ_CURRENT_RATING_A

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _INTEGRATED_POWER_MODULE_STGIPQ8C60T_HZ_H_
