#ifndef _GMP_INV_HOST_SIM_XPLT_CONFIG_H_
#define _GMP_INV_HOST_SIM_XPLT_CONFIG_H_

#define SPECIFY_DISABLE_CSP
#define SPECIFY_DISABLE_GMP_LOGO
#define SPECIFY_ENABLE_GMP_CTL
#define SPECIFY_CTRL_GT_TYPE USING_FLOAT_FPU
#define SPECIFY_PC_ENVIRONMENT
#define PC_ENV_MAX_ITERATION (1)

#endif // _GMP_INV_HOST_SIM_XPLT_CONFIG_H_
