#ifndef _GMP_DQ_CONTROLLER_HOST_SIM_CTL_INTERFACE_H_
#define _GMP_DQ_CONTROLLER_HOST_SIM_CTL_INTERFACE_H_

GMP_STATIC_INLINE void ctl_input_callback(void)
{
}

GMP_STATIC_INLINE void ctl_output_callback(void)
{
}

#endif // _GMP_DQ_CONTROLLER_HOST_SIM_CTL_INTERFACE_H_
