function simulation_output = run_pil_stage(expected_build_level, stop_time, output_directory)
%RUN_PIL_STAGE Run one SDPE-matched F280049C Processor-in-the-Loop stage.
%   SIMULATION_OUTPUT = RUN_PIL_STAGE(LEVEL, STOP_TIME, OUTPUT_DIRECTORY)
%   loads the generated target settings, configures the standard GMP UDP
%   block from the same SDPE contract, runs the ACIM plant, and saves the
%   complete SimulationOutput plus a machine-readable manifest.

arguments
    expected_build_level (1,1) double {mustBeMember(expected_build_level, 1:4)}
    stop_time (1,1) double {mustBePositive}
    output_directory (1,1) string = ""
end

pil_directory = fileparts(mfilename('fullpath'));
target_directory = fileparts(pil_directory);
project_directory = fileparts(target_directory);
settings_directory = fullfile(target_directory, 'sdpe_mgr');
addpath(settings_directory);
settings_path_cleanup = onCleanup(@() rmpath(settings_directory)); %#ok<NASGU>
sdpe_mcs_acim_nt_f280049c_settings_matlab_init;

assert(ENABLE_GMP_DL_PIL_SIM, ...
    'MCS:PILDisabled', 'ENABLE_GMP_DL_PIL_SIM must be enabled in target SDPE.');
assert(BUILD_LEVEL == expected_build_level, ...
    'MCS:PILBuildLevelMismatch', ...
    'Generated target selects BUILD_LEVEL %d, but stage %d was requested.', ...
    BUILD_LEVEL, expected_build_level);

if strlength(output_directory) == 0
    stamp = string(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
    output_directory = fullfile(pil_directory, 'results', stamp, ...
        sprintf('build_level_%d', BUILD_LEVEL));
end
if ~isfolder(output_directory)
    mkdir(output_directory);
end

model_file = fullfile(project_directory, 'simulate', 'MCS_STD_ACM_MODEL.slx');
model_name = 'MCS_STD_ACM_MODEL';
load_system(model_file);
model_cleanup = onCleanup(@() close_system(model_name, 0)); %#ok<NASGU>

core = find_system(model_name, 'LookUnderMasks', 'all', 'FollowLinks', 'on', ...
    'MaskType', 'GMP CTL SIL Core');
assert(isscalar(core), 'MCS:PILCoreNotFound', ...
    'Expected exactly one standard GMP SIL/PIL UDP core in the plant model.');
core = core{1};
set_param(core, ...
    'MaskHostAddr', sprintf('''%s''', GMP_PIL_UDP_HOST), ...
    'MaskMsgTxPort', num2str(GMP_PIL_MATLAB_UDP_LISTEN_PORT), ...
    'MaskMsgRxPort', num2str(GMP_PIL_BRIDGE_UDP_LISTEN_PORT), ...
    'MaskCmdTxPort', num2str(GMP_PIL_MATLAB_COMMAND_TX_PORT), ...
    'MaskCmdRxPort', num2str(GMP_PIL_MATLAB_COMMAND_RX_PORT));

assert(strcmp(get_param(core, 'MaskPackedDataTypes'), ...
    '{''double'', ''uint32'', ''double'', ''int32''}'), ...
    'MCS:PILInputTypeMismatch', 'The model input packing no longer matches GMP PIL.');
assert(strcmp(get_param(core, 'MaskPackedDataSizes'), '{[1],[24],[16],[8]}'), ...
    'MCS:PILInputSizeMismatch', 'The model input channel sizes no longer match GMP PIL.');
assert(strcmp(get_param(core, 'MaskUnpackedDataTypes'), ...
    '{''double'', ''uint32'', ''uint32'', ''double''}'), ...
    'MCS:PILOutputTypeMismatch', 'The model output unpacking no longer matches GMP PIL.');
assert(strcmp(get_param(core, 'MaskUnpackedDataSizes'), '{[1],[8],[8],[16]}'), ...
    'MCS:PILOutputSizeMismatch', 'The model output channel sizes no longer match GMP PIL.');

set_param(model_name, 'SignalLogging', 'on');
set_param(model_name, 'SimulationCommand', 'update');
simulation_output = sim(model_name, ...
    'StopTime', num2str(stop_time, 17), ...
    'ReturnWorkspaceOutputs', 'on');

metadata = struct( ...
    'project', 'mcs_acm_nt_f280049c', ...
    'mode', 'PIL', ...
    'build_level', BUILD_LEVEL, ...
    'stop_time_s', stop_time, ...
    'controller_frequency_hz', CONTROLLER_FREQUENCY, ...
    'sample_time_s', 1 / CONTROLLER_FREQUENCY, ...
    'serial_baudrate', GMP_DL_UART_BAUDRATE, ...
    'datalink_base_command', GMP_PIL_DL_BASE_COMMAND, ...
    'rx_mask', GMP_PIL_RX_MASK, ...
    'tx_mask', GMP_PIL_TX_MASK, ...
    'udp_host', GMP_PIL_UDP_HOST, ...
    'bridge_listen_port', GMP_PIL_BRIDGE_UDP_LISTEN_PORT, ...
    'matlab_listen_port', GMP_PIL_MATLAB_UDP_LISTEN_PORT, ...
    'completed_at', char(datetime('now', 'TimeZone', 'local', ...
        'Format', 'yyyy-MM-dd''T''HH:mm:ssXXX')));

save(fullfile(output_directory, 'pil_simulation.mat'), ...
    'simulation_output', 'metadata', '-v7.3');
manifest = fopen(fullfile(output_directory, 'manifest.json'), 'w');
assert(manifest >= 0, 'MCS:PILManifestOpenFailed', ...
    'Cannot create the PIL result manifest.');
manifest_cleanup = onCleanup(@() fclose(manifest)); %#ok<NASGU>
fprintf(manifest, '%s\n', jsonencode(metadata, PrettyPrint=true));
fprintf('Saved BUILD_LEVEL %d PIL data to %s\n', BUILD_LEVEL, output_directory);
end
