/**
 * @file dsa_dl_scope.h
 * @brief Connects a four-channel DSA recorder to the GMP Data Link Scope service.
 */

#ifndef _FILE_CTL_DSA_DL_SCOPE_H_
#define _FILE_CTL_DSA_DL_SCOPE_H_

#include <core/dev/scope.h>
#include <ctl/component/dsa/dsa_scope.h>
#include <ctl/component/dsa/dsa_trigger.h>

#ifdef __cplusplus
extern "C"
{
#endif

/** @brief Number of channels exported by every suite hardware scope. */
#define CTL_DSA_DL_SCOPE_CHANNELS 4U

/** @brief Default command allocated to the independent Scope service. */
#define CTL_DSA_DL_SCOPE_DEFAULT_CMD 0x60U

/** @brief Acquisition state and storage owned by one Data Link Scope. */
typedef struct
{
    gmp_scope_service_t service;       /**< Data Link command service. */
    gmp_scope_resource_t resource;     /**< Discoverable scope resource. */
    ctl_dsa_trigger_t trigger;         /**< Trigger detector. */
    ctl_dsa_scope_t recorder;          /**< Four-channel post-trigger recorder. */
    ctrl_gt* buffer;                   /**< Published structure-of-arrays buffer. */
    ctrl_gt* history;                  /**< Circular pre-trigger history buffer. */
    uint32_t depth;                    /**< Samples stored per channel. */
    uint32_t sample_rate_hz;           /**< Undivided control sampling rate. */
    volatile uint32_t generation;      /**< Completed-capture generation counter. */
    volatile uint32_t history_write;   /**< Next circular-history write index. */
    volatile uint32_t history_count;   /**< Valid samples in circular history. */
    volatile uint16_t position_permille; /**< Requested pre-trigger position. */
    volatile fast16_gt trigger_channel;  /**< Zero-based trigger source. */
    volatile ctl_dsa_trigger_option_t trigger_mode; /**< Active trigger mode. */
    volatile uint32_t auto_timeout_ms; /**< Auto-trigger timeout. */
    volatile uint16_t sample_divider;  /**< Sampling divider; zero samples every tick. */
    volatile uint16_t sample_divider_counter; /**< Control ticks skipped before sampling. */
    volatile parameter_gt trigger_level; /**< Trigger comparison level. */
    volatile gmp_scope_capture_state_t state; /**< Current acquisition state. */
} ctl_dsa_dl_scope_t;

/**
 * @brief Initialize a four-channel DSA Data Link Scope.
 * @param scope Scope object to initialize.
 * @param dl Data Link object that owns the Scope command.
 * @param command Scope service command, normally 0x60.
 * @param name Stable English resource name; NULL selects "Control Scope".
 * @param buffer Published sample buffer with four times @p depth elements.
 * @param history Pre-trigger history buffer with four times @p depth elements.
 * @param depth Number of samples per channel; must be nonzero.
 * @param sample_rate_hz Sampling frequency in hertz; must be nonzero.
 */
void ctl_init_dsa_dl_scope(ctl_dsa_dl_scope_t* scope, gmp_datalink_t* dl,
                           uint16_t command, const char* name,
                           ctrl_gt* buffer, ctrl_gt* history,
                           uint32_t depth, uint32_t sample_rate_hz);

/**
 * @brief Process one four-channel sample in the real-time interrupt.
 * @param scope Initialized scope object.
 * @param channel_0 First channel and default trigger source.
 * @param channel_1 Second channel.
 * @param channel_2 Third channel.
 * @param channel_3 Fourth channel.
 */
void ctl_step_dsa_dl_scope_4ch(ctl_dsa_dl_scope_t* scope,
                               ctrl_gt channel_0, ctrl_gt channel_1,
                               ctrl_gt channel_2, ctrl_gt channel_3);

/**
 * @brief Dispatch the current Data Link packet to the Scope service.
 * @param scope Initialized scope object.
 * @return Nonzero when the Scope service handled the packet.
 */
fast_gt ctl_dsa_dl_scope_rx_cb(ctl_dsa_dl_scope_t* scope);

/**
 * @brief Fill the four suite-specific values sampled by a hardware scope.
 * @param channels Output array containing exactly four control values.
 * @note Every non-simulation suite application using the standard user
 * scope must provide this function.
 */
void user_get_scope_channels(ctrl_gt channels[CTL_DSA_DL_SCOPE_CHANNELS]);

/**
 * @brief Initialize the standard scope instance owned by user_main.c.
 * @param dl Data Link object used by the suite application.
 */
void user_init_dl_scope(gmp_datalink_t* dl);

/**
 * @brief Dispatch a received packet to the user-owned Scope instance.
 * @return Nonzero when the Scope service handled the packet.
 */
fast_gt user_dispatch_dl_scope(void);

/** @brief Offer one control sample to the user-owned Scope. */
void user_step_dl_scope(void);

/**
 * @brief Define the standard four-channel Scope inside user_main.c.
 * @param resource_name Stable English name reported during discovery.
 *
 * @details `GMP_DL_SCOPE_DEPTH` is generated by the target SDPE settings and
 * `CONTROLLER_FREQUENCY` is the target control interrupt frequency. Keeping
 * The application may place the two named buffers in a target-specific linker
 * section before invoking this macro.
 */
#define CTL_DSA_DL_SCOPE_DEFINE_USER(resource_name)                                          \
    static ctrl_gt user_dl_scope_buffer[CTL_DSA_DL_SCOPE_CHANNELS * GMP_DL_SCOPE_DEPTH];      \
    static ctrl_gt user_dl_scope_history[CTL_DSA_DL_SCOPE_CHANNELS * GMP_DL_SCOPE_DEPTH];     \
    static ctl_dsa_dl_scope_t user_dl_scope;                                                   \
    void user_init_dl_scope(gmp_datalink_t* dl)                                                \
    {                                                                                          \
        ctl_init_dsa_dl_scope(&user_dl_scope, dl, CTL_DSA_DL_SCOPE_DEFAULT_CMD,                \
                              (resource_name), user_dl_scope_buffer,                            \
                              user_dl_scope_history, GMP_DL_SCOPE_DEPTH,                        \
                              (uint32_t)(CONTROLLER_FREQUENCY));                                \
    }                                                                                          \
    fast_gt user_dispatch_dl_scope(void)                                                       \
    {                                                                                          \
        return ctl_dsa_dl_scope_rx_cb(&user_dl_scope);                                         \
    }                                                                                          \
    void user_step_dl_scope(void)                                                              \
    {                                                                                          \
        ctrl_gt channels[CTL_DSA_DL_SCOPE_CHANNELS];                                           \
        user_get_scope_channels(channels);                                                     \
        ctl_step_dsa_dl_scope_4ch(&user_dl_scope, channels[0], channels[1],                    \
                                   channels[2], channels[3]);                                  \
    }

#ifdef __cplusplus
}
#endif

#endif /* _FILE_CTL_DSA_DL_SCOPE_H_ */
