%% SDPE MATLAB initialization script
% Project: PGS Grid-Forming Inverter Common Settings
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

%% GMP numeric-domain conversion contract
if ~exist('GMP_SDPE_REAL_TYPE', 'var'); GMP_SDPE_REAL_TYPE = 'double'; end
if ~exist('GMP_SDPE_PARAMETER_TYPE', 'var'); GMP_SDPE_PARAMETER_TYPE = 'double'; end
if ~exist('GMP_SDPE_CTRL_TYPE', 'var'); GMP_SDPE_CTRL_TYPE = 'double'; end
if ~exist('GMP_SDPE_REAL_TO_CTRL', 'var')
    GMP_SDPE_REAL_TO_CTRL = @(value) cast(value, GMP_SDPE_CTRL_TYPE);
end
if ~exist('GMP_SDPE_CTRL_TO_REAL', 'var')
    GMP_SDPE_CTRL_TO_REAL = @(value) cast(value, GMP_SDPE_REAL_TYPE);
end
real2param = @(value) cast(cast(value, GMP_SDPE_REAL_TYPE), GMP_SDPE_PARAMETER_TYPE);
real2ctrl = @(value) GMP_SDPE_REAL_TO_CTRL(cast(value, GMP_SDPE_REAL_TYPE));
param2ctrl = @(value) GMP_SDPE_REAL_TO_CTRL(cast(value, GMP_SDPE_PARAMETER_TYPE));
ctrl2param = @(value) cast(GMP_SDPE_CTRL_TO_REAL(value), GMP_SDPE_PARAMETER_TYPE);

% Notes:
%   Platform-independent control contract for the replaceable grid-forming outer loop, voltage loop, GFL-derived current core, and PLL-to-GFM transition.

%% Project metadata
PGS_INV_GFM_COMMON_SDPE_PROJECT_ID = 'pgs_inv_gfm_common';

PGS_INV_GFM_COMMON_SDPE_PROJECT_SUITE = 'pgs_inv_GFM_inverter';

PGS_INV_GFM_COMMON_SDPE_PROJECT_VERSION = '1.0.0';

PGS_INV_GFM_COMMON_SDPE_PROJECT_UPDATED_AT = '2026-08-15';

%% Control Algorithm
% Enable the established discrete controller anti-saturation path.
USE_DEBUG_DISCRETE_PID = true;

% USING_DSOGI_PLL is disabled in the SDPE project requirement.
% USING_DSOGI_PLL = true;

% USING_3D_SVPWM is disabled in the SDPE project requirement.
% USING_3D_SVPWM = true;

% Enable omega*C capacitor coupling feed-forward in BUILD_LEVEL 3 and 5.
GFM_ENABLE_VOLTAGE_DECOUPLE = true;

% Enable circular limiting of the complete voltage-loop current reference.
GFM_ENABLE_VOLTAGE_CIRCLE_LIMIT = true;

% GFM_ENABLE_VOLTAGE_SQUARE_LIMIT is disabled in the SDPE project requirement.
% GFM_ENABLE_VOLTAGE_SQUARE_LIMIT = true;

%% Runtime
% SPECIFY_ENABLE_ADC_CALIBRATE is disabled in the SDPE project requirement.
% SPECIFY_ENABLE_ADC_CALIBRATE = true;

%% Control Algorithm
% BUILD_LEVEL 5 grid-forming technique: 1=P-f/Q-V droop, 2=virtual synchronous machine, 3=droop angle source plus virtual impedance.
% Options: (1), (2), (3)
GFM_CONTROL_TECHNOLOGY = 1;

%% Requirement bindings
% Enable the seven ADC slots used by the three-phase inverter SIL input ABI.
GMP_PIL_RX_MASK = 127;

% Enable four PWM slots and all sixteen monitor slots used by the GFM SIL output ABI.
GMP_PIL_TX_MASK = 4294901775;

% Nominal grid phase-voltage magnitude in controller per unit.
GFM_GRID_VOLTAGE_PU = real2param(0.33);

% Nominal grid-forming and synchronization frequency.
GFM_GRID_FREQUENCY_HZ = real2param(50.0);

% BUILD_LEVEL 1 d-axis open-loop voltage command.
GFM_OPEN_LOOP_VD_PU = real2param(0.50);

% BUILD_LEVEL 1 q-axis open-loop voltage command.
GFM_OPEN_LOOP_VQ_PU = real2param(0.0);

% BUILD_LEVEL 2 d-axis current command using the internal ramp angle.
GFM_CURRENT_LEVEL2_ID_PU = real2param(0.10);

% BUILD_LEVEL 2 q-axis current command using the internal ramp angle.
GFM_CURRENT_LEVEL2_IQ_PU = real2param(0.10);

% BUILD_LEVEL 4 PLL-oriented d-axis grid current command.
GFM_CURRENT_LEVEL4_ID_PU = real2param(0.10);

% BUILD_LEVEL 4 PLL-oriented q-axis grid current command.
GFM_CURRENT_LEVEL4_IQ_PU = real2param(0.0);

% BUILD_LEVEL 3 fixed voltage reference and BUILD_LEVEL 5 nominal droop voltage.
GFM_VOLTAGE_VD_PU = real2param(0.50);

% BUILD_LEVEL 3 fixed q-axis voltage reference.
GFM_VOLTAGE_VQ_PU = real2param(0.0);

% LC capacitor-voltage loop bandwidth.
GFM_VOLTAGE_LOOP_BW_HZ = real2param(100.0);

% LC capacitor-voltage ordinary PI zero frequency.
GFM_VOLTAGE_LOOP_ZERO_HZ = real2param(20.0);

% Circular magnitude limit of the complete voltage-loop current reference.
GFM_VOLTAGE_CIRCLE_LIMIT_PU = real2param(0.80);

% Independent symmetric d/q-axis voltage-loop current-reference limit.
GFM_VOLTAGE_SQUARE_LIMIT_PU = real2param(0.80);

% Active-power to frequency droop slope in Hz per power PU.
GFM_DROOP_P_HZ_PER_PU = real2param(0.50);

% Reactive-power to voltage droop slope in voltage PU per reactive-power PU.
GFM_DROOP_Q_V_PER_PU = real2param(0.05);

% Droop active/reactive-power measurement low-pass cutoff.
GFM_DROOP_POWER_LPF_HZ = real2param(10.0);

% Maximum absolute droop frequency deviation from nominal.
GFM_DROOP_FREQUENCY_DELTA_LIMIT_HZ = real2param(2.0);

% Minimum voltage magnitude requested by the droop module.
GFM_DROOP_VOLTAGE_MIN_PU = real2param(0.40);

% Maximum voltage magnitude requested by the droop module.
GFM_DROOP_VOLTAGE_MAX_PU = real2param(0.60);

% Default active-power reference for the droop algorithm.
GFM_DROOP_ACTIVE_POWER_REF_PU = real2param(0.0);

% Default reactive-power reference for the droop algorithm.
GFM_DROOP_REACTIVE_POWER_REF_PU = real2param(0.0);

% VSM normalized swing-equation inertia in seconds.
GFM_VSM_INERTIA_S = real2param(1.0);

% VSM damping power coefficient in power PU per hertz.
GFM_VSM_DAMPING_PU_PER_HZ = real2param(2.0);

% VSM reactive-power voltage droop in voltage PU per reactive-power PU.
GFM_VSM_Q_DROOP_V_PER_PU = real2param(0.05);

% VSM active/reactive-power measurement low-pass cutoff.
GFM_VSM_POWER_LPF_HZ = real2param(10.0);

% Virtual resistance used to condition the voltage-loop reference.
GFM_VIRTUAL_IMPEDANCE_R_PU = real2param(0.03);

% Virtual reactance used to condition the voltage-loop reference.
GFM_VIRTUAL_IMPEDANCE_X_PU = real2param(0.03);

% Circular voltage-reference limit after virtual-impedance compensation.
GFM_VIRTUAL_IMPEDANCE_VOLTAGE_LIMIT_PU = real2param(0.60);

% PLL-to-grid-forming phasor and current-command blend duration.
GFM_TRANSITION_TIME_S = real2param(0.10);

% Continuous PLL-lock duration required before requesting grid-forming takeover.
GFM_SYNC_HOLD_TIME_S = real2param(0.20);

% Maximum instantaneous PLL q-axis error during the continuous grid-forming synchronization hold.
GFM_SYNC_PLL_ERROR_PU = real2param(0.08);

% Tracking-mode d-axis current command before grid-forming takeover.
GFM_SYNC_ID_PU = real2param(0.0);

% Tracking-mode q-axis current command before grid-forming takeover.
GFM_SYNC_IQ_PU = real2param(0.0);

% Zero-sequence current QPR proportional gain for four-wire operation.
GFM_ZERO_QPR_KP = real2param(0.10);

% Zero-sequence current QPR resonant gain.
GFM_ZERO_QPR_KR = real2param(50.0);

% Zero-sequence QPR resonant bandwidth.
GFM_ZERO_QPR_CUTOFF_HZ = real2param(5.0);

% Symmetric zero-axis voltage-command limit.
GFM_ZERO_VOLTAGE_LIMIT_PU = real2param(0.20);

% ADC offset calibrator cutoff.
GFM_ADC_CALIBRATOR_FC_HZ = real2param(20.0);

% ADC offset calibrator quality factor.
GFM_ADC_CALIBRATOR_Q = real2param(0.707);

% Minimum CiA402 delay before Operation Enabled.
GFM_CIA402_OPERATION_ENABLE_DELAY_MS = 100;

% PLL lock-error threshold used before grid-forming takeover.
CTRL_SPLL_EPSILON = real2ctrl(0.005);

%% SDPE project summary
fprintf('\n============================================================\n');
fprintf('SDPE Project : %s\n', 'PGS Grid-Forming Inverter Common Settings');
fprintf('Project ID   : %s\n', 'pgs_inv_gfm_common');
fprintf('Suite        : %s\n', 'pgs_inv_GFM_inverter');
fprintf('Version      : %s\n', '1.0.0');
fprintf('Hardware (0):\n');
fprintf('Common requirements (0):\n');
fprintf('Enabled variables (52):\n');
fprintf('  CTRL_SPLL_EPSILON = '); disp(CTRL_SPLL_EPSILON);
fprintf('  GFM_ADC_CALIBRATOR_FC_HZ = '); disp(GFM_ADC_CALIBRATOR_FC_HZ);
fprintf('  GFM_ADC_CALIBRATOR_Q = '); disp(GFM_ADC_CALIBRATOR_Q);
fprintf('  GFM_CIA402_OPERATION_ENABLE_DELAY_MS = '); disp(GFM_CIA402_OPERATION_ENABLE_DELAY_MS);
fprintf('  GFM_CONTROL_TECHNOLOGY = '); disp(GFM_CONTROL_TECHNOLOGY);
fprintf('  GFM_CURRENT_LEVEL2_ID_PU = '); disp(GFM_CURRENT_LEVEL2_ID_PU);
fprintf('  GFM_CURRENT_LEVEL2_IQ_PU = '); disp(GFM_CURRENT_LEVEL2_IQ_PU);
fprintf('  GFM_CURRENT_LEVEL4_ID_PU = '); disp(GFM_CURRENT_LEVEL4_ID_PU);
fprintf('  GFM_CURRENT_LEVEL4_IQ_PU = '); disp(GFM_CURRENT_LEVEL4_IQ_PU);
fprintf('  GFM_DROOP_ACTIVE_POWER_REF_PU = '); disp(GFM_DROOP_ACTIVE_POWER_REF_PU);
fprintf('  GFM_DROOP_FREQUENCY_DELTA_LIMIT_HZ = '); disp(GFM_DROOP_FREQUENCY_DELTA_LIMIT_HZ);
fprintf('  GFM_DROOP_POWER_LPF_HZ = '); disp(GFM_DROOP_POWER_LPF_HZ);
fprintf('  GFM_DROOP_P_HZ_PER_PU = '); disp(GFM_DROOP_P_HZ_PER_PU);
fprintf('  GFM_DROOP_Q_V_PER_PU = '); disp(GFM_DROOP_Q_V_PER_PU);
fprintf('  GFM_DROOP_REACTIVE_POWER_REF_PU = '); disp(GFM_DROOP_REACTIVE_POWER_REF_PU);
fprintf('  GFM_DROOP_VOLTAGE_MAX_PU = '); disp(GFM_DROOP_VOLTAGE_MAX_PU);
fprintf('  GFM_DROOP_VOLTAGE_MIN_PU = '); disp(GFM_DROOP_VOLTAGE_MIN_PU);
fprintf('  GFM_ENABLE_VOLTAGE_CIRCLE_LIMIT = '); disp(GFM_ENABLE_VOLTAGE_CIRCLE_LIMIT);
fprintf('  GFM_ENABLE_VOLTAGE_DECOUPLE = '); disp(GFM_ENABLE_VOLTAGE_DECOUPLE);
fprintf('  GFM_GRID_FREQUENCY_HZ = '); disp(GFM_GRID_FREQUENCY_HZ);
fprintf('  GFM_GRID_VOLTAGE_PU = '); disp(GFM_GRID_VOLTAGE_PU);
fprintf('  GFM_OPEN_LOOP_VD_PU = '); disp(GFM_OPEN_LOOP_VD_PU);
fprintf('  GFM_OPEN_LOOP_VQ_PU = '); disp(GFM_OPEN_LOOP_VQ_PU);
fprintf('  GFM_SYNC_HOLD_TIME_S = '); disp(GFM_SYNC_HOLD_TIME_S);
fprintf('  GFM_SYNC_ID_PU = '); disp(GFM_SYNC_ID_PU);
fprintf('  GFM_SYNC_IQ_PU = '); disp(GFM_SYNC_IQ_PU);
fprintf('  GFM_SYNC_PLL_ERROR_PU = '); disp(GFM_SYNC_PLL_ERROR_PU);
fprintf('  GFM_TRANSITION_TIME_S = '); disp(GFM_TRANSITION_TIME_S);
fprintf('  GFM_VIRTUAL_IMPEDANCE_R_PU = '); disp(GFM_VIRTUAL_IMPEDANCE_R_PU);
fprintf('  GFM_VIRTUAL_IMPEDANCE_VOLTAGE_LIMIT_PU = '); disp(GFM_VIRTUAL_IMPEDANCE_VOLTAGE_LIMIT_PU);
fprintf('  GFM_VIRTUAL_IMPEDANCE_X_PU = '); disp(GFM_VIRTUAL_IMPEDANCE_X_PU);
fprintf('  GFM_VOLTAGE_CIRCLE_LIMIT_PU = '); disp(GFM_VOLTAGE_CIRCLE_LIMIT_PU);
fprintf('  GFM_VOLTAGE_LOOP_BW_HZ = '); disp(GFM_VOLTAGE_LOOP_BW_HZ);
fprintf('  GFM_VOLTAGE_LOOP_ZERO_HZ = '); disp(GFM_VOLTAGE_LOOP_ZERO_HZ);
fprintf('  GFM_VOLTAGE_SQUARE_LIMIT_PU = '); disp(GFM_VOLTAGE_SQUARE_LIMIT_PU);
fprintf('  GFM_VOLTAGE_VD_PU = '); disp(GFM_VOLTAGE_VD_PU);
fprintf('  GFM_VOLTAGE_VQ_PU = '); disp(GFM_VOLTAGE_VQ_PU);
fprintf('  GFM_VSM_DAMPING_PU_PER_HZ = '); disp(GFM_VSM_DAMPING_PU_PER_HZ);
fprintf('  GFM_VSM_INERTIA_S = '); disp(GFM_VSM_INERTIA_S);
fprintf('  GFM_VSM_POWER_LPF_HZ = '); disp(GFM_VSM_POWER_LPF_HZ);
fprintf('  GFM_VSM_Q_DROOP_V_PER_PU = '); disp(GFM_VSM_Q_DROOP_V_PER_PU);
fprintf('  GFM_ZERO_QPR_CUTOFF_HZ = '); disp(GFM_ZERO_QPR_CUTOFF_HZ);
fprintf('  GFM_ZERO_QPR_KP = '); disp(GFM_ZERO_QPR_KP);
fprintf('  GFM_ZERO_QPR_KR = '); disp(GFM_ZERO_QPR_KR);
fprintf('  GFM_ZERO_VOLTAGE_LIMIT_PU = '); disp(GFM_ZERO_VOLTAGE_LIMIT_PU);
fprintf('  GMP_PIL_RX_MASK = '); disp(GMP_PIL_RX_MASK);
fprintf('  GMP_PIL_TX_MASK = '); disp(GMP_PIL_TX_MASK);
fprintf('  PGS_INV_GFM_COMMON_SDPE_PROJECT_ID = '); disp(PGS_INV_GFM_COMMON_SDPE_PROJECT_ID);
fprintf('  PGS_INV_GFM_COMMON_SDPE_PROJECT_SUITE = '); disp(PGS_INV_GFM_COMMON_SDPE_PROJECT_SUITE);
fprintf('  PGS_INV_GFM_COMMON_SDPE_PROJECT_UPDATED_AT = '); disp(PGS_INV_GFM_COMMON_SDPE_PROJECT_UPDATED_AT);
fprintf('  PGS_INV_GFM_COMMON_SDPE_PROJECT_VERSION = '); disp(PGS_INV_GFM_COMMON_SDPE_PROJECT_VERSION);
fprintf('  USE_DEBUG_DISCRETE_PID = '); disp(USE_DEBUG_DISCRETE_PID);
fprintf('Disabled macros (4):\n');
fprintf('  - GFM_ENABLE_VOLTAGE_SQUARE_LIMIT\n');
fprintf('  - SPECIFY_ENABLE_ADC_CALIBRATE\n');
fprintf('  - USING_3D_SVPWM\n');
fprintf('  - USING_DSOGI_PLL\n');
fprintf('============================================================\n');

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
