%% SDPE MATLAB initialization script
% Project: PGS Grid-Forming Inverter Common Settings
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

% Notes:
%   Platform-independent control contract for the replaceable grid-forming outer loop, voltage loop, GFL-derived current core, and PLL-to-GFM transition.

%% Project metadata
PGS_INV_GFM_COMMON_SDPE_PROJECT_ID = 'pgs_inv_gfm_common';

PGS_INV_GFM_COMMON_SDPE_PROJECT_SUITE = 'pgs_inv_GFM_inverter';

PGS_INV_GFM_COMMON_SDPE_PROJECT_VERSION = '1.0.0';

PGS_INV_GFM_COMMON_SDPE_PROJECT_UPDATED_AT = '2026-07-28';

%% Control Algorithm
% Enable the established discrete controller anti-saturation path.
USE_DEBUG_DISCRETE_PID = true;

% USING_DSOGI_PLL is disabled in the SDPE project requirement.
% USING_DSOGI_PLL = true;

% USING_3D_SVPWM is disabled in the SDPE project requirement.
% USING_3D_SVPWM = true;

% Enable omega*C capacitor coupling feed-forward in BUILD_LEVEL 3 and 5.
GFM_ENABLE_VOLTAGE_DECOUPLE = true;

% Enable circular limiting of the complete voltage-loop current reference.
GFM_ENABLE_VOLTAGE_CIRCLE_LIMIT = true;

% GFM_ENABLE_VOLTAGE_SQUARE_LIMIT is disabled in the SDPE project requirement.
% GFM_ENABLE_VOLTAGE_SQUARE_LIMIT = true;

%% Runtime
% SPECIFY_ENABLE_ADC_CALIBRATE is disabled in the SDPE project requirement.
% SPECIFY_ENABLE_ADC_CALIBRATE = true;

% ENABLE_GMP_DL_PIL_SIM is disabled in the SDPE project requirement.
% ENABLE_GMP_DL_PIL_SIM = true;

%% Requirement bindings
% Nominal grid phase-voltage magnitude in controller per unit.
GFM_GRID_VOLTAGE_PU = 0.33;

% Nominal grid-forming and synchronization frequency.
GFM_GRID_FREQUENCY_HZ = 50.0;

% BUILD_LEVEL 1 d-axis open-loop voltage command.
GFM_OPEN_LOOP_VD_PU = 0.50;

% BUILD_LEVEL 1 q-axis open-loop voltage command.
GFM_OPEN_LOOP_VQ_PU = 0.0;

% BUILD_LEVEL 2 d-axis current command using the internal ramp angle.
GFM_CURRENT_LEVEL2_ID_PU = 0.10;

% BUILD_LEVEL 2 q-axis current command using the internal ramp angle.
GFM_CURRENT_LEVEL2_IQ_PU = 0.10;

% BUILD_LEVEL 4 PLL-oriented d-axis grid current command.
GFM_CURRENT_LEVEL4_ID_PU = 0.10;

% BUILD_LEVEL 4 PLL-oriented q-axis grid current command.
GFM_CURRENT_LEVEL4_IQ_PU = 0.0;

% BUILD_LEVEL 3 fixed voltage reference and BUILD_LEVEL 5 nominal droop voltage.
GFM_VOLTAGE_VD_PU = 0.50;

% BUILD_LEVEL 3 fixed q-axis voltage reference.
GFM_VOLTAGE_VQ_PU = 0.0;

% LC capacitor-voltage loop bandwidth.
GFM_VOLTAGE_LOOP_BW_HZ = 100.0;

% LC capacitor-voltage ordinary PI zero frequency.
GFM_VOLTAGE_LOOP_ZERO_HZ = 20.0;

% Circular magnitude limit of the complete voltage-loop current reference.
GFM_VOLTAGE_CIRCLE_LIMIT_PU = 0.80;

% Independent symmetric d/q-axis voltage-loop current-reference limit.
GFM_VOLTAGE_SQUARE_LIMIT_PU = 0.80;

% Active-power to frequency droop slope in Hz per power PU.
GFM_DROOP_P_HZ_PER_PU = 0.50;

% Reactive-power to voltage droop slope in voltage PU per reactive-power PU.
GFM_DROOP_Q_V_PER_PU = 0.05;

% Droop active/reactive-power measurement low-pass cutoff.
GFM_DROOP_POWER_LPF_HZ = 10.0;

% Maximum absolute droop frequency deviation from nominal.
GFM_DROOP_FREQUENCY_DELTA_LIMIT_HZ = 2.0;

% Minimum voltage magnitude requested by the droop module.
GFM_DROOP_VOLTAGE_MIN_PU = 0.40;

% Maximum voltage magnitude requested by the droop module.
GFM_DROOP_VOLTAGE_MAX_PU = 0.60;

% Default active-power reference for the droop algorithm.
GFM_DROOP_ACTIVE_POWER_REF_PU = 0.0;

% Default reactive-power reference for the droop algorithm.
GFM_DROOP_REACTIVE_POWER_REF_PU = 0.0;

% PLL-to-grid-forming phasor and current-command blend duration.
GFM_TRANSITION_TIME_S = 0.10;

% Continuous PLL-lock duration required before requesting grid-forming takeover.
GFM_SYNC_HOLD_TIME_S = 0.20;

% Maximum instantaneous PLL q-axis error during the continuous grid-forming synchronization hold.
GFM_SYNC_PLL_ERROR_PU = 0.08;

% Tracking-mode d-axis current command before grid-forming takeover.
GFM_SYNC_ID_PU = 0.0;

% Tracking-mode q-axis current command before grid-forming takeover.
GFM_SYNC_IQ_PU = 0.0;

% Zero-sequence current QPR proportional gain for four-wire operation.
GFM_ZERO_QPR_KP = 0.10;

% Zero-sequence current QPR resonant gain.
GFM_ZERO_QPR_KR = 50.0;

% Zero-sequence QPR resonant bandwidth.
GFM_ZERO_QPR_CUTOFF_HZ = 5.0;

% Symmetric zero-axis voltage-command limit.
GFM_ZERO_VOLTAGE_LIMIT_PU = 0.20;

% ADC offset calibrator cutoff.
GFM_ADC_CALIBRATOR_FC_HZ = 20.0;

% ADC offset calibrator quality factor.
GFM_ADC_CALIBRATOR_Q = 0.707;

% Minimum CiA402 delay before Operation Enabled.
GFM_CIA402_OPERATION_ENABLE_DELAY_MS = 100;

% PLL lock-error threshold used before grid-forming takeover.
CTRL_SPLL_EPSILON = float2ctrl(0.005);

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
