%% SDPE MATLAB initialization script
% Project: PGS Grid-Following Inverter Common Settings
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

% Notes:
%   Platform-independent control contract shared by all pgs_inv_GFL_inverter projects. Hardware timing, sensing, board resources and BUILD_LEVEL selection remain in each platform requirement.

%% Project metadata
PGS_INV_GFL_COMMON_SDPE_PROJECT_ID = 'pgs_inv_gfl_common';

PGS_INV_GFL_COMMON_SDPE_PROJECT_SUITE = 'pgs_inv_GFL_inverter';

PGS_INV_GFL_COMMON_SDPE_PROJECT_VERSION = '1.0.0';

PGS_INV_GFL_COMMON_SDPE_PROJECT_UPDATED_AT = '2026-07-15';

%% Control Algorithm
% Enable the existing discrete PID anti-saturation path.
USE_DEBUG_DISCRETE_PID = true;

% USING_DSOGI_PLL is disabled in the SDPE project requirement.
% USING_DSOGI_PLL = true;

% USING_NPC_MODULATOR is disabled in the SDPE project requirement.
% USING_NPC_MODULATOR = true;

%% Runtime
% SPECIFY_ENABLE_ADC_CALIBRATE is disabled in the SDPE project requirement.
% SPECIFY_ENABLE_ADC_CALIBRATE = true;

% ENABLE_GMP_DL_PIL_SIM is disabled in the SDPE project requirement.
% ENABLE_GMP_DL_PIL_SIM = true;

% GMP_CTL_FM_CONFIG_ENABLE_DEBUG_INFO is disabled in the SDPE project requirement.
% GMP_CTL_FM_CONFIG_ENABLE_DEBUG_INFO = true;

%% Sampling
% Capacitor-current source: direct measurement, current difference, or capacitor-voltage derivative.
% Options: (1), (2), (3)
GFL_CAPACITOR_CURRENT_CALCULATE_MODE = 3;

%% Requirement bindings
% Nominal grid phase-voltage magnitude in controller per unit.
GFL_GRID_VOLTAGE_PU = 0.33;

% Nominal grid frequency in hertz.
GFL_GRID_FREQUENCY_HZ = 50.0;

% P/Q outer-loop execution frequency in hertz.
GFL_PQ_LOOP_FREQUENCY_HZ = 1000.0;

% Current-ISR to P/Q-loop execution divider.
GFL_PQ_LOOP_DIVIDER = CONTROLLER_FREQUENCY / GFL_PQ_LOOP_FREQUENCY_HZ;

% Active-power loop proportional gain from P error PU to d-axis current PU.
GFL_PQ_ACTIVE_KP = 0.75;

% Active-power loop integral gain in inverse seconds.
GFL_PQ_ACTIVE_KI = 0.001;

% Reactive-power loop proportional gain from Q error PU to q-axis current PU.
GFL_PQ_REACTIVE_KP = 0.75;

% Reactive-power loop integral gain in inverse seconds.
GFL_PQ_REACTIVE_KI = 0.001;

% Circular magnitude limit applied to the d/q current reference produced by the P/Q loop.
GFL_PQ_CURRENT_LIMIT_PU = 1.0;

% Default active-power reference. Positive power exports energy to the grid.
GFL_ACTIVE_POWER_REF_PU = 0.1;

% Default reactive-power reference using Q = vq*id - vd*iq.
GFL_REACTIVE_POWER_REF_PU = 0.0;

% BUILD_LEVEL 1 d-axis open-loop voltage command.
GFL_OPEN_LOOP_VD_PU = 0.6;

% BUILD_LEVEL 1 q-axis open-loop voltage command.
GFL_OPEN_LOOP_VQ_PU = 0.6;

% BUILD_LEVEL 2 d-axis current command.
GFL_CURRENT_LEVEL2_ID_PU = 0.1;

% BUILD_LEVEL 2 q-axis current command.
GFL_CURRENT_LEVEL2_IQ_PU = 0.1;

% BUILD_LEVEL 3 grid-connected d-axis current command.
GFL_CURRENT_LEVEL3_ID_PU = 0.1;

% BUILD_LEVEL 3 grid-connected q-axis current command.
GFL_CURRENT_LEVEL3_IQ_PU = 0.0;

% BUILD_LEVEL 4 d-axis current command.
GFL_CURRENT_LEVEL4_ID_PU = 0.6;

% BUILD_LEVEL 4 q-axis current command.
GFL_CURRENT_LEVEL4_IQ_PU = 0.6;

% ADC offset calibrator filter cutoff frequency.
GFL_ADC_CALIBRATOR_FC_HZ = 20.0;

% ADC offset calibrator second-order filter quality factor.
GFL_ADC_CALIBRATOR_Q = 0.707;

% Minimum CiA402 delay before Operation Enabled.
GFL_CIA402_OPERATION_ENABLE_DELAY_MS = 100;

% PLL lock-error threshold in controller per unit.
CTRL_SPLL_EPSILON = float2ctrl(0.005);

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
