%% SDPE MATLAB initialization script
% Project: PGS SINV RC F280039C IRIS Node
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

% Notes:
%   Single-phase inverter project requirement prepared from xplt/ctrl_settings.h.
%   This requirement introduces the GMP LVFB 150V 2-phase inverter board as the switching stage and the GMP Harmonia 3-phase LC filter as the grid filter. IRIS F280039C is included as the peripheral option provider.

%% Project metadata
SDPE_PROJECT_ID = 'pgs_sinv_rc_iris_node';

SDPE_PROJECT_SUITE = 'pgs_sinv_rc';

SDPE_PROJECT_VERSION = '0.1.0';

SDPE_PROJECT_UPDATED_AT = '2026-07-10';

%% Hardware macros
IRIS_F280039C_ID = 'iris_f280039c_node';

IRIS_F280039C_SCHEMA = 'iris_c2000_core_board';

IRIS_F280039C_NAME = 'IRIS F280039C Core Board';

% C2000 device name.
IRIS_F280039C_CHIP = 'TMS320F280039C';

% SysConfig source file used by this binding.
IRIS_F280039C_SYSCFG_FILE = 'ctl/suite/dps_fsbb/project/f280039c_Iris_node/F280039_Iris_node.syscfg';

% SysConfig EPWM1 base macro.
IRIS_F280039C_EPWM1_BASE = 'IRIS_EPWM1_BASE';

% SysConfig EPWM2 base macro.
IRIS_F280039C_EPWM2_BASE = 'IRIS_EPWM2_BASE';

% SysConfig ADC channel 1 macro.
IRIS_F280039C_ADC_CH1 = 'ADC_CH1';

% SysConfig ADC channel 2 macro.
IRIS_F280039C_ADC_CH2 = 'ADC_CH2';

% SysConfig ADC channel 3 macro.
IRIS_F280039C_ADC_CH3 = 'ADC_CH3';

% SysConfig ADC channel 4 macro.
IRIS_F280039C_ADC_CH4 = 'ADC_CH4';

GMP_LVFB_ID = 'gmp_lvfb_150_2ph_v2';

GMP_LVFB_SCHEMA = 'half_bridge';

GMP_LVFB_NAME = 'GMP LVFB 150V 2-Phase V2 Inverter Board';

% Board or module name.
GMP_LVFB_BOARD_NAME = 'GMP LVFB 2ph V6.1';

% Integrated gate driver part number.
GMP_LVFB_GATE_DRIVER = 'UCC21520DWR';

% Power MOSFET part number.
GMP_LVFB_MOSFET = 'BSC093N15NS5';

% On-board current sensing device.
GMP_LVFB_CURRENT_SENSOR_NAME = 'TMCS1133B5A';

% On-board voltage sensing device.
GMP_LVFB_VOLTAGE_SENSOR_NAME = 'AMC1311BDWVR';

% Number of half-bridge phases represented by this module.
GMP_LVFB_PHASE_COUNT = 2;

% Current measurement range exported by the current sensor sub component.
GMP_LVFB_MEASURED_CURRENT_RANGE_A = TMCS1133_B5A_RANGE_A;

% Maximum allowable DC bus voltage.
GMP_LVFB_VBUS_MAX_V = 120.0;

% Maximum instantaneous peak phase current.
GMP_LVFB_CURRENT_MAX_PEAK_A = 55.0;

% Maximum continuous RMS phase current.
GMP_LVFB_CURRENT_MAX_RMS_A = 35.0;

% Recommended hardware deadtime.
GMP_LVFB_DEADTIME_NS = 523.0;

% Current sensing signal bandwidth.
GMP_LVFB_CURRENT_BW_HZ = 300.0e3;

% Current sensor ADC bias voltage.
GMP_LVFB_CURRENT_BIAS_V = 1.65;

% Configured current sensitivity.
GMP_LVFB_CURRENT_SENSITIVITY = TMCS1133_B5A_SENSITIVITY_V_PER_A;

% ADC reference scale voltage.
GMP_LVFB_VOLTAGE_BASE_V = 3.3;

% Voltage sensing ADC bias voltage.
GMP_LVFB_VOLTAGE_BIAS_V = 0.0;

% Voltage sensing bandwidth.
GMP_LVFB_VOLTAGE_BW_HZ = 114.47e3;

% Default low-side voltage divider resistance.
GMP_LVFB_VOLTAGE_R_LOW_OHM = 15e3;

% Default high-side voltage divider resistance.
GMP_LVFB_VOLTAGE_R_HIGH_OHM = 300e3;

% Configured voltage sensing gain.
GMP_LVFB_VOLTAGE_SENSITIVITY = (15e3) / ((15e3) + ((300e3) * 3)) * 1.65;

% Configured maximum measurable voltage.
GMP_LVFB_VOLTAGE_MAX = 3.3 / ((15e3) / ((15e3) + ((300e3) * 3)) * 1.65);

% Optional local DC bus capacitance.
GMP_LVFB_BUS_CAPACITANCE_F = 0.0;

% Whether this module declares a local bus capacitor.
GMP_LVFB_HAS_LOCAL_BUS_CAP = GMP_LVFB_BUS_CAPACITANCE_F > 0.0;

BSC093N15NS5_ID = 'bsc093n15ns5';

BSC093N15NS5_SCHEMA = 'power_switch';

BSC093N15NS5_NAME = 'BSC093N15NS5';

% Power device part number.
BSC093N15NS5_PART_NUMBER = 'BSC093N15NS5';

% MOSFET, IGBT, GaN, SiC, etc.
BSC093N15NS5_DEVICE_TYPE = 'MOSFET';

% Drain-source or collector-emitter voltage rating.
BSC093N15NS5_VOLTAGE_RATING_V = 150.0;

% Current rating.
BSC093N15NS5_CURRENT_RATING_A = 55.0;

% On resistance.
BSC093N15NS5_RDSON_OHM = 0.0093;

TMCS1133_B5A_ID = 'tmcs1133_b5a';

TMCS1133_B5A_SCHEMA = 'current_sensor';

TMCS1133_B5A_NAME = 'TMCS1133 B5A Hall Current Sensor';

% Main sensing IC or technology name.
TMCS1133_B5A_CHIP = 'TMCS1133B5A';

% Current sensing technology, such as Hall, shunt, or fluxgate.
TMCS1133_B5A_SENSOR_TYPE = 'Hall';

% Nominal measurable current range.
TMCS1133_B5A_RANGE_A = 10.3;

% Minimum output voltage.
TMCS1133_B5A_OUTPUT_MIN_V = 0.0;

% Maximum output voltage.
TMCS1133_B5A_OUTPUT_MAX_V = 3.3;

% Zero-current output bias.
TMCS1133_B5A_BIAS_V = 1.65;

% Current sensor sensitivity.
TMCS1133_B5A_SENSITIVITY_MV_PER_A = 150.0;

% Typical small-signal bandwidth.
TMCS1133_B5A_BANDWIDTH_HZ = 300000.0;

% Sensor internal series resistance.
TMCS1133_B5A_INTERNAL_RESISTANCE_OHM = 0.0018;

% Current sensor sensitivity converted to V/A.
TMCS1133_B5A_SENSITIVITY_V_PER_A = TMCS1133_B5A_SENSITIVITY_MV_PER_A / 1000.0;

% Positive current range implied by bias and sensitivity.
TMCS1133_B5A_MAX_CURRENT_FROM_BIAS_A = TMCS1133_B5A_BIAS_V / TMCS1133_B5A_SENSITIVITY_V_PER_A;

LVFB_VDIV_150V_ID = 'lvfb_voltage_divider_150v';

LVFB_VDIV_150V_SCHEMA = 'voltage_sensor';

LVFB_VDIV_150V_NAME = 'LVFB 150V Voltage Divider';

% Main sensing IC or front-end topology.
LVFB_VDIV_150V_CHIP = 'AMC1311BDWVR + resistor divider';

% Nominal measurable voltage.
LVFB_VDIV_150V_RATED_VOLTAGE_V = 150.0;

% Output bias voltage.
LVFB_VDIV_150V_BIAS_V = 0.0;

% Voltage sensor sensitivity.
LVFB_VDIV_150V_SENSITIVITY_V_PER_V = 0.016129;

% Equivalent input resistance.
LVFB_VDIV_150V_INPUT_RESISTANCE_OHM = 915000.0;

% Approximate positive full scale voltage when biased at mid-supply.
LVFB_VDIV_150V_MAX_BY_BIAS_V = sdpe_select(LVFB_VDIV_150V_BIAS_V > 0.0, LVFB_VDIV_150V_BIAS_V / LVFB_VDIV_150V_SENSITIVITY_V_PER_V, LVFB_VDIV_150V_RATED_VOLTAGE_V);

HARMONIA_3PH_LC_FILTER_ID = 'gmp_harmonia_3ph_lc_filter';

HARMONIA_3PH_LC_FILTER_SCHEMA = 'Harmonia_3ph_LC_filter';

HARMONIA_3PH_LC_FILTER_NAME = 'GMP Harmonia 3-Phase LC Filter';

% Main filter inductance.
HARMONIA_3PH_LC_FILTER_INDUCTANCE_H = 0.0015;

% Main filter capacitance.
HARMONIA_3PH_LC_FILTER_CAPACITANCE_F = 0.000005;

% Board or module name.
HARMONIA_3PH_LC_FILTER_BOARD_NAME = 'Harmonia 3Ph LC Filter';

% Maximum DC bus voltage.
HARMONIA_3PH_LC_FILTER_VBUS_MAX_V = 1000.0;

% Minimum DC bus voltage.
HARMONIA_3PH_LC_FILTER_VBUS_MIN_V = 0.0;

% Maximum continuous RMS current.
HARMONIA_3PH_LC_FILTER_CURRENT_MAX_RMS_A = 40.0;

% Maximum peak current.
HARMONIA_3PH_LC_FILTER_CURRENT_MAX_PEAK_A = HARMONIA_3PH_LC_FILTER_CURRENT_MAX_RMS_A * 1.41421356237;

% Recommended maximum PCB operating temperature.
HARMONIA_3PH_LC_FILTER_TEMP_MAX_C = 85.0;

% Phase current sensor type enum.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TYPE = 2;

% Phase current sensing topology enum.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TOPOLOGY = 3;

% Phase voltage sensing type enum.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_TYPE = 1;

% Phase current sensor bandwidth.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_POLE_HZ = TLE4971A025_BANDWIDTH_HZ;

% Total high-side voltage divider resistance.
HARMONIA_3PH_LC_FILTER_VS_R_TOP_TOTAL_OHM = 3920000.0;

% Bottom voltage divider resistance.
HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM = 560000.0;

% Isolation amplifier voltage gain.
HARMONIA_3PH_LC_FILTER_VS_ISO_GAIN_V_V = 0.4;

% Voltage sensing op-amp feedback resistor.
HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_FB_OHM = 1650.0;

% Voltage sensing op-amp input resistor.
HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_IN_OHM = 2000.0;

% ADC bias for phase voltage sensing.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_BIAS_V = 1.65;

% Approximate phase voltage sense bandwidth.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_POLE_HZ = 100000.0;

% Phase voltage sensor model.
HARMONIA_3PH_LC_FILTER_VOLTAGE_SENSOR_MODEL = ResDiv + AMC1350 + TLV9061;

% Calculated phase voltage sense gain.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_GAIN = (HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM / (HARMONIA_3PH_LC_FILTER_VS_R_TOP_TOTAL_OHM + HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM)) * HARMONIA_3PH_LC_FILTER_VS_ISO_GAIN_V_V * (HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_FB_OHM / HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_IN_OHM);

% Phase current sensor model.
HARMONIA_3PH_LC_FILTER_CURRENT_SENSOR_MODEL = Infineon TLE4971A025;

% Phase current sensor sensitivity.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSITIVITY_MV_A = TLE4971A025_SENSITIVITY_MV_PER_A;

% Zero-current output bias.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_ZERO_BIAS_V = TLE4971A025_BIAS_V;

TLE4971A025_ID = 'tle4971a025';

TLE4971A025_SCHEMA = 'current_sensor';

TLE4971A025_NAME = 'TLE4971A025 Coreless Hall Current Sensor';

% Main sensing IC or technology name.
TLE4971A025_CHIP = 'TLE4971A025';

% Current sensing technology, such as Hall, shunt, or fluxgate.
TLE4971A025_SENSOR_TYPE = 'Coreless Hall';

% Nominal measurable current range.
TLE4971A025_RANGE_A = 25.0;

% Minimum output voltage.
TLE4971A025_OUTPUT_MIN_V = 0.0;

% Maximum output voltage.
TLE4971A025_OUTPUT_MAX_V = 3.3;

% Zero-current output bias.
TLE4971A025_BIAS_V = 1.65;

% Current sensor sensitivity.
TLE4971A025_SENSITIVITY_MV_PER_A = 48.0;

% Typical small-signal bandwidth.
TLE4971A025_BANDWIDTH_HZ = 210000.0;

% Sensor internal series resistance.
TLE4971A025_INTERNAL_RESISTANCE_OHM = 0.0;

% Current sensor sensitivity converted to V/A.
TLE4971A025_SENSITIVITY_V_PER_A = TLE4971A025_SENSITIVITY_MV_PER_A / 1000.0;

% Positive current range implied by bias and sensitivity.
TLE4971A025_MAX_CURRENT_FROM_BIAS_A = TLE4971A025_BIAS_V / TLE4971A025_SENSITIVITY_V_PER_A;

%% Project selection macros
% Enable Discrete PID controller anti-saturation algorithm.
USE_DEBUG_DISCRETE_PID = true;

% Enable ADC calibration.
SPECIFY_ENABLE_ADC_CALIBRATE = true;

% ENBALE_GMP_DL_PIL_SIM is disabled in the SDPE project requirement.
% ENBALE_GMP_DL_PIL_SIM = true;

% GMP_CTL_FM_CONFIG_ENABLE_DEBUG_INFO is disabled in the SDPE project requirement.
% GMP_CTL_FM_CONFIG_ENABLE_DEBUG_INFO = true;

%% Project option macros
% Single-phase inverter incremental debug build level.
% BUILD_LEVEL 1: modulator and resistive-load validation.
% BUILD_LEVEL 2: voltage closed-loop validation.
% BUILD_LEVEL 3: current-loop and full controller validation.
% Options: (1), (2), (3)
BUILD_LEVEL = 1;

% Use negative PWM modulator logic.
% Options: (0), (1)
PWM_MODULATOR_USING_NEGATIVE_LOGIC = 0;

% PWM base for inverter phase L.
% Options: IRIS_EPWM1_BASE, IRIS_EPWM2_BASE, IRIS_EPWM3_BASE, IRIS_EPWM4_BASE, IRIS_EPWM5_BASE, IRIS_EPWM6_BASE
PHASE_L_BASE = 'IRIS_EPWM3_BASE';

% PWM base for inverter phase N.
% Options: IRIS_EPWM1_BASE, IRIS_EPWM2_BASE, IRIS_EPWM3_BASE, IRIS_EPWM4_BASE, IRIS_EPWM5_BASE, IRIS_EPWM6_BASE
PHASE_N_BASE = 'IRIS_EPWM4_BASE';

% Gate-driver enable GPIO.
% Options: IRIS_GPIO1, IRIS_GPIO2, IRIS_GPIO3, IRIS_GPIO4, IRIS_GPIO5, IRIS_GPIO6
PWM_ENABLE_PORT = 'IRIS_GPIO1';

% Gate-driver reset GPIO.
% Options: IRIS_GPIO1, IRIS_GPIO2, IRIS_GPIO3, IRIS_GPIO4, IRIS_GPIO5, IRIS_GPIO6
PWM_RESET_PORT = 'IRIS_GPIO3';

% System status LED.
% Options: IRIS_LED1, IRIS_LED2, LED_R, LED_G
SYSTEM_LED = 'IRIS_LED1';

% Controller status LED.
% Options: IRIS_LED1, IRIS_LED2, LED_R, LED_G
CONTROLLER_LED = 'IRIS_LED2';

% AC current ADC result register base.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_IAC_RESULT_BASE = 'ADC_CH1_RESULT_BASE';

% AC current ADC channel.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_IAC = 'ADC_CH1';

% AC voltage ADC result register base.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_VAC_RESULT_BASE = 'ADC_CH2_RESULT_BASE';

% AC voltage ADC channel.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_VAC = 'ADC_CH2';

% DC bus voltage ADC result register base.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_VBUS_RESULT_BASE = 'ADC_CH3_RESULT_BASE';

% DC bus voltage ADC channel.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_VBUS = 'ADC_CH3';

%% Requirement bindings
% Startup delay in ms.
CTRL_STARTUP_DELAY = 100;

% Controller ISR frequency.
CONTROLLER_FREQUENCY = 20e3;

% PWM compare maximum.
CTRL_PWM_CMP_MAX = 3000 - 1;

% PWM deadband compare value.
CTRL_PWM_DEADBAND_CMP = 50;

% System tick divider derived from PWM period.
DSP_C2000_DSP_TIME_DIV = 120000 / CTRL_PWM_CMP_MAX / 2;

% ADC voltage reference.
CTRL_ADC_VOLTAGE_REF = 3.3;

% Rated DC bus voltage.
CTRL_DCBUS_VOLTAGE = 60.0;

% Rated AC grid/load RMS voltage.
CTRL_GRID_VOLTAGE_RMS = 24.0;

% Rated AC output RMS current.
CTRL_RATED_CURRENT_RMS = 10.0;

% Voltage per-unit base, using peak value.
CTRL_VOLTAGE_BASE = 34.0;

% Current per-unit base, using peak value.
CTRL_CURRENT_BASE = 14.14;

% AC voltage sensing gain from the grid LC filter voltage sense path.
CTRL_AC_VOLTAGE_SENSITIVITY = HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_GAIN;

% AC voltage sensing ADC bias from the grid LC filter.
CTRL_AC_VOLTAGE_BIAS = HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_BIAS_V;

% AC current sensing sensitivity from the LVFB inverter current sensor.
CTRL_AC_CURRENT_SENSITIVITY = GMP_LVFB_CURRENT_SENSITIVITY;

% AC current sensing ADC bias from the LVFB inverter current sensor.
CTRL_AC_CURRENT_BIAS = GMP_LVFB_CURRENT_BIAS_V;

% DC bus voltage sensing gain from the LVFB inverter voltage sensor.
CTRL_DC_VOLTAGE_SENSITIVITY = GMP_LVFB_VOLTAGE_SENSITIVITY;

% DC bus voltage sensing ADC bias from the LVFB inverter voltage sensor.
CTRL_DC_VOLTAGE_BIAS = GMP_LVFB_VOLTAGE_BIAS_V;

% Maximum hardware DC bus voltage from the LVFB inverter board.
CTRL_MAX_HW_VOLTAGE = GMP_LVFB_VBUS_MAX_V;

% Maximum continuous RMS hardware current from the LVFB inverter board.
CTRL_MAX_HW_CURRENT = GMP_LVFB_CURRENT_MAX_RMS_A;

% Project DC bus over-voltage protection threshold.
CTRL_PROT_VBUS_MAX = 100.0;

% ADC calibration timeout in ms.
TIMEOUT_ADC_CALIB_MS = 3000;

% SPLL close-loop convergence criterion.
CTRL_SPLL_EPSILON = float2ctrl(0.005);

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
