%% SDPE MATLAB initialization script
% Project: PGS SINV RC F280039C IRIS Node
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

% Load the explicitly bound common requirement first.
run(fullfile(fileparts(mfilename('fullpath')), 'sdpe_pgs_sinv_rc_common_settings_matlab_init.m'));

% Notes:
%   Single-phase inverter project requirement prepared from xplt/ctrl_settings.h.
%   This requirement introduces the GMP LVFB 150V 2-phase inverter board as the switching stage and the GMP Harmonia 3-phase LC filter as the grid filter. IRIS F280039C is included as the peripheral option provider.

%% Project metadata
SDPE_PROJECT_ID = 'pgs_sinv_rc_iris_node';

SDPE_PROJECT_SUITE = 'pgs_sinv_rc';

SDPE_PROJECT_VERSION = '0.2.0';

SDPE_PROJECT_UPDATED_AT = '2026-08-08';

%% Hardware macros
IRIS_F280039C_ID = 'iris_f280039c_node';

IRIS_F280039C_SCHEMA = 'iris_c2000_core_board';

IRIS_F280039C_NAME = 'IRIS F280039C Core Board';

% C2000 device name.
IRIS_F280039C_CHIP = 'TMS320F280039C';

% SysConfig source file used by this binding.
IRIS_F280039C_SYSCFG_FILE = 'ctl/suite/dps_fsbb/project/f280039c_Iris_node/F280039_Iris_node.syscfg';

% SysConfig EPWM1 base macro.
IRIS_F280039C_EPWM1_BASE = 'IRIS_EPWM1_BASE';

% SysConfig EPWM2 base macro.
IRIS_F280039C_EPWM2_BASE = 'IRIS_EPWM2_BASE';

% SysConfig ADC channel 1 macro.
IRIS_F280039C_ADC_CH1 = 'ADC_CH1';

% SysConfig ADC channel 2 macro.
IRIS_F280039C_ADC_CH2 = 'ADC_CH2';

% SysConfig ADC channel 3 macro.
IRIS_F280039C_ADC_CH3 = 'ADC_CH3';

% SysConfig ADC channel 4 macro.
IRIS_F280039C_ADC_CH4 = 'ADC_CH4';

BSC093N15NS5_ID = 'bsc093n15ns5';

BSC093N15NS5_SCHEMA = 'power_switch';

BSC093N15NS5_NAME = 'BSC093N15NS5';

% Power device part number.
BSC093N15NS5_PART_NUMBER = 'BSC093N15NS5';

% MOSFET, IGBT, GaN, SiC, etc.
BSC093N15NS5_DEVICE_TYPE = 'MOSFET';

% Drain-source or collector-emitter voltage rating.
BSC093N15NS5_VOLTAGE_RATING_V = 150.0;

% Current rating.
BSC093N15NS5_CURRENT_RATING_A = 55.0;

% On resistance.
BSC093N15NS5_RDSON_OHM = 0.0093;

% Single switch, dual switch, half bridge power block, etc.
BSC093N15NS5_CONFIGURATION = 'single';

% Maximum on resistance at the documented gate voltage.
BSC093N15NS5_RDSON_MAX_OHM = 0.0;

% Gate voltage associated with the resistance value.
BSC093N15NS5_GATE_VOLTAGE_V = 0.0;

% Typical total gate charge.
BSC093N15NS5_GATE_CHARGE_NC = 0.0;

% Manufacturer package name.
BSC093N15NS5_PACKAGE = 'unknown';

TMCS1133_B5A_ID = 'tmcs1133_b5a';

TMCS1133_B5A_SCHEMA = 'current_sensor';

TMCS1133_B5A_NAME = 'TMCS1133 B5A Hall Current Sensor';

% Main sensing IC or technology name.
TMCS1133_B5A_CHIP = 'TMCS1133B5A';

% Current sensing technology, such as Hall, shunt, or fluxgate.
TMCS1133_B5A_SENSOR_TYPE = 'Hall';

% Nominal measurable current range.
TMCS1133_B5A_RANGE_A = 10.3;

% Minimum output voltage.
TMCS1133_B5A_OUTPUT_MIN_V = 0.0;

% Maximum output voltage.
TMCS1133_B5A_OUTPUT_MAX_V = 3.3;

% Zero-current output bias.
TMCS1133_B5A_BIAS_V = 1.65;

% Current sensor sensitivity.
TMCS1133_B5A_SENSITIVITY_MV_PER_A = 150.0;

% Typical small-signal bandwidth.
TMCS1133_B5A_BANDWIDTH_HZ = 300000.0;

% Sensor internal series resistance.
TMCS1133_B5A_INTERNAL_RESISTANCE_OHM = 0.0018;

% Current sensor sensitivity converted to V/A.
TMCS1133_B5A_SENSITIVITY_V_PER_A = TMCS1133_B5A_SENSITIVITY_MV_PER_A / 1000.0;

% Positive current range implied by bias and sensitivity.
TMCS1133_B5A_MAX_CURRENT_FROM_BIAS_A = TMCS1133_B5A_BIAS_V / TMCS1133_B5A_SENSITIVITY_V_PER_A;

LVFB_VDIV_150V_ID = 'lvfb_voltage_divider_150v';

LVFB_VDIV_150V_SCHEMA = 'voltage_sensor';

LVFB_VDIV_150V_NAME = 'LVFB 150V Voltage Divider';

% Main sensing IC or front-end topology.
LVFB_VDIV_150V_CHIP = 'AMC1311BDWVR + resistor divider';

% Nominal measurable voltage.
LVFB_VDIV_150V_RATED_VOLTAGE_V = 150.0;

% Output bias voltage.
LVFB_VDIV_150V_BIAS_V = 0.0;

% Voltage sensor sensitivity.
LVFB_VDIV_150V_SENSITIVITY_V_PER_V = 0.016129;

% Equivalent input resistance.
LVFB_VDIV_150V_INPUT_RESISTANCE_OHM = 915000.0;

% Small-signal sensing bandwidth.
LVFB_VDIV_150V_BANDWIDTH_HZ = 0.0;

% Approximate positive full scale voltage when biased at mid-supply.
LVFB_VDIV_150V_MAX_BY_BIAS_V = sdpe_select(LVFB_VDIV_150V_BIAS_V > 0.0, LVFB_VDIV_150V_BIAS_V / LVFB_VDIV_150V_SENSITIVITY_V_PER_V, LVFB_VDIV_150V_RATED_VOLTAGE_V);

GMP_LVFB_ID = 'gmp_lvfb_150_2ph_v2';

GMP_LVFB_SCHEMA = 'half_bridge';

GMP_LVFB_NAME = 'GMP LVFB 150V 2-Phase V2 Inverter Board';

% Board or module name.
GMP_LVFB_BOARD_NAME = 'GMP LVFB 2ph V6.1';

% Integrated gate driver part number.
GMP_LVFB_GATE_DRIVER = 'UCC21520DWR';

% Power MOSFET part number.
GMP_LVFB_MOSFET = 'BSC093N15NS5';

% On-board current sensing device.
GMP_LVFB_CURRENT_SENSOR_NAME = 'TMCS1133B5A';

% On-board voltage sensing device.
GMP_LVFB_VOLTAGE_SENSOR_NAME = 'AMC1311BDWVR';

% Number of half-bridge phases represented by this module.
GMP_LVFB_PHASE_COUNT = 2;

% Current measurement range exported by the current sensor sub component.
GMP_LVFB_MEASURED_CURRENT_RANGE_A = TMCS1133_B5A_RANGE_A;

% Maximum allowable DC bus voltage.
GMP_LVFB_VBUS_MAX_V = 120.0;

% Maximum instantaneous peak phase current.
GMP_LVFB_CURRENT_MAX_PEAK_A = 55.0;

% Maximum continuous RMS phase current.
GMP_LVFB_CURRENT_MAX_RMS_A = 35.0;

% Recommended hardware deadtime.
GMP_LVFB_DEADTIME_NS = 523.0;

% Current sensing signal bandwidth.
GMP_LVFB_CURRENT_BW_HZ = 300.0e3;

% Current sensor ADC bias voltage.
GMP_LVFB_CURRENT_BIAS_V = 1.65;

% Configured current sensitivity.
GMP_LVFB_CURRENT_SENSITIVITY = TMCS1133_B5A_SENSITIVITY_V_PER_A;

% ADC reference scale voltage.
GMP_LVFB_VOLTAGE_BASE_V = 3.3;

% Voltage sensing ADC bias voltage.
GMP_LVFB_VOLTAGE_BIAS_V = 0.0;

% Voltage sensing bandwidth.
GMP_LVFB_VOLTAGE_BW_HZ = 114.47e3;

% Default low-side voltage divider resistance.
GMP_LVFB_VOLTAGE_R_LOW_OHM = 15000.0;

% Default high-side voltage divider resistance.
GMP_LVFB_VOLTAGE_R_HIGH_OHM = 300000.0;

% Configured voltage sensing gain.
GMP_LVFB_VOLTAGE_SENSITIVITY = (15e3) / ((15e3) + ((300e3) * 3)) * 1.65;

% Configured maximum measurable voltage.
GMP_LVFB_VOLTAGE_MAX = 3.3 / ((15e3) / ((15e3) + ((300e3) * 3)) * 1.65);

% Optional local DC bus capacitance.
GMP_LVFB_BUS_CAPACITANCE_F = 0.0;

% Whether this module declares a local bus capacitor.
GMP_LVFB_HAS_LOCAL_BUS_CAP = GMP_LVFB_BUS_CAPACITANCE_F > 0.0;

TLE4971A025_ID = 'tle4971a025';

TLE4971A025_SCHEMA = 'current_sensor';

TLE4971A025_NAME = 'TLE4971A025 Coreless Hall Current Sensor';

% Main sensing IC or technology name.
TLE4971A025_CHIP = 'TLE4971A025';

% Current sensing technology, such as Hall, shunt, or fluxgate.
TLE4971A025_SENSOR_TYPE = 'Coreless Hall';

% Nominal measurable current range.
TLE4971A025_RANGE_A = 25.0;

% Minimum output voltage.
TLE4971A025_OUTPUT_MIN_V = 0.0;

% Maximum output voltage.
TLE4971A025_OUTPUT_MAX_V = 3.3;

% Zero-current output bias.
TLE4971A025_BIAS_V = 1.65;

% Current sensor sensitivity.
TLE4971A025_SENSITIVITY_MV_PER_A = 48.0;

% Typical small-signal bandwidth.
TLE4971A025_BANDWIDTH_HZ = 210000.0;

% Sensor internal series resistance.
TLE4971A025_INTERNAL_RESISTANCE_OHM = 0.0;

% Current sensor sensitivity converted to V/A.
TLE4971A025_SENSITIVITY_V_PER_A = TLE4971A025_SENSITIVITY_MV_PER_A / 1000.0;

% Positive current range implied by bias and sensitivity.
TLE4971A025_MAX_CURRENT_FROM_BIAS_A = TLE4971A025_BIAS_V / TLE4971A025_SENSITIVITY_V_PER_A;

HARMONIA_3PH_LC_FILTER_ID = 'gmp_harmonia_3ph_lc_filter';

HARMONIA_3PH_LC_FILTER_SCHEMA = 'Harmonia_3ph_LC_filter';

HARMONIA_3PH_LC_FILTER_NAME = 'GMP Harmonia 3-Phase LC Filter';

% Main filter inductance.
HARMONIA_3PH_LC_FILTER_INDUCTANCE_H = 0.0015;

% Main filter capacitance.
HARMONIA_3PH_LC_FILTER_CAPACITANCE_F = 0.000005;

% Board or module name.
HARMONIA_3PH_LC_FILTER_BOARD_NAME = 'Harmonia 3Ph LC Filter';

% Maximum DC bus voltage.
HARMONIA_3PH_LC_FILTER_VBUS_MAX_V = 1000.0;

% Minimum DC bus voltage.
HARMONIA_3PH_LC_FILTER_VBUS_MIN_V = 0.0;

% Maximum continuous RMS current.
HARMONIA_3PH_LC_FILTER_CURRENT_MAX_RMS_A = 40.0;

% Maximum peak current.
HARMONIA_3PH_LC_FILTER_CURRENT_MAX_PEAK_A = HARMONIA_3PH_LC_FILTER_CURRENT_MAX_RMS_A * 1.41421356237;

% Recommended maximum PCB operating temperature.
HARMONIA_3PH_LC_FILTER_TEMP_MAX_C = 85.0;

% Phase current sensor type enum.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TYPE = 2;

% Phase current sensing topology enum.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TOPOLOGY = 3;

% Phase voltage sensing type enum.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_TYPE = 1;

% Phase current sensor bandwidth.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_POLE_HZ = TLE4971A025_BANDWIDTH_HZ;

% Total high-side voltage divider resistance.
HARMONIA_3PH_LC_FILTER_VS_R_TOP_TOTAL_OHM = 3920000.0;

% Bottom voltage divider resistance.
HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM = 560000.0;

% Isolation amplifier voltage gain.
HARMONIA_3PH_LC_FILTER_VS_ISO_GAIN_V_V = 0.4;

% Voltage sensing op-amp feedback resistor.
HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_FB_OHM = 1650.0;

% Voltage sensing op-amp input resistor.
HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_IN_OHM = 2000.0;

% ADC bias for phase voltage sensing.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_BIAS_V = 1.65;

% Approximate phase voltage sense bandwidth.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_POLE_HZ = 100000.0;

% Phase voltage sensor model.
HARMONIA_3PH_LC_FILTER_VOLTAGE_SENSOR_MODEL = ResDiv + AMC1350 + TLV9061;

% Calculated phase voltage sense gain.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_GAIN = (HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM / (HARMONIA_3PH_LC_FILTER_VS_R_TOP_TOTAL_OHM + HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM)) * HARMONIA_3PH_LC_FILTER_VS_ISO_GAIN_V_V * (HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_FB_OHM / HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_IN_OHM);

% Phase current sensor model.
HARMONIA_3PH_LC_FILTER_CURRENT_SENSOR_MODEL = Infineon TLE4971A025;

% Phase current sensor sensitivity.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSITIVITY_MV_A = TLE4971A025_SENSITIVITY_MV_PER_A;

% Zero-current output bias.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_ZERO_BIAS_V = TLE4971A025_BIAS_V;

%% Controller Features
% Enable Discrete PID controller anti-saturation algorithm.
USE_DEBUG_DISCRETE_PID = true;

% ENABLE_DEADBAND_COMP is disabled in the SDPE project requirement.
% ENABLE_DEADBAND_COMP = true;

%% Sensing and Calibration
% Enable ADC calibration.
SPECIFY_ENABLE_ADC_CALIBRATE = true;

%% Diagnostics and Simulation
% ENABLE_GMP_DL_PIL_SIM is disabled in the SDPE project requirement.
% ENABLE_GMP_DL_PIL_SIM = true;

% GMP_CTL_FM_CONFIG_ENABLE_DEBUG_INFO is disabled in the SDPE project requirement.
% GMP_CTL_FM_CONFIG_ENABLE_DEBUG_INFO = true;

%% Control Mode
% Single-phase converter commissioning level.
% BUILD_LEVEL 1: open-loop sinusoidal H-bridge voltage on an isolated resistive load; validates ADC polarity, PWM mapping and the power stage without a current loop.
% BUILD_LEVEL 2: closed AC-current loop on an isolated resistive load; validates QPR tracking, grid-voltage feedforward and optional FDRC.
% BUILD_LEVEL 3: grid-connected signed P/Q command through the current loop; positive P exports power and negative P rectifies.
% BUILD_LEVEL 4: grid-connected measured-active-power outer loop feeding the current loop.
% BUILD_LEVEL 5: active-front-end rectifier with a DC-bus voltage outer loop; takeover is initialized from the measured passive-rectifier power.
% Options: (1), (2), (3), (4), (5)
BUILD_LEVEL = 1;

%% PWM Modulator
% Use negative PWM modulator logic.
% Options: (0), (1)
PWM_MODULATOR_USING_NEGATIVE_LOGIC = 0;

%% PWM Channel Mapping
% PWM base for inverter phase L.
% Options: IRIS_EPWM1_BASE, IRIS_EPWM2_BASE, IRIS_EPWM3_BASE, IRIS_EPWM4_BASE, IRIS_EPWM5_BASE, IRIS_EPWM6_BASE
PHASE_L_BASE = 'IRIS_EPWM3_BASE';

% PWM base for inverter phase N.
% Options: IRIS_EPWM1_BASE, IRIS_EPWM2_BASE, IRIS_EPWM3_BASE, IRIS_EPWM4_BASE, IRIS_EPWM5_BASE, IRIS_EPWM6_BASE
PHASE_N_BASE = 'IRIS_EPWM4_BASE';

%% Gate Driver GPIO
% Gate-driver enable GPIO.
% Options: IRIS_GPIO1, IRIS_GPIO2, IRIS_GPIO3, IRIS_GPIO4, IRIS_GPIO5, IRIS_GPIO6
PWM_ENABLE_PORT = 'IRIS_GPIO1';

% Gate-driver reset GPIO.
% Options: IRIS_GPIO1, IRIS_GPIO2, IRIS_GPIO3, IRIS_GPIO4, IRIS_GPIO5, IRIS_GPIO6
PWM_RESET_PORT = 'IRIS_GPIO3';

%% Status GPIO
% System status LED.
% Options: IRIS_LED1, IRIS_LED2, LED_R, LED_G
SYSTEM_LED = 'IRIS_LED1';

% Controller status LED.
% Options: IRIS_LED1, IRIS_LED2, LED_R, LED_G
CONTROLLER_LED = 'IRIS_LED2';

%% AC Current Sensing
% AC current ADC result register base.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_IAC_RESULT_BASE = 'ADC_CH1_RESULT_BASE';

% AC current ADC channel.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_IAC = 'ADC_CH1';

%% AC Voltage Sensing
% AC voltage ADC result register base.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_VAC_RESULT_BASE = 'ADC_CH2_RESULT_BASE';

% AC voltage ADC channel.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_VAC = 'ADC_CH2';

%% DC Bus Sensing
% DC bus voltage ADC result register base.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
INV_VBUS_RESULT_BASE = 'ADC_CH3_RESULT_BASE';

% DC bus voltage ADC channel.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
INV_VBUS = 'ADC_CH3';

%% Requirement bindings
% Number of samples stored per channel by the four-channel hardware Data Link Scope.
GMP_DL_SCOPE_DEPTH = 100;

% Controller ISR frequency.
CONTROLLER_FREQUENCY = 20e3;

% PWM compare maximum.
CTRL_PWM_CMP_MAX = 3000 - 1;

% PWM deadband compare value.
CTRL_PWM_DEADBAND_CMP = 50;

% System tick divider derived from PWM period.
DSP_C2000_DSP_TIME_DIV = 120000 / CTRL_PWM_CMP_MAX / 2;

% ADC voltage reference.
CTRL_ADC_VOLTAGE_REF = 3.3;

% Rated DC bus voltage.
CTRL_DCBUS_VOLTAGE = 60.0;

% Rated AC grid/load RMS voltage.
CTRL_GRID_VOLTAGE_RMS = 24.0;

% Rated AC output RMS current.
CTRL_RATED_CURRENT_RMS = 10.0;

% Voltage per-unit base, using peak value.
CTRL_VOLTAGE_BASE = 34.0;

% Current per-unit base, using peak value.
CTRL_CURRENT_BASE = 14.14;

% Nominal AC grid/fundamental frequency in Hz.
CTRL_GRID_FREQUENCY = 50.0;

% Total AC-side filter/grid inductance in H.
CTRL_AC_INDUCTANCE = 0.0015;

% Total AC-side series resistance in Ohm.
CTRL_AC_RESISTANCE = 0.05;

% Minimum PLL voltage magnitude used by P/Q reference division.
CTRL_GRID_VMIN_PU = 0.1;

% Maximum hardware DC bus voltage from the LVFB inverter board.
CTRL_MAX_HW_VOLTAGE = GMP_LVFB_VBUS_MAX_V;

% Maximum continuous RMS hardware current from the LVFB inverter board.
CTRL_MAX_HW_CURRENT = GMP_LVFB_CURRENT_MAX_RMS_A;

% Project DC bus over-voltage protection threshold.
CTRL_PROT_VBUS_MAX = 100.0;

% Fast AC peak-current trip threshold in A.
CTRL_PROT_IAC_PEAK_MAX = CTRL_MAX_HW_CURRENT * 0.9 * 1.41421356;

% Maximum unsaturated modulation command before controller-divergence trip.
CTRL_PROT_VCTRL_MAX_PU = 1.5;

% Minimum physical DC-bus voltage accepted by the startup state machine.
CTRL_DCBUS_READY_MIN = CTRL_DCBUS_VOLTAGE * 0.8;

% Maximum physical DC-bus voltage accepted by the startup state machine.
CTRL_DCBUS_READY_MAX = CTRL_PROT_VBUS_MAX;

% Single-phase PLL proportional gain.
CTRL_PLL_KP = 2.0;

% Single-phase PLL integral time constant in seconds.
CTRL_PLL_TI = 0.02;

% PLL q-axis error low-pass cutoff in Hz.
CTRL_PLL_LPF_FC = 20.0;

% SPLL close-loop convergence criterion.
CTRL_SPLL_EPSILON = float2ctrl(0.005);

% DC-bus outer-loop proportional gain.
SINV_DC_BUS_LOOP_KP = 0.8;

% DC-bus outer-loop integral gain per second.
SINV_DC_BUS_LOOP_KI = 12.0;

% Symmetric outer-loop active-power command limit.
SINV_OUTER_LOOP_POWER_LIMIT_PU = 0.65;

% Power and DC-bus outer-loop execution frequency.
SINV_OUTER_LOOP_FREQUENCY_HZ = 1000.0;

% Current polarity deadband for PWM dead-time compensation.
CTRL_CURRENT_DB_PU = 0.01;

% ADC calibration timeout in ms.
TIMEOUT_ADC_CALIB_MS = 3000;

% Active-power command slew limit in PU/s.
CTRL_P_SLEW_PU_S = 10.0;

% Reactive-power command slew limit in PU/s.
CTRL_Q_SLEW_PU_S = 20.0;

% Active-power outer-loop proportional gain.
SINV_POWER_LOOP_KP = 0.6;

% Active-power outer-loop integral gain per second.
SINV_POWER_LOOP_KI = 8.0;

% Peak current-reference limit in per unit.
CTRL_CURRENT_LIMIT_PU = 1.5;

% Measured active/reactive power low-pass cutoff in Hz.
CTRL_PQ_LPF_FC = 200.0;

% Minimum fundamental frequency tracked by the repetitive controller in Hz.
CTRL_FDRC_MIN_FREQ = 45.0;

% Repetitive-control learning gain.
SINV_FDRC_LEARNING_GAIN = 0.10;

% FDRC robustness-filter cutoff frequency.
SINV_FDRC_Q_FILTER_HZ = 1000.0;

% Plant-delay compensation in controller samples.
SINV_FDRC_LEAD_STEPS = 3.0;

% Current-error threshold above which RC learning is frozen.
SINV_FDRC_FREEZE_ERROR_PU = 0.05;

% Settling time before repetitive control starts learning.
SINV_FDRC_ENABLE_DELAY_MS = 300;

% Startup delay in ms.
CTRL_STARTUP_DELAY = 100;

% DC bus voltage sensing gain from the LVFB inverter voltage sensor.
CTRL_DC_VOLTAGE_SENSITIVITY = GMP_LVFB_VOLTAGE_SENSITIVITY;

% DC bus voltage sensing ADC bias from the LVFB inverter voltage sensor.
CTRL_DC_VOLTAGE_BIAS = GMP_LVFB_VOLTAGE_BIAS_V;

% AC voltage sensing gain from the grid LC filter voltage sense path.
CTRL_AC_VOLTAGE_SENSITIVITY = HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_GAIN;

% AC voltage sensing ADC bias from the grid LC filter.
CTRL_AC_VOLTAGE_BIAS = HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_BIAS_V;

% AC current sensing sensitivity from the LVFB inverter current sensor.
CTRL_AC_CURRENT_SENSITIVITY = GMP_LVFB_CURRENT_SENSITIVITY;

% AC current sensing ADC bias from the LVFB inverter current sensor.
CTRL_AC_CURRENT_BIAS = GMP_LVFB_CURRENT_BIAS_V;

%% SDPE project summary
fprintf('\n============================================================\n');
fprintf('SDPE Project : %s\n', 'PGS SINV RC F280039C IRIS Node');
fprintf('Project ID   : %s\n', 'pgs_sinv_rc_iris_node');
fprintf('Suite        : %s\n', 'pgs_sinv_rc');
fprintf('Version      : %s\n', '0.2.0');
fprintf('Hardware (3):\n');
fprintf('  - %s\n', 'iris_f280039c_node');
fprintf('  - %s\n', 'gmp_lvfb_150_2ph_v2');
fprintf('  - %s\n', 'gmp_harmonia_3ph_lc_filter');
fprintf('Common requirements (1):\n');
fprintf('  - %s\n', 'PGS Single-Phase Inverter Common Control');
fprintf('Enabled variables (201):\n');
fprintf('  BSC093N15NS5_CONFIGURATION = '); disp(BSC093N15NS5_CONFIGURATION);
fprintf('  BSC093N15NS5_CURRENT_RATING_A = '); disp(BSC093N15NS5_CURRENT_RATING_A);
fprintf('  BSC093N15NS5_DEVICE_TYPE = '); disp(BSC093N15NS5_DEVICE_TYPE);
fprintf('  BSC093N15NS5_GATE_CHARGE_NC = '); disp(BSC093N15NS5_GATE_CHARGE_NC);
fprintf('  BSC093N15NS5_GATE_VOLTAGE_V = '); disp(BSC093N15NS5_GATE_VOLTAGE_V);
fprintf('  BSC093N15NS5_ID = '); disp(BSC093N15NS5_ID);
fprintf('  BSC093N15NS5_NAME = '); disp(BSC093N15NS5_NAME);
fprintf('  BSC093N15NS5_PACKAGE = '); disp(BSC093N15NS5_PACKAGE);
fprintf('  BSC093N15NS5_PART_NUMBER = '); disp(BSC093N15NS5_PART_NUMBER);
fprintf('  BSC093N15NS5_RDSON_MAX_OHM = '); disp(BSC093N15NS5_RDSON_MAX_OHM);
fprintf('  BSC093N15NS5_RDSON_OHM = '); disp(BSC093N15NS5_RDSON_OHM);
fprintf('  BSC093N15NS5_SCHEMA = '); disp(BSC093N15NS5_SCHEMA);
fprintf('  BSC093N15NS5_VOLTAGE_RATING_V = '); disp(BSC093N15NS5_VOLTAGE_RATING_V);
fprintf('  BUILD_LEVEL = '); disp(BUILD_LEVEL);
fprintf('  CIA402_CONFIG_ENABLE_SEQUENCE_SWITCH = '); disp(CIA402_CONFIG_ENABLE_SEQUENCE_SWITCH);
fprintf('  CONTROLLER_FREQUENCY = '); disp(CONTROLLER_FREQUENCY);
fprintf('  CONTROLLER_LED = '); disp(CONTROLLER_LED);
fprintf('  CTRL_AC_CURRENT_BIAS = '); disp(CTRL_AC_CURRENT_BIAS);
fprintf('  CTRL_AC_CURRENT_SENSITIVITY = '); disp(CTRL_AC_CURRENT_SENSITIVITY);
fprintf('  CTRL_AC_INDUCTANCE = '); disp(CTRL_AC_INDUCTANCE);
fprintf('  CTRL_AC_RESISTANCE = '); disp(CTRL_AC_RESISTANCE);
fprintf('  CTRL_AC_VOLTAGE_BIAS = '); disp(CTRL_AC_VOLTAGE_BIAS);
fprintf('  CTRL_AC_VOLTAGE_SENSITIVITY = '); disp(CTRL_AC_VOLTAGE_SENSITIVITY);
fprintf('  CTRL_ADC_VOLTAGE_REF = '); disp(CTRL_ADC_VOLTAGE_REF);
fprintf('  CTRL_CURRENT_BASE = '); disp(CTRL_CURRENT_BASE);
fprintf('  CTRL_CURRENT_DB_PU = '); disp(CTRL_CURRENT_DB_PU);
fprintf('  CTRL_CURRENT_LIMIT_PU = '); disp(CTRL_CURRENT_LIMIT_PU);
fprintf('  CTRL_DCBUS_READY_MAX = '); disp(CTRL_DCBUS_READY_MAX);
fprintf('  CTRL_DCBUS_READY_MIN = '); disp(CTRL_DCBUS_READY_MIN);
fprintf('  CTRL_DCBUS_VOLTAGE = '); disp(CTRL_DCBUS_VOLTAGE);
fprintf('  CTRL_DC_VOLTAGE_BIAS = '); disp(CTRL_DC_VOLTAGE_BIAS);
fprintf('  CTRL_DC_VOLTAGE_SENSITIVITY = '); disp(CTRL_DC_VOLTAGE_SENSITIVITY);
fprintf('  CTRL_FDRC_MIN_FREQ = '); disp(CTRL_FDRC_MIN_FREQ);
fprintf('  CTRL_GRID_FREQUENCY = '); disp(CTRL_GRID_FREQUENCY);
fprintf('  CTRL_GRID_VMIN_PU = '); disp(CTRL_GRID_VMIN_PU);
fprintf('  CTRL_GRID_VOLTAGE_RMS = '); disp(CTRL_GRID_VOLTAGE_RMS);
fprintf('  CTRL_MAX_HW_CURRENT = '); disp(CTRL_MAX_HW_CURRENT);
fprintf('  CTRL_MAX_HW_VOLTAGE = '); disp(CTRL_MAX_HW_VOLTAGE);
fprintf('  CTRL_PLL_KP = '); disp(CTRL_PLL_KP);
fprintf('  CTRL_PLL_LPF_FC = '); disp(CTRL_PLL_LPF_FC);
fprintf('  CTRL_PLL_TI = '); disp(CTRL_PLL_TI);
fprintf('  CTRL_PQ_LPF_FC = '); disp(CTRL_PQ_LPF_FC);
fprintf('  CTRL_PROT_IAC_PEAK_MAX = '); disp(CTRL_PROT_IAC_PEAK_MAX);
fprintf('  CTRL_PROT_VBUS_MAX = '); disp(CTRL_PROT_VBUS_MAX);
fprintf('  CTRL_PROT_VCTRL_MAX_PU = '); disp(CTRL_PROT_VCTRL_MAX_PU);
fprintf('  CTRL_PWM_CMP_MAX = '); disp(CTRL_PWM_CMP_MAX);
fprintf('  CTRL_PWM_DEADBAND_CMP = '); disp(CTRL_PWM_DEADBAND_CMP);
fprintf('  CTRL_P_SLEW_PU_S = '); disp(CTRL_P_SLEW_PU_S);
fprintf('  CTRL_Q_SLEW_PU_S = '); disp(CTRL_Q_SLEW_PU_S);
fprintf('  CTRL_RATED_CURRENT_RMS = '); disp(CTRL_RATED_CURRENT_RMS);
fprintf('  CTRL_SPLL_EPSILON = '); disp(CTRL_SPLL_EPSILON);
fprintf('  CTRL_STARTUP_DELAY = '); disp(CTRL_STARTUP_DELAY);
fprintf('  CTRL_VOLTAGE_BASE = '); disp(CTRL_VOLTAGE_BASE);
fprintf('  DSP_C2000_DSP_TIME_DIV = '); disp(DSP_C2000_DSP_TIME_DIV);
fprintf('  GMP_DL_SCOPE_DEPTH = '); disp(GMP_DL_SCOPE_DEPTH);
fprintf('  GMP_LVFB_BOARD_NAME = '); disp(GMP_LVFB_BOARD_NAME);
fprintf('  GMP_LVFB_BUS_CAPACITANCE_F = '); disp(GMP_LVFB_BUS_CAPACITANCE_F);
fprintf('  GMP_LVFB_CURRENT_BIAS_V = '); disp(GMP_LVFB_CURRENT_BIAS_V);
fprintf('  GMP_LVFB_CURRENT_BW_HZ = '); disp(GMP_LVFB_CURRENT_BW_HZ);
fprintf('  GMP_LVFB_CURRENT_MAX_PEAK_A = '); disp(GMP_LVFB_CURRENT_MAX_PEAK_A);
fprintf('  GMP_LVFB_CURRENT_MAX_RMS_A = '); disp(GMP_LVFB_CURRENT_MAX_RMS_A);
fprintf('  GMP_LVFB_CURRENT_SENSITIVITY = '); disp(GMP_LVFB_CURRENT_SENSITIVITY);
fprintf('  GMP_LVFB_CURRENT_SENSOR_NAME = '); disp(GMP_LVFB_CURRENT_SENSOR_NAME);
fprintf('  GMP_LVFB_DEADTIME_NS = '); disp(GMP_LVFB_DEADTIME_NS);
fprintf('  GMP_LVFB_GATE_DRIVER = '); disp(GMP_LVFB_GATE_DRIVER);
fprintf('  GMP_LVFB_HAS_LOCAL_BUS_CAP = '); disp(GMP_LVFB_HAS_LOCAL_BUS_CAP);
fprintf('  GMP_LVFB_ID = '); disp(GMP_LVFB_ID);
fprintf('  GMP_LVFB_MEASURED_CURRENT_RANGE_A = '); disp(GMP_LVFB_MEASURED_CURRENT_RANGE_A);
fprintf('  GMP_LVFB_MOSFET = '); disp(GMP_LVFB_MOSFET);
fprintf('  GMP_LVFB_NAME = '); disp(GMP_LVFB_NAME);
fprintf('  GMP_LVFB_PHASE_COUNT = '); disp(GMP_LVFB_PHASE_COUNT);
fprintf('  GMP_LVFB_SCHEMA = '); disp(GMP_LVFB_SCHEMA);
fprintf('  GMP_LVFB_VBUS_MAX_V = '); disp(GMP_LVFB_VBUS_MAX_V);
fprintf('  GMP_LVFB_VOLTAGE_BASE_V = '); disp(GMP_LVFB_VOLTAGE_BASE_V);
fprintf('  GMP_LVFB_VOLTAGE_BIAS_V = '); disp(GMP_LVFB_VOLTAGE_BIAS_V);
fprintf('  GMP_LVFB_VOLTAGE_BW_HZ = '); disp(GMP_LVFB_VOLTAGE_BW_HZ);
fprintf('  GMP_LVFB_VOLTAGE_MAX = '); disp(GMP_LVFB_VOLTAGE_MAX);
fprintf('  GMP_LVFB_VOLTAGE_R_HIGH_OHM = '); disp(GMP_LVFB_VOLTAGE_R_HIGH_OHM);
fprintf('  GMP_LVFB_VOLTAGE_R_LOW_OHM = '); disp(GMP_LVFB_VOLTAGE_R_LOW_OHM);
fprintf('  GMP_LVFB_VOLTAGE_SENSITIVITY = '); disp(GMP_LVFB_VOLTAGE_SENSITIVITY);
fprintf('  GMP_LVFB_VOLTAGE_SENSOR_NAME = '); disp(GMP_LVFB_VOLTAGE_SENSOR_NAME);
fprintf('  HARMONIA_3PH_LC_FILTER_BOARD_NAME = '); disp(HARMONIA_3PH_LC_FILTER_BOARD_NAME);
fprintf('  HARMONIA_3PH_LC_FILTER_CAPACITANCE_F = '); disp(HARMONIA_3PH_LC_FILTER_CAPACITANCE_F);
fprintf('  HARMONIA_3PH_LC_FILTER_CURRENT_MAX_PEAK_A = '); disp(HARMONIA_3PH_LC_FILTER_CURRENT_MAX_PEAK_A);
fprintf('  HARMONIA_3PH_LC_FILTER_CURRENT_MAX_RMS_A = '); disp(HARMONIA_3PH_LC_FILTER_CURRENT_MAX_RMS_A);
fprintf('  HARMONIA_3PH_LC_FILTER_CURRENT_SENSOR_MODEL = '); disp(HARMONIA_3PH_LC_FILTER_CURRENT_SENSOR_MODEL);
fprintf('  HARMONIA_3PH_LC_FILTER_ID = '); disp(HARMONIA_3PH_LC_FILTER_ID);
fprintf('  HARMONIA_3PH_LC_FILTER_INDUCTANCE_H = '); disp(HARMONIA_3PH_LC_FILTER_INDUCTANCE_H);
fprintf('  HARMONIA_3PH_LC_FILTER_NAME = '); disp(HARMONIA_3PH_LC_FILTER_NAME);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_POLE_HZ = '); disp(HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_POLE_HZ);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TOPOLOGY = '); disp(HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TOPOLOGY);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TYPE = '); disp(HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TYPE);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSITIVITY_MV_A = '); disp(HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSITIVITY_MV_A);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_CURRENT_ZERO_BIAS_V = '); disp(HARMONIA_3PH_LC_FILTER_PH_CURRENT_ZERO_BIAS_V);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_BIAS_V = '); disp(HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_BIAS_V);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_GAIN = '); disp(HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_GAIN);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_POLE_HZ = '); disp(HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_POLE_HZ);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_TYPE = '); disp(HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_TYPE);
fprintf('  HARMONIA_3PH_LC_FILTER_SCHEMA = '); disp(HARMONIA_3PH_LC_FILTER_SCHEMA);
fprintf('  HARMONIA_3PH_LC_FILTER_TEMP_MAX_C = '); disp(HARMONIA_3PH_LC_FILTER_TEMP_MAX_C);
fprintf('  HARMONIA_3PH_LC_FILTER_VBUS_MAX_V = '); disp(HARMONIA_3PH_LC_FILTER_VBUS_MAX_V);
fprintf('  HARMONIA_3PH_LC_FILTER_VBUS_MIN_V = '); disp(HARMONIA_3PH_LC_FILTER_VBUS_MIN_V);
fprintf('  HARMONIA_3PH_LC_FILTER_VOLTAGE_SENSOR_MODEL = '); disp(HARMONIA_3PH_LC_FILTER_VOLTAGE_SENSOR_MODEL);
fprintf('  HARMONIA_3PH_LC_FILTER_VS_ISO_GAIN_V_V = '); disp(HARMONIA_3PH_LC_FILTER_VS_ISO_GAIN_V_V);
fprintf('  HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_FB_OHM = '); disp(HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_FB_OHM);
fprintf('  HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_IN_OHM = '); disp(HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_IN_OHM);
fprintf('  HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM = '); disp(HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM);
fprintf('  HARMONIA_3PH_LC_FILTER_VS_R_TOP_TOTAL_OHM = '); disp(HARMONIA_3PH_LC_FILTER_VS_R_TOP_TOTAL_OHM);
fprintf('  INV_IAC = '); disp(INV_IAC);
fprintf('  INV_IAC_RESULT_BASE = '); disp(INV_IAC_RESULT_BASE);
fprintf('  INV_VAC = '); disp(INV_VAC);
fprintf('  INV_VAC_RESULT_BASE = '); disp(INV_VAC_RESULT_BASE);
fprintf('  INV_VBUS = '); disp(INV_VBUS);
fprintf('  INV_VBUS_RESULT_BASE = '); disp(INV_VBUS_RESULT_BASE);
fprintf('  IRIS_F280039C_ADC_CH1 = '); disp(IRIS_F280039C_ADC_CH1);
fprintf('  IRIS_F280039C_ADC_CH2 = '); disp(IRIS_F280039C_ADC_CH2);
fprintf('  IRIS_F280039C_ADC_CH3 = '); disp(IRIS_F280039C_ADC_CH3);
fprintf('  IRIS_F280039C_ADC_CH4 = '); disp(IRIS_F280039C_ADC_CH4);
fprintf('  IRIS_F280039C_CHIP = '); disp(IRIS_F280039C_CHIP);
fprintf('  IRIS_F280039C_EPWM1_BASE = '); disp(IRIS_F280039C_EPWM1_BASE);
fprintf('  IRIS_F280039C_EPWM2_BASE = '); disp(IRIS_F280039C_EPWM2_BASE);
fprintf('  IRIS_F280039C_ID = '); disp(IRIS_F280039C_ID);
fprintf('  IRIS_F280039C_NAME = '); disp(IRIS_F280039C_NAME);
fprintf('  IRIS_F280039C_SCHEMA = '); disp(IRIS_F280039C_SCHEMA);
fprintf('  IRIS_F280039C_SYSCFG_FILE = '); disp(IRIS_F280039C_SYSCFG_FILE);
fprintf('  LVFB_VDIV_150V_BANDWIDTH_HZ = '); disp(LVFB_VDIV_150V_BANDWIDTH_HZ);
fprintf('  LVFB_VDIV_150V_BIAS_V = '); disp(LVFB_VDIV_150V_BIAS_V);
fprintf('  LVFB_VDIV_150V_CHIP = '); disp(LVFB_VDIV_150V_CHIP);
fprintf('  LVFB_VDIV_150V_ID = '); disp(LVFB_VDIV_150V_ID);
fprintf('  LVFB_VDIV_150V_INPUT_RESISTANCE_OHM = '); disp(LVFB_VDIV_150V_INPUT_RESISTANCE_OHM);
fprintf('  LVFB_VDIV_150V_MAX_BY_BIAS_V = '); disp(LVFB_VDIV_150V_MAX_BY_BIAS_V);
fprintf('  LVFB_VDIV_150V_NAME = '); disp(LVFB_VDIV_150V_NAME);
fprintf('  LVFB_VDIV_150V_RATED_VOLTAGE_V = '); disp(LVFB_VDIV_150V_RATED_VOLTAGE_V);
fprintf('  LVFB_VDIV_150V_SCHEMA = '); disp(LVFB_VDIV_150V_SCHEMA);
fprintf('  LVFB_VDIV_150V_SENSITIVITY_V_PER_V = '); disp(LVFB_VDIV_150V_SENSITIVITY_V_PER_V);
fprintf('  PGS_SINV_RC_COMMON_SDPE_PROJECT_ID = '); disp(PGS_SINV_RC_COMMON_SDPE_PROJECT_ID);
fprintf('  PGS_SINV_RC_COMMON_SDPE_PROJECT_SUITE = '); disp(PGS_SINV_RC_COMMON_SDPE_PROJECT_SUITE);
fprintf('  PGS_SINV_RC_COMMON_SDPE_PROJECT_UPDATED_AT = '); disp(PGS_SINV_RC_COMMON_SDPE_PROJECT_UPDATED_AT);
fprintf('  PGS_SINV_RC_COMMON_SDPE_PROJECT_VERSION = '); disp(PGS_SINV_RC_COMMON_SDPE_PROJECT_VERSION);
fprintf('  PHASE_L_BASE = '); disp(PHASE_L_BASE);
fprintf('  PHASE_N_BASE = '); disp(PHASE_N_BASE);
fprintf('  PWM_ENABLE_PORT = '); disp(PWM_ENABLE_PORT);
fprintf('  PWM_MODULATOR_USING_NEGATIVE_LOGIC = '); disp(PWM_MODULATOR_USING_NEGATIVE_LOGIC);
fprintf('  PWM_RESET_PORT = '); disp(PWM_RESET_PORT);
fprintf('  SDPE_PROJECT_ID = '); disp(SDPE_PROJECT_ID);
fprintf('  SDPE_PROJECT_SUITE = '); disp(SDPE_PROJECT_SUITE);
fprintf('  SDPE_PROJECT_UPDATED_AT = '); disp(SDPE_PROJECT_UPDATED_AT);
fprintf('  SDPE_PROJECT_VERSION = '); disp(SDPE_PROJECT_VERSION);
fprintf('  SINV_CIA402_OPERATION_ENABLE_DELAY_MS = '); disp(SINV_CIA402_OPERATION_ENABLE_DELAY_MS);
fprintf('  SINV_CURRENT_LOOP_BANDWIDTH_HZ = '); disp(SINV_CURRENT_LOOP_BANDWIDTH_HZ);
fprintf('  SINV_DC_BUS_LOOP_KI = '); disp(SINV_DC_BUS_LOOP_KI);
fprintf('  SINV_DC_BUS_LOOP_KP = '); disp(SINV_DC_BUS_LOOP_KP);
fprintf('  SINV_DC_BUS_REF_V = '); disp(SINV_DC_BUS_REF_V);
fprintf('  SINV_ENABLE_GRID_VOLTAGE_FEEDFORWARD = '); disp(SINV_ENABLE_GRID_VOLTAGE_FEEDFORWARD);
fprintf('  SINV_ENABLE_REPETITIVE_CONTROL = '); disp(SINV_ENABLE_REPETITIVE_CONTROL);
fprintf('  SINV_FDRC_ENABLE_DELAY_MS = '); disp(SINV_FDRC_ENABLE_DELAY_MS);
fprintf('  SINV_FDRC_FREEZE_ERROR_PU = '); disp(SINV_FDRC_FREEZE_ERROR_PU);
fprintf('  SINV_FDRC_LEAD_STEPS = '); disp(SINV_FDRC_LEAD_STEPS);
fprintf('  SINV_FDRC_LEARNING_GAIN = '); disp(SINV_FDRC_LEARNING_GAIN);
fprintf('  SINV_FDRC_Q_FILTER_HZ = '); disp(SINV_FDRC_Q_FILTER_HZ);
fprintf('  SINV_LEVEL1_VOLTAGE_REF_PU = '); disp(SINV_LEVEL1_VOLTAGE_REF_PU);
fprintf('  SINV_LEVEL2_CURRENT_REF_PEAK_PU = '); disp(SINV_LEVEL2_CURRENT_REF_PEAK_PU);
fprintf('  SINV_LEVEL3_ACTIVE_POWER_REF_PU = '); disp(SINV_LEVEL3_ACTIVE_POWER_REF_PU);
fprintf('  SINV_LEVEL3_REACTIVE_POWER_REF_PU = '); disp(SINV_LEVEL3_REACTIVE_POWER_REF_PU);
fprintf('  SINV_LEVEL4_ACTIVE_POWER_REF_PU = '); disp(SINV_LEVEL4_ACTIVE_POWER_REF_PU);
fprintf('  SINV_OUTER_LOOP_FREQUENCY_HZ = '); disp(SINV_OUTER_LOOP_FREQUENCY_HZ);
fprintf('  SINV_OUTER_LOOP_POWER_LIMIT_PU = '); disp(SINV_OUTER_LOOP_POWER_LIMIT_PU);
fprintf('  SINV_POWER_LOOP_KI = '); disp(SINV_POWER_LOOP_KI);
fprintf('  SINV_POWER_LOOP_KP = '); disp(SINV_POWER_LOOP_KP);
fprintf('  SPECIFY_ENABLE_ADC_CALIBRATE = '); disp(SPECIFY_ENABLE_ADC_CALIBRATE);
fprintf('  SYSTEM_LED = '); disp(SYSTEM_LED);
fprintf('  TIMEOUT_ADC_CALIB_MS = '); disp(TIMEOUT_ADC_CALIB_MS);
fprintf('  TLE4971A025_BANDWIDTH_HZ = '); disp(TLE4971A025_BANDWIDTH_HZ);
fprintf('  TLE4971A025_BIAS_V = '); disp(TLE4971A025_BIAS_V);
fprintf('  TLE4971A025_CHIP = '); disp(TLE4971A025_CHIP);
fprintf('  TLE4971A025_ID = '); disp(TLE4971A025_ID);
fprintf('  TLE4971A025_INTERNAL_RESISTANCE_OHM = '); disp(TLE4971A025_INTERNAL_RESISTANCE_OHM);
fprintf('  TLE4971A025_MAX_CURRENT_FROM_BIAS_A = '); disp(TLE4971A025_MAX_CURRENT_FROM_BIAS_A);
fprintf('  TLE4971A025_NAME = '); disp(TLE4971A025_NAME);
fprintf('  TLE4971A025_OUTPUT_MAX_V = '); disp(TLE4971A025_OUTPUT_MAX_V);
fprintf('  TLE4971A025_OUTPUT_MIN_V = '); disp(TLE4971A025_OUTPUT_MIN_V);
fprintf('  TLE4971A025_RANGE_A = '); disp(TLE4971A025_RANGE_A);
fprintf('  TLE4971A025_SCHEMA = '); disp(TLE4971A025_SCHEMA);
fprintf('  TLE4971A025_SENSITIVITY_MV_PER_A = '); disp(TLE4971A025_SENSITIVITY_MV_PER_A);
fprintf('  TLE4971A025_SENSITIVITY_V_PER_A = '); disp(TLE4971A025_SENSITIVITY_V_PER_A);
fprintf('  TLE4971A025_SENSOR_TYPE = '); disp(TLE4971A025_SENSOR_TYPE);
fprintf('  TMCS1133_B5A_BANDWIDTH_HZ = '); disp(TMCS1133_B5A_BANDWIDTH_HZ);
fprintf('  TMCS1133_B5A_BIAS_V = '); disp(TMCS1133_B5A_BIAS_V);
fprintf('  TMCS1133_B5A_CHIP = '); disp(TMCS1133_B5A_CHIP);
fprintf('  TMCS1133_B5A_ID = '); disp(TMCS1133_B5A_ID);
fprintf('  TMCS1133_B5A_INTERNAL_RESISTANCE_OHM = '); disp(TMCS1133_B5A_INTERNAL_RESISTANCE_OHM);
fprintf('  TMCS1133_B5A_MAX_CURRENT_FROM_BIAS_A = '); disp(TMCS1133_B5A_MAX_CURRENT_FROM_BIAS_A);
fprintf('  TMCS1133_B5A_NAME = '); disp(TMCS1133_B5A_NAME);
fprintf('  TMCS1133_B5A_OUTPUT_MAX_V = '); disp(TMCS1133_B5A_OUTPUT_MAX_V);
fprintf('  TMCS1133_B5A_OUTPUT_MIN_V = '); disp(TMCS1133_B5A_OUTPUT_MIN_V);
fprintf('  TMCS1133_B5A_RANGE_A = '); disp(TMCS1133_B5A_RANGE_A);
fprintf('  TMCS1133_B5A_SCHEMA = '); disp(TMCS1133_B5A_SCHEMA);
fprintf('  TMCS1133_B5A_SENSITIVITY_MV_PER_A = '); disp(TMCS1133_B5A_SENSITIVITY_MV_PER_A);
fprintf('  TMCS1133_B5A_SENSITIVITY_V_PER_A = '); disp(TMCS1133_B5A_SENSITIVITY_V_PER_A);
fprintf('  TMCS1133_B5A_SENSOR_TYPE = '); disp(TMCS1133_B5A_SENSOR_TYPE);
fprintf('  USE_DEBUG_DISCRETE_PID = '); disp(USE_DEBUG_DISCRETE_PID);
fprintf('Disabled macros (3):\n');
fprintf('  - ENABLE_DEADBAND_COMP\n');
fprintf('  - ENABLE_GMP_DL_PIL_SIM\n');
fprintf('  - GMP_CTL_FM_CONFIG_ENABLE_DEBUG_INFO\n');
fprintf('============================================================\n');

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
