/** @brief Full GMP configuration used when a CTL test includes core services. */
#ifndef GMP_CTL_UNIT_TEST_XPLT_CONFIG_H
#define GMP_CTL_UNIT_TEST_XPLT_CONFIG_H

#define SPECIFY_DISABLE_CSP
#define SPECIFY_ENABLE_GMP_CTL
#define SPECIFY_PC_ENVIRONMENT
#define SPECIFY_DISABLE_GMP_LOGO
#define SPECIFY_PARAMETER_GT_TYPE USING_DOUBLE_FPU
#define SPECIFY_REAL_GT_TYPE USING_DOUBLE_FPU
#define SPECIFY_CTRL_GT_TYPE USING_FLOAT_FPU

#endif /* GMP_CTL_UNIT_TEST_XPLT_CONFIG_H */
