/**
 * @file tyi_5008_kv335.h
 * @brief SDPE hardware preset for TYI-5008 KV335 Brushless Motor.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _PMSM_MOTOR_TYI_5008_KV335_H_
#define _PMSM_MOTOR_TYI_5008_KV335_H_

#include <ctl/component/motor_control/consultant/unit_consultant.h>

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_tyi_5008_kv335 TYI-5008 KV335 Brushless Motor
 * @{
 */

// Identification
#define TYI_5008_KV335_ID "tyi_5008_kv335"
#define TYI_5008_KV335_SCHEMA "PMSM"
#define TYI_5008_KV335_NAME "TYI-5008 KV335 Brushless Motor"

// Tags: bldc, motor, pmsm

/*
 * Schema: Permanent magnet synchronous motor parameter template.
 * Vendor: TYI
 * Document: ctl/component/hardware_preset/pmsm_motor/TYI_5008_KV335.h
 */

// Parameter macros
/**
 * @brief Human-readable motor model name.
 */
#define TYI_5008_KV335_MOTOR_NAME "TYI-5008 KV335"

/**
 * @brief GMP motor type macro.
 */
#define TYI_5008_KV335_MOTOR_TYPE PMSM_MOTOR

/**
 * @brief Stator resistance per phase.
 * @unit ohm
 */
#define TYI_5008_KV335_RS ((130.0e-3f))

/**
 * @brief D-axis stator inductance.
 * @unit H
 */
#define TYI_5008_KV335_LD ((50.0e-6f))

/**
 * @brief Q-axis stator inductance.
 * @unit H
 */
#define TYI_5008_KV335_LQ ((50.0e-6f))

/**
 * @brief Permanent magnet flux linkage.
 * @unit Wb
 */
#define TYI_5008_KV335_FLUX ((0.0023f))

/**
 * @brief Number of pole pairs in the motor.
 */
#define TYI_5008_KV335_POLE_PAIRS ((7))

/**
 * @brief Motor velocity constant.
 * @unit RPM/V
 */
#define TYI_5008_KV335_KV ((335.0f))

/**
 * @brief Back-EMF constant.
 * @unit V/kRPM
 */
#define TYI_5008_KV335_EMF ((4.85f))

/**
 * @brief Rated operating voltage.
 * @unit V
 */
#define TYI_5008_KV335_RATED_VOLTAGE ((24.0f/1.732f))

/**
 * @brief No-load phase current.
 * @unit A
 */
#define TYI_5008_KV335_NO_LOAD_CURRENT ((0.5f))

/**
 * @brief Rated operating frequency.
 * @unit Hz
 */
#define TYI_5008_KV335_RATED_FREQUENCY ((700.0f))

/**
 * @brief Maximum allowable speed.
 * @unit RPM
 */
#define TYI_5008_KV335_MAX_SPEED ((6000))

/**
 * @brief Maximum intermittent torque.
 * @unit N*m
 */
#define TYI_5008_KV335_MAX_TORQUE ((0.4))

/**
 * @brief Maximum allowable DC bus voltage.
 * @unit V
 */
#define TYI_5008_KV335_MAX_DC_VOLTAGE ((25.2))

/**
 * @brief Maximum allowable phase current.
 * @unit A
 */
#define TYI_5008_KV335_MAX_PH_CURRENT ((27.0))

// Logical exports
// rs: TYI_5008_KV335_RS
// ld: TYI_5008_KV335_LD
// lq: TYI_5008_KV335_LQ
// flux: TYI_5008_KV335_FLUX
// pole_pairs: TYI_5008_KV335_POLE_PAIRS

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _PMSM_MOTOR_TYI_5008_KV335_H_
