/**
 * @file tyi_5010_360kv.h
 * @brief SDPE hardware preset for TYI-5010 360KV Brushless Motor.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _PMSM_MOTOR_TYI_5010_360KV_H_
#define _PMSM_MOTOR_TYI_5010_360KV_H_

#include <ctl/component/motor_control/consultant/unit_consultant.h>

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_tyi_5010_360kv TYI-5010 360KV Brushless Motor
 * @{
 */

// Identification
#define TYI_5010_360KV_ID "tyi_5010_360kv"
#define TYI_5010_360KV_SCHEMA "PMSM"
#define TYI_5010_360KV_NAME "TYI-5010 360KV Brushless Motor"

// Tags: bldc, motor, pmsm

/*
 * Schema: Permanent magnet synchronous motor parameter template.
 * Vendor: TYI
 * Document: ctl/component/hardware_preset/pmsm_motor/TYI_5010_360KV.h
 */

// Parameter macros
/**
 * @brief Human-readable motor model name.
 */
#define TYI_5010_360KV_MOTOR_NAME "TYI-5010 360KV"

/**
 * @brief GMP motor type macro.
 */
#define TYI_5010_360KV_MOTOR_TYPE PMSM_MOTOR

/**
 * @brief Stator resistance per phase.
 * @unit ohm
 */
#define TYI_5010_360KV_RS ((0.12))

/**
 * @brief D-axis stator inductance.
 * @unit H
 */
#define TYI_5010_360KV_LD ((5e-05))

/**
 * @brief Q-axis stator inductance.
 * @unit H
 */
#define TYI_5010_360KV_LQ ((5e-05))

/**
 * @brief Permanent magnet flux linkage.
 * @unit Wb
 */
#define TYI_5010_360KV_FLUX ((0.0021))

/**
 * @brief Number of pole pairs in the motor.
 */
#define TYI_5010_360KV_POLE_PAIRS ((7))

/**
 * @brief Motor velocity constant.
 * @unit RPM/V
 */
#define TYI_5010_360KV_KV ((360.0))

/**
 * @brief Back-EMF constant.
 * @unit V/kRPM
 */
#define TYI_5010_360KV_EMF ((4.85))

/**
 * @brief Rated operating voltage.
 * @unit V
 */
#define TYI_5010_360KV_RATED_VOLTAGE ((24.0))

/**
 * @brief No-load phase current.
 * @unit A
 */
#define TYI_5010_360KV_NO_LOAD_CURRENT ((0.5))

/**
 * @brief Maximum allowable speed.
 * @unit RPM
 */
#define TYI_5010_360KV_MAX_SPEED ((8600))

/**
 * @brief Maximum intermittent torque.
 * @unit N*m
 */
#define TYI_5010_360KV_MAX_TORQUE ((0.25))

/**
 * @brief Maximum allowable DC bus voltage.
 * @unit V
 */
#define TYI_5010_360KV_MAX_DC_VOLTAGE ((25.2))

/**
 * @brief Maximum allowable phase current.
 * @unit A
 */
#define TYI_5010_360KV_MAX_PH_CURRENT ((23.0))

// Logical exports
// rs: TYI_5010_360KV_RS
// ld: TYI_5010_360KV_LD
// lq: TYI_5010_360KV_LQ
// flux: TYI_5010_360KV_FLUX
// pole_pairs: TYI_5010_360KV_POLE_PAIRS

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _PMSM_MOTOR_TYI_5010_360KV_H_
