%% SDPE MATLAB initialization script
% Project: DPS FSBB F280039C IRIS Node
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

% Notes:
%   Four-switch buck-boost converter SDPE project requirement prepared from ctl/suite/dps_fsbb/project/f280039c_Iris_node/xplt/ctrl_settings.h.
%   The requirement introduces the GMP LVFB 150V 2-phase board as the switching stage and sensor source, and IRIS F280039C Node as the peripheral option provider.

%% Project metadata
SDPE_PROJECT_ID = 'dps_fsbb_f280039c_Iris_node';

SDPE_PROJECT_SUITE = 'dps_fsbb';

SDPE_PROJECT_VERSION = '0.1.0';

SDPE_PROJECT_UPDATED_AT = '2026-07-16';

%% Hardware macros
IRIS_F280039C_ID = 'iris_f280039c_node';

IRIS_F280039C_SCHEMA = 'iris_c2000_core_board';

IRIS_F280039C_NAME = 'IRIS F280039C Core Board';

% C2000 device name.
IRIS_F280039C_CHIP = 'TMS320F280039C';

% SysConfig source file used by this binding.
IRIS_F280039C_SYSCFG_FILE = 'ctl/suite/dps_fsbb/project/f280039c_Iris_node/F280039_Iris_node.syscfg';

% SysConfig EPWM1 base macro.
IRIS_F280039C_EPWM1_BASE = 'IRIS_EPWM1_BASE';

% SysConfig EPWM2 base macro.
IRIS_F280039C_EPWM2_BASE = 'IRIS_EPWM2_BASE';

% SysConfig ADC channel 1 macro.
IRIS_F280039C_ADC_CH1 = 'ADC_CH1';

% SysConfig ADC channel 2 macro.
IRIS_F280039C_ADC_CH2 = 'ADC_CH2';

% SysConfig ADC channel 3 macro.
IRIS_F280039C_ADC_CH3 = 'ADC_CH3';

% SysConfig ADC channel 4 macro.
IRIS_F280039C_ADC_CH4 = 'ADC_CH4';

BSC093N15NS5_ID = 'bsc093n15ns5';

BSC093N15NS5_SCHEMA = 'power_switch';

BSC093N15NS5_NAME = 'BSC093N15NS5';

% Power device part number.
BSC093N15NS5_PART_NUMBER = 'BSC093N15NS5';

% MOSFET, IGBT, GaN, SiC, etc.
BSC093N15NS5_DEVICE_TYPE = 'MOSFET';

% Drain-source or collector-emitter voltage rating.
BSC093N15NS5_VOLTAGE_RATING_V = 150.0;

% Current rating.
BSC093N15NS5_CURRENT_RATING_A = 55.0;

% On resistance.
BSC093N15NS5_RDSON_OHM = 0.0093;

% Single switch, dual switch, half bridge power block, etc.
BSC093N15NS5_CONFIGURATION = 'single';

% Maximum on resistance at the documented gate voltage.
BSC093N15NS5_RDSON_MAX_OHM = 0.0;

% Gate voltage associated with the resistance value.
BSC093N15NS5_GATE_VOLTAGE_V = 0.0;

% Typical total gate charge.
BSC093N15NS5_GATE_CHARGE_NC = 0.0;

% Manufacturer package name.
BSC093N15NS5_PACKAGE = 'unknown';

TMCS1133_B5A_ID = 'tmcs1133_b5a';

TMCS1133_B5A_SCHEMA = 'current_sensor';

TMCS1133_B5A_NAME = 'TMCS1133 B5A Hall Current Sensor';

% Main sensing IC or technology name.
TMCS1133_B5A_CHIP = 'TMCS1133B5A';

% Current sensing technology, such as Hall, shunt, or fluxgate.
TMCS1133_B5A_SENSOR_TYPE = 'Hall';

% Nominal measurable current range.
TMCS1133_B5A_RANGE_A = 10.3;

% Minimum output voltage.
TMCS1133_B5A_OUTPUT_MIN_V = 0.0;

% Maximum output voltage.
TMCS1133_B5A_OUTPUT_MAX_V = 3.3;

% Zero-current output bias.
TMCS1133_B5A_BIAS_V = 1.65;

% Current sensor sensitivity.
TMCS1133_B5A_SENSITIVITY_MV_PER_A = 150.0;

% Typical small-signal bandwidth.
TMCS1133_B5A_BANDWIDTH_HZ = 300000.0;

% Sensor internal series resistance.
TMCS1133_B5A_INTERNAL_RESISTANCE_OHM = 0.0018;

% Current sensor sensitivity converted to V/A.
TMCS1133_B5A_SENSITIVITY_V_PER_A = TMCS1133_B5A_SENSITIVITY_MV_PER_A / 1000.0;

% Positive current range implied by bias and sensitivity.
TMCS1133_B5A_MAX_CURRENT_FROM_BIAS_A = TMCS1133_B5A_BIAS_V / TMCS1133_B5A_SENSITIVITY_V_PER_A;

LVFB_VDIV_150V_ID = 'lvfb_voltage_divider_150v';

LVFB_VDIV_150V_SCHEMA = 'voltage_sensor';

LVFB_VDIV_150V_NAME = 'LVFB 150V Voltage Divider';

% Main sensing IC or front-end topology.
LVFB_VDIV_150V_CHIP = 'AMC1311BDWVR + resistor divider';

% Nominal measurable voltage.
LVFB_VDIV_150V_RATED_VOLTAGE_V = 150.0;

% Output bias voltage.
LVFB_VDIV_150V_BIAS_V = 0.0;

% Voltage sensor sensitivity.
LVFB_VDIV_150V_SENSITIVITY_V_PER_V = 0.016129;

% Equivalent input resistance.
LVFB_VDIV_150V_INPUT_RESISTANCE_OHM = 915000.0;

% Approximate positive full scale voltage when biased at mid-supply.
LVFB_VDIV_150V_MAX_BY_BIAS_V = sdpe_select(LVFB_VDIV_150V_BIAS_V > 0.0, LVFB_VDIV_150V_BIAS_V / LVFB_VDIV_150V_SENSITIVITY_V_PER_V, LVFB_VDIV_150V_RATED_VOLTAGE_V);

GMP_LVFB_ID = 'gmp_lvfb_150_2ph_v2';

GMP_LVFB_SCHEMA = 'half_bridge';

GMP_LVFB_NAME = 'GMP LVFB 150V 2-Phase V2 Inverter Board';

% Board or module name.
GMP_LVFB_BOARD_NAME = 'GMP LVFB 2ph V6.1';

% Integrated gate driver part number.
GMP_LVFB_GATE_DRIVER = 'UCC21520DWR';

% Power MOSFET part number.
GMP_LVFB_MOSFET = 'BSC093N15NS5';

% On-board current sensing device.
GMP_LVFB_CURRENT_SENSOR_NAME = 'TMCS1133B5A';

% On-board voltage sensing device.
GMP_LVFB_VOLTAGE_SENSOR_NAME = 'AMC1311BDWVR';

% Number of half-bridge phases represented by this module.
GMP_LVFB_PHASE_COUNT = 2;

% Current measurement range exported by the current sensor sub component.
GMP_LVFB_MEASURED_CURRENT_RANGE_A = TMCS1133_B5A_RANGE_A;

% Maximum allowable DC bus voltage.
GMP_LVFB_VBUS_MAX_V = 120.0;

% Maximum instantaneous peak phase current.
GMP_LVFB_CURRENT_MAX_PEAK_A = 55.0;

% Maximum continuous RMS phase current.
GMP_LVFB_CURRENT_MAX_RMS_A = 35.0;

% Recommended hardware deadtime.
GMP_LVFB_DEADTIME_NS = 523.0;

% Current sensing signal bandwidth.
GMP_LVFB_CURRENT_BW_HZ = 300.0e3;

% Current sensor ADC bias voltage.
GMP_LVFB_CURRENT_BIAS_V = 1.65;

% Configured current sensitivity.
GMP_LVFB_CURRENT_SENSITIVITY = TMCS1133_B5A_SENSITIVITY_V_PER_A;

% ADC reference scale voltage.
GMP_LVFB_VOLTAGE_BASE_V = 3.3;

% Voltage sensing ADC bias voltage.
GMP_LVFB_VOLTAGE_BIAS_V = 0.0;

% Voltage sensing bandwidth.
GMP_LVFB_VOLTAGE_BW_HZ = 114.47e3;

% Default low-side voltage divider resistance.
GMP_LVFB_VOLTAGE_R_LOW_OHM = 15000.0;

% Default high-side voltage divider resistance.
GMP_LVFB_VOLTAGE_R_HIGH_OHM = 300000.0;

% Configured voltage sensing gain.
GMP_LVFB_VOLTAGE_SENSITIVITY = (15e3) / ((15e3) + ((300e3) * 3)) * 1.65;

% Configured maximum measurable voltage.
GMP_LVFB_VOLTAGE_MAX = 3.3 / ((15e3) / ((15e3) + ((300e3) * 3)) * 1.65);

% Optional local DC bus capacitance.
GMP_LVFB_BUS_CAPACITANCE_F = 0.0;

% Whether this module declares a local bus capacitor.
GMP_LVFB_HAS_LOCAL_BUS_CAP = GMP_LVFB_BUS_CAPACITANCE_F > 0.0;

%% Controller Settings
% Enable ADC calibration before normal control starts.
SPECIFY_ENABLE_ADC_CALIBRATE = true;

% ENABLE_GMP_DL_PIL_SIM is disabled in the SDPE project requirement.
% ENABLE_GMP_DL_PIL_SIM = true;

% GMP_CTL_FM_CONFIG_ENABLE_DEBUG_INFO is disabled in the SDPE project requirement.
% GMP_CTL_FM_CONFIG_ENABLE_DEBUG_INFO = true;

% Invert duty-to-CMP mapping because the IRIS ePWM action qualifier sets high on up-count CMPA and low on down-count CMPA.
PWM_MODULATOR_USING_NEGATIVE_LOGIC = 1;

% This macro will disable the fault request of the controller. That's dangerous.
DISABLE_FSBB_PROTECTION_FAULT_LOGIC = true;

%% Optional Sampling Channels
% FSBB_ENABLE_IOUT_SAMPLE is disabled in the SDPE project requirement.
% FSBB_ENABLE_IOUT_SAMPLE = true;

% FSBB_ENABLE_VIN_SAMPLE is disabled in the SDPE project requirement.
% FSBB_ENABLE_VIN_SAMPLE = true;

%% Controller Options
% Incremental debug build level. 1: modulation and hardware check; 2: current loop; 3: voltage loop.
% Options: (1), (2), (3)
BUILD_LEVEL = 1;

%% Board GPIO
% Gate-driver enable GPIO.
% Options: IRIS_GPIO1, IRIS_GPIO2, IRIS_GPIO3, IRIS_GPIO4, IRIS_GPIO5, IRIS_GPIO6
PWM_ENABLE_PORT = 'IRIS_GPIO1';

% Gate-driver reset GPIO.
% Options: IRIS_GPIO1, IRIS_GPIO2, IRIS_GPIO3, IRIS_GPIO4, IRIS_GPIO5, IRIS_GPIO6
PWM_RESET_PORT = 'IRIS_GPIO3';

% System status LED.
% Options: IRIS_LED1, IRIS_LED2, LED_R, LED_G
SYSTEM_LED = 'IRIS_LED1';

%% PWM Channel
% Buck phase ePWM base.
% Options: IRIS_EPWM1_BASE, IRIS_EPWM2_BASE, IRIS_EPWM3_BASE, IRIS_EPWM4_BASE, IRIS_EPWM5_BASE, IRIS_EPWM6_BASE
PHASE_BUCK_BASE = 'IRIS_EPWM1_BASE';

% Boost phase ePWM base.
% Options: IRIS_EPWM1_BASE, IRIS_EPWM2_BASE, IRIS_EPWM3_BASE, IRIS_EPWM4_BASE, IRIS_EPWM5_BASE, IRIS_EPWM6_BASE
PHASE_BOOST_BASE = 'IRIS_EPWM2_BASE';

%% ADC Channel
% Input voltage ADC result register base.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
FSBB_VIN_ADC_BASE = 'ADC_CH1_RESULT_BASE';

% Input voltage ADC channel index.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
FSBB_VIN = 'ADC_CH1';

% Output voltage ADC result register base.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
FSBB_VOUT_ADC_BASE = 'ADC_CH2_RESULT_BASE';

% Output voltage ADC channel index.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
FSBB_VOUT = 'ADC_CH2';

% Inductor current ADC result register base.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
FSBB_IL_ADC_BASE = 'ADC_CH3_RESULT_BASE';

% Inductor current ADC channel index.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
FSBB_IL = 'ADC_CH3';

% Input current ADC result register base, available when input-current sampling is enabled.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
FSBB_IIN_ADC_BASE = 'ADC_CH4_RESULT_BASE';

% Input current ADC channel index, available when input-current sampling is enabled.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
FSBB_IIN = 'ADC_CH4';

% Output/load current ADC result register base.
% Options: ADC_CH1_RESULT_BASE, ADC_CH2_RESULT_BASE, ADC_CH3_RESULT_BASE, ADC_CH4_RESULT_BASE, ADC_CH5_RESULT_BASE, ADC_CH6_RESULT_BASE, ADC_CH7_RESULT_BASE, ADC_CH8_RESULT_BASE, ADC_CH9_RESULT_BASE, ADC_CH10_RESULT_BASE, ADC_CH11_RESULT_BASE, ADC_CH12_RESULT_BASE
FSBB_IOUT_ADC_BASE = 'ADC_CH5_RESULT_BASE';

% Output/load current ADC channel index.
% Options: ADC_CH1, ADC_CH2, ADC_CH3, ADC_CH4, ADC_CH5, ADC_CH6, ADC_CH7, ADC_CH8, ADC_CH9, ADC_CH10, ADC_CH11, ADC_CH12
FSBB_IOUT = 'ADC_CH5';

%% Requirement bindings
% PWM carrier frequency used by the FSBB power stage.
PWM_FREQ = 20e3;

% Main control ISR frequency.
CONTROLLER_FREQUENCY = 20e3;

% PWM compare maximum value for the configured ePWM time base.
CTRL_PWM_CMP_MAX = 3000 - 1;

% PWM deadband compare count.
CTRL_PWM_DEADBAND_CMP = 50;

% CPU main clock frequency.
CTRL_SYS_FREQUENCY = 120e6;

% C2000 system tick divider derived from PWM period.
DSP_C2000_DSP_TIME_DIV = CTRL_SYS_FREQUENCY / 1000 / CTRL_PWM_CMP_MAX / 2;

% ADC voltage reference used by sensor gain and bias conversion.
CTRL_ADC_VOLTAGE_REF = 3.3;

% Voltage per-unit base value, using the peak value of the nominal 24 Vrms system.
CTRL_VOLTAGE_BASE = 34.0;

% Current per-unit base value, using the peak value of the nominal 10 Arms system.
CTRL_CURRENT_BASE = 14.14;

% Minimum load resistance used by FSBB controller initialization.
FSBB_PARAM_RLOAD_MIN = 20.0;

% Input DC-link capacitance.
FSBB_PARAM_CIN = 440e-6;

% Output capacitance used by FSBB controller initialization.
FSBB_PARAM_COUT = 440e-6;

% Output capacitor equivalent series resistance.
FSBB_PARAM_COUT_ESR = 0.1;

% Main FSBB inductor value.
FSBB_PARAM_L = 1.5e-3;

% Main inductor equivalent series resistance.
FSBB_PARAM_L_ESR = 0.05;

% Input voltage ADC sensing sensitivity provided by the LVFB voltage sensor path.
CTRL_FSBB_VIN_SENSITIVITY = GMP_LVFB_VOLTAGE_SENSITIVITY;

% Input voltage ADC bias voltage provided by the LVFB voltage sensor path.
CTRL_FSBB_VIN_BIAS = GMP_LVFB_VOLTAGE_BIAS_V;

% Output voltage ADC sensing sensitivity provided by the LVFB voltage sensor path.
CTRL_FSBB_VOUT_SENSITIVITY = GMP_LVFB_VOLTAGE_SENSITIVITY;

% Output voltage ADC bias voltage provided by the LVFB voltage sensor path.
CTRL_FSBB_VOUT_BIAS = GMP_LVFB_VOLTAGE_BIAS_V;

% Load/output current ADC sensing sensitivity provided by the LVFB current sensor path.
CTRL_FSBB_IOUT_SENSITIVITY = GMP_LVFB_CURRENT_SENSITIVITY;

% Load/output current ADC bias voltage provided by the LVFB current sensor path.
CTRL_FSBB_IOUT_BIAS = GMP_LVFB_CURRENT_BIAS_V;

% Inductor current ADC sensing sensitivity provided by the LVFB current sensor path.
CTRL_FSBB_IL_SENSITIVITY = GMP_LVFB_CURRENT_SENSITIVITY;

% Inductor current ADC bias voltage provided by the LVFB current sensor path.
CTRL_FSBB_IL_BIAS = GMP_LVFB_CURRENT_BIAS_V;

FSBB_INPUT_VOLTAGE_MAX = 60.0;

% Minimum allowed FSBB input voltage.
FSBB_INPUT_VOLTAGE_MIN = 12.0;

% Nominal input voltage used when input-voltage sampling is disabled.
FSBB_INPUT_VOLTAGE_NOMINAL = 24.0;

% Maximum allowed FSBB output voltage command.
FSBB_OUTPUT_VOLTAGE_MAX = 72.0;

% Minimum allowed FSBB output voltage command.
FSBB_OUTPUT_VOLTAGE_MIN = 3.0;

% Maximum allowed FSBB output/load current.
FSBB_OUTPUT_CURRENT_LIM = 10.0;

% Default startup output-voltage command.
FSBB_DEFAULT_OUTPUT_VOLTAGE = 24.0;

% Default startup current command and limit.
FSBB_DEFAULT_CURRENT_LIMIT = 5.0;

% Maximum FSBB leg duty ratio.
FSBB_DUTY_MAX = 0.95;

% Minimum FSBB leg duty ratio.
FSBB_DUTY_MIN = 0.05;

% Positive inductor current protection threshold.
FSBB_PROTECT_IL_MAX = 25.0;

% Negative inductor current protection threshold.
FSBB_PROTECT_IL_MIN = -2.0;

% Equivalent output-voltage command used by BUILD_LEVEL 1.
FSBB_OPEN_LOOP_VOLTAGE_COMMAND = 12.0;

% Requested current-loop crossover frequency.
FSBB_CURRENT_LOOP_BANDWIDTH = 800.0;

% Requested voltage-loop crossover frequency.
FSBB_VOLTAGE_LOOP_BANDWIDTH = 40.0;

% Lower voltage-ratio boundary of the buck-boost transition region.
FSBB_TRANSITION_RATIO_LOW = 0.90;

% Upper voltage-ratio boundary of the buck-boost transition region.
FSBB_TRANSITION_RATIO_HIGH = 1.10;

% ADC calibration timeout in ms.
TIMEOUT_ADC_CALIB_MS = 3000;

% SPLL close-loop convergence threshold.
CTRL_SPLL_EPSILON = float2ctrl(0.005);

% Voltage-reference slew rate in PU/s.
FSBB_VOLTAGE_RAMP_PU_S = 1.0;

% Current-reference slew rate in PU/s.
FSBB_CURRENT_RAMP_PU_S = 1.0;

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
