/**
 * @file launchxl_f280025c.h
 * @brief SDPE hardware preset for LAUNCHXL-F280025C.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _MCU_BOARD_LAUNCHXL_F280025C_H_
#define _MCU_BOARD_LAUNCHXL_F280025C_H_

#include <ctl/hardware_preset/interface/boostxl_dual_site.h>

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_launchxl_f280025c LAUNCHXL-F280025C
 * @{
 */

// Identification
#define LAUNCHXL_F280025C_ID "launchxl_f280025c"
#define LAUNCHXL_F280025C_SCHEMA "launchxl_f280025c_board"
#define LAUNCHXL_F280025C_NAME "LAUNCHXL-F280025C"

// Tags: c2000, f280025c, launchpad

/*
 * Schema: Board-specific SDPE template for LAUNCHXL-F280025C.
 */

// Parameter macros
/**
 * @brief LaunchPad board name.
 */
#define LAUNCHXL_F280025C_BOARD_NAME "LAUNCHXL-F280025C"

/**
 * @brief C2000 device.
 */
#define LAUNCHXL_F280025C_CHIP "TMS320F280025C"

/**
 * @brief Board SysConfig source filename.
 */
#define LAUNCHXL_F280025C_SYSCFG_FILE "LAUNCHXL_F280025C.syscfg"

/**
 * @brief Maximum configured CPU clock.
 * @unit Hz
 */
#define LAUNCHXL_F280025C_SYSTEM_CLOCK_HZ (100000000UL)

/**
 * @brief ePWM-triggered ADC control interrupt rate.
 * @unit Hz
 */
#define LAUNCHXL_F280025C_CONTROL_ISR_HZ (20000UL)

/**
 * @brief Heartbeat LED GPIO alias.
 */
#define LAUNCHXL_F280025C_USER_LED_GPIO LED_R

/**
 * @brief One when a hardware DAC output is configured.
 */
#define LAUNCHXL_F280025C_HAS_EXTERNAL_DAC (0U)

/**
 * @brief Selected DAC base or zero.
 */
#define LAUNCHXL_F280025C_CONTROL_DAC_BASE 0U

/**
 * @brief Classic CAN service selection.
 */
#define LAUNCHXL_F280025C_CAN_CLASSIC (1U)

/**
 * @brief MCAN service selection.
 */
#define LAUNCHXL_F280025C_CAN_MCAN (0U)

/**
 * @brief Selected CAN/MCAN base alias.
 */
#define LAUNCHXL_F280025C_CAN_BASE LAUNCHXL_CAN_BASE

// Logical exports
// board_name: LAUNCHXL_F280025C_BOARD_NAME
// control_isr_hz: LAUNCHXL_F280025C_CONTROL_ISR_HZ
// user_led_gpio: LAUNCHXL_F280025C_USER_LED_GPIO
// has_external_dac: LAUNCHXL_F280025C_HAS_EXTERNAL_DAC
// control_dac_base: LAUNCHXL_F280025C_CONTROL_DAC_BASE
// can_classic: LAUNCHXL_F280025C_CAN_CLASSIC
// can_mcan: LAUNCHXL_F280025C_CAN_MCAN
// can_base: LAUNCHXL_F280025C_CAN_BASE

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _MCU_BOARD_LAUNCHXL_F280025C_H_
