/**
 * @file quad_sensor_voltage_channel.h
 * @brief SDPE hardware preset for Quad Sensor Docker Voltage Channel.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _SDPE_V2_HARDWARE_PRESET_VOLTAGE_SENSOR_QUAD_SENSOR_VOLTAGE_CHANNEL_H_
#define _SDPE_V2_HARDWARE_PRESET_VOLTAGE_SENSOR_QUAD_SENSOR_VOLTAGE_CHANNEL_H_

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_quad_sensor_voltage_channel Quad Sensor Docker Voltage Channel
 * @{
 */

// Identification
#define QUAD_SENSOR_VCH_ID "quad_sensor_voltage_channel"
#define QUAD_SENSOR_VCH_SCHEMA "voltage_sensor"
#define QUAD_SENSOR_VCH_NAME "Quad Sensor Docker Voltage Channel"

// Tags: isolated, quad_sensor, sensor, voltage_sensor

/*
 * Schema: Voltage sensor or resistor divider model.
 * Vendor: GMP
 */

// Parameter macros
/**
 * @brief Main sensing IC or front-end topology.
 */
#ifndef QUAD_SENSOR_VCH_CHIP
#define QUAD_SENSOR_VCH_CHIP "AMC1350 + TLV9061"
#endif // QUAD_SENSOR_VCH_CHIP

/**
 * @brief Nominal measurable voltage.
 * @unit V
 */
#ifndef QUAD_SENSOR_VCH_RATED_VOLTAGE_V
#define QUAD_SENSOR_VCH_RATED_VOLTAGE_V (100.0f)
#endif // QUAD_SENSOR_VCH_RATED_VOLTAGE_V

/**
 * @brief Output bias voltage.
 * @unit V
 */
#ifndef QUAD_SENSOR_VCH_BIAS_V
#define QUAD_SENSOR_VCH_BIAS_V (1.65f)
#endif // QUAD_SENSOR_VCH_BIAS_V

/**
 * @brief Voltage sensor sensitivity.
 * @unit V/V
 */
#ifndef QUAD_SENSOR_VCH_SENSITIVITY_V_PER_V
#define QUAD_SENSOR_VCH_SENSITIVITY_V_PER_V (0.01454f)
#endif // QUAD_SENSOR_VCH_SENSITIVITY_V_PER_V

/**
 * @brief Equivalent input resistance.
 * @unit ohm
 */
#ifndef QUAD_SENSOR_VCH_INPUT_RESISTANCE_OHM
#define QUAD_SENSOR_VCH_INPUT_RESISTANCE_OHM (444600.0f)
#endif // QUAD_SENSOR_VCH_INPUT_RESISTANCE_OHM

// Derived macros
/**
 * @brief Approximate positive full scale voltage when biased at mid-supply.
 * @unit V
 */
#define QUAD_SENSOR_VCH_MAX_BY_BIAS_V ((QUAD_SENSOR_VCH_BIAS_V > 0.0f) ? (QUAD_SENSOR_VCH_BIAS_V / QUAD_SENSOR_VCH_SENSITIVITY_V_PER_V) : QUAD_SENSOR_VCH_RATED_VOLTAGE_V)

// Logical exports
// sensitivity: QUAD_SENSOR_VCH_SENSITIVITY_V_PER_V
// bias: QUAD_SENSOR_VCH_BIAS_V
// range: QUAD_SENSOR_VCH_RATED_VOLTAGE_V

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _SDPE_V2_HARDWARE_PRESET_VOLTAGE_SENSOR_QUAD_SENSOR_VOLTAGE_CHANNEL_H_
