#ifndef GMP_CORE_UNIT_TEST_XPLT_CONFIG_H
#define GMP_CORE_UNIT_TEST_XPLT_CONFIG_H

#define SPECIFY_DISABLE_CSP
#define SPECIFY_PC_ENVIRONMENT
#define SPECIFY_DISABLE_GMP_LOGO
#define SPECIFY_GMP_BLOCK_MEMORY_ENABLE

#endif

