%% SDPE MATLAB initialization script
% Project: PGS SINV RC MATLAB/Simulink SIL
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

% Load the explicitly bound common requirement first.
run(fullfile(fileparts(mfilename('fullpath')), 'sdpe_pgs_sinv_rc_common_settings_matlab_init.m'));

% Notes:
%   Windows SIL platform, plant and sensing settings for all SINV commissioning models.

%% Project metadata
PGS_SINV_RC_SIM_SDPE_PROJECT_ID = 'pgs_sinv_rc_simulate';

PGS_SINV_RC_SIM_SDPE_PROJECT_SUITE = 'pgs_sinv_rc';

PGS_SINV_RC_SIM_SDPE_PROJECT_VERSION = '1.0.0';

PGS_SINV_RC_SIM_SDPE_PROJECT_UPDATED_AT = '2026-08-08';

%% Hardware macros
BSC093N15NS5_ID = 'bsc093n15ns5';

BSC093N15NS5_SCHEMA = 'power_switch';

BSC093N15NS5_NAME = 'BSC093N15NS5';

% Power device part number.
BSC093N15NS5_PART_NUMBER = 'BSC093N15NS5';

% MOSFET, IGBT, GaN, SiC, etc.
BSC093N15NS5_DEVICE_TYPE = 'MOSFET';

% Drain-source or collector-emitter voltage rating.
BSC093N15NS5_VOLTAGE_RATING_V = 150.0;

% Current rating.
BSC093N15NS5_CURRENT_RATING_A = 55.0;

% On resistance.
BSC093N15NS5_RDSON_OHM = 0.0093;

% Single switch, dual switch, half bridge power block, etc.
BSC093N15NS5_CONFIGURATION = 'single';

% Maximum on resistance at the documented gate voltage.
BSC093N15NS5_RDSON_MAX_OHM = 0.0;

% Gate voltage associated with the resistance value.
BSC093N15NS5_GATE_VOLTAGE_V = 0.0;

% Typical total gate charge.
BSC093N15NS5_GATE_CHARGE_NC = 0.0;

% Manufacturer package name.
BSC093N15NS5_PACKAGE = 'unknown';

TMCS1133_B5A_ID = 'tmcs1133_b5a';

TMCS1133_B5A_SCHEMA = 'current_sensor';

TMCS1133_B5A_NAME = 'TMCS1133 B5A Hall Current Sensor';

% Main sensing IC or technology name.
TMCS1133_B5A_CHIP = 'TMCS1133B5A';

% Current sensing technology, such as Hall, shunt, or fluxgate.
TMCS1133_B5A_SENSOR_TYPE = 'Hall';

% Nominal measurable current range.
TMCS1133_B5A_RANGE_A = 10.3;

% Minimum output voltage.
TMCS1133_B5A_OUTPUT_MIN_V = 0.0;

% Maximum output voltage.
TMCS1133_B5A_OUTPUT_MAX_V = 3.3;

% Zero-current output bias.
TMCS1133_B5A_BIAS_V = 1.65;

% Current sensor sensitivity.
TMCS1133_B5A_SENSITIVITY_MV_PER_A = 150.0;

% Typical small-signal bandwidth.
TMCS1133_B5A_BANDWIDTH_HZ = 300000.0;

% Sensor internal series resistance.
TMCS1133_B5A_INTERNAL_RESISTANCE_OHM = 0.0018;

% Current sensor sensitivity converted to V/A.
TMCS1133_B5A_SENSITIVITY_V_PER_A = TMCS1133_B5A_SENSITIVITY_MV_PER_A / 1000.0;

% Positive current range implied by bias and sensitivity.
TMCS1133_B5A_MAX_CURRENT_FROM_BIAS_A = TMCS1133_B5A_BIAS_V / TMCS1133_B5A_SENSITIVITY_V_PER_A;

LVFB_VDIV_150V_ID = 'lvfb_voltage_divider_150v';

LVFB_VDIV_150V_SCHEMA = 'voltage_sensor';

LVFB_VDIV_150V_NAME = 'LVFB 150V Voltage Divider';

% Main sensing IC or front-end topology.
LVFB_VDIV_150V_CHIP = 'AMC1311BDWVR + resistor divider';

% Nominal measurable voltage.
LVFB_VDIV_150V_RATED_VOLTAGE_V = 150.0;

% Output bias voltage.
LVFB_VDIV_150V_BIAS_V = 0.0;

% Voltage sensor sensitivity.
LVFB_VDIV_150V_SENSITIVITY_V_PER_V = 0.016129;

% Equivalent input resistance.
LVFB_VDIV_150V_INPUT_RESISTANCE_OHM = 915000.0;

% Small-signal sensing bandwidth.
LVFB_VDIV_150V_BANDWIDTH_HZ = 0.0;

% Approximate positive full scale voltage when biased at mid-supply.
LVFB_VDIV_150V_MAX_BY_BIAS_V = sdpe_select(LVFB_VDIV_150V_BIAS_V > 0.0, LVFB_VDIV_150V_BIAS_V / LVFB_VDIV_150V_SENSITIVITY_V_PER_V, LVFB_VDIV_150V_RATED_VOLTAGE_V);

GMP_LVFB_ID = 'gmp_lvfb_150_2ph_v2';

GMP_LVFB_SCHEMA = 'half_bridge';

GMP_LVFB_NAME = 'GMP LVFB 150V 2-Phase V2 Inverter Board';

% Board or module name.
GMP_LVFB_BOARD_NAME = 'GMP LVFB 2ph V6.1';

% Integrated gate driver part number.
GMP_LVFB_GATE_DRIVER = 'UCC21520DWR';

% Power MOSFET part number.
GMP_LVFB_MOSFET = 'BSC093N15NS5';

% On-board current sensing device.
GMP_LVFB_CURRENT_SENSOR_NAME = 'TMCS1133B5A';

% On-board voltage sensing device.
GMP_LVFB_VOLTAGE_SENSOR_NAME = 'AMC1311BDWVR';

% Number of half-bridge phases represented by this module.
GMP_LVFB_PHASE_COUNT = 2;

% Current measurement range exported by the current sensor sub component.
GMP_LVFB_MEASURED_CURRENT_RANGE_A = TMCS1133_B5A_RANGE_A;

% Maximum allowable DC bus voltage.
GMP_LVFB_VBUS_MAX_V = 120.0;

% Maximum instantaneous peak phase current.
GMP_LVFB_CURRENT_MAX_PEAK_A = 55.0;

% Maximum continuous RMS phase current.
GMP_LVFB_CURRENT_MAX_RMS_A = 35.0;

% Recommended hardware deadtime.
GMP_LVFB_DEADTIME_NS = 523.0;

% Current sensing signal bandwidth.
GMP_LVFB_CURRENT_BW_HZ = 300.0e3;

% Current sensor ADC bias voltage.
GMP_LVFB_CURRENT_BIAS_V = 1.65;

% Configured current sensitivity.
GMP_LVFB_CURRENT_SENSITIVITY = TMCS1133_B5A_SENSITIVITY_V_PER_A;

% ADC reference scale voltage.
GMP_LVFB_VOLTAGE_BASE_V = 3.3;

% Voltage sensing ADC bias voltage.
GMP_LVFB_VOLTAGE_BIAS_V = 0.0;

% Voltage sensing bandwidth.
GMP_LVFB_VOLTAGE_BW_HZ = 114.47e3;

% Default low-side voltage divider resistance.
GMP_LVFB_VOLTAGE_R_LOW_OHM = 15000.0;

% Default high-side voltage divider resistance.
GMP_LVFB_VOLTAGE_R_HIGH_OHM = 300000.0;

% Configured voltage sensing gain.
GMP_LVFB_VOLTAGE_SENSITIVITY = (15e3) / ((15e3) + ((300e3) * 3)) * 1.65;

% Configured maximum measurable voltage.
GMP_LVFB_VOLTAGE_MAX = 3.3 / ((15e3) / ((15e3) + ((300e3) * 3)) * 1.65);

% Optional local DC bus capacitance.
GMP_LVFB_BUS_CAPACITANCE_F = 0.0;

% Whether this module declares a local bus capacitor.
GMP_LVFB_HAS_LOCAL_BUS_CAP = GMP_LVFB_BUS_CAPACITANCE_F > 0.0;

TLE4971A025_ID = 'tle4971a025';

TLE4971A025_SCHEMA = 'current_sensor';

TLE4971A025_NAME = 'TLE4971A025 Coreless Hall Current Sensor';

% Main sensing IC or technology name.
TLE4971A025_CHIP = 'TLE4971A025';

% Current sensing technology, such as Hall, shunt, or fluxgate.
TLE4971A025_SENSOR_TYPE = 'Coreless Hall';

% Nominal measurable current range.
TLE4971A025_RANGE_A = 25.0;

% Minimum output voltage.
TLE4971A025_OUTPUT_MIN_V = 0.0;

% Maximum output voltage.
TLE4971A025_OUTPUT_MAX_V = 3.3;

% Zero-current output bias.
TLE4971A025_BIAS_V = 1.65;

% Current sensor sensitivity.
TLE4971A025_SENSITIVITY_MV_PER_A = 48.0;

% Typical small-signal bandwidth.
TLE4971A025_BANDWIDTH_HZ = 210000.0;

% Sensor internal series resistance.
TLE4971A025_INTERNAL_RESISTANCE_OHM = 0.0;

% Current sensor sensitivity converted to V/A.
TLE4971A025_SENSITIVITY_V_PER_A = TLE4971A025_SENSITIVITY_MV_PER_A / 1000.0;

% Positive current range implied by bias and sensitivity.
TLE4971A025_MAX_CURRENT_FROM_BIAS_A = TLE4971A025_BIAS_V / TLE4971A025_SENSITIVITY_V_PER_A;

HARMONIA_3PH_LC_FILTER_ID = 'gmp_harmonia_3ph_lc_filter';

HARMONIA_3PH_LC_FILTER_SCHEMA = 'Harmonia_3ph_LC_filter';

HARMONIA_3PH_LC_FILTER_NAME = 'GMP Harmonia 3-Phase LC Filter';

% Main filter inductance.
HARMONIA_3PH_LC_FILTER_INDUCTANCE_H = 0.0015;

% Main filter capacitance.
HARMONIA_3PH_LC_FILTER_CAPACITANCE_F = 0.000005;

% Board or module name.
HARMONIA_3PH_LC_FILTER_BOARD_NAME = 'Harmonia 3Ph LC Filter';

% Maximum DC bus voltage.
HARMONIA_3PH_LC_FILTER_VBUS_MAX_V = 1000.0;

% Minimum DC bus voltage.
HARMONIA_3PH_LC_FILTER_VBUS_MIN_V = 0.0;

% Maximum continuous RMS current.
HARMONIA_3PH_LC_FILTER_CURRENT_MAX_RMS_A = 40.0;

% Maximum peak current.
HARMONIA_3PH_LC_FILTER_CURRENT_MAX_PEAK_A = HARMONIA_3PH_LC_FILTER_CURRENT_MAX_RMS_A * 1.41421356237;

% Recommended maximum PCB operating temperature.
HARMONIA_3PH_LC_FILTER_TEMP_MAX_C = 85.0;

% Phase current sensor type enum.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TYPE = 2;

% Phase current sensing topology enum.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TOPOLOGY = 3;

% Phase voltage sensing type enum.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_TYPE = 1;

% Phase current sensor bandwidth.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_POLE_HZ = TLE4971A025_BANDWIDTH_HZ;

% Total high-side voltage divider resistance.
HARMONIA_3PH_LC_FILTER_VS_R_TOP_TOTAL_OHM = 3920000.0;

% Bottom voltage divider resistance.
HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM = 560000.0;

% Isolation amplifier voltage gain.
HARMONIA_3PH_LC_FILTER_VS_ISO_GAIN_V_V = 0.4;

% Voltage sensing op-amp feedback resistor.
HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_FB_OHM = 1650.0;

% Voltage sensing op-amp input resistor.
HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_IN_OHM = 2000.0;

% ADC bias for phase voltage sensing.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_BIAS_V = 1.65;

% Approximate phase voltage sense bandwidth.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_POLE_HZ = 100000.0;

% Phase voltage sensor model.
HARMONIA_3PH_LC_FILTER_VOLTAGE_SENSOR_MODEL = ResDiv + AMC1350 + TLV9061;

% Calculated phase voltage sense gain.
HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_GAIN = (HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM / (HARMONIA_3PH_LC_FILTER_VS_R_TOP_TOTAL_OHM + HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM)) * HARMONIA_3PH_LC_FILTER_VS_ISO_GAIN_V_V * (HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_FB_OHM / HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_IN_OHM);

% Phase current sensor model.
HARMONIA_3PH_LC_FILTER_CURRENT_SENSOR_MODEL = Infineon TLE4971A025;

% Phase current sensor sensitivity.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSITIVITY_MV_A = TLE4971A025_SENSITIVITY_MV_PER_A;

% Zero-current output bias.
HARMONIA_3PH_LC_FILTER_PH_CURRENT_ZERO_BIAS_V = TLE4971A025_BIAS_V;

%% SIL Runtime
% Automatically request CiA402 ENABLE_OPERATION in the simulation executable.
SINV_SIM_AUTO_ENABLE = true;

% SPECIFY_ENABLE_ADC_CALIBRATE is disabled in the SDPE project requirement.
% SPECIFY_ENABLE_ADC_CALIBRATE = true;

% ENABLE_GMP_DL_PIL_SIM is disabled in the SDPE project requirement.
% ENABLE_GMP_DL_PIL_SIM = true;

%% Commissioning
% Single-phase converter commissioning level.
% BUILD_LEVEL 1: open-loop sinusoidal H-bridge voltage on an isolated resistive load; validates ADC polarity, PWM mapping and the power stage without a current loop.
% BUILD_LEVEL 2: closed AC-current loop on an isolated resistive load; validates QPR tracking, grid-voltage feedforward and optional FDRC.
% BUILD_LEVEL 3: grid-connected signed P/Q command through the current loop; positive P exports power and negative P rectifies.
% BUILD_LEVEL 4: grid-connected measured-active-power outer loop feeding the current loop.
% BUILD_LEVEL 5: active-front-end rectifier with a DC-bus voltage outer loop; takeover is initialized from the measured passive-rectifier power.
% Options: (1), (2), (3), (4), (5)
BUILD_LEVEL = 5;

%% Requirement bindings
% SIL controller and PWM update frequency.
CONTROLLER_FREQUENCY = 20e3;

% Plant switching frequency.
SINV_PWM_FREQUENCY_HZ = 20e3;

% Virtual PWM compare maximum.
CTRL_PWM_CMP_MAX = 2999;

% Virtual PWM deadband counts.
CTRL_PWM_DEADBAND_CMP = 50;

% ADC resolution used by all sensor blocks.
CTRL_ADC_RESOLUTION = 12;

% ADC reference voltage.
CTRL_ADC_VOLTAGE_REF = 3.3;

% Rated and nominal DC-bus voltage.
CTRL_DCBUS_VOLTAGE = 60.0;

% Nominal grid/load RMS voltage.
CTRL_GRID_VOLTAGE_RMS = 24.0;

% Rated RMS AC current.
CTRL_RATED_CURRENT_RMS = 10.0;

% Peak voltage PU base.
CTRL_VOLTAGE_BASE = 34.0;

% Peak current PU base.
CTRL_CURRENT_BASE = 14.14;

% AC filter series inductance.
CTRL_AC_INDUCTANCE = 480e-6;

% AC filter series resistance.
CTRL_AC_RESISTANCE = 0.10;

% AC filter shunt capacitance.
SINV_FILTER_CAPACITANCE_F = 22e-6;

% Filter capacitor ESR.
SINV_FILTER_CAP_ESR_OHM = 0.10;

% DC-link capacitance.
SINV_DC_CAPACITANCE_F = 2200e-6;

% Resistive load for levels 1 and 2.
SINV_RLOAD_OHM = 12.0;

% DC-side load for level 5. At 60 V this draws 120 W, within the configured converter current rating.
SINV_RECTIFIER_RLOAD_OHM = 30.0;

% AC voltage sensor sensitivity in V/V.
CTRL_AC_VOLTAGE_SENSITIVITY = 0.020;

% AC voltage ADC bias.
CTRL_AC_VOLTAGE_BIAS = 1.65;

% AC current sensor sensitivity in V/A.
CTRL_AC_CURRENT_SENSITIVITY = 0.150;

% AC current ADC bias.
CTRL_AC_CURRENT_BIAS = 1.65;

% DC bus voltage sensor sensitivity in V/V.
CTRL_DC_VOLTAGE_SENSITIVITY = 0.040;

% DC bus voltage ADC bias.
CTRL_DC_VOLTAGE_BIAS = 0.0;

% DC bus overvoltage threshold.
CTRL_PROT_VBUS_MAX = 90.0;

% Fast AC peak-current threshold.
CTRL_PROT_IAC_PEAK_MAX = 18.0;

% Controller divergence threshold; BUILD_LEVEL 5 masks it only during passive-rectifier takeover.
CTRL_PROT_VCTRL_MAX_PU = 1.5;

% Minimum precharged DC bus accepted by startup.
CTRL_DCBUS_READY_MIN = 25.0;

% Maximum DC bus accepted by startup.
CTRL_DCBUS_READY_MAX = 90.0;

% ADC calibration timeout.
TIMEOUT_ADC_CALIB_MS = 3000;

% Plant MOSFET on resistance.
SINV_MODEL_MOSFET_RON = 4.6e-3;

% Body-diode on resistance.
SINV_MODEL_DIODE_RON = 0.01;

% Body-diode forward voltage.
SINV_MODEL_DIODE_VF = 0.5;

%% SDPE project summary
fprintf('\n============================================================\n');
fprintf('SDPE Project : %s\n', 'PGS SINV RC MATLAB/Simulink SIL');
fprintf('Project ID   : %s\n', 'pgs_sinv_rc_simulate');
fprintf('Suite        : %s\n', 'pgs_sinv_rc');
fprintf('Version      : %s\n', '1.0.0');
fprintf('Hardware (2):\n');
fprintf('  - %s\n', 'gmp_lvfb_150_2ph_v2');
fprintf('  - %s\n', 'gmp_harmonia_3ph_lc_filter');
fprintf('Common requirements (1):\n');
fprintf('  - %s\n', 'PGS Single-Phase Inverter Common Control');
fprintf('Enabled variables (170):\n');
fprintf('  BSC093N15NS5_CONFIGURATION = '); disp(BSC093N15NS5_CONFIGURATION);
fprintf('  BSC093N15NS5_CURRENT_RATING_A = '); disp(BSC093N15NS5_CURRENT_RATING_A);
fprintf('  BSC093N15NS5_DEVICE_TYPE = '); disp(BSC093N15NS5_DEVICE_TYPE);
fprintf('  BSC093N15NS5_GATE_CHARGE_NC = '); disp(BSC093N15NS5_GATE_CHARGE_NC);
fprintf('  BSC093N15NS5_GATE_VOLTAGE_V = '); disp(BSC093N15NS5_GATE_VOLTAGE_V);
fprintf('  BSC093N15NS5_ID = '); disp(BSC093N15NS5_ID);
fprintf('  BSC093N15NS5_NAME = '); disp(BSC093N15NS5_NAME);
fprintf('  BSC093N15NS5_PACKAGE = '); disp(BSC093N15NS5_PACKAGE);
fprintf('  BSC093N15NS5_PART_NUMBER = '); disp(BSC093N15NS5_PART_NUMBER);
fprintf('  BSC093N15NS5_RDSON_MAX_OHM = '); disp(BSC093N15NS5_RDSON_MAX_OHM);
fprintf('  BSC093N15NS5_RDSON_OHM = '); disp(BSC093N15NS5_RDSON_OHM);
fprintf('  BSC093N15NS5_SCHEMA = '); disp(BSC093N15NS5_SCHEMA);
fprintf('  BSC093N15NS5_VOLTAGE_RATING_V = '); disp(BSC093N15NS5_VOLTAGE_RATING_V);
fprintf('  BUILD_LEVEL = '); disp(BUILD_LEVEL);
fprintf('  CIA402_CONFIG_ENABLE_SEQUENCE_SWITCH = '); disp(CIA402_CONFIG_ENABLE_SEQUENCE_SWITCH);
fprintf('  CONTROLLER_FREQUENCY = '); disp(CONTROLLER_FREQUENCY);
fprintf('  CTRL_AC_CURRENT_BIAS = '); disp(CTRL_AC_CURRENT_BIAS);
fprintf('  CTRL_AC_CURRENT_SENSITIVITY = '); disp(CTRL_AC_CURRENT_SENSITIVITY);
fprintf('  CTRL_AC_INDUCTANCE = '); disp(CTRL_AC_INDUCTANCE);
fprintf('  CTRL_AC_RESISTANCE = '); disp(CTRL_AC_RESISTANCE);
fprintf('  CTRL_AC_VOLTAGE_BIAS = '); disp(CTRL_AC_VOLTAGE_BIAS);
fprintf('  CTRL_AC_VOLTAGE_SENSITIVITY = '); disp(CTRL_AC_VOLTAGE_SENSITIVITY);
fprintf('  CTRL_ADC_RESOLUTION = '); disp(CTRL_ADC_RESOLUTION);
fprintf('  CTRL_ADC_VOLTAGE_REF = '); disp(CTRL_ADC_VOLTAGE_REF);
fprintf('  CTRL_CURRENT_BASE = '); disp(CTRL_CURRENT_BASE);
fprintf('  CTRL_CURRENT_DB_PU = '); disp(CTRL_CURRENT_DB_PU);
fprintf('  CTRL_CURRENT_LIMIT_PU = '); disp(CTRL_CURRENT_LIMIT_PU);
fprintf('  CTRL_DCBUS_READY_MAX = '); disp(CTRL_DCBUS_READY_MAX);
fprintf('  CTRL_DCBUS_READY_MIN = '); disp(CTRL_DCBUS_READY_MIN);
fprintf('  CTRL_DCBUS_VOLTAGE = '); disp(CTRL_DCBUS_VOLTAGE);
fprintf('  CTRL_DC_VOLTAGE_BIAS = '); disp(CTRL_DC_VOLTAGE_BIAS);
fprintf('  CTRL_DC_VOLTAGE_SENSITIVITY = '); disp(CTRL_DC_VOLTAGE_SENSITIVITY);
fprintf('  CTRL_FDRC_MIN_FREQ = '); disp(CTRL_FDRC_MIN_FREQ);
fprintf('  CTRL_GRID_FREQUENCY = '); disp(CTRL_GRID_FREQUENCY);
fprintf('  CTRL_GRID_VMIN_PU = '); disp(CTRL_GRID_VMIN_PU);
fprintf('  CTRL_GRID_VOLTAGE_RMS = '); disp(CTRL_GRID_VOLTAGE_RMS);
fprintf('  CTRL_PLL_KP = '); disp(CTRL_PLL_KP);
fprintf('  CTRL_PLL_LPF_FC = '); disp(CTRL_PLL_LPF_FC);
fprintf('  CTRL_PLL_TI = '); disp(CTRL_PLL_TI);
fprintf('  CTRL_PQ_LPF_FC = '); disp(CTRL_PQ_LPF_FC);
fprintf('  CTRL_PROT_IAC_PEAK_MAX = '); disp(CTRL_PROT_IAC_PEAK_MAX);
fprintf('  CTRL_PROT_VBUS_MAX = '); disp(CTRL_PROT_VBUS_MAX);
fprintf('  CTRL_PROT_VCTRL_MAX_PU = '); disp(CTRL_PROT_VCTRL_MAX_PU);
fprintf('  CTRL_PWM_CMP_MAX = '); disp(CTRL_PWM_CMP_MAX);
fprintf('  CTRL_PWM_DEADBAND_CMP = '); disp(CTRL_PWM_DEADBAND_CMP);
fprintf('  CTRL_P_SLEW_PU_S = '); disp(CTRL_P_SLEW_PU_S);
fprintf('  CTRL_Q_SLEW_PU_S = '); disp(CTRL_Q_SLEW_PU_S);
fprintf('  CTRL_RATED_CURRENT_RMS = '); disp(CTRL_RATED_CURRENT_RMS);
fprintf('  CTRL_SPLL_EPSILON = '); disp(CTRL_SPLL_EPSILON);
fprintf('  CTRL_VOLTAGE_BASE = '); disp(CTRL_VOLTAGE_BASE);
fprintf('  GMP_LVFB_BOARD_NAME = '); disp(GMP_LVFB_BOARD_NAME);
fprintf('  GMP_LVFB_BUS_CAPACITANCE_F = '); disp(GMP_LVFB_BUS_CAPACITANCE_F);
fprintf('  GMP_LVFB_CURRENT_BIAS_V = '); disp(GMP_LVFB_CURRENT_BIAS_V);
fprintf('  GMP_LVFB_CURRENT_BW_HZ = '); disp(GMP_LVFB_CURRENT_BW_HZ);
fprintf('  GMP_LVFB_CURRENT_MAX_PEAK_A = '); disp(GMP_LVFB_CURRENT_MAX_PEAK_A);
fprintf('  GMP_LVFB_CURRENT_MAX_RMS_A = '); disp(GMP_LVFB_CURRENT_MAX_RMS_A);
fprintf('  GMP_LVFB_CURRENT_SENSITIVITY = '); disp(GMP_LVFB_CURRENT_SENSITIVITY);
fprintf('  GMP_LVFB_CURRENT_SENSOR_NAME = '); disp(GMP_LVFB_CURRENT_SENSOR_NAME);
fprintf('  GMP_LVFB_DEADTIME_NS = '); disp(GMP_LVFB_DEADTIME_NS);
fprintf('  GMP_LVFB_GATE_DRIVER = '); disp(GMP_LVFB_GATE_DRIVER);
fprintf('  GMP_LVFB_HAS_LOCAL_BUS_CAP = '); disp(GMP_LVFB_HAS_LOCAL_BUS_CAP);
fprintf('  GMP_LVFB_ID = '); disp(GMP_LVFB_ID);
fprintf('  GMP_LVFB_MEASURED_CURRENT_RANGE_A = '); disp(GMP_LVFB_MEASURED_CURRENT_RANGE_A);
fprintf('  GMP_LVFB_MOSFET = '); disp(GMP_LVFB_MOSFET);
fprintf('  GMP_LVFB_NAME = '); disp(GMP_LVFB_NAME);
fprintf('  GMP_LVFB_PHASE_COUNT = '); disp(GMP_LVFB_PHASE_COUNT);
fprintf('  GMP_LVFB_SCHEMA = '); disp(GMP_LVFB_SCHEMA);
fprintf('  GMP_LVFB_VBUS_MAX_V = '); disp(GMP_LVFB_VBUS_MAX_V);
fprintf('  GMP_LVFB_VOLTAGE_BASE_V = '); disp(GMP_LVFB_VOLTAGE_BASE_V);
fprintf('  GMP_LVFB_VOLTAGE_BIAS_V = '); disp(GMP_LVFB_VOLTAGE_BIAS_V);
fprintf('  GMP_LVFB_VOLTAGE_BW_HZ = '); disp(GMP_LVFB_VOLTAGE_BW_HZ);
fprintf('  GMP_LVFB_VOLTAGE_MAX = '); disp(GMP_LVFB_VOLTAGE_MAX);
fprintf('  GMP_LVFB_VOLTAGE_R_HIGH_OHM = '); disp(GMP_LVFB_VOLTAGE_R_HIGH_OHM);
fprintf('  GMP_LVFB_VOLTAGE_R_LOW_OHM = '); disp(GMP_LVFB_VOLTAGE_R_LOW_OHM);
fprintf('  GMP_LVFB_VOLTAGE_SENSITIVITY = '); disp(GMP_LVFB_VOLTAGE_SENSITIVITY);
fprintf('  GMP_LVFB_VOLTAGE_SENSOR_NAME = '); disp(GMP_LVFB_VOLTAGE_SENSOR_NAME);
fprintf('  HARMONIA_3PH_LC_FILTER_BOARD_NAME = '); disp(HARMONIA_3PH_LC_FILTER_BOARD_NAME);
fprintf('  HARMONIA_3PH_LC_FILTER_CAPACITANCE_F = '); disp(HARMONIA_3PH_LC_FILTER_CAPACITANCE_F);
fprintf('  HARMONIA_3PH_LC_FILTER_CURRENT_MAX_PEAK_A = '); disp(HARMONIA_3PH_LC_FILTER_CURRENT_MAX_PEAK_A);
fprintf('  HARMONIA_3PH_LC_FILTER_CURRENT_MAX_RMS_A = '); disp(HARMONIA_3PH_LC_FILTER_CURRENT_MAX_RMS_A);
fprintf('  HARMONIA_3PH_LC_FILTER_CURRENT_SENSOR_MODEL = '); disp(HARMONIA_3PH_LC_FILTER_CURRENT_SENSOR_MODEL);
fprintf('  HARMONIA_3PH_LC_FILTER_ID = '); disp(HARMONIA_3PH_LC_FILTER_ID);
fprintf('  HARMONIA_3PH_LC_FILTER_INDUCTANCE_H = '); disp(HARMONIA_3PH_LC_FILTER_INDUCTANCE_H);
fprintf('  HARMONIA_3PH_LC_FILTER_NAME = '); disp(HARMONIA_3PH_LC_FILTER_NAME);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_POLE_HZ = '); disp(HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_POLE_HZ);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TOPOLOGY = '); disp(HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TOPOLOGY);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TYPE = '); disp(HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSE_TYPE);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSITIVITY_MV_A = '); disp(HARMONIA_3PH_LC_FILTER_PH_CURRENT_SENSITIVITY_MV_A);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_CURRENT_ZERO_BIAS_V = '); disp(HARMONIA_3PH_LC_FILTER_PH_CURRENT_ZERO_BIAS_V);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_BIAS_V = '); disp(HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_BIAS_V);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_GAIN = '); disp(HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_GAIN);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_POLE_HZ = '); disp(HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_POLE_HZ);
fprintf('  HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_TYPE = '); disp(HARMONIA_3PH_LC_FILTER_PH_VOLTAGE_SENSE_TYPE);
fprintf('  HARMONIA_3PH_LC_FILTER_SCHEMA = '); disp(HARMONIA_3PH_LC_FILTER_SCHEMA);
fprintf('  HARMONIA_3PH_LC_FILTER_TEMP_MAX_C = '); disp(HARMONIA_3PH_LC_FILTER_TEMP_MAX_C);
fprintf('  HARMONIA_3PH_LC_FILTER_VBUS_MAX_V = '); disp(HARMONIA_3PH_LC_FILTER_VBUS_MAX_V);
fprintf('  HARMONIA_3PH_LC_FILTER_VBUS_MIN_V = '); disp(HARMONIA_3PH_LC_FILTER_VBUS_MIN_V);
fprintf('  HARMONIA_3PH_LC_FILTER_VOLTAGE_SENSOR_MODEL = '); disp(HARMONIA_3PH_LC_FILTER_VOLTAGE_SENSOR_MODEL);
fprintf('  HARMONIA_3PH_LC_FILTER_VS_ISO_GAIN_V_V = '); disp(HARMONIA_3PH_LC_FILTER_VS_ISO_GAIN_V_V);
fprintf('  HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_FB_OHM = '); disp(HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_FB_OHM);
fprintf('  HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_IN_OHM = '); disp(HARMONIA_3PH_LC_FILTER_VS_OPAMP_R_IN_OHM);
fprintf('  HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM = '); disp(HARMONIA_3PH_LC_FILTER_VS_R_BOT_OHM);
fprintf('  HARMONIA_3PH_LC_FILTER_VS_R_TOP_TOTAL_OHM = '); disp(HARMONIA_3PH_LC_FILTER_VS_R_TOP_TOTAL_OHM);
fprintf('  LVFB_VDIV_150V_BANDWIDTH_HZ = '); disp(LVFB_VDIV_150V_BANDWIDTH_HZ);
fprintf('  LVFB_VDIV_150V_BIAS_V = '); disp(LVFB_VDIV_150V_BIAS_V);
fprintf('  LVFB_VDIV_150V_CHIP = '); disp(LVFB_VDIV_150V_CHIP);
fprintf('  LVFB_VDIV_150V_ID = '); disp(LVFB_VDIV_150V_ID);
fprintf('  LVFB_VDIV_150V_INPUT_RESISTANCE_OHM = '); disp(LVFB_VDIV_150V_INPUT_RESISTANCE_OHM);
fprintf('  LVFB_VDIV_150V_MAX_BY_BIAS_V = '); disp(LVFB_VDIV_150V_MAX_BY_BIAS_V);
fprintf('  LVFB_VDIV_150V_NAME = '); disp(LVFB_VDIV_150V_NAME);
fprintf('  LVFB_VDIV_150V_RATED_VOLTAGE_V = '); disp(LVFB_VDIV_150V_RATED_VOLTAGE_V);
fprintf('  LVFB_VDIV_150V_SCHEMA = '); disp(LVFB_VDIV_150V_SCHEMA);
fprintf('  LVFB_VDIV_150V_SENSITIVITY_V_PER_V = '); disp(LVFB_VDIV_150V_SENSITIVITY_V_PER_V);
fprintf('  PGS_SINV_RC_COMMON_SDPE_PROJECT_ID = '); disp(PGS_SINV_RC_COMMON_SDPE_PROJECT_ID);
fprintf('  PGS_SINV_RC_COMMON_SDPE_PROJECT_SUITE = '); disp(PGS_SINV_RC_COMMON_SDPE_PROJECT_SUITE);
fprintf('  PGS_SINV_RC_COMMON_SDPE_PROJECT_UPDATED_AT = '); disp(PGS_SINV_RC_COMMON_SDPE_PROJECT_UPDATED_AT);
fprintf('  PGS_SINV_RC_COMMON_SDPE_PROJECT_VERSION = '); disp(PGS_SINV_RC_COMMON_SDPE_PROJECT_VERSION);
fprintf('  PGS_SINV_RC_SIM_SDPE_PROJECT_ID = '); disp(PGS_SINV_RC_SIM_SDPE_PROJECT_ID);
fprintf('  PGS_SINV_RC_SIM_SDPE_PROJECT_SUITE = '); disp(PGS_SINV_RC_SIM_SDPE_PROJECT_SUITE);
fprintf('  PGS_SINV_RC_SIM_SDPE_PROJECT_UPDATED_AT = '); disp(PGS_SINV_RC_SIM_SDPE_PROJECT_UPDATED_AT);
fprintf('  PGS_SINV_RC_SIM_SDPE_PROJECT_VERSION = '); disp(PGS_SINV_RC_SIM_SDPE_PROJECT_VERSION);
fprintf('  SINV_CIA402_OPERATION_ENABLE_DELAY_MS = '); disp(SINV_CIA402_OPERATION_ENABLE_DELAY_MS);
fprintf('  SINV_CURRENT_LOOP_BANDWIDTH_HZ = '); disp(SINV_CURRENT_LOOP_BANDWIDTH_HZ);
fprintf('  SINV_DC_BUS_REF_V = '); disp(SINV_DC_BUS_REF_V);
fprintf('  SINV_DC_CAPACITANCE_F = '); disp(SINV_DC_CAPACITANCE_F);
fprintf('  SINV_ENABLE_GRID_VOLTAGE_FEEDFORWARD = '); disp(SINV_ENABLE_GRID_VOLTAGE_FEEDFORWARD);
fprintf('  SINV_ENABLE_REPETITIVE_CONTROL = '); disp(SINV_ENABLE_REPETITIVE_CONTROL);
fprintf('  SINV_FILTER_CAPACITANCE_F = '); disp(SINV_FILTER_CAPACITANCE_F);
fprintf('  SINV_FILTER_CAP_ESR_OHM = '); disp(SINV_FILTER_CAP_ESR_OHM);
fprintf('  SINV_LEVEL1_VOLTAGE_REF_PU = '); disp(SINV_LEVEL1_VOLTAGE_REF_PU);
fprintf('  SINV_LEVEL2_CURRENT_REF_PEAK_PU = '); disp(SINV_LEVEL2_CURRENT_REF_PEAK_PU);
fprintf('  SINV_LEVEL3_ACTIVE_POWER_REF_PU = '); disp(SINV_LEVEL3_ACTIVE_POWER_REF_PU);
fprintf('  SINV_LEVEL3_REACTIVE_POWER_REF_PU = '); disp(SINV_LEVEL3_REACTIVE_POWER_REF_PU);
fprintf('  SINV_LEVEL4_ACTIVE_POWER_REF_PU = '); disp(SINV_LEVEL4_ACTIVE_POWER_REF_PU);
fprintf('  SINV_MODEL_DIODE_RON = '); disp(SINV_MODEL_DIODE_RON);
fprintf('  SINV_MODEL_DIODE_VF = '); disp(SINV_MODEL_DIODE_VF);
fprintf('  SINV_MODEL_MOSFET_RON = '); disp(SINV_MODEL_MOSFET_RON);
fprintf('  SINV_PWM_FREQUENCY_HZ = '); disp(SINV_PWM_FREQUENCY_HZ);
fprintf('  SINV_RECTIFIER_RLOAD_OHM = '); disp(SINV_RECTIFIER_RLOAD_OHM);
fprintf('  SINV_RLOAD_OHM = '); disp(SINV_RLOAD_OHM);
fprintf('  SINV_SIM_AUTO_ENABLE = '); disp(SINV_SIM_AUTO_ENABLE);
fprintf('  TIMEOUT_ADC_CALIB_MS = '); disp(TIMEOUT_ADC_CALIB_MS);
fprintf('  TLE4971A025_BANDWIDTH_HZ = '); disp(TLE4971A025_BANDWIDTH_HZ);
fprintf('  TLE4971A025_BIAS_V = '); disp(TLE4971A025_BIAS_V);
fprintf('  TLE4971A025_CHIP = '); disp(TLE4971A025_CHIP);
fprintf('  TLE4971A025_ID = '); disp(TLE4971A025_ID);
fprintf('  TLE4971A025_INTERNAL_RESISTANCE_OHM = '); disp(TLE4971A025_INTERNAL_RESISTANCE_OHM);
fprintf('  TLE4971A025_MAX_CURRENT_FROM_BIAS_A = '); disp(TLE4971A025_MAX_CURRENT_FROM_BIAS_A);
fprintf('  TLE4971A025_NAME = '); disp(TLE4971A025_NAME);
fprintf('  TLE4971A025_OUTPUT_MAX_V = '); disp(TLE4971A025_OUTPUT_MAX_V);
fprintf('  TLE4971A025_OUTPUT_MIN_V = '); disp(TLE4971A025_OUTPUT_MIN_V);
fprintf('  TLE4971A025_RANGE_A = '); disp(TLE4971A025_RANGE_A);
fprintf('  TLE4971A025_SCHEMA = '); disp(TLE4971A025_SCHEMA);
fprintf('  TLE4971A025_SENSITIVITY_MV_PER_A = '); disp(TLE4971A025_SENSITIVITY_MV_PER_A);
fprintf('  TLE4971A025_SENSITIVITY_V_PER_A = '); disp(TLE4971A025_SENSITIVITY_V_PER_A);
fprintf('  TLE4971A025_SENSOR_TYPE = '); disp(TLE4971A025_SENSOR_TYPE);
fprintf('  TMCS1133_B5A_BANDWIDTH_HZ = '); disp(TMCS1133_B5A_BANDWIDTH_HZ);
fprintf('  TMCS1133_B5A_BIAS_V = '); disp(TMCS1133_B5A_BIAS_V);
fprintf('  TMCS1133_B5A_CHIP = '); disp(TMCS1133_B5A_CHIP);
fprintf('  TMCS1133_B5A_ID = '); disp(TMCS1133_B5A_ID);
fprintf('  TMCS1133_B5A_INTERNAL_RESISTANCE_OHM = '); disp(TMCS1133_B5A_INTERNAL_RESISTANCE_OHM);
fprintf('  TMCS1133_B5A_MAX_CURRENT_FROM_BIAS_A = '); disp(TMCS1133_B5A_MAX_CURRENT_FROM_BIAS_A);
fprintf('  TMCS1133_B5A_NAME = '); disp(TMCS1133_B5A_NAME);
fprintf('  TMCS1133_B5A_OUTPUT_MAX_V = '); disp(TMCS1133_B5A_OUTPUT_MAX_V);
fprintf('  TMCS1133_B5A_OUTPUT_MIN_V = '); disp(TMCS1133_B5A_OUTPUT_MIN_V);
fprintf('  TMCS1133_B5A_RANGE_A = '); disp(TMCS1133_B5A_RANGE_A);
fprintf('  TMCS1133_B5A_SCHEMA = '); disp(TMCS1133_B5A_SCHEMA);
fprintf('  TMCS1133_B5A_SENSITIVITY_MV_PER_A = '); disp(TMCS1133_B5A_SENSITIVITY_MV_PER_A);
fprintf('  TMCS1133_B5A_SENSITIVITY_V_PER_A = '); disp(TMCS1133_B5A_SENSITIVITY_V_PER_A);
fprintf('  TMCS1133_B5A_SENSOR_TYPE = '); disp(TMCS1133_B5A_SENSOR_TYPE);
fprintf('Disabled macros (2):\n');
fprintf('  - ENABLE_GMP_DL_PIL_SIM\n');
fprintf('  - SPECIFY_ENABLE_ADC_CALIBRATE\n');
fprintf('============================================================\n');

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
