/**
 * @file csp.config.h
 * @author Javnson (javnson@zju.edu.cn)
 * @brief
 * @version 0.1
 * @date 2024-09-30
 *
 * @copyright Copyright GMP(c) 2024
 *
 */

// This file provide a Chip Support Package configuration for STM32

// Specify this project is generated by CubeMX.
#define SPECIFY_PROJECT_GENERATED_BY_CUBEMX

#define USER_SPECIFIED_PRINT_FUNCTION(A, ...) gmp_base_print_n32(A, ##__VA_ARGS__)

#define SPECIFY_DISABLE_CSP_EXIT

// disable using assert.h, N32 do not support this feature
#define USE_GMP_SELF_BASE_ASSERT

// disable dev default function
#define DISABLE_GMP_DEV_PRINT_DEFAULT
