/**
 * @file csp.config.h
 * @author Javnson (javnson@zju.edu.cn)
 * @brief
 * @version 0.1
 * @date 2024-09-30
 *
 * @copyright Copyright GMP(c) 2024
 *
 */

// Chip Support Package configuration for the Nations N32H47x/N32H48x family.

// The target project is generated by N32Cube/Nations Tool Framework (NTFx).
#define SPECIFY_PROJECT_GENERATED_BY_N32CUBE

#define USER_SPECIFIED_PRINT_FUNCTION(A, ...) gmp_base_print_n32(A, ##__VA_ARGS__)

#define SPECIFY_DISABLE_CSP_EXIT

// Use GMP's small embedded assert implementation instead of the C library one.
#define USE_GMP_SELF_BASE_ASSERT

// disable dev default function
#define DISABLE_GMP_DEV_PRINT_DEFAULT
