/**
 * @file tmcs1133_b2a.h
 * @brief SDPE hardware preset for TMCS1133 B2A Hall Current Sensor.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _CURRENT_SENSOR_TMCS1133_B2A_H_
#define _CURRENT_SENSOR_TMCS1133_B2A_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_tmcs1133_b2a TMCS1133 B2A Hall Current Sensor
 * @{
 */

// Identification
#define TMCS1133_B2A_ID "tmcs1133_b2a"
#define TMCS1133_B2A_SCHEMA "current_sensor"
#define TMCS1133_B2A_NAME "TMCS1133 B2A Hall Current Sensor"

// Tags: current_sensor, hall, sensor, tmcs1133

/*
 * Schema: Basic current sensor model used to scale ADC voltage into current.
 * Vendor: Texas Instruments
 * Datasheet: https://www.ti.com/lit/ds/symlink/tmcs1133.pdf
 */

// Parameter macros
/**
 * @brief Main sensing IC or technology name.
 */
#ifndef TMCS1133_B2A_CHIP
#define TMCS1133_B2A_CHIP "TMCS1133B2A"
#endif // TMCS1133_B2A_CHIP

/**
 * @brief Current sensing technology, such as Hall, shunt, or fluxgate.
 */
#ifndef TMCS1133_B2A_SENSOR_TYPE
#define TMCS1133_B2A_SENSOR_TYPE "Hall"
#endif // TMCS1133_B2A_SENSOR_TYPE

/**
 * @brief Nominal measurable current range.
 * @unit A
 */
#ifndef TMCS1133_B2A_RANGE_A
#define TMCS1133_B2A_RANGE_A (31.0f)
#endif // TMCS1133_B2A_RANGE_A

/**
 * @brief Minimum output voltage.
 * @unit V
 */
#ifndef TMCS1133_B2A_OUTPUT_MIN_V
#define TMCS1133_B2A_OUTPUT_MIN_V (0.0f)
#endif // TMCS1133_B2A_OUTPUT_MIN_V

/**
 * @brief Maximum output voltage.
 * @unit V
 */
#ifndef TMCS1133_B2A_OUTPUT_MAX_V
#define TMCS1133_B2A_OUTPUT_MAX_V (3.3f)
#endif // TMCS1133_B2A_OUTPUT_MAX_V

/**
 * @brief Zero-current output bias.
 * @unit V
 */
#ifndef TMCS1133_B2A_BIAS_V
#define TMCS1133_B2A_BIAS_V (1.65f)
#endif // TMCS1133_B2A_BIAS_V

/**
 * @brief Current sensor sensitivity.
 * @unit mV/A
 */
#ifndef TMCS1133_B2A_SENSITIVITY_MV_PER_A
#define TMCS1133_B2A_SENSITIVITY_MV_PER_A (50.0f)
#endif // TMCS1133_B2A_SENSITIVITY_MV_PER_A

/**
 * @brief Typical small-signal bandwidth.
 * @unit Hz
 */
#ifndef TMCS1133_B2A_BANDWIDTH_HZ
#define TMCS1133_B2A_BANDWIDTH_HZ (300000.0f)
#endif // TMCS1133_B2A_BANDWIDTH_HZ

/**
 * @brief Sensor internal series resistance.
 * @unit ohm
 */
#ifndef TMCS1133_B2A_INTERNAL_RESISTANCE_OHM
#define TMCS1133_B2A_INTERNAL_RESISTANCE_OHM (0.0018f)
#endif // TMCS1133_B2A_INTERNAL_RESISTANCE_OHM

// Derived macros
/**
 * @brief Current sensor sensitivity converted to V/A.
 * @unit V/A
 */
#define TMCS1133_B2A_SENSITIVITY_V_PER_A (TMCS1133_B2A_SENSITIVITY_MV_PER_A / 1000.0f)

/**
 * @brief Positive current range implied by bias and sensitivity.
 * @unit A
 */
#define TMCS1133_B2A_MAX_CURRENT_FROM_BIAS_A (TMCS1133_B2A_BIAS_V / TMCS1133_B2A_SENSITIVITY_V_PER_A)

// Logical exports
// sensitivity: TMCS1133_B2A_SENSITIVITY_V_PER_A
// bias: TMCS1133_B2A_BIAS_V
// range: TMCS1133_B2A_RANGE_A

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _CURRENT_SENSOR_TMCS1133_B2A_H_
