/**
 * @file gmp_3ph_2136sinv_dual.h
 * @brief SDPE hardware preset for GMP 3PH 2136SINV DUAL.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _INVERTER_3PH_GMP_3PH_2136SINV_DUAL_H_
#define _INVERTER_3PH_GMP_3PH_2136SINV_DUAL_H_

#include <ctl/hardware_preset/power_switch/bsc040n10ns5.h>
#include <ctl/component/hardware_preset/inverter_3ph/inverter_3ph_general.h>

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_gmp_3ph_2136sinv_dual GMP 3PH 2136SINV DUAL
 * @{
 */

// Identification
#define GMP_3PH_2136SINV_DUAL_ID "gmp_3ph_2136sinv_dual"
#define GMP_3PH_2136SINV_DUAL_SCHEMA "inverter_3ph"
#define GMP_3PH_2136SINV_DUAL_NAME "GMP 3PH 2136SINV DUAL"

// Tags: full_bridge, gmp, inverter, power_stage, three_phase

/*
 * Schema: Canonical control-facing description of a three-phase full bridge inverter board.
 * Vendor: GMP
 * Document: ctl/component/hardware_preset/inverter_3ph/GMP_3PH_2136SINV_DUAL_TMPL.h
 */

// Parameter macros
/**
 * @brief Board name.
 */
#ifndef GMP_3PH_2136SINV_DUAL_BOARD_NAME
#define GMP_3PH_2136SINV_DUAL_BOARD_NAME "GMP 3PH 2136SINV DUAL"
#endif // GMP_3PH_2136SINV_DUAL_BOARD_NAME

/**
 * @brief Gate driver or integrated driver.
 */
#ifndef GMP_3PH_2136SINV_DUAL_GATE_DRIVER
#define GMP_3PH_2136SINV_DUAL_GATE_DRIVER "IR2136S"
#endif // GMP_3PH_2136SINV_DUAL_GATE_DRIVER

/**
 * @brief discrete_mosfet, discrete_igbt, ipm or integrated_power_stage.
 */
#ifndef GMP_3PH_2136SINV_DUAL_POWER_STAGE_KIND
#define GMP_3PH_2136SINV_DUAL_POWER_STAGE_KIND "discrete_mosfet"
#endif // GMP_3PH_2136SINV_DUAL_POWER_STAGE_KIND

/**
 * @brief Minimum documented operating bus voltage; zero means unspecified.
 * @unit V
 */
#ifndef GMP_3PH_2136SINV_DUAL_VBUS_MIN_V
#define GMP_3PH_2136SINV_DUAL_VBUS_MIN_V (10.0f)
#endif // GMP_3PH_2136SINV_DUAL_VBUS_MIN_V

/**
 * @brief Maximum documented operating bus voltage; zero means unspecified.
 * @unit V
 */
#ifndef GMP_3PH_2136SINV_DUAL_VBUS_MAX_V
#define GMP_3PH_2136SINV_DUAL_VBUS_MAX_V (100.0f)
#endif // GMP_3PH_2136SINV_DUAL_VBUS_MAX_V

/**
 * @brief Board continuous RMS current; zero means unspecified.
 * @unit A
 */
#ifndef GMP_3PH_2136SINV_DUAL_CURRENT_MAX_RMS_A
#define GMP_3PH_2136SINV_DUAL_CURRENT_MAX_RMS_A (30.0f)
#endif // GMP_3PH_2136SINV_DUAL_CURRENT_MAX_RMS_A

/**
 * @brief Board peak current; zero means unspecified.
 * @unit A
 */
#ifndef GMP_3PH_2136SINV_DUAL_CURRENT_MAX_PEAK_A
#define GMP_3PH_2136SINV_DUAL_CURRENT_MAX_PEAK_A (50.0f)
#endif // GMP_3PH_2136SINV_DUAL_CURRENT_MAX_PEAK_A

/**
 * @brief PWM control inputs (3 or 6); zero means not verified.
 */
#ifndef GMP_3PH_2136SINV_DUAL_PWM_INPUT_COUNT
#define GMP_3PH_2136SINV_DUAL_PWM_INPUT_COUNT (6U)
#endif // GMP_3PH_2136SINV_DUAL_PWM_INPUT_COUNT

/**
 * @brief One active-high, zero active-low.
 */
#ifndef GMP_3PH_2136SINV_DUAL_PWM_ACTIVE_LEVEL
#define GMP_3PH_2136SINV_DUAL_PWM_ACTIVE_LEVEL (1U)
#endif // GMP_3PH_2136SINV_DUAL_PWM_ACTIVE_LEVEL

/**
 * @brief One only when PWM polarity was checked against a primary schematic or datasheet.
 */
#ifndef GMP_3PH_2136SINV_DUAL_PWM_POLARITY_VERIFIED
#define GMP_3PH_2136SINV_DUAL_PWM_POLARITY_VERIFIED (0U)
#endif // GMP_3PH_2136SINV_DUAL_PWM_POLARITY_VERIFIED

/**
 * @brief Enable polarity; one active-high, zero active-low.
 */
#ifndef GMP_3PH_2136SINV_DUAL_ENABLE_ACTIVE_LEVEL
#define GMP_3PH_2136SINV_DUAL_ENABLE_ACTIVE_LEVEL (1U)
#endif // GMP_3PH_2136SINV_DUAL_ENABLE_ACTIVE_LEVEL

/**
 * @brief Independently measurable motor phase-current channels.
 */
#ifndef GMP_3PH_2136SINV_DUAL_PH_CURRENT_CHANNEL_COUNT
#define GMP_3PH_2136SINV_DUAL_PH_CURRENT_CHANNEL_COUNT (3U)
#endif // GMP_3PH_2136SINV_DUAL_PH_CURRENT_CHANNEL_COUNT

/**
 * @brief SENSOR_TYPE_* constant.
 */
#ifndef GMP_3PH_2136SINV_DUAL_PH_CURRENT_SENSE_TYPE
#define GMP_3PH_2136SINV_DUAL_PH_CURRENT_SENSE_TYPE SENSOR_TYPE_SHUNT
#endif // GMP_3PH_2136SINV_DUAL_PH_CURRENT_SENSE_TYPE

/**
 * @brief CS_TOPOLOGY_* constant.
 */
#ifndef GMP_3PH_2136SINV_DUAL_PH_CURRENT_SENSE_TOPOLOGY
#define GMP_3PH_2136SINV_DUAL_PH_CURRENT_SENSE_TOPOLOGY CS_TOPOLOGY_LOW_SIDE
#endif // GMP_3PH_2136SINV_DUAL_PH_CURRENT_SENSE_TOPOLOGY

/**
 * @brief Per-channel shunt resistance; zero for sensor IC or unknown.
 * @unit ohm
 */
#ifndef GMP_3PH_2136SINV_DUAL_PH_SHUNT_RESISTANCE_OHM
#define GMP_3PH_2136SINV_DUAL_PH_SHUNT_RESISTANCE_OHM (0.005f)
#endif // GMP_3PH_2136SINV_DUAL_PH_SHUNT_RESISTANCE_OHM

/**
 * @brief Current signal-chain gain; zero means configurable/unknown.
 * @unit V/V
 */
#ifndef GMP_3PH_2136SINV_DUAL_PH_CSA_GAIN_V_V
#define GMP_3PH_2136SINV_DUAL_PH_CSA_GAIN_V_V (15.0f)
#endif // GMP_3PH_2136SINV_DUAL_PH_CSA_GAIN_V_V

/**
 * @brief Zero-current ADC bias; zero may mean differential/unknown.
 * @unit V
 */
#ifndef GMP_3PH_2136SINV_DUAL_PH_CSA_BIAS_V
#define GMP_3PH_2136SINV_DUAL_PH_CSA_BIAS_V (1.65f)
#endif // GMP_3PH_2136SINV_DUAL_PH_CSA_BIAS_V

/**
 * @brief DC-link current measurement channels.
 */
#ifndef GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_CHANNEL_COUNT
#define GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_CHANNEL_COUNT (0U)
#endif // GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_CHANNEL_COUNT

/**
 * @brief SENSOR_TYPE_* constant.
 */
#ifndef GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_SENSE_TYPE
#define GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_SENSE_TYPE SENSOR_NONE
#endif // GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_SENSE_TYPE

/**
 * @brief CS_TOPOLOGY_* constant.
 */
#ifndef GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_SENSE_TOPOLOGY
#define GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_SENSE_TOPOLOGY CS_TOPOLOGY_NONE
#endif // GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_SENSE_TOPOLOGY

/**
 * @brief DC-link shunt resistance.
 * @unit ohm
 */
#ifndef GMP_3PH_2136SINV_DUAL_DCBUS_SHUNT_RESISTANCE_OHM
#define GMP_3PH_2136SINV_DUAL_DCBUS_SHUNT_RESISTANCE_OHM (0.0f)
#endif // GMP_3PH_2136SINV_DUAL_DCBUS_SHUNT_RESISTANCE_OHM

/**
 * @brief Measured phase-voltage channels.
 */
#ifndef GMP_3PH_2136SINV_DUAL_PH_VOLTAGE_CHANNEL_COUNT
#define GMP_3PH_2136SINV_DUAL_PH_VOLTAGE_CHANNEL_COUNT (3U)
#endif // GMP_3PH_2136SINV_DUAL_PH_VOLTAGE_CHANNEL_COUNT

/**
 * @brief VS_TYPE_* constant.
 */
#ifndef GMP_3PH_2136SINV_DUAL_PH_VOLTAGE_SENSE_TYPE
#define GMP_3PH_2136SINV_DUAL_PH_VOLTAGE_SENSE_TYPE VS_TYPE_PHASE_GND
#endif // GMP_3PH_2136SINV_DUAL_PH_VOLTAGE_SENSE_TYPE

/**
 * @brief Phase-voltage divider or signal-chain gain; zero means unknown.
 * @unit V/V
 */
#ifndef GMP_3PH_2136SINV_DUAL_PH_VOLTAGE_SENSE_GAIN
#define GMP_3PH_2136SINV_DUAL_PH_VOLTAGE_SENSE_GAIN (0.02083f)
#endif // GMP_3PH_2136SINV_DUAL_PH_VOLTAGE_SENSE_GAIN

/**
 * @brief Phase-voltage signal bias.
 * @unit V
 */
#ifndef GMP_3PH_2136SINV_DUAL_PH_VOLTAGE_SENSE_BIAS_V
#define GMP_3PH_2136SINV_DUAL_PH_VOLTAGE_SENSE_BIAS_V (0.0f)
#endif // GMP_3PH_2136SINV_DUAL_PH_VOLTAGE_SENSE_BIAS_V

/**
 * @brief DC-bus voltage channels.
 */
#ifndef GMP_3PH_2136SINV_DUAL_DCBUS_VOLTAGE_CHANNEL_COUNT
#define GMP_3PH_2136SINV_DUAL_DCBUS_VOLTAGE_CHANNEL_COUNT (1U)
#endif // GMP_3PH_2136SINV_DUAL_DCBUS_VOLTAGE_CHANNEL_COUNT

/**
 * @brief VS_TYPE_* constant.
 */
#ifndef GMP_3PH_2136SINV_DUAL_DCBUS_VOLTAGE_SENSE_TYPE
#define GMP_3PH_2136SINV_DUAL_DCBUS_VOLTAGE_SENSE_TYPE VS_TYPE_PHASE_GND
#endif // GMP_3PH_2136SINV_DUAL_DCBUS_VOLTAGE_SENSE_TYPE

/**
 * @brief DC-bus voltage divider or signal-chain gain; zero means unknown.
 * @unit V/V
 */
#ifndef GMP_3PH_2136SINV_DUAL_DCBUS_VOLTAGE_SENSE_GAIN
#define GMP_3PH_2136SINV_DUAL_DCBUS_VOLTAGE_SENSE_GAIN (0.02083f)
#endif // GMP_3PH_2136SINV_DUAL_DCBUS_VOLTAGE_SENSE_GAIN

/**
 * @brief DC-bus voltage signal bias.
 * @unit V
 */
#ifndef GMP_3PH_2136SINV_DUAL_DCBUS_VOLTAGE_SENSE_BIAS_V
#define GMP_3PH_2136SINV_DUAL_DCBUS_VOLTAGE_SENSE_BIAS_V (0.0f)
#endif // GMP_3PH_2136SINV_DUAL_DCBUS_VOLTAGE_SENSE_BIAS_V

/**
 * @brief DC-link current sensitivity; one is the compatibility value when absent.
 * @unit V/A
 */
#ifndef GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_SENSE_GAIN
#define GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_SENSE_GAIN (1.0f)
#endif // GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_SENSE_GAIN

/**
 * @brief DC-link current signal bias.
 * @unit V
 */
#ifndef GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_SENSE_BIAS_V
#define GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_SENSE_BIAS_V (0.0f)
#endif // GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_SENSE_BIAS_V

/**
 * @brief Power-stage temperature channels.
 */
#ifndef GMP_3PH_2136SINV_DUAL_THERMAL_CHANNEL_COUNT
#define GMP_3PH_2136SINV_DUAL_THERMAL_CHANNEL_COUNT (0U)
#endif // GMP_3PH_2136SINV_DUAL_THERMAL_CHANNEL_COUNT

/**
 * @brief verified, partial, schematic_required or template.
 */
#ifndef GMP_3PH_2136SINV_DUAL_VERIFICATION_STATUS
#define GMP_3PH_2136SINV_DUAL_VERIFICATION_STATUS "partial_internal_preset"
#endif // GMP_3PH_2136SINV_DUAL_VERIFICATION_STATUS

/**
 * @brief Primary board manual, schematic or internal design reference.
 */
#ifndef GMP_3PH_2136SINV_DUAL_SOURCE_REFERENCE
#define GMP_3PH_2136SINV_DUAL_SOURCE_REFERENCE "GMP_3PH_2136SINV_DUAL_TMPL.h; confirm against board schematic"
#endif // GMP_3PH_2136SINV_DUAL_SOURCE_REFERENCE

// Derived macros
/**
 * @brief At least one phase-current channel is present.
 */
#define GMP_3PH_2136SINV_DUAL_HAS_PHASE_CURRENT_SENSE (GMP_3PH_2136SINV_DUAL_PH_CURRENT_CHANNEL_COUNT > 0U)

/**
 * @brief A DC-link current channel is present.
 */
#define GMP_3PH_2136SINV_DUAL_HAS_DCBUS_CURRENT_SENSE (GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_CHANNEL_COUNT > 0U)

/**
 * @brief At least one phase-voltage channel is present.
 */
#define GMP_3PH_2136SINV_DUAL_HAS_PHASE_VOLTAGE_SENSE (GMP_3PH_2136SINV_DUAL_PH_VOLTAGE_CHANNEL_COUNT > 0U)

/**
 * @brief A DC-bus voltage channel is present.
 */
#define GMP_3PH_2136SINV_DUAL_HAS_DCBUS_VOLTAGE_SENSE (GMP_3PH_2136SINV_DUAL_DCBUS_VOLTAGE_CHANNEL_COUNT > 0U)

// Logical exports
// vbus_max: GMP_3PH_2136SINV_DUAL_VBUS_MAX_V
// phase_current_channels: GMP_3PH_2136SINV_DUAL_PH_CURRENT_CHANNEL_COUNT
// phase_current_topology: GMP_3PH_2136SINV_DUAL_PH_CURRENT_SENSE_TOPOLOGY
// bus_current_channels: GMP_3PH_2136SINV_DUAL_DCBUS_CURRENT_CHANNEL_COUNT
// phase_voltage_channels: GMP_3PH_2136SINV_DUAL_PH_VOLTAGE_CHANNEL_COUNT
// pwm_active_level: GMP_3PH_2136SINV_DUAL_PWM_ACTIVE_LEVEL

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _INVERTER_3PH_GMP_3PH_2136SINV_DUAL_H_
