/**
 * @file st_steval_ihm023v3.h
 * @brief SDPE hardware preset for ST STEVAL-IHM023V3.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _INVERTER_3PH_ST_STEVAL_IHM023V3_H_
#define _INVERTER_3PH_ST_STEVAL_IHM023V3_H_

#include <ctl/hardware_preset/power_switch/stgp10h60df.h>
#include <ctl/component/hardware_preset/inverter_3ph/inverter_3ph_general.h>

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_st_steval_ihm023v3 ST STEVAL-IHM023V3
 * @{
 */

// Identification
#define ST_STEVAL_IHM023V3_ID "st_steval_ihm023v3"
#define ST_STEVAL_IHM023V3_SCHEMA "inverter_3ph"
#define ST_STEVAL_IHM023V3_NAME "ST STEVAL-IHM023V3"

// Tags: full_bridge, high_voltage, inverter, power_stage, st, three_phase

/*
 * Schema: Canonical control-facing description of a three-phase full bridge inverter board.
 * Vendor: STMicroelectronics
 * Datasheet: https://www.st.com/resource/en/user_manual/um1823-1-kw-threephase-motor-control-evaluation-board-featuring-l6390-drivers-and-stgp10h60df-igbt-stmicroelectronics.pdf
 */

// Parameter macros
/**
 * @brief Board name.
 */
#define ST_STEVAL_IHM023V3_BOARD_NAME "STEVAL-IHM023V3"

/**
 * @brief Gate driver or integrated driver.
 */
#define ST_STEVAL_IHM023V3_GATE_DRIVER "L6390"

/**
 * @brief discrete_mosfet, discrete_igbt, ipm or integrated_power_stage.
 */
#define ST_STEVAL_IHM023V3_POWER_STAGE_KIND "discrete_igbt"

/**
 * @brief Minimum documented operating bus voltage; zero means unspecified.
 * @unit V
 */
#define ST_STEVAL_IHM023V3_VBUS_MIN_V (125.0f)

/**
 * @brief Maximum documented operating bus voltage; zero means unspecified.
 * @unit V
 */
#define ST_STEVAL_IHM023V3_VBUS_MAX_V (400.0f)

/**
 * @brief Board continuous RMS current; zero means unspecified.
 * @unit A
 */
#define ST_STEVAL_IHM023V3_CURRENT_MAX_RMS_A (0.0f)

/**
 * @brief Board peak current; zero means unspecified.
 * @unit A
 */
#define ST_STEVAL_IHM023V3_CURRENT_MAX_PEAK_A (0.0f)

/**
 * @brief PWM control inputs (3 or 6); zero means not verified.
 */
#define ST_STEVAL_IHM023V3_PWM_INPUT_COUNT (6U)

/**
 * @brief One active-high, zero active-low.
 */
#define ST_STEVAL_IHM023V3_PWM_ACTIVE_LEVEL (1U)

/**
 * @brief One only when PWM polarity was checked against a primary schematic or datasheet.
 */
#define ST_STEVAL_IHM023V3_PWM_POLARITY_VERIFIED (0U)

/**
 * @brief Enable polarity; one active-high, zero active-low.
 */
#define ST_STEVAL_IHM023V3_ENABLE_ACTIVE_LEVEL (1U)

/**
 * @brief Independently measurable motor phase-current channels.
 */
#define ST_STEVAL_IHM023V3_PH_CURRENT_CHANNEL_COUNT (0U)

/**
 * @brief SENSOR_TYPE_* constant.
 */
#define ST_STEVAL_IHM023V3_PH_CURRENT_SENSE_TYPE SENSOR_NONE

/**
 * @brief CS_TOPOLOGY_* constant.
 */
#define ST_STEVAL_IHM023V3_PH_CURRENT_SENSE_TOPOLOGY CS_TOPOLOGY_NONE

/**
 * @brief Per-channel shunt resistance; zero for sensor IC or unknown.
 * @unit ohm
 */
#define ST_STEVAL_IHM023V3_PH_SHUNT_RESISTANCE_OHM (0.0f)

/**
 * @brief Current signal-chain gain; zero means configurable/unknown.
 * @unit V/V
 */
#define ST_STEVAL_IHM023V3_PH_CSA_GAIN_V_V (0.0f)

/**
 * @brief Zero-current ADC bias; zero may mean differential/unknown.
 * @unit V
 */
#define ST_STEVAL_IHM023V3_PH_CSA_BIAS_V (0.0f)

/**
 * @brief DC-link current measurement channels.
 */
#define ST_STEVAL_IHM023V3_DCBUS_CURRENT_CHANNEL_COUNT (1U)

/**
 * @brief SENSOR_TYPE_* constant.
 */
#define ST_STEVAL_IHM023V3_DCBUS_CURRENT_SENSE_TYPE SENSOR_TYPE_SHUNT

/**
 * @brief CS_TOPOLOGY_* constant.
 */
#define ST_STEVAL_IHM023V3_DCBUS_CURRENT_SENSE_TOPOLOGY CS_TOPOLOGY_DC_LINK

/**
 * @brief DC-link shunt resistance.
 * @unit ohm
 */
#define ST_STEVAL_IHM023V3_DCBUS_SHUNT_RESISTANCE_OHM (0.0f)

/**
 * @brief Measured phase-voltage channels.
 */
#define ST_STEVAL_IHM023V3_PH_VOLTAGE_CHANNEL_COUNT (0U)

/**
 * @brief VS_TYPE_* constant.
 */
#define ST_STEVAL_IHM023V3_PH_VOLTAGE_SENSE_TYPE VS_TYPE_NONE

/**
 * @brief Phase-voltage divider or signal-chain gain; zero means unknown.
 * @unit V/V
 */
#define ST_STEVAL_IHM023V3_PH_VOLTAGE_SENSE_GAIN (0.0f)

/**
 * @brief Phase-voltage signal bias.
 * @unit V
 */
#define ST_STEVAL_IHM023V3_PH_VOLTAGE_SENSE_BIAS_V (0.0f)

/**
 * @brief DC-bus voltage channels.
 */
#define ST_STEVAL_IHM023V3_DCBUS_VOLTAGE_CHANNEL_COUNT (1U)

/**
 * @brief VS_TYPE_* constant.
 */
#define ST_STEVAL_IHM023V3_DCBUS_VOLTAGE_SENSE_TYPE VS_TYPE_PHASE_GND

/**
 * @brief DC-bus voltage divider or signal-chain gain; zero means unknown.
 * @unit V/V
 */
#define ST_STEVAL_IHM023V3_DCBUS_VOLTAGE_SENSE_GAIN (0.0f)

/**
 * @brief DC-bus voltage signal bias.
 * @unit V
 */
#define ST_STEVAL_IHM023V3_DCBUS_VOLTAGE_SENSE_BIAS_V (0.0f)

/**
 * @brief DC-link current sensitivity; one is the compatibility value when absent.
 * @unit V/A
 */
#define ST_STEVAL_IHM023V3_DCBUS_CURRENT_SENSE_GAIN (1.0f)

/**
 * @brief DC-link current signal bias.
 * @unit V
 */
#define ST_STEVAL_IHM023V3_DCBUS_CURRENT_SENSE_BIAS_V (0.0f)

/**
 * @brief Power-stage temperature channels.
 */
#define ST_STEVAL_IHM023V3_THERMAL_CHANNEL_COUNT (0U)

/**
 * @brief verified, partial, schematic_required or template.
 */
#define ST_STEVAL_IHM023V3_VERIFICATION_STATUS "verified_board_manual"

/**
 * @brief Primary board manual, schematic or internal design reference.
 */
#define ST_STEVAL_IHM023V3_SOURCE_REFERENCE "ST UM1823; 18-35 V low-voltage test configuration is an alternate mode"

// Derived macros
/**
 * @brief At least one phase-current channel is present.
 */
#define ST_STEVAL_IHM023V3_HAS_PHASE_CURRENT_SENSE (ST_STEVAL_IHM023V3_PH_CURRENT_CHANNEL_COUNT > 0U)

/**
 * @brief A DC-link current channel is present.
 */
#define ST_STEVAL_IHM023V3_HAS_DCBUS_CURRENT_SENSE (ST_STEVAL_IHM023V3_DCBUS_CURRENT_CHANNEL_COUNT > 0U)

/**
 * @brief At least one phase-voltage channel is present.
 */
#define ST_STEVAL_IHM023V3_HAS_PHASE_VOLTAGE_SENSE (ST_STEVAL_IHM023V3_PH_VOLTAGE_CHANNEL_COUNT > 0U)

/**
 * @brief A DC-bus voltage channel is present.
 */
#define ST_STEVAL_IHM023V3_HAS_DCBUS_VOLTAGE_SENSE (ST_STEVAL_IHM023V3_DCBUS_VOLTAGE_CHANNEL_COUNT > 0U)

// Logical exports
// vbus_max: ST_STEVAL_IHM023V3_VBUS_MAX_V
// phase_current_channels: ST_STEVAL_IHM023V3_PH_CURRENT_CHANNEL_COUNT
// phase_current_topology: ST_STEVAL_IHM023V3_PH_CURRENT_SENSE_TOPOLOGY
// bus_current_channels: ST_STEVAL_IHM023V3_DCBUS_CURRENT_CHANNEL_COUNT
// phase_voltage_channels: ST_STEVAL_IHM023V3_PH_VOLTAGE_CHANNEL_COUNT
// pwm_active_level: ST_STEVAL_IHM023V3_PWM_ACTIVE_LEVEL

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _INVERTER_3PH_ST_STEVAL_IHM023V3_H_
