/**
 * @file st_x_nucleo_ihm11m1.h
 * @brief SDPE hardware preset for ST X-NUCLEO-IHM11M1.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _INVERTER_3PH_ST_X_NUCLEO_IHM11M1_H_
#define _INVERTER_3PH_ST_X_NUCLEO_IHM11M1_H_

#include <ctl/hardware_preset/integrated_power_stage/stspin230.h>
#include <ctl/component/hardware_preset/inverter_3ph/inverter_3ph_general.h>

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_st_x_nucleo_ihm11m1 ST X-NUCLEO-IHM11M1
 * @{
 */

// Identification
#define ST_X_NUCLEO_IHM11M1_ID "st_x_nucleo_ihm11m1"
#define ST_X_NUCLEO_IHM11M1_SCHEMA "inverter_3ph"
#define ST_X_NUCLEO_IHM11M1_NAME "ST X-NUCLEO-IHM11M1"

// Tags: full_bridge, inverter, nucleo, power_stage, st, three_phase

/*
 * Schema: Canonical control-facing description of a three-phase full bridge inverter board.
 * Vendor: STMicroelectronics
 * Datasheet: https://www.st.com/resource/en/user_manual/dm00313598-getting-started-with-the-x-nucleo-ihm11m1-low-voltage-3-phase-brushless-dc-motor-driver-expansion-board-based-on-stspin230-stmicroelectronics.pdf
 */

// Parameter macros
/**
 * @brief Board name.
 */
#define ST_X_NUCLEO_IHM11M1_BOARD_NAME "X-NUCLEO-IHM11M1"

/**
 * @brief Gate driver or integrated driver.
 */
#define ST_X_NUCLEO_IHM11M1_GATE_DRIVER "integrated in STSPIN230"

/**
 * @brief discrete_mosfet, discrete_igbt, ipm or integrated_power_stage.
 */
#define ST_X_NUCLEO_IHM11M1_POWER_STAGE_KIND "integrated_power_stage"

/**
 * @brief Minimum documented operating bus voltage; zero means unspecified.
 * @unit V
 */
#define ST_X_NUCLEO_IHM11M1_VBUS_MIN_V (1.8f)

/**
 * @brief Maximum documented operating bus voltage; zero means unspecified.
 * @unit V
 */
#define ST_X_NUCLEO_IHM11M1_VBUS_MAX_V (10.0f)

/**
 * @brief Board continuous RMS current; zero means unspecified.
 * @unit A
 */
#define ST_X_NUCLEO_IHM11M1_CURRENT_MAX_RMS_A (1.3f)

/**
 * @brief Board peak current; zero means unspecified.
 * @unit A
 */
#define ST_X_NUCLEO_IHM11M1_CURRENT_MAX_PEAK_A (2.0f)

/**
 * @brief PWM control inputs (3 or 6); zero means not verified.
 */
#define ST_X_NUCLEO_IHM11M1_PWM_INPUT_COUNT (6U)

/**
 * @brief One active-high, zero active-low.
 */
#define ST_X_NUCLEO_IHM11M1_PWM_ACTIVE_LEVEL (1U)

/**
 * @brief One only when PWM polarity was checked against a primary schematic or datasheet.
 */
#define ST_X_NUCLEO_IHM11M1_PWM_POLARITY_VERIFIED (1U)

/**
 * @brief Enable polarity; one active-high, zero active-low.
 */
#define ST_X_NUCLEO_IHM11M1_ENABLE_ACTIVE_LEVEL (1U)

/**
 * @brief Independently measurable motor phase-current channels.
 */
#define ST_X_NUCLEO_IHM11M1_PH_CURRENT_CHANNEL_COUNT (0U)

/**
 * @brief SENSOR_TYPE_* constant.
 */
#define ST_X_NUCLEO_IHM11M1_PH_CURRENT_SENSE_TYPE SENSOR_NONE

/**
 * @brief CS_TOPOLOGY_* constant.
 */
#define ST_X_NUCLEO_IHM11M1_PH_CURRENT_SENSE_TOPOLOGY CS_TOPOLOGY_NONE

/**
 * @brief Per-channel shunt resistance; zero for sensor IC or unknown.
 * @unit ohm
 */
#define ST_X_NUCLEO_IHM11M1_PH_SHUNT_RESISTANCE_OHM (0.0f)

/**
 * @brief Current signal-chain gain; zero means configurable/unknown.
 * @unit V/V
 */
#define ST_X_NUCLEO_IHM11M1_PH_CSA_GAIN_V_V (0.0f)

/**
 * @brief Zero-current ADC bias; zero may mean differential/unknown.
 * @unit V
 */
#define ST_X_NUCLEO_IHM11M1_PH_CSA_BIAS_V (0.0f)

/**
 * @brief DC-link current measurement channels.
 */
#define ST_X_NUCLEO_IHM11M1_DCBUS_CURRENT_CHANNEL_COUNT (1U)

/**
 * @brief SENSOR_TYPE_* constant.
 */
#define ST_X_NUCLEO_IHM11M1_DCBUS_CURRENT_SENSE_TYPE SENSOR_TYPE_SHUNT

/**
 * @brief CS_TOPOLOGY_* constant.
 */
#define ST_X_NUCLEO_IHM11M1_DCBUS_CURRENT_SENSE_TOPOLOGY CS_TOPOLOGY_DC_LINK

/**
 * @brief DC-link shunt resistance.
 * @unit ohm
 */
#define ST_X_NUCLEO_IHM11M1_DCBUS_SHUNT_RESISTANCE_OHM (0.0f)

/**
 * @brief Measured phase-voltage channels.
 */
#define ST_X_NUCLEO_IHM11M1_PH_VOLTAGE_CHANNEL_COUNT (3U)

/**
 * @brief VS_TYPE_* constant.
 */
#define ST_X_NUCLEO_IHM11M1_PH_VOLTAGE_SENSE_TYPE VS_TYPE_PHASE_GND

/**
 * @brief Phase-voltage divider or signal-chain gain; zero means unknown.
 * @unit V/V
 */
#define ST_X_NUCLEO_IHM11M1_PH_VOLTAGE_SENSE_GAIN (0.0f)

/**
 * @brief Phase-voltage signal bias.
 * @unit V
 */
#define ST_X_NUCLEO_IHM11M1_PH_VOLTAGE_SENSE_BIAS_V (0.0f)

/**
 * @brief DC-bus voltage channels.
 */
#define ST_X_NUCLEO_IHM11M1_DCBUS_VOLTAGE_CHANNEL_COUNT (1U)

/**
 * @brief VS_TYPE_* constant.
 */
#define ST_X_NUCLEO_IHM11M1_DCBUS_VOLTAGE_SENSE_TYPE VS_TYPE_PHASE_GND

/**
 * @brief DC-bus voltage divider or signal-chain gain; zero means unknown.
 * @unit V/V
 */
#define ST_X_NUCLEO_IHM11M1_DCBUS_VOLTAGE_SENSE_GAIN (0.0f)

/**
 * @brief DC-bus voltage signal bias.
 * @unit V
 */
#define ST_X_NUCLEO_IHM11M1_DCBUS_VOLTAGE_SENSE_BIAS_V (0.0f)

/**
 * @brief DC-link current sensitivity; one is the compatibility value when absent.
 * @unit V/A
 */
#define ST_X_NUCLEO_IHM11M1_DCBUS_CURRENT_SENSE_GAIN (1.0f)

/**
 * @brief DC-link current signal bias.
 * @unit V
 */
#define ST_X_NUCLEO_IHM11M1_DCBUS_CURRENT_SENSE_BIAS_V (0.0f)

/**
 * @brief Power-stage temperature channels.
 */
#define ST_X_NUCLEO_IHM11M1_THERMAL_CHANNEL_COUNT (0U)

/**
 * @brief verified, partial, schematic_required or template.
 */
#define ST_X_NUCLEO_IHM11M1_VERIFICATION_STATUS "verified_board_manual"

/**
 * @brief Primary board manual, schematic or internal design reference.
 */
#define ST_X_NUCLEO_IHM11M1_SOURCE_REFERENCE "ST UM2095 and STSPIN230 datasheet"

// Derived macros
/**
 * @brief At least one phase-current channel is present.
 */
#define ST_X_NUCLEO_IHM11M1_HAS_PHASE_CURRENT_SENSE (ST_X_NUCLEO_IHM11M1_PH_CURRENT_CHANNEL_COUNT > 0U)

/**
 * @brief A DC-link current channel is present.
 */
#define ST_X_NUCLEO_IHM11M1_HAS_DCBUS_CURRENT_SENSE (ST_X_NUCLEO_IHM11M1_DCBUS_CURRENT_CHANNEL_COUNT > 0U)

/**
 * @brief At least one phase-voltage channel is present.
 */
#define ST_X_NUCLEO_IHM11M1_HAS_PHASE_VOLTAGE_SENSE (ST_X_NUCLEO_IHM11M1_PH_VOLTAGE_CHANNEL_COUNT > 0U)

/**
 * @brief A DC-bus voltage channel is present.
 */
#define ST_X_NUCLEO_IHM11M1_HAS_DCBUS_VOLTAGE_SENSE (ST_X_NUCLEO_IHM11M1_DCBUS_VOLTAGE_CHANNEL_COUNT > 0U)

// Logical exports
// vbus_max: ST_X_NUCLEO_IHM11M1_VBUS_MAX_V
// phase_current_channels: ST_X_NUCLEO_IHM11M1_PH_CURRENT_CHANNEL_COUNT
// phase_current_topology: ST_X_NUCLEO_IHM11M1_PH_CURRENT_SENSE_TOPOLOGY
// bus_current_channels: ST_X_NUCLEO_IHM11M1_DCBUS_CURRENT_CHANNEL_COUNT
// phase_voltage_channels: ST_X_NUCLEO_IHM11M1_PH_VOLTAGE_CHANNEL_COUNT
// pwm_active_level: ST_X_NUCLEO_IHM11M1_PWM_ACTIVE_LEVEL

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _INVERTER_3PH_ST_X_NUCLEO_IHM11M1_H_
