/**
 * @file ti_boostxl_drv8301.h
 * @brief SDPE hardware preset for TI BOOSTXL-DRV8301.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _INVERTER_3PH_TI_BOOSTXL_DRV8301_H_
#define _INVERTER_3PH_TI_BOOSTXL_DRV8301_H_

#include <ctl/hardware_preset/power_switch/csd18533q5a.h>
#include <ctl/hardware_preset/inverter_3ph/inverter_3ph_general.h>

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_ti_boostxl_drv8301 TI BOOSTXL-DRV8301
 * @{
 */

// Identification
#define TI_BOOSTXL_DRV8301_ID "ti_boostxl_drv8301"
#define TI_BOOSTXL_DRV8301_SCHEMA "inverter_3ph"
#define TI_BOOSTXL_DRV8301_NAME "TI BOOSTXL-DRV8301"

// Tags: boosterpack, full_bridge, inverter, power_stage, three_phase, ti

/*
 * Schema: Canonical control-facing description of a three-phase full bridge inverter board.
 * Vendor: Texas Instruments
 * Datasheet: https://www.ti.com/lit/ug/slvu974/slvu974.pdf
 */

// Parameter macros
/**
 * @brief Board name.
 */
#ifndef TI_BOOSTXL_DRV8301_BOARD_NAME
#define TI_BOOSTXL_DRV8301_BOARD_NAME "BOOSTXL-DRV8301"
#endif // TI_BOOSTXL_DRV8301_BOARD_NAME

/**
 * @brief Gate driver or integrated driver.
 */
#ifndef TI_BOOSTXL_DRV8301_GATE_DRIVER
#define TI_BOOSTXL_DRV8301_GATE_DRIVER "DRV8301"
#endif // TI_BOOSTXL_DRV8301_GATE_DRIVER

/**
 * @brief discrete_mosfet, discrete_igbt, ipm or integrated_power_stage.
 */
#ifndef TI_BOOSTXL_DRV8301_POWER_STAGE_KIND
#define TI_BOOSTXL_DRV8301_POWER_STAGE_KIND "discrete_mosfet"
#endif // TI_BOOSTXL_DRV8301_POWER_STAGE_KIND

/**
 * @brief Minimum documented operating bus voltage; zero means unspecified.
 * @unit V
 */
#ifndef TI_BOOSTXL_DRV8301_VBUS_MIN_V
#define TI_BOOSTXL_DRV8301_VBUS_MIN_V (6.0f)
#endif // TI_BOOSTXL_DRV8301_VBUS_MIN_V

/**
 * @brief Maximum documented operating bus voltage; zero means unspecified.
 * @unit V
 */
#ifndef TI_BOOSTXL_DRV8301_VBUS_MAX_V
#define TI_BOOSTXL_DRV8301_VBUS_MAX_V (24.0f)
#endif // TI_BOOSTXL_DRV8301_VBUS_MAX_V

/**
 * @brief Board continuous RMS current; zero means unspecified.
 * @unit A
 */
#ifndef TI_BOOSTXL_DRV8301_CURRENT_MAX_RMS_A
#define TI_BOOSTXL_DRV8301_CURRENT_MAX_RMS_A (10.0f)
#endif // TI_BOOSTXL_DRV8301_CURRENT_MAX_RMS_A

/**
 * @brief Board peak current; zero means unspecified.
 * @unit A
 */
#ifndef TI_BOOSTXL_DRV8301_CURRENT_MAX_PEAK_A
#define TI_BOOSTXL_DRV8301_CURRENT_MAX_PEAK_A (0.0f)
#endif // TI_BOOSTXL_DRV8301_CURRENT_MAX_PEAK_A

/**
 * @brief PWM control inputs (3 or 6); zero means not verified.
 */
#ifndef TI_BOOSTXL_DRV8301_PWM_INPUT_COUNT
#define TI_BOOSTXL_DRV8301_PWM_INPUT_COUNT (6U)
#endif // TI_BOOSTXL_DRV8301_PWM_INPUT_COUNT

/**
 * @brief One active-high, zero active-low.
 */
#ifndef TI_BOOSTXL_DRV8301_PWM_ACTIVE_LEVEL
#define TI_BOOSTXL_DRV8301_PWM_ACTIVE_LEVEL (1U)
#endif // TI_BOOSTXL_DRV8301_PWM_ACTIVE_LEVEL

/**
 * @brief One only when PWM polarity was checked against a primary schematic or datasheet.
 */
#ifndef TI_BOOSTXL_DRV8301_PWM_POLARITY_VERIFIED
#define TI_BOOSTXL_DRV8301_PWM_POLARITY_VERIFIED (0U)
#endif // TI_BOOSTXL_DRV8301_PWM_POLARITY_VERIFIED

/**
 * @brief Enable polarity; one active-high, zero active-low.
 */
#ifndef TI_BOOSTXL_DRV8301_ENABLE_ACTIVE_LEVEL
#define TI_BOOSTXL_DRV8301_ENABLE_ACTIVE_LEVEL (1U)
#endif // TI_BOOSTXL_DRV8301_ENABLE_ACTIVE_LEVEL

/**
 * @brief Independently measurable motor phase-current channels.
 */
#ifndef TI_BOOSTXL_DRV8301_PH_CURRENT_CHANNEL_COUNT
#define TI_BOOSTXL_DRV8301_PH_CURRENT_CHANNEL_COUNT (3U)
#endif // TI_BOOSTXL_DRV8301_PH_CURRENT_CHANNEL_COUNT

/**
 * @brief SENSOR_TYPE_* constant.
 */
#ifndef TI_BOOSTXL_DRV8301_PH_CURRENT_SENSE_TYPE
#define TI_BOOSTXL_DRV8301_PH_CURRENT_SENSE_TYPE SENSOR_TYPE_SHUNT
#endif // TI_BOOSTXL_DRV8301_PH_CURRENT_SENSE_TYPE

/**
 * @brief CS_TOPOLOGY_* constant.
 */
#ifndef TI_BOOSTXL_DRV8301_PH_CURRENT_SENSE_TOPOLOGY
#define TI_BOOSTXL_DRV8301_PH_CURRENT_SENSE_TOPOLOGY CS_TOPOLOGY_LOW_SIDE
#endif // TI_BOOSTXL_DRV8301_PH_CURRENT_SENSE_TOPOLOGY

/**
 * @brief Per-channel shunt resistance; zero for sensor IC or unknown.
 * @unit ohm
 */
#ifndef TI_BOOSTXL_DRV8301_PH_SHUNT_RESISTANCE_OHM
#define TI_BOOSTXL_DRV8301_PH_SHUNT_RESISTANCE_OHM (0.01f)
#endif // TI_BOOSTXL_DRV8301_PH_SHUNT_RESISTANCE_OHM

/**
 * @brief Current signal-chain gain; zero means configurable/unknown.
 * @unit V/V
 */
#ifndef TI_BOOSTXL_DRV8301_PH_CSA_GAIN_V_V
#define TI_BOOSTXL_DRV8301_PH_CSA_GAIN_V_V (0.0f)
#endif // TI_BOOSTXL_DRV8301_PH_CSA_GAIN_V_V

/**
 * @brief Zero-current ADC bias; zero may mean differential/unknown.
 * @unit V
 */
#ifndef TI_BOOSTXL_DRV8301_PH_CSA_BIAS_V
#define TI_BOOSTXL_DRV8301_PH_CSA_BIAS_V (0.0f)
#endif // TI_BOOSTXL_DRV8301_PH_CSA_BIAS_V

/**
 * @brief DC-link current measurement channels.
 */
#ifndef TI_BOOSTXL_DRV8301_DCBUS_CURRENT_CHANNEL_COUNT
#define TI_BOOSTXL_DRV8301_DCBUS_CURRENT_CHANNEL_COUNT (0U)
#endif // TI_BOOSTXL_DRV8301_DCBUS_CURRENT_CHANNEL_COUNT

/**
 * @brief SENSOR_TYPE_* constant.
 */
#ifndef TI_BOOSTXL_DRV8301_DCBUS_CURRENT_SENSE_TYPE
#define TI_BOOSTXL_DRV8301_DCBUS_CURRENT_SENSE_TYPE SENSOR_NONE
#endif // TI_BOOSTXL_DRV8301_DCBUS_CURRENT_SENSE_TYPE

/**
 * @brief CS_TOPOLOGY_* constant.
 */
#ifndef TI_BOOSTXL_DRV8301_DCBUS_CURRENT_SENSE_TOPOLOGY
#define TI_BOOSTXL_DRV8301_DCBUS_CURRENT_SENSE_TOPOLOGY CS_TOPOLOGY_NONE
#endif // TI_BOOSTXL_DRV8301_DCBUS_CURRENT_SENSE_TOPOLOGY

/**
 * @brief DC-link shunt resistance.
 * @unit ohm
 */
#ifndef TI_BOOSTXL_DRV8301_DCBUS_SHUNT_RESISTANCE_OHM
#define TI_BOOSTXL_DRV8301_DCBUS_SHUNT_RESISTANCE_OHM (0.0f)
#endif // TI_BOOSTXL_DRV8301_DCBUS_SHUNT_RESISTANCE_OHM

/**
 * @brief Measured phase-voltage channels.
 */
#ifndef TI_BOOSTXL_DRV8301_PH_VOLTAGE_CHANNEL_COUNT
#define TI_BOOSTXL_DRV8301_PH_VOLTAGE_CHANNEL_COUNT (3U)
#endif // TI_BOOSTXL_DRV8301_PH_VOLTAGE_CHANNEL_COUNT

/**
 * @brief VS_TYPE_* constant.
 */
#ifndef TI_BOOSTXL_DRV8301_PH_VOLTAGE_SENSE_TYPE
#define TI_BOOSTXL_DRV8301_PH_VOLTAGE_SENSE_TYPE VS_TYPE_PHASE_GND
#endif // TI_BOOSTXL_DRV8301_PH_VOLTAGE_SENSE_TYPE

/**
 * @brief Phase-voltage divider or signal-chain gain; zero means unknown.
 * @unit V/V
 */
#ifndef TI_BOOSTXL_DRV8301_PH_VOLTAGE_SENSE_GAIN
#define TI_BOOSTXL_DRV8301_PH_VOLTAGE_SENSE_GAIN (0.0f)
#endif // TI_BOOSTXL_DRV8301_PH_VOLTAGE_SENSE_GAIN

/**
 * @brief Phase-voltage signal bias.
 * @unit V
 */
#ifndef TI_BOOSTXL_DRV8301_PH_VOLTAGE_SENSE_BIAS_V
#define TI_BOOSTXL_DRV8301_PH_VOLTAGE_SENSE_BIAS_V (0.0f)
#endif // TI_BOOSTXL_DRV8301_PH_VOLTAGE_SENSE_BIAS_V

/**
 * @brief DC-bus voltage channels.
 */
#ifndef TI_BOOSTXL_DRV8301_DCBUS_VOLTAGE_CHANNEL_COUNT
#define TI_BOOSTXL_DRV8301_DCBUS_VOLTAGE_CHANNEL_COUNT (1U)
#endif // TI_BOOSTXL_DRV8301_DCBUS_VOLTAGE_CHANNEL_COUNT

/**
 * @brief VS_TYPE_* constant.
 */
#ifndef TI_BOOSTXL_DRV8301_DCBUS_VOLTAGE_SENSE_TYPE
#define TI_BOOSTXL_DRV8301_DCBUS_VOLTAGE_SENSE_TYPE VS_TYPE_PHASE_GND
#endif // TI_BOOSTXL_DRV8301_DCBUS_VOLTAGE_SENSE_TYPE

/**
 * @brief DC-bus voltage divider or signal-chain gain; zero means unknown.
 * @unit V/V
 */
#ifndef TI_BOOSTXL_DRV8301_DCBUS_VOLTAGE_SENSE_GAIN
#define TI_BOOSTXL_DRV8301_DCBUS_VOLTAGE_SENSE_GAIN (0.0f)
#endif // TI_BOOSTXL_DRV8301_DCBUS_VOLTAGE_SENSE_GAIN

/**
 * @brief DC-bus voltage signal bias.
 * @unit V
 */
#ifndef TI_BOOSTXL_DRV8301_DCBUS_VOLTAGE_SENSE_BIAS_V
#define TI_BOOSTXL_DRV8301_DCBUS_VOLTAGE_SENSE_BIAS_V (0.0f)
#endif // TI_BOOSTXL_DRV8301_DCBUS_VOLTAGE_SENSE_BIAS_V

/**
 * @brief DC-link current sensitivity; one is the compatibility value when absent.
 * @unit V/A
 */
#ifndef TI_BOOSTXL_DRV8301_DCBUS_CURRENT_SENSE_GAIN
#define TI_BOOSTXL_DRV8301_DCBUS_CURRENT_SENSE_GAIN (1.0f)
#endif // TI_BOOSTXL_DRV8301_DCBUS_CURRENT_SENSE_GAIN

/**
 * @brief DC-link current signal bias.
 * @unit V
 */
#ifndef TI_BOOSTXL_DRV8301_DCBUS_CURRENT_SENSE_BIAS_V
#define TI_BOOSTXL_DRV8301_DCBUS_CURRENT_SENSE_BIAS_V (0.0f)
#endif // TI_BOOSTXL_DRV8301_DCBUS_CURRENT_SENSE_BIAS_V

/**
 * @brief Power-stage temperature channels.
 */
#ifndef TI_BOOSTXL_DRV8301_THERMAL_CHANNEL_COUNT
#define TI_BOOSTXL_DRV8301_THERMAL_CHANNEL_COUNT (0U)
#endif // TI_BOOSTXL_DRV8301_THERMAL_CHANNEL_COUNT

/**
 * @brief verified, partial, schematic_required or template.
 */
#ifndef TI_BOOSTXL_DRV8301_VERIFICATION_STATUS
#define TI_BOOSTXL_DRV8301_VERIFICATION_STATUS "verified_board_manual"
#endif // TI_BOOSTXL_DRV8301_VERIFICATION_STATUS

/**
 * @brief Primary board manual, schematic or internal design reference.
 */
#ifndef TI_BOOSTXL_DRV8301_SOURCE_REFERENCE
#define TI_BOOSTXL_DRV8301_SOURCE_REFERENCE "TI SLVU974"
#endif // TI_BOOSTXL_DRV8301_SOURCE_REFERENCE

// Derived macros
/**
 * @brief At least one phase-current channel is present.
 */
#define TI_BOOSTXL_DRV8301_HAS_PHASE_CURRENT_SENSE (TI_BOOSTXL_DRV8301_PH_CURRENT_CHANNEL_COUNT > 0U)

/**
 * @brief A DC-link current channel is present.
 */
#define TI_BOOSTXL_DRV8301_HAS_DCBUS_CURRENT_SENSE (TI_BOOSTXL_DRV8301_DCBUS_CURRENT_CHANNEL_COUNT > 0U)

/**
 * @brief At least one phase-voltage channel is present.
 */
#define TI_BOOSTXL_DRV8301_HAS_PHASE_VOLTAGE_SENSE (TI_BOOSTXL_DRV8301_PH_VOLTAGE_CHANNEL_COUNT > 0U)

/**
 * @brief A DC-bus voltage channel is present.
 */
#define TI_BOOSTXL_DRV8301_HAS_DCBUS_VOLTAGE_SENSE (TI_BOOSTXL_DRV8301_DCBUS_VOLTAGE_CHANNEL_COUNT > 0U)

// Logical exports
// vbus_max: TI_BOOSTXL_DRV8301_VBUS_MAX_V
// phase_current_channels: TI_BOOSTXL_DRV8301_PH_CURRENT_CHANNEL_COUNT
// phase_current_topology: TI_BOOSTXL_DRV8301_PH_CURRENT_SENSE_TOPOLOGY
// bus_current_channels: TI_BOOSTXL_DRV8301_DCBUS_CURRENT_CHANNEL_COUNT
// phase_voltage_channels: TI_BOOSTXL_DRV8301_PH_VOLTAGE_CHANNEL_COUNT
// pwm_active_level: TI_BOOSTXL_DRV8301_PWM_ACTIVE_LEVEL

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _INVERTER_3PH_TI_BOOSTXL_DRV8301_H_
