/**
 * @file ti_boostxl_3phganinv.h
 * @brief SDPE hardware preset for TI BOOSTXL-3PHGANINV.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _INVERTER_3PH_TI_BOOSTXL_3PHGANINV_H_
#define _INVERTER_3PH_TI_BOOSTXL_3PHGANINV_H_

#include <ctl/hardware_preset/integrated_power_stage/lmg5200.h>
#include <ctl/component/hardware_preset/inverter_3ph/inverter_3ph_general.h>

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_ti_boostxl_3phganinv TI BOOSTXL-3PHGANINV
 * @{
 */

// Identification
#define TI_BOOSTXL_3PHGANINV_ID "ti_boostxl_3phganinv"
#define TI_BOOSTXL_3PHGANINV_SCHEMA "inverter_3ph"
#define TI_BOOSTXL_3PHGANINV_NAME "TI BOOSTXL-3PHGANINV"

// Tags: boosterpack, full_bridge, gan, inverter, power_stage, three_phase, ti

/*
 * Schema: Canonical control-facing description of a three-phase full bridge inverter board.
 * Vendor: Texas Instruments
 * Datasheet: https://www.ti.com/lit/ug/sluubp1a/sluubp1a.pdf
 */

// Parameter macros
/**
 * @brief Board name.
 */
#define TI_BOOSTXL_3PHGANINV_BOARD_NAME "BOOSTXL-3PHGANINV"

/**
 * @brief Gate driver or integrated driver.
 */
#define TI_BOOSTXL_3PHGANINV_GATE_DRIVER "integrated in LMG5200"

/**
 * @brief discrete_mosfet, discrete_igbt, ipm or integrated_power_stage.
 */
#define TI_BOOSTXL_3PHGANINV_POWER_STAGE_KIND "integrated_power_stage"

/**
 * @brief Minimum documented operating bus voltage; zero means unspecified.
 * @unit V
 */
#define TI_BOOSTXL_3PHGANINV_VBUS_MIN_V (12.0f)

/**
 * @brief Maximum documented operating bus voltage; zero means unspecified.
 * @unit V
 */
#define TI_BOOSTXL_3PHGANINV_VBUS_MAX_V (60.0f)

/**
 * @brief Board continuous RMS current; zero means unspecified.
 * @unit A
 */
#define TI_BOOSTXL_3PHGANINV_CURRENT_MAX_RMS_A (7.0f)

/**
 * @brief Board peak current; zero means unspecified.
 * @unit A
 */
#define TI_BOOSTXL_3PHGANINV_CURRENT_MAX_PEAK_A (10.0f)

/**
 * @brief PWM control inputs (3 or 6); zero means not verified.
 */
#define TI_BOOSTXL_3PHGANINV_PWM_INPUT_COUNT (6U)

/**
 * @brief One active-high, zero active-low.
 */
#define TI_BOOSTXL_3PHGANINV_PWM_ACTIVE_LEVEL (1U)

/**
 * @brief One only when PWM polarity was checked against a primary schematic or datasheet.
 */
#define TI_BOOSTXL_3PHGANINV_PWM_POLARITY_VERIFIED (1U)

/**
 * @brief Enable polarity; one active-high, zero active-low.
 */
#define TI_BOOSTXL_3PHGANINV_ENABLE_ACTIVE_LEVEL (1U)

/**
 * @brief Independently measurable motor phase-current channels.
 */
#define TI_BOOSTXL_3PHGANINV_PH_CURRENT_CHANNEL_COUNT (3U)

/**
 * @brief SENSOR_TYPE_* constant.
 */
#define TI_BOOSTXL_3PHGANINV_PH_CURRENT_SENSE_TYPE SENSOR_TYPE_SHUNT

/**
 * @brief CS_TOPOLOGY_* constant.
 */
#define TI_BOOSTXL_3PHGANINV_PH_CURRENT_SENSE_TOPOLOGY CS_TOPOLOGY_INLINE

/**
 * @brief Per-channel shunt resistance; zero for sensor IC or unknown.
 * @unit ohm
 */
#define TI_BOOSTXL_3PHGANINV_PH_SHUNT_RESISTANCE_OHM (0.005f)

/**
 * @brief Current signal-chain gain; zero means configurable/unknown.
 * @unit V/V
 */
#define TI_BOOSTXL_3PHGANINV_PH_CSA_GAIN_V_V (20.0f)

/**
 * @brief Zero-current ADC bias; zero may mean differential/unknown.
 * @unit V
 */
#define TI_BOOSTXL_3PHGANINV_PH_CSA_BIAS_V (1.65f)

/**
 * @brief DC-link current measurement channels.
 */
#define TI_BOOSTXL_3PHGANINV_DCBUS_CURRENT_CHANNEL_COUNT (0U)

/**
 * @brief SENSOR_TYPE_* constant.
 */
#define TI_BOOSTXL_3PHGANINV_DCBUS_CURRENT_SENSE_TYPE SENSOR_NONE

/**
 * @brief CS_TOPOLOGY_* constant.
 */
#define TI_BOOSTXL_3PHGANINV_DCBUS_CURRENT_SENSE_TOPOLOGY CS_TOPOLOGY_NONE

/**
 * @brief DC-link shunt resistance.
 * @unit ohm
 */
#define TI_BOOSTXL_3PHGANINV_DCBUS_SHUNT_RESISTANCE_OHM (0.0f)

/**
 * @brief Measured phase-voltage channels.
 */
#define TI_BOOSTXL_3PHGANINV_PH_VOLTAGE_CHANNEL_COUNT (3U)

/**
 * @brief VS_TYPE_* constant.
 */
#define TI_BOOSTXL_3PHGANINV_PH_VOLTAGE_SENSE_TYPE VS_TYPE_PHASE_GND

/**
 * @brief Phase-voltage divider or signal-chain gain; zero means unknown.
 * @unit V/V
 */
#define TI_BOOSTXL_3PHGANINV_PH_VOLTAGE_SENSE_GAIN (0.06367f)

/**
 * @brief Phase-voltage signal bias.
 * @unit V
 */
#define TI_BOOSTXL_3PHGANINV_PH_VOLTAGE_SENSE_BIAS_V (0.0f)

/**
 * @brief DC-bus voltage channels.
 */
#define TI_BOOSTXL_3PHGANINV_DCBUS_VOLTAGE_CHANNEL_COUNT (1U)

/**
 * @brief VS_TYPE_* constant.
 */
#define TI_BOOSTXL_3PHGANINV_DCBUS_VOLTAGE_SENSE_TYPE VS_TYPE_PHASE_GND

/**
 * @brief DC-bus voltage divider or signal-chain gain; zero means unknown.
 * @unit V/V
 */
#define TI_BOOSTXL_3PHGANINV_DCBUS_VOLTAGE_SENSE_GAIN (0.06367f)

/**
 * @brief DC-bus voltage signal bias.
 * @unit V
 */
#define TI_BOOSTXL_3PHGANINV_DCBUS_VOLTAGE_SENSE_BIAS_V (0.0f)

/**
 * @brief DC-link current sensitivity; one is the compatibility value when absent.
 * @unit V/A
 */
#define TI_BOOSTXL_3PHGANINV_DCBUS_CURRENT_SENSE_GAIN (1.0f)

/**
 * @brief DC-link current signal bias.
 * @unit V
 */
#define TI_BOOSTXL_3PHGANINV_DCBUS_CURRENT_SENSE_BIAS_V (0.0f)

/**
 * @brief Power-stage temperature channels.
 */
#define TI_BOOSTXL_3PHGANINV_THERMAL_CHANNEL_COUNT (0U)

/**
 * @brief verified, partial, schematic_required or template.
 */
#define TI_BOOSTXL_3PHGANINV_VERIFICATION_STATUS "verified_board_manual"

/**
 * @brief Primary board manual, schematic or internal design reference.
 */
#define TI_BOOSTXL_3PHGANINV_SOURCE_REFERENCE "TI SLUUBP1A"

// Derived macros
/**
 * @brief At least one phase-current channel is present.
 */
#define TI_BOOSTXL_3PHGANINV_HAS_PHASE_CURRENT_SENSE (TI_BOOSTXL_3PHGANINV_PH_CURRENT_CHANNEL_COUNT > 0U)

/**
 * @brief A DC-link current channel is present.
 */
#define TI_BOOSTXL_3PHGANINV_HAS_DCBUS_CURRENT_SENSE (TI_BOOSTXL_3PHGANINV_DCBUS_CURRENT_CHANNEL_COUNT > 0U)

/**
 * @brief At least one phase-voltage channel is present.
 */
#define TI_BOOSTXL_3PHGANINV_HAS_PHASE_VOLTAGE_SENSE (TI_BOOSTXL_3PHGANINV_PH_VOLTAGE_CHANNEL_COUNT > 0U)

/**
 * @brief A DC-bus voltage channel is present.
 */
#define TI_BOOSTXL_3PHGANINV_HAS_DCBUS_VOLTAGE_SENSE (TI_BOOSTXL_3PHGANINV_DCBUS_VOLTAGE_CHANNEL_COUNT > 0U)

// Logical exports
// vbus_max: TI_BOOSTXL_3PHGANINV_VBUS_MAX_V
// phase_current_channels: TI_BOOSTXL_3PHGANINV_PH_CURRENT_CHANNEL_COUNT
// phase_current_topology: TI_BOOSTXL_3PHGANINV_PH_CURRENT_SENSE_TOPOLOGY
// bus_current_channels: TI_BOOSTXL_3PHGANINV_DCBUS_CURRENT_CHANNEL_COUNT
// phase_voltage_channels: TI_BOOSTXL_3PHGANINV_PH_VOLTAGE_CHANNEL_COUNT
// pwm_active_level: TI_BOOSTXL_3PHGANINV_PWM_ACTIVE_LEVEL

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _INVERTER_3PH_TI_BOOSTXL_3PHGANINV_H_
