/**
 * @file iris_f280039c_node.h
 * @brief SDPE hardware preset for IRIS F280039C Core Board.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _MCU_BOARD_IRIS_F280039C_NODE_H_
#define _MCU_BOARD_IRIS_F280039C_NODE_H_

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_iris_f280039c_node IRIS F280039C Core Board
 * @{
 */

// Identification
#define IRIS_F280039C_ID "iris_f280039c_node"
#define IRIS_F280039C_SCHEMA "iris_c2000_core_board"
#define IRIS_F280039C_NAME "IRIS F280039C Core Board"

/*
 * Schema: DSP C2000 core board peripheral name binding model.
 */

// Parameter macros
/**
 * @brief C2000 device name.
 */
#ifndef IRIS_F280039C_CHIP
#define IRIS_F280039C_CHIP "TMS320F280039C"
#endif // IRIS_F280039C_CHIP

/**
 * @brief SysConfig source file used by this binding.
 */
#ifndef IRIS_F280039C_SYSCFG_FILE
#define IRIS_F280039C_SYSCFG_FILE "ctl/suite/dps_fsbb/project/f280039c_Iris_node/F280039_Iris_node.syscfg"
#endif // IRIS_F280039C_SYSCFG_FILE

/**
 * @brief SysConfig EPWM1 base macro.
 */
#ifndef IRIS_F280039C_EPWM1_BASE
#define IRIS_F280039C_EPWM1_BASE IRIS_EPWM1_BASE
#endif // IRIS_F280039C_EPWM1_BASE

/**
 * @brief SysConfig EPWM2 base macro.
 */
#ifndef IRIS_F280039C_EPWM2_BASE
#define IRIS_F280039C_EPWM2_BASE IRIS_EPWM2_BASE
#endif // IRIS_F280039C_EPWM2_BASE

/**
 * @brief SysConfig ADC channel 1 macro.
 */
#ifndef IRIS_F280039C_ADC_CH1
#define IRIS_F280039C_ADC_CH1 ADC_CH1
#endif // IRIS_F280039C_ADC_CH1

/**
 * @brief SysConfig ADC channel 2 macro.
 */
#ifndef IRIS_F280039C_ADC_CH2
#define IRIS_F280039C_ADC_CH2 ADC_CH2
#endif // IRIS_F280039C_ADC_CH2

/**
 * @brief SysConfig ADC channel 3 macro.
 */
#ifndef IRIS_F280039C_ADC_CH3
#define IRIS_F280039C_ADC_CH3 ADC_CH3
#endif // IRIS_F280039C_ADC_CH3

/**
 * @brief SysConfig ADC channel 4 macro.
 */
#ifndef IRIS_F280039C_ADC_CH4
#define IRIS_F280039C_ADC_CH4 ADC_CH4
#endif // IRIS_F280039C_ADC_CH4

// Logical exports
// epwm1_base: IRIS_F280039C_EPWM1_BASE
// epwm2_base: IRIS_F280039C_EPWM2_BASE
// adc_ch1: IRIS_F280039C_ADC_CH1
// adc_ch2: IRIS_F280039C_ADC_CH2
// adc_ch3: IRIS_F280039C_ADC_CH3
// adc_ch4: IRIS_F280039C_ADC_CH4

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _MCU_BOARD_IRIS_F280039C_NODE_H_
