/**
 * @file bsc093n15ns5.h
 * @brief SDPE hardware preset for BSC093N15NS5.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _POWER_SWITCH_BSC093N15NS5_H_
#define _POWER_SWITCH_BSC093N15NS5_H_

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_bsc093n15ns5 BSC093N15NS5
 * @{
 */

// Identification
#define BSC093N15NS5_ID "bsc093n15ns5"
#define BSC093N15NS5_SCHEMA "power_switch"
#define BSC093N15NS5_NAME "BSC093N15NS5"

// Tags: infineon, mosfet, power_device, switch

/*
 * Schema: Power switch device used by bridge modules.
 * Vendor: Infineon
 * Datasheet: https://www.infineon.com/cms/en/product/power/mosfet/n-channel/bsc093n15ns5/
 */

// Parameter macros
/**
 * @brief Power device part number.
 */
#ifndef BSC093N15NS5_PART_NUMBER
#define BSC093N15NS5_PART_NUMBER "BSC093N15NS5"
#endif // BSC093N15NS5_PART_NUMBER

/**
 * @brief MOSFET, IGBT, GaN, SiC, etc.
 */
#ifndef BSC093N15NS5_DEVICE_TYPE
#define BSC093N15NS5_DEVICE_TYPE "MOSFET"
#endif // BSC093N15NS5_DEVICE_TYPE

/**
 * @brief Drain-source or collector-emitter voltage rating.
 * @unit V
 */
#ifndef BSC093N15NS5_VOLTAGE_RATING_V
#define BSC093N15NS5_VOLTAGE_RATING_V (150.0f)
#endif // BSC093N15NS5_VOLTAGE_RATING_V

/**
 * @brief Current rating.
 * @unit A
 */
#ifndef BSC093N15NS5_CURRENT_RATING_A
#define BSC093N15NS5_CURRENT_RATING_A (55.0f)
#endif // BSC093N15NS5_CURRENT_RATING_A

/**
 * @brief On resistance.
 * @unit ohm
 */
#ifndef BSC093N15NS5_RDSON_OHM
#define BSC093N15NS5_RDSON_OHM (0.0093f)
#endif // BSC093N15NS5_RDSON_OHM

// Logical exports
// voltage_rating: BSC093N15NS5_VOLTAGE_RATING_V
// current_rating: BSC093N15NS5_CURRENT_RATING_A

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _POWER_SWITCH_BSC093N15NS5_H_
