/** @file ctrl_settings.h @brief Dioscuri SDPE settings compatibility entry. */
#ifndef DPS_CLLLC_CTRL_SETTINGS_H
#define DPS_CLLLC_CTRL_SETTINGS_H

/* All physical, control and peripheral constants are generated by the two
 * SDPE layers. Keep this wrapper because GMP platform code includes the
 * historical ctrl_settings.h entry point. */
#include <sdpe_dps_clllc_dioscuri_settings.h>

#endif
