/**
 * @file gmp_lvfb_150_2ph_v2.h
 * @brief SDPE hardware preset for GMP LVFB 150V 2-Phase V2 Inverter Board.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _HALF_BRIDGE_GMP_LVFB_150_2PH_V2_H_
#define _HALF_BRIDGE_GMP_LVFB_150_2PH_V2_H_

#include <ctl/hardware_preset/current_sensor/tmcs1133_b5a.h>
#include <ctl/hardware_preset/power_switch/bsc093n15ns5.h>
#include <ctl/hardware_preset/voltage_sensor/lvfb_voltage_divider_150v.h>

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_gmp_lvfb_150_2ph_v2 GMP LVFB 150V 2-Phase V2 Inverter Board
 * @{
 */

// Identification
#define GMP_LVFB_ID "gmp_lvfb_150_2ph_v2"
#define GMP_LVFB_SCHEMA "half_bridge"
#define GMP_LVFB_NAME "GMP LVFB 150V 2-Phase V2 Inverter Board"

// Tags: half_bridge, lvfb, power_stage, two_phase

/*
 * Schema: Composable half-bridge module containing power switches and sensors.
 * Vendor: GMP
 * Document: ctl/component/hardware_preset/inverter_HB/GMP_LVFB_150_2ph_v2.h
 */

// Parameter macros
/**
 * @brief Board or module name.
 */
#define GMP_LVFB_BOARD_NAME "GMP LVFB 2ph V6.1"

/**
 * @brief Integrated gate driver part number.
 */
#define GMP_LVFB_GATE_DRIVER "UCC21520DWR"

/**
 * @brief Power MOSFET part number.
 */
#define GMP_LVFB_MOSFET "BSC093N15NS5"

/**
 * @brief On-board current sensing device.
 */
#define GMP_LVFB_CURRENT_SENSOR_NAME "TMCS1133B5A"

/**
 * @brief On-board voltage sensing device.
 */
#define GMP_LVFB_VOLTAGE_SENSOR_NAME "AMC1311BDWVR"

/**
 * @brief Number of half-bridge phases represented by this module.
 */
#define GMP_LVFB_PHASE_COUNT (2U)

/**
 * @brief Current measurement range exported by the current sensor sub component.
 * @unit A
 */
#define GMP_LVFB_MEASURED_CURRENT_RANGE_A TMCS1133_B5A_RANGE_A

/**
 * @brief Maximum allowable DC bus voltage.
 * @unit V
 */
#define GMP_LVFB_VBUS_MAX_V (120.0f)

/**
 * @brief Maximum instantaneous peak phase current.
 * @unit A
 */
#define GMP_LVFB_CURRENT_MAX_PEAK_A (55.0f)

/**
 * @brief Maximum continuous RMS phase current.
 * @unit A
 */
#define GMP_LVFB_CURRENT_MAX_RMS_A (35.0f)

/**
 * @brief Recommended hardware deadtime.
 * @unit ns
 */
#define GMP_LVFB_DEADTIME_NS (523.0f)

/**
 * @brief Current sensing signal bandwidth.
 * @unit Hz
 */
#define GMP_LVFB_CURRENT_BW_HZ (300.0e3f)

/**
 * @brief Current sensor ADC bias voltage.
 * @unit V
 */
#define GMP_LVFB_CURRENT_BIAS_V (1.65f)

/**
 * @brief Configured current sensitivity.
 * @unit V/A
 */
#define GMP_LVFB_CURRENT_SENSITIVITY TMCS1133_B5A_SENSITIVITY_V_PER_A

/**
 * @brief ADC reference scale voltage.
 * @unit V
 */
#define GMP_LVFB_VOLTAGE_BASE_V (3.3f)

/**
 * @brief Voltage sensing ADC bias voltage.
 * @unit V
 */
#define GMP_LVFB_VOLTAGE_BIAS_V (0.0f)

/**
 * @brief Voltage sensing bandwidth.
 * @unit Hz
 */
#define GMP_LVFB_VOLTAGE_BW_HZ (114.47e3f)

/**
 * @brief Default low-side voltage divider resistance.
 * @unit ohm
 */
#define GMP_LVFB_VOLTAGE_R_LOW_OHM ((15000.0))

/**
 * @brief Default high-side voltage divider resistance.
 * @unit ohm
 */
#define GMP_LVFB_VOLTAGE_R_HIGH_OHM ((300000.0))

/**
 * @brief Configured voltage sensing gain.
 * @unit V/V
 */
#define GMP_LVFB_VOLTAGE_SENSITIVITY ((15e3) / ((15e3) + ((300e3) * 3)) * 1.65f)

/**
 * @brief Configured maximum measurable voltage.
 * @unit V
 */
#define GMP_LVFB_VOLTAGE_MAX (3.3f / ((15e3) / ((15e3) + ((300e3) * 3)) * 1.65f))

/**
 * @brief Optional local DC bus capacitance.
 * @unit F
 */
#define GMP_LVFB_BUS_CAPACITANCE_F (0.0f)

// Derived macros
/**
 * @brief Whether this module declares a local bus capacitor.
 */
#define GMP_LVFB_HAS_LOCAL_BUS_CAP (GMP_LVFB_BUS_CAPACITANCE_F > 0.0f)

// Logical exports
// measured_current_range: GMP_LVFB_MEASURED_CURRENT_RANGE_A

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _HALF_BRIDGE_GMP_LVFB_150_2PH_V2_H_
