/**
 * @file lvfb_half_bridge_phase_b_tuned.h
 * @brief SDPE hardware preset for GMP LVFB Half Bridge Phase B Tuned.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _HALF_BRIDGE_LVFB_HALF_BRIDGE_PHASE_B_TUNED_H_
#define _HALF_BRIDGE_LVFB_HALF_BRIDGE_PHASE_B_TUNED_H_

#include <ctl/hardware_preset/current_sensor/tmcs1133_b2a.h>
#include <ctl/hardware_preset/power_switch/bsc093n15ns5.h>
#include <ctl/hardware_preset/voltage_sensor/lvfb_voltage_divider_150v.h>

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_lvfb_half_bridge_phase_b_tuned GMP LVFB Half Bridge Phase B Tuned
 * @{
 */

// Identification
#define GMP_LVFB_HB_B_TUNED_ID "lvfb_half_bridge_phase_b_tuned"
#define GMP_LVFB_HB_B_TUNED_SCHEMA "half_bridge"
#define GMP_LVFB_HB_B_TUNED_NAME "GMP LVFB Half Bridge Phase B Tuned"

// Tags: half_bridge, hall, lvfb, override, power_stage

/*
 * Schema: Composable half-bridge module containing power switches and sensors.
 */

// Parameter macros
/**
 * @brief Board or module name.
 */
#ifndef GMP_LVFB_HB_B_TUNED_BOARD_NAME
#define GMP_LVFB_HB_B_TUNED_BOARD_NAME "GMP LVFB 150V 2ph V2 Phase B tuned"
#endif // GMP_LVFB_HB_B_TUNED_BOARD_NAME

/**
 * @brief Number of half-bridge phases represented by this module.
 */
#ifndef GMP_LVFB_HB_B_TUNED_PHASE_COUNT
#define GMP_LVFB_HB_B_TUNED_PHASE_COUNT (1U)
#endif // GMP_LVFB_HB_B_TUNED_PHASE_COUNT

/**
 * @brief Current measurement range exported by the current sensor sub component.
 * @unit A
 */
#ifndef GMP_LVFB_HB_B_TUNED_MEASURED_CURRENT_RANGE_A
#define GMP_LVFB_HB_B_TUNED_MEASURED_CURRENT_RANGE_A GMP_LVFB_HB_B_TUNED_CURRENT_SENSOR_RANGE_A
#endif // GMP_LVFB_HB_B_TUNED_MEASURED_CURRENT_RANGE_A

/**
 * @brief Recommended hardware deadtime.
 * @unit ns
 */
#ifndef GMP_LVFB_HB_B_TUNED_DEADTIME_NS
#define GMP_LVFB_HB_B_TUNED_DEADTIME_NS (523.0f)
#endif // GMP_LVFB_HB_B_TUNED_DEADTIME_NS

/**
 * @brief Optional local DC bus capacitance.
 * @unit F
 */
#ifndef GMP_LVFB_HB_B_TUNED_BUS_CAPACITANCE_F
#define GMP_LVFB_HB_B_TUNED_BUS_CAPACITANCE_F (0.0f)
#endif // GMP_LVFB_HB_B_TUNED_BUS_CAPACITANCE_F

// Derived macros
/**
 * @brief Whether this module declares a local bus capacitor.
 */
#define GMP_LVFB_HB_B_TUNED_HAS_LOCAL_BUS_CAP (GMP_LVFB_HB_B_TUNED_BUS_CAPACITANCE_F > 0.0f)

// Component local override macros
// Local overrides for current_sensor
#define GMP_LVFB_HB_B_TUNED_CURRENT_SENSOR_CHIP TMCS1133_B2A_CHIP
#define GMP_LVFB_HB_B_TUNED_CURRENT_SENSOR_SENSOR_TYPE TMCS1133_B2A_SENSOR_TYPE
#define GMP_LVFB_HB_B_TUNED_CURRENT_SENSOR_RANGE_A (25.0f)
#define GMP_LVFB_HB_B_TUNED_CURRENT_SENSOR_OUTPUT_MIN_V TMCS1133_B2A_OUTPUT_MIN_V
#define GMP_LVFB_HB_B_TUNED_CURRENT_SENSOR_OUTPUT_MAX_V TMCS1133_B2A_OUTPUT_MAX_V
#define GMP_LVFB_HB_B_TUNED_CURRENT_SENSOR_BIAS_V (1.64f)
#define GMP_LVFB_HB_B_TUNED_CURRENT_SENSOR_SENSITIVITY_MV_PER_A TMCS1133_B2A_SENSITIVITY_MV_PER_A
#define GMP_LVFB_HB_B_TUNED_CURRENT_SENSOR_BANDWIDTH_HZ TMCS1133_B2A_BANDWIDTH_HZ
#define GMP_LVFB_HB_B_TUNED_CURRENT_SENSOR_INTERNAL_RESISTANCE_OHM TMCS1133_B2A_INTERNAL_RESISTANCE_OHM
#define GMP_LVFB_HB_B_TUNED_CURRENT_SENSOR_SENSITIVITY_V_PER_A (GMP_LVFB_HB_B_TUNED_CURRENT_SENSOR_SENSITIVITY_MV_PER_A / 1000.0f)
#define GMP_LVFB_HB_B_TUNED_CURRENT_SENSOR_MAX_CURRENT_FROM_BIAS_A (GMP_LVFB_HB_B_TUNED_CURRENT_SENSOR_BIAS_V / GMP_LVFB_HB_B_TUNED_CURRENT_SENSOR_SENSITIVITY_V_PER_A)

// Local overrides for voltage_sensor
#define GMP_LVFB_HB_B_TUNED_VOLTAGE_SENSOR_CHIP LVFB_VDIV_150V_CHIP
#define GMP_LVFB_HB_B_TUNED_VOLTAGE_SENSOR_RATED_VOLTAGE_V LVFB_VDIV_150V_RATED_VOLTAGE_V
#define GMP_LVFB_HB_B_TUNED_VOLTAGE_SENSOR_BIAS_V (0.01f)
#define GMP_LVFB_HB_B_TUNED_VOLTAGE_SENSOR_SENSITIVITY_V_PER_V LVFB_VDIV_150V_SENSITIVITY_V_PER_V
#define GMP_LVFB_HB_B_TUNED_VOLTAGE_SENSOR_INPUT_RESISTANCE_OHM LVFB_VDIV_150V_INPUT_RESISTANCE_OHM
#define GMP_LVFB_HB_B_TUNED_VOLTAGE_SENSOR_MAX_BY_BIAS_V ((GMP_LVFB_HB_B_TUNED_VOLTAGE_SENSOR_BIAS_V > 0.0f) ? (GMP_LVFB_HB_B_TUNED_VOLTAGE_SENSOR_BIAS_V / GMP_LVFB_HB_B_TUNED_VOLTAGE_SENSOR_SENSITIVITY_V_PER_V) : GMP_LVFB_HB_B_TUNED_VOLTAGE_SENSOR_RATED_VOLTAGE_V)

// Logical exports
// measured_current_range: GMP_LVFB_HB_B_TUNED_MEASURED_CURRENT_RANGE_A

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _HALF_BRIDGE_LVFB_HALF_BRIDGE_PHASE_B_TUNED_H_
