/**
 * @file lvfb_half_bridge_phase_a.h
 * @brief SDPE hardware preset for GMP LVFB Half Bridge Phase A.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _HALF_BRIDGE_LVFB_HALF_BRIDGE_PHASE_A_H_
#define _HALF_BRIDGE_LVFB_HALF_BRIDGE_PHASE_A_H_

#include <ctl/hardware_preset/current_sensor/tmcs1133_b5a.h>
#include <ctl/hardware_preset/power_switch/bsc093n15ns5.h>
#include <ctl/hardware_preset/voltage_sensor/lvfb_voltage_divider_150v.h>

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_lvfb_half_bridge_phase_a GMP LVFB Half Bridge Phase A
 * @{
 */

// Identification
#define GMP_LVFB_HB_A_ID "lvfb_half_bridge_phase_a"
#define GMP_LVFB_HB_A_SCHEMA "half_bridge"
#define GMP_LVFB_HB_A_NAME "GMP LVFB Half Bridge Phase A"

// Tags: half_bridge, hall, lvfb, power_stage

/*
 * Schema: Composable half-bridge module containing power switches and sensors.
 */

// Parameter macros
/**
 * @brief Board or module name.
 */
#define GMP_LVFB_HB_A_BOARD_NAME "GMP LVFB 150V 2ph V2 Phase A"

/**
 * @brief Number of half-bridge phases represented by this module.
 */
#define GMP_LVFB_HB_A_PHASE_COUNT (1U)

/**
 * @brief Current measurement range exported by the current sensor sub component.
 * @unit A
 */
#define GMP_LVFB_HB_A_MEASURED_CURRENT_RANGE_A TMCS1133_B5A_RANGE_A

/**
 * @brief Recommended hardware deadtime.
 * @unit ns
 */
#define GMP_LVFB_HB_A_DEADTIME_NS (523.0f)

/**
 * @brief Optional local DC bus capacitance.
 * @unit F
 */
#define GMP_LVFB_HB_A_BUS_CAPACITANCE_F (0.0f)

// Derived macros
/**
 * @brief Whether this module declares a local bus capacitor.
 */
#define GMP_LVFB_HB_A_HAS_LOCAL_BUS_CAP (GMP_LVFB_HB_A_BUS_CAPACITANCE_F > 0.0f)

// Logical exports
// measured_current_range: GMP_LVFB_HB_A_MEASURED_CURRENT_RANGE_A

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _HALF_BRIDGE_LVFB_HALF_BRIDGE_PHASE_A_H_
