%% SDPE MATLAB initialization script
% Project: PGS Single-Phase Inverter Common Control
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

%% GMP numeric-domain conversion contract
if ~exist('GMP_SDPE_REAL_TYPE', 'var'); GMP_SDPE_REAL_TYPE = 'double'; end
if ~exist('GMP_SDPE_PARAMETER_TYPE', 'var'); GMP_SDPE_PARAMETER_TYPE = 'double'; end
if ~exist('GMP_SDPE_CTRL_TYPE', 'var'); GMP_SDPE_CTRL_TYPE = 'double'; end
if ~exist('GMP_SDPE_REAL_TO_CTRL', 'var')
    GMP_SDPE_REAL_TO_CTRL = @(value) cast(value, GMP_SDPE_CTRL_TYPE);
end
if ~exist('GMP_SDPE_CTRL_TO_REAL', 'var')
    GMP_SDPE_CTRL_TO_REAL = @(value) cast(value, GMP_SDPE_REAL_TYPE);
end
real2param = @(value) cast(cast(value, GMP_SDPE_REAL_TYPE), GMP_SDPE_PARAMETER_TYPE);
real2ctrl = @(value) GMP_SDPE_REAL_TO_CTRL(cast(value, GMP_SDPE_REAL_TYPE));
param2ctrl = @(value) GMP_SDPE_REAL_TO_CTRL(cast(value, GMP_SDPE_PARAMETER_TYPE));
ctrl2param = @(value) cast(GMP_SDPE_CTRL_TO_REAL(value), GMP_SDPE_PARAMETER_TYPE);

% Notes:
%   Platform-independent control contract shared by all pgs_sinv_rc projects.

%% Project metadata
PGS_SINV_RC_COMMON_SDPE_PROJECT_ID = 'pgs_sinv_rc_common';

PGS_SINV_RC_COMMON_SDPE_PROJECT_SUITE = 'pgs_sinv_rc';

PGS_SINV_RC_COMMON_SDPE_PROJECT_VERSION = '1.0.0';

PGS_SINV_RC_COMMON_SDPE_PROJECT_UPDATED_AT = '2026-08-08';

%% Control Features
% FDRC master switch. Select this switch to enable delayed insertion of the frequency-adaptive repetitive controller; clear it to keep FDRC disabled at every BUILD_LEVEL.
SINV_ENABLE_REPETITIVE_CONTROL = true;

% Enable grid-voltage feedforward for closed-current-loop build levels.
SINV_ENABLE_GRID_VOLTAGE_FEEDFORWARD = true;

%% Runtime
% Allow ENABLE_OPERATION to advance through the complete CiA402 startup sequence.
CIA402_CONFIG_ENABLE_SEQUENCE_SWITCH = true;

%% Requirement bindings
% DC-bus outer-loop proportional gain.
SINV_DC_BUS_LOOP_KP = real2param(0.8);

% DC-bus outer-loop integral gain per second.
SINV_DC_BUS_LOOP_KI = real2param(12.0);

% Symmetric outer-loop active-power command limit.
SINV_OUTER_LOOP_POWER_LIMIT_PU = real2param(0.65);

% Power and DC-bus outer-loop execution frequency.
SINV_OUTER_LOOP_FREQUENCY_HZ = real2param(1000.0);

% Active-power outer-loop proportional gain.
SINV_POWER_LOOP_KP = real2param(0.6);

% Active-power outer-loop integral gain per second.
SINV_POWER_LOOP_KI = real2param(8.0);

% Repetitive-control learning gain.
SINV_FDRC_LEARNING_GAIN = real2param(0.10);

% FDRC robustness-filter cutoff frequency.
SINV_FDRC_Q_FILTER_HZ = real2param(1000.0);

% Plant-delay compensation in controller samples.
SINV_FDRC_LEAD_STEPS = real2param(3.0);

% Current-error threshold above which RC learning is frozen.
SINV_FDRC_FREEZE_ERROR_PU = real2param(0.05);

% Settling time before repetitive control starts learning.
SINV_FDRC_ENABLE_DELAY_MS = 300;

% Enable the three sparse ADC slots used by the single-phase inverter SIL input ABI.
GMP_PIL_RX_MASK = 21;

% Enable two PWM slots and all sixteen monitor slots used by the single-phase inverter SIL output ABI.
GMP_PIL_TX_MASK = 4294901763;

% Nominal grid frequency in Hz.
CTRL_GRID_FREQUENCY = real2param(50.0);

% Minimum voltage magnitude used by the P/Q reference generator.
CTRL_GRID_VMIN_PU = real2param(0.1);

% SOGI PLL proportional gain.
CTRL_PLL_KP = real2param(10.0);

% SOGI PLL integral time constant in seconds.
CTRL_PLL_TI = real2param(0.02);

% PLL error-filter cutoff frequency in Hz.
CTRL_PLL_LPF_FC = real2param(20.0);

% PLL frequency-error lock threshold in PU.
CTRL_SPLL_EPSILON = real2param(0.005);

% Current deadband used by PWM dead-time compensation.
CTRL_CURRENT_DB_PU = real2param(0.01);

% Active-power command slew limit in PU/s.
CTRL_P_SLEW_PU_S = real2param(5.0);

% Reactive-power command slew limit in PU/s.
CTRL_Q_SLEW_PU_S = real2param(5.0);

% Peak current command limit in PU.
CTRL_CURRENT_LIMIT_PU = real2param(0.9);

% Power measurement low-pass cutoff frequency in Hz.
CTRL_PQ_LPF_FC = real2param(200.0);

% Minimum fundamental tracked by FDRC in Hz.
CTRL_FDRC_MIN_FREQ = real2param(45.0);

% QPR current-loop crossover target in Hz.
SINV_CURRENT_LOOP_BANDWIDTH_HZ = real2param(600.0);

% Minimum operation-enabled transition delay.
SINV_CIA402_OPERATION_ENABLE_DELAY_MS = 100;

% BUILD_LEVEL 1 sinusoidal H-bridge voltage amplitude.
SINV_LEVEL1_VOLTAGE_REF_PU = real2param(0.35);

% BUILD_LEVEL 2 peak current command with a resistive load.
SINV_LEVEL2_CURRENT_REF_PEAK_PU = real2param(0.20);

% BUILD_LEVEL 3 signed grid active-power command; positive exports power.
SINV_LEVEL3_ACTIVE_POWER_REF_PU = real2param(0.10);

% BUILD_LEVEL 3 grid reactive-power command.
SINV_LEVEL3_REACTIVE_POWER_REF_PU = real2param(0.0);

% BUILD_LEVEL 4 measured active-power closed-loop target.
SINV_LEVEL4_ACTIVE_POWER_REF_PU = real2param(0.15);

% BUILD_LEVEL 5 physical DC bus voltage target.
SINV_DC_BUS_REF_V = real2param(60.0);

%% SDPE project summary
fprintf('\n============================================================\n');
fprintf('SDPE Project : %s\n', 'PGS Single-Phase Inverter Common Control');
fprintf('Project ID   : %s\n', 'pgs_sinv_rc_common');
fprintf('Suite        : %s\n', 'pgs_sinv_rc');
fprintf('Version      : %s\n', '1.0.0');
fprintf('Hardware (0):\n');
fprintf('Common requirements (0):\n');
fprintf('Enabled variables (40):\n');
fprintf('  CIA402_CONFIG_ENABLE_SEQUENCE_SWITCH = '); disp(CIA402_CONFIG_ENABLE_SEQUENCE_SWITCH);
fprintf('  CTRL_CURRENT_DB_PU = '); disp(CTRL_CURRENT_DB_PU);
fprintf('  CTRL_CURRENT_LIMIT_PU = '); disp(CTRL_CURRENT_LIMIT_PU);
fprintf('  CTRL_FDRC_MIN_FREQ = '); disp(CTRL_FDRC_MIN_FREQ);
fprintf('  CTRL_GRID_FREQUENCY = '); disp(CTRL_GRID_FREQUENCY);
fprintf('  CTRL_GRID_VMIN_PU = '); disp(CTRL_GRID_VMIN_PU);
fprintf('  CTRL_PLL_KP = '); disp(CTRL_PLL_KP);
fprintf('  CTRL_PLL_LPF_FC = '); disp(CTRL_PLL_LPF_FC);
fprintf('  CTRL_PLL_TI = '); disp(CTRL_PLL_TI);
fprintf('  CTRL_PQ_LPF_FC = '); disp(CTRL_PQ_LPF_FC);
fprintf('  CTRL_P_SLEW_PU_S = '); disp(CTRL_P_SLEW_PU_S);
fprintf('  CTRL_Q_SLEW_PU_S = '); disp(CTRL_Q_SLEW_PU_S);
fprintf('  CTRL_SPLL_EPSILON = '); disp(CTRL_SPLL_EPSILON);
fprintf('  GMP_PIL_RX_MASK = '); disp(GMP_PIL_RX_MASK);
fprintf('  GMP_PIL_TX_MASK = '); disp(GMP_PIL_TX_MASK);
fprintf('  PGS_SINV_RC_COMMON_SDPE_PROJECT_ID = '); disp(PGS_SINV_RC_COMMON_SDPE_PROJECT_ID);
fprintf('  PGS_SINV_RC_COMMON_SDPE_PROJECT_SUITE = '); disp(PGS_SINV_RC_COMMON_SDPE_PROJECT_SUITE);
fprintf('  PGS_SINV_RC_COMMON_SDPE_PROJECT_UPDATED_AT = '); disp(PGS_SINV_RC_COMMON_SDPE_PROJECT_UPDATED_AT);
fprintf('  PGS_SINV_RC_COMMON_SDPE_PROJECT_VERSION = '); disp(PGS_SINV_RC_COMMON_SDPE_PROJECT_VERSION);
fprintf('  SINV_CIA402_OPERATION_ENABLE_DELAY_MS = '); disp(SINV_CIA402_OPERATION_ENABLE_DELAY_MS);
fprintf('  SINV_CURRENT_LOOP_BANDWIDTH_HZ = '); disp(SINV_CURRENT_LOOP_BANDWIDTH_HZ);
fprintf('  SINV_DC_BUS_LOOP_KI = '); disp(SINV_DC_BUS_LOOP_KI);
fprintf('  SINV_DC_BUS_LOOP_KP = '); disp(SINV_DC_BUS_LOOP_KP);
fprintf('  SINV_DC_BUS_REF_V = '); disp(SINV_DC_BUS_REF_V);
fprintf('  SINV_ENABLE_GRID_VOLTAGE_FEEDFORWARD = '); disp(SINV_ENABLE_GRID_VOLTAGE_FEEDFORWARD);
fprintf('  SINV_ENABLE_REPETITIVE_CONTROL = '); disp(SINV_ENABLE_REPETITIVE_CONTROL);
fprintf('  SINV_FDRC_ENABLE_DELAY_MS = '); disp(SINV_FDRC_ENABLE_DELAY_MS);
fprintf('  SINV_FDRC_FREEZE_ERROR_PU = '); disp(SINV_FDRC_FREEZE_ERROR_PU);
fprintf('  SINV_FDRC_LEAD_STEPS = '); disp(SINV_FDRC_LEAD_STEPS);
fprintf('  SINV_FDRC_LEARNING_GAIN = '); disp(SINV_FDRC_LEARNING_GAIN);
fprintf('  SINV_FDRC_Q_FILTER_HZ = '); disp(SINV_FDRC_Q_FILTER_HZ);
fprintf('  SINV_LEVEL1_VOLTAGE_REF_PU = '); disp(SINV_LEVEL1_VOLTAGE_REF_PU);
fprintf('  SINV_LEVEL2_CURRENT_REF_PEAK_PU = '); disp(SINV_LEVEL2_CURRENT_REF_PEAK_PU);
fprintf('  SINV_LEVEL3_ACTIVE_POWER_REF_PU = '); disp(SINV_LEVEL3_ACTIVE_POWER_REF_PU);
fprintf('  SINV_LEVEL3_REACTIVE_POWER_REF_PU = '); disp(SINV_LEVEL3_REACTIVE_POWER_REF_PU);
fprintf('  SINV_LEVEL4_ACTIVE_POWER_REF_PU = '); disp(SINV_LEVEL4_ACTIVE_POWER_REF_PU);
fprintf('  SINV_OUTER_LOOP_FREQUENCY_HZ = '); disp(SINV_OUTER_LOOP_FREQUENCY_HZ);
fprintf('  SINV_OUTER_LOOP_POWER_LIMIT_PU = '); disp(SINV_OUTER_LOOP_POWER_LIMIT_PU);
fprintf('  SINV_POWER_LOOP_KI = '); disp(SINV_POWER_LOOP_KI);
fprintf('  SINV_POWER_LOOP_KP = '); disp(SINV_POWER_LOOP_KP);
fprintf('Disabled macros (0):\n');
fprintf('============================================================\n');

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
