/**
 * @file boostxl_dual_site.h
 * @brief SDPE hardware preset for TI BOOSTXL Dual-Site Connector.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _INTERFACE_BOOSTXL_DUAL_SITE_H_
#define _INTERFACE_BOOSTXL_DUAL_SITE_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_boostxl_dual_site TI BOOSTXL Dual-Site Connector
 * @{
 */

// Identification
#define BOOSTXL_DUAL_SITE_ID "boostxl_dual_site"
#define BOOSTXL_DUAL_SITE_SCHEMA "boostxl_interface"
#define BOOSTXL_DUAL_SITE_NAME "TI BOOSTXL Dual-Site Connector"

// Tags: boostxl, interface, launchpad, ti

/*
 * Schema: Portable physical connector contract shared by C2000 LaunchPads with two 40-pin BOOSTXL sites.
 */

// Parameter macros
/**
 * @brief Number of BOOSTXL sites.
 */
#define BOOSTXL_DUAL_SITE_SITE_COUNT (2U)

/**
 * @brief Nominal analog connector positions before device conflicts.
 */
#define BOOSTXL_DUAL_SITE_ANALOG_INPUT_COUNT (16U)

/**
 * @brief Nominal PWM pairs across both sites.
 */
#define BOOSTXL_DUAL_SITE_PWM_PAIR_COUNT (6U)

/**
 * @brief Default physical-position ADC SOC alias.
 */
#define BOOSTXL_DUAL_SITE_CONTROL_ADC_SOC BOOSTXL_ADC23

/**
 * @brief Result base paired with the default ADC SOC.
 */
#define BOOSTXL_DUAL_SITE_CONTROL_ADC_RESULT BOOSTXL_ADC23_RESULT_BASE

/**
 * @brief Default physical-position PWM base alias.
 */
#define BOOSTXL_DUAL_SITE_CONTROL_PWM_BASE BOOSTXL_EPWM4039_BASE

// Logical exports
// control_adc_soc: BOOSTXL_DUAL_SITE_CONTROL_ADC_SOC
// control_adc_result: BOOSTXL_DUAL_SITE_CONTROL_ADC_RESULT
// control_pwm_base: BOOSTXL_DUAL_SITE_CONTROL_PWM_BASE

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _INTERFACE_BOOSTXL_DUAL_SITE_H_
