%% SDPE MATLAB initialization script
% Project: MCS ACIM NT Common Controller Settings
% Generated by tools/SDPE_v2. Do not edit generated variables directly.

% Notes:
%   Platform-independent AC induction-motor FOC settings.

%% Project metadata
MCS_ACIM_NT_COMMON_SDPE_PROJECT_ID = 'mcs_acim_nt_common';

MCS_ACIM_NT_COMMON_SDPE_PROJECT_SUITE = 'mcs_acim_nt';

MCS_ACIM_NT_COMMON_SDPE_PROJECT_VERSION = '0.1.0';

MCS_ACIM_NT_COMMON_SDPE_PROJECT_UPDATED_AT = '2026-08-09';

%% Control Algorithm
% Apply ACIM-specific cross-coupling through the generic FOC feedforward port.
ENABLE_ACIM_DECOUPLING = true;

% ENABLE_PWM_DEADTIME_COMPENSATION is disabled in the SDPE project requirement.
% ENABLE_PWM_DEADTIME_COMPENSATION = true;

%% Protection
% ENABLE_MOTOR_FAULT_PROTECTION is disabled in the SDPE project requirement.
% ENABLE_MOTOR_FAULT_PROTECTION = true;

%% Controller Options
% Incremental commissioning gate: 1 open-angle V/f and PWM/ADC polarity; 2 I/F dq-current loop with synthetic field angle; 3 real field-angle current loop using external ACIM_POS_CALC or ACIM_FO; 4 mechanical speed loop. Do not advance until the previous level passes the commissioning record.
% Options: (1), (2), (3), (4)
BUILD_LEVEL = 1;

% Select speed-feedback IFOC or the voltage/current flux observer.
% Options: MCS_ACIM_FEEDBACK_SENSORED, MCS_ACIM_FEEDBACK_SENSORLESS
MCS_ACIM_FEEDBACK_MODE = 'MCS_ACIM_FEEDBACK_SENSORED';

% Select pre-dead-time controller command reconstruction or sampled phase voltage for the ACIM voltage model.
% Options: MCS_FO_VOLTAGE_FROM_COMMAND, MCS_FO_VOLTAGE_FROM_MEASUREMENT
MCS_FO_VOLTAGE_SOURCE = 'MCS_FO_VOLTAGE_FROM_COMMAND';

%% Requirement bindings
% Fast-loop frequency in hertz.
CONTROLLER_FREQUENCY = 20e3;

% Motor Rs
MOTOR_PARAM_RS = 0.329;

% Motor Rr
MOTOR_PARAM_RR = 0.44;

% Motor L1s
MOTOR_PARAM_L1S = 0.0003;

% Motor L1r
MOTOR_PARAM_L1R = 0.0005;

% Motor Lm
MOTOR_PARAM_LM = 0.0012;

% Motor Pole Pairs
MOTOR_PARAM_POLE_PAIRS = 2;

% Motor Rated Frequency
MOTOR_PARAM_RATED_FREQUENCY = 50.0;

% Motor Maximum Speed
MOTOR_PARAM_MAX_SPEED = 1450.0;

% Synchronous Speed Base
CTRL_SPEED_RPM_BASE = 1500.0;

% Nominal DC Bus Voltage
MCS_NOMINAL_DC_BUS_VOLTAGE_V = 48.0;

% Rectangular Voltage Limit
MCS_MAX_RECT_SATURATION_VOLTAGE_V = 24.0;

% Circular Voltage Limit
MCS_MAX_CIR_SATURATION_VOLTAGE_V = 24.0;

% Deadtime Current Deadband
MCS_PWM_DEADTIME_COMP_CURRENT_DEADBAND_A = 0.2;

% Deadtime Current Hysteresis
MCS_PWM_DEADTIME_COMP_CURRENT_HYSTERESIS_A = 0.05;

% Open Loop Frequency
MCS_OPEN_LOOP_FREQ_HZ = 30.0;

% Open Loop Frequency Slope
MCS_OPEN_LOOP_FREQ_SLOPE_HZ_S = 20.0;

% Optional constant d-axis voltage boost for BUILD_LEVEL 1, in volts.
MCS_OPEN_LOOP_VD_REF_V = 0.0;

% BUILD_LEVEL 1 q-axis voltage at MCS_OPEN_LOOP_FREQ_HZ. Runtime command is ramped proportionally with frequency (V/f).
MCS_OPEN_LOOP_VQ_REF_V = 6.0;

% Closed-loop ACIM magnetizing-current reference; unlike PMSM this normally must remain nonzero.
MCS_COMMISSIONING_ID_REF_A = 3.0;

% High I/F startup excitation current before the observer is sufficiently observable.
MCS_SENSORLESS_STARTUP_ID_REF_A = 4.0;

% I/F excitation reached at the angle-handover speed.
MCS_SENSORLESS_HANDOVER_ID_REF_A = 3.0;

% Absolute I/F electrical frequency where startup Id begins to decrease.
MCS_STARTUP_ID_FADE_START_HZ = 5.0;

% Absolute I/F electrical frequency where startup Id reaches the handover value.
MCS_STARTUP_ID_FADE_END_HZ = 25.0;

% Commissioning Iq
MCS_COMMISSIONING_IQ_REF_A = 1.0;

% Commissioning Speed
MCS_COMMISSIONING_SPEED_REF_RPM = 300.0;

% Magnetizing Time
MCS_MAGNETIZING_TIME_MS = 300.0;

% Mech Position Kp
MCS_MECH_POSITION_KP_PU = 5.0;

% Mech Position Ki
MCS_MECH_POSITION_KI_PU_S = 1.0;

% Mech Velocity Kp
MCS_MECH_VELOCITY_KP_PU = 1.0;

% Mech Velocity Ki
MCS_MECH_VELOCITY_KI_PU_S = 10.0;

% Mech Speed Limit
MCS_MECH_SPEED_LIMIT_RPM = 1400.0;

% Mech Speed Slope
MCS_MECH_SPEED_SLOPE_RPM_S = 1000.0;

% Mech Current Limit
MCS_MECH_CURRENT_LIMIT_A = 3.0;

% Encoder Speed Filter
MCS_ENCODER_SPEED_FILTER_FC_HZ = 20.0;

% Current-model correction bandwidth while the known I/F field frame owns the current loop and initializes the voltage model.
MCS_FO_COMP_BW_HZ = 20.0;

% Post-handover correction bandwidth used only to reject voltage-integrator DC drift; keep it far below the sensorless operating frequency.
MCS_FO_RUN_COMP_BW_HZ = 0.5;

% Voltage-model leaky-integrator cutoff used to block DC voltage and current offsets. Keep it below the handover frequency and account for its phase lag during tuning.
MCS_FO_VM_LEAK_HZ = 5.0;

% Rotor-flux PLL bandwidth. A modest value avoids speed saturation from low-speed voltage-model phase error.
MCS_FO_ATO_BW_HZ = 10.0;

% Flux Observer Fault Time
MCS_FO_FAULT_TIME_MS = 20.0;

% Multiply DC-bus PU by this target-specific modulator gain when reconstructing applied phase voltage from alpha-beta command.
MCS_FO_COMMAND_VOLTAGE_SCALE = 0.5;

% I/F electrical frequency at which the flux PLL is released to acquire the voltage-model angle while the current loop remains on the I/F field angle.
MCS_FO_ACQUIRE_FREQ_HZ = 10.0;

% Minimum I/F electrical frequency before a qualified flux observer may take ownership of field angle. Keep this well above MCS_FO_COMP_BW_HZ so the voltage model has directional authority.
MCS_FO_HANDOVER_FREQ_HZ = 25.0;

% Maximum wrapped angle mismatch in electrical-turn PU (1 pu = 360 degrees).
MCS_FO_HANDOVER_ANGLE_ERR_PU = 0.08;

% Maximum observer-versus-I/F synchronous-speed mismatch in PU before the enforced startup synchronization is applied.
MCS_FO_HANDOVER_SPEED_ERR_PU = 0.10;

% Larger speed mismatch that resets handover qualification; the gap above the enter tolerance is noise hysteresis.
MCS_FO_HANDOVER_SPEED_EXIT_ERR_PU = 0.15;

% Continuous qualification time before the sensorless field-angle handover.
MCS_FO_HANDOVER_DEBOUNCE_MS = 100.0;

% Time used to decay captured angle offset and synchronously blend startup Id to closed-loop Id.
MCS_FO_HANDOVER_TRANSITION_MS = 100.0;

% Maximum post-handover synchronous-speed deviation from the continuing I/F reference before fallback qualification.
MCS_FO_LOSS_SPEED_ERR_PU = 0.15;

% Post-handover observer-loss debounce time. A confirmed loss latches I/F fallback until controllers are cleared.
MCS_FO_LOSS_DEBOUNCE_MS = 20.0;

% Maximum DC Bus Voltage
MCS_MAX_DC_BUS_VOLTAGE_V = MCS_NOMINAL_DC_BUS_VOLTAGE_V * 1.2;

% Minimum DC Bus Voltage
MCS_MIN_DC_BUS_VOLTAGE_V = MCS_NOMINAL_DC_BUS_VOLTAGE_V * 0.2;

% Maximum Shutdown Current
MCS_MAX_SHUTDOWN_CURRENT_A = 10.0;

% CiA402 Enable Delay
MCS_CIA402_OPERATION_ENABLE_DELAY_MS = 0;

%% SDPE project summary
fprintf('\n============================================================\n');
fprintf('SDPE Project : %s\n', 'MCS ACIM NT Common Controller Settings');
fprintf('Project ID   : %s\n', 'mcs_acim_nt_common');
fprintf('Suite        : %s\n', 'mcs_acim_nt');
fprintf('Version      : %s\n', '0.1.0');
fprintf('Hardware (0):\n');
fprintf('Common requirements (0):\n');
fprintf('Enabled variables (62):\n');
fprintf('  BUILD_LEVEL = '); disp(BUILD_LEVEL);
fprintf('  CONTROLLER_FREQUENCY = '); disp(CONTROLLER_FREQUENCY);
fprintf('  CTRL_SPEED_RPM_BASE = '); disp(CTRL_SPEED_RPM_BASE);
fprintf('  ENABLE_ACIM_DECOUPLING = '); disp(ENABLE_ACIM_DECOUPLING);
fprintf('  MCS_ACIM_FEEDBACK_MODE = '); disp(MCS_ACIM_FEEDBACK_MODE);
fprintf('  MCS_ACIM_NT_COMMON_SDPE_PROJECT_ID = '); disp(MCS_ACIM_NT_COMMON_SDPE_PROJECT_ID);
fprintf('  MCS_ACIM_NT_COMMON_SDPE_PROJECT_SUITE = '); disp(MCS_ACIM_NT_COMMON_SDPE_PROJECT_SUITE);
fprintf('  MCS_ACIM_NT_COMMON_SDPE_PROJECT_UPDATED_AT = '); disp(MCS_ACIM_NT_COMMON_SDPE_PROJECT_UPDATED_AT);
fprintf('  MCS_ACIM_NT_COMMON_SDPE_PROJECT_VERSION = '); disp(MCS_ACIM_NT_COMMON_SDPE_PROJECT_VERSION);
fprintf('  MCS_CIA402_OPERATION_ENABLE_DELAY_MS = '); disp(MCS_CIA402_OPERATION_ENABLE_DELAY_MS);
fprintf('  MCS_COMMISSIONING_ID_REF_A = '); disp(MCS_COMMISSIONING_ID_REF_A);
fprintf('  MCS_COMMISSIONING_IQ_REF_A = '); disp(MCS_COMMISSIONING_IQ_REF_A);
fprintf('  MCS_COMMISSIONING_SPEED_REF_RPM = '); disp(MCS_COMMISSIONING_SPEED_REF_RPM);
fprintf('  MCS_ENCODER_SPEED_FILTER_FC_HZ = '); disp(MCS_ENCODER_SPEED_FILTER_FC_HZ);
fprintf('  MCS_FO_ACQUIRE_FREQ_HZ = '); disp(MCS_FO_ACQUIRE_FREQ_HZ);
fprintf('  MCS_FO_ATO_BW_HZ = '); disp(MCS_FO_ATO_BW_HZ);
fprintf('  MCS_FO_COMMAND_VOLTAGE_SCALE = '); disp(MCS_FO_COMMAND_VOLTAGE_SCALE);
fprintf('  MCS_FO_COMP_BW_HZ = '); disp(MCS_FO_COMP_BW_HZ);
fprintf('  MCS_FO_FAULT_TIME_MS = '); disp(MCS_FO_FAULT_TIME_MS);
fprintf('  MCS_FO_HANDOVER_ANGLE_ERR_PU = '); disp(MCS_FO_HANDOVER_ANGLE_ERR_PU);
fprintf('  MCS_FO_HANDOVER_DEBOUNCE_MS = '); disp(MCS_FO_HANDOVER_DEBOUNCE_MS);
fprintf('  MCS_FO_HANDOVER_FREQ_HZ = '); disp(MCS_FO_HANDOVER_FREQ_HZ);
fprintf('  MCS_FO_HANDOVER_SPEED_ERR_PU = '); disp(MCS_FO_HANDOVER_SPEED_ERR_PU);
fprintf('  MCS_FO_HANDOVER_SPEED_EXIT_ERR_PU = '); disp(MCS_FO_HANDOVER_SPEED_EXIT_ERR_PU);
fprintf('  MCS_FO_HANDOVER_TRANSITION_MS = '); disp(MCS_FO_HANDOVER_TRANSITION_MS);
fprintf('  MCS_FO_LOSS_DEBOUNCE_MS = '); disp(MCS_FO_LOSS_DEBOUNCE_MS);
fprintf('  MCS_FO_LOSS_SPEED_ERR_PU = '); disp(MCS_FO_LOSS_SPEED_ERR_PU);
fprintf('  MCS_FO_RUN_COMP_BW_HZ = '); disp(MCS_FO_RUN_COMP_BW_HZ);
fprintf('  MCS_FO_VM_LEAK_HZ = '); disp(MCS_FO_VM_LEAK_HZ);
fprintf('  MCS_FO_VOLTAGE_SOURCE = '); disp(MCS_FO_VOLTAGE_SOURCE);
fprintf('  MCS_MAGNETIZING_TIME_MS = '); disp(MCS_MAGNETIZING_TIME_MS);
fprintf('  MCS_MAX_CIR_SATURATION_VOLTAGE_V = '); disp(MCS_MAX_CIR_SATURATION_VOLTAGE_V);
fprintf('  MCS_MAX_DC_BUS_VOLTAGE_V = '); disp(MCS_MAX_DC_BUS_VOLTAGE_V);
fprintf('  MCS_MAX_RECT_SATURATION_VOLTAGE_V = '); disp(MCS_MAX_RECT_SATURATION_VOLTAGE_V);
fprintf('  MCS_MAX_SHUTDOWN_CURRENT_A = '); disp(MCS_MAX_SHUTDOWN_CURRENT_A);
fprintf('  MCS_MECH_CURRENT_LIMIT_A = '); disp(MCS_MECH_CURRENT_LIMIT_A);
fprintf('  MCS_MECH_POSITION_KI_PU_S = '); disp(MCS_MECH_POSITION_KI_PU_S);
fprintf('  MCS_MECH_POSITION_KP_PU = '); disp(MCS_MECH_POSITION_KP_PU);
fprintf('  MCS_MECH_SPEED_LIMIT_RPM = '); disp(MCS_MECH_SPEED_LIMIT_RPM);
fprintf('  MCS_MECH_SPEED_SLOPE_RPM_S = '); disp(MCS_MECH_SPEED_SLOPE_RPM_S);
fprintf('  MCS_MECH_VELOCITY_KI_PU_S = '); disp(MCS_MECH_VELOCITY_KI_PU_S);
fprintf('  MCS_MECH_VELOCITY_KP_PU = '); disp(MCS_MECH_VELOCITY_KP_PU);
fprintf('  MCS_MIN_DC_BUS_VOLTAGE_V = '); disp(MCS_MIN_DC_BUS_VOLTAGE_V);
fprintf('  MCS_NOMINAL_DC_BUS_VOLTAGE_V = '); disp(MCS_NOMINAL_DC_BUS_VOLTAGE_V);
fprintf('  MCS_OPEN_LOOP_FREQ_HZ = '); disp(MCS_OPEN_LOOP_FREQ_HZ);
fprintf('  MCS_OPEN_LOOP_FREQ_SLOPE_HZ_S = '); disp(MCS_OPEN_LOOP_FREQ_SLOPE_HZ_S);
fprintf('  MCS_OPEN_LOOP_VD_REF_V = '); disp(MCS_OPEN_LOOP_VD_REF_V);
fprintf('  MCS_OPEN_LOOP_VQ_REF_V = '); disp(MCS_OPEN_LOOP_VQ_REF_V);
fprintf('  MCS_PWM_DEADTIME_COMP_CURRENT_DEADBAND_A = '); disp(MCS_PWM_DEADTIME_COMP_CURRENT_DEADBAND_A);
fprintf('  MCS_PWM_DEADTIME_COMP_CURRENT_HYSTERESIS_A = '); disp(MCS_PWM_DEADTIME_COMP_CURRENT_HYSTERESIS_A);
fprintf('  MCS_SENSORLESS_HANDOVER_ID_REF_A = '); disp(MCS_SENSORLESS_HANDOVER_ID_REF_A);
fprintf('  MCS_SENSORLESS_STARTUP_ID_REF_A = '); disp(MCS_SENSORLESS_STARTUP_ID_REF_A);
fprintf('  MCS_STARTUP_ID_FADE_END_HZ = '); disp(MCS_STARTUP_ID_FADE_END_HZ);
fprintf('  MCS_STARTUP_ID_FADE_START_HZ = '); disp(MCS_STARTUP_ID_FADE_START_HZ);
fprintf('  MOTOR_PARAM_L1R = '); disp(MOTOR_PARAM_L1R);
fprintf('  MOTOR_PARAM_L1S = '); disp(MOTOR_PARAM_L1S);
fprintf('  MOTOR_PARAM_LM = '); disp(MOTOR_PARAM_LM);
fprintf('  MOTOR_PARAM_MAX_SPEED = '); disp(MOTOR_PARAM_MAX_SPEED);
fprintf('  MOTOR_PARAM_POLE_PAIRS = '); disp(MOTOR_PARAM_POLE_PAIRS);
fprintf('  MOTOR_PARAM_RATED_FREQUENCY = '); disp(MOTOR_PARAM_RATED_FREQUENCY);
fprintf('  MOTOR_PARAM_RR = '); disp(MOTOR_PARAM_RR);
fprintf('  MOTOR_PARAM_RS = '); disp(MOTOR_PARAM_RS);
fprintf('Disabled macros (2):\n');
fprintf('  - ENABLE_MOTOR_FAULT_PROTECTION\n');
fprintf('  - ENABLE_PWM_DEADTIME_COMPENSATION\n');
fprintf('============================================================\n');

%% Local helpers
function value = sdpe_select(condition, true_value, false_value)
if condition
    value = true_value;
else
    value = false_value;
end
end
