"""C header generator for SDPE v2."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .library import SDPELibrary
from .model import ComponentRef, HardwareEntity, HardwareSchema, SDPEError
from .util import c_literal, header_guard, macro_name, read_json, write_if_changed


@dataclass(frozen=True)
class GeneratedFile:
    """Generated file metadata."""

    path: Path
    changed: bool


class HeaderGenerator:
    """Generate hardware entity and project binding headers."""

    def __init__(self, library: SDPELibrary, out_dir: Path, include_prefix: str = "ctl/component"):
        self.library = library
        self.out_dir = out_dir
        self.include_prefix = include_prefix.strip("/")

    def generate_entity_tree(self, entity_id: str) -> list[GeneratedFile]:
        """Generate headers for an entity and every referenced non-inline child."""

        entity = self.library.entity(entity_id)
        generated: list[GeneratedFile] = []
        visited: set[str] = set()

        def walk(node: HardwareEntity) -> None:
            for comp in node.components.values():
                if not comp.inline:
                    walk(comp.entity)
            if not node.inline and node.id not in visited:
                visited.add(node.id)
                path = self.entity_header_path(node)
                changed = write_if_changed(path, self.render_entity_header(node))
                generated.append(GeneratedFile(path, changed))

        walk(entity)
        return generated

    def generate_all_entities(self) -> list[GeneratedFile]:
        """Generate all entity headers in the library."""

        generated: list[GeneratedFile] = []
        seen: set[Path] = set()
        for entity_id in sorted(self.library.entity_files):
            for item in self.generate_entity_tree(entity_id):
                if item.path not in seen:
                    seen.add(item.path)
                    generated.append(item)
        return generated

    def entity_header_path(self, entity: HardwareEntity) -> Path:
        """Return the output header path for an entity."""

        schema = self.library.schema(entity.schema_id)
        subdir = entity.output_subdir or schema.output_subdir or schema.id
        return self.out_dir / "hardware_preset" / subdir / f"{entity.id}.h"

    def entity_include_path(self, entity: HardwareEntity) -> str:
        """Return generated include path relative to the output root."""

        path = self.entity_header_path(entity)
        rel = path.relative_to(self.out_dir).as_posix()
        if self.include_prefix:
            return f"{self.include_prefix}/{rel}"
        return rel

    def render_entity_header(self, entity: HardwareEntity) -> str:
        """Render a hardware entity header."""

        schema = self.library.schema(entity.schema_id)
        rel = self.entity_header_path(entity).relative_to(self.out_dir).as_posix()
        guard = header_guard(rel)
        prefix = self.prefix(entity, schema)
        includes = self._entity_includes(entity, schema)

        lines: list[str] = []
        lines.extend(
            [
                "/**",
                f" * @file {entity.id}.h",
                f" * @brief SDPE hardware preset for {entity.display_name or entity.id}.",
                " * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.",
                " */",
                "",
                f"#ifndef {guard}",
                f"#define {guard}",
                "",
            ]
        )
        for inc in includes:
            lines.append(f"#include <{inc}>")
        if includes:
            lines.append("")
        self._append_code_section(lines, schema, entity, "after_includes", "User code after includes")
        lines.extend(
            [
                "#ifdef __cplusplus",
                'extern "C"',
                "{",
                "#endif",
                "",
                "/**",
                f" * @defgroup sdpe_{entity.id} {entity.display_name or entity.id}",
                " * @{",
                " */",
                "",
                "// Identification",
                f"#define {prefix}_ID \"{entity.id}\"",
                f"#define {prefix}_SCHEMA \"{schema.id}\"",
                f"#define {prefix}_NAME \"{entity.display_name or entity.id}\"",
                "",
            ]
        )

        tags = sorted(dict.fromkeys([*schema.tags, *entity.tags]))
        if tags:
            lines.append(f"// Tags: {', '.join(tags)}")
            lines.append("")

        if schema.description or entity.description or entity.vendor or entity.datasheet_url or entity.document_url:
            lines.append("/*")
            if schema.description:
                lines.append(f" * Schema: {schema.description}")
            if entity.description:
                lines.append(f" * Entity: {entity.description}")
            if entity.vendor:
                lines.append(f" * Vendor: {entity.vendor}")
            if entity.datasheet_url:
                lines.append(f" * Datasheet: {entity.datasheet_url}")
            if entity.document_url:
                lines.append(f" * Document: {entity.document_url}")
            lines.append(" */")
            lines.append("")

        self._append_code_section(lines, schema, entity, "before_parameters", "User code before parameters")
        self._append_parameter_macros(lines, entity, schema, prefix)
        self._append_derived_macros(lines, entity, schema, prefix)
        self._append_inline_components(lines, entity)
        self._append_component_overrides(lines, entity, schema)
        self._append_code_section(lines, schema, entity, "before_exports", "User code before exports")
        self._append_export_comments(lines, schema, prefix)
        self._append_code_section(lines, schema, entity, "before_footer", "User code before footer")

        lines.extend(
            [
                "/** @} */",
                "",
                "#ifdef __cplusplus",
                "}",
                "#endif",
                "",
                f"#endif // {guard}",
                "",
            ]
        )
        return "\n".join(lines)

    def _entity_includes(self, entity: HardwareEntity, schema: HardwareSchema) -> list[str]:
        includes = [*schema.includes, *entity.includes]
        for comp in entity.components.values():
            if not comp.inline:
                includes.append(self.entity_include_path(comp.entity))
        return sorted(dict.fromkeys(includes))

    def _append_code_section(
        self, lines: list[str], schema: HardwareSchema, entity: HardwareEntity, name: str, title: str
    ) -> None:
        snippets: list[str] = []
        snippets.extend(self._code_section_values(schema.code_sections.get(name)))
        snippets.extend(self._code_section_values(entity.code_sections.get(name)))
        if not snippets:
            return
        lines.append(f"// {title}")
        for snippet in snippets:
            if snippet.strip():
                lines.extend(snippet.rstrip().splitlines())
        lines.append("")

    def _code_section_values(self, value: Any) -> list[str]:
        if value is None:
            return []
        if isinstance(value, str):
            return [value]
        if isinstance(value, list):
            return [str(item) for item in value if str(item).strip()]
        return [str(value)]

    def _append_parameter_macros(
        self, lines: list[str], entity: HardwareEntity, schema: HardwareSchema, prefix: str
    ) -> None:
        if not schema.parameters:
            return
        lines.append("// Parameter macros")
        for pname, pspec in schema.parameters.items():
            found, value = self._entity_parameter_value(entity, pname, pspec.c_name)
            if found:
                pass
            elif pspec.default is not None:
                value = pspec.default
            elif pspec.required:
                raise SDPEError(f"Entity {entity.id} misses required parameter '{pname}'.")
            else:
                continue
            macro = f"{prefix}_{pspec.c_name}"
            desc = pspec.description or pname
            lines.extend(
                [
                    "/**",
                    f" * @brief {desc}",
                ]
            )
            if pspec.unit:
                lines.append(f" * @unit {pspec.unit}")
            lines.extend(
                [
                    " */",
                    f"#ifndef {macro}",
                    f"#define {macro} {self._format_parameter_value(value, pspec.value_format, entity, prefix)}",
                    f"#endif // {macro}",
                    "",
                ]
            )

    def _append_derived_macros(
        self, lines: list[str], entity: HardwareEntity, schema: HardwareSchema, prefix: str
    ) -> None:
        if not schema.derived_macros:
            return
        lines.append("// Derived macros")
        for item in schema.derived_macros:
            macro = f"{prefix}_{item.name}"
            expr = self._format_expr(item.expr, prefix)
            lines.extend(
                [
                    "/**",
                    f" * @brief {item.description or item.name}",
                ]
            )
            if item.unit:
                lines.append(f" * @unit {item.unit}")
            lines.extend([" */", f"#define {macro} {expr}", ""])

    def _append_inline_components(self, lines: list[str], entity: HardwareEntity) -> None:
        inline_components = [comp for comp in entity.components.values() if comp.inline]
        if not inline_components:
            return
        lines.append("// Inline component macros")
        for comp in inline_components:
            child_schema = self.library.schema(comp.entity.schema_id)
            lines.append(f"// Inline component: {comp.slot} ({child_schema.display_name})")
            self._append_parameter_macros(lines, comp.entity, child_schema, self.prefix(comp.entity, child_schema))
            self._append_derived_macros(lines, comp.entity, child_schema, self.prefix(comp.entity, child_schema))
            if comp.overrides:
                self._append_component_override_macros(lines, comp, entity, self.library.schema(entity.schema_id))

    def _append_component_overrides(
        self, lines: list[str], entity: HardwareEntity, schema: HardwareSchema
    ) -> None:
        if not entity.components:
            return
        override_components = [comp for comp in entity.components.values() if comp.overrides and not comp.inline]
        if not override_components:
            return
        lines.append("// Component local override macros")
        for comp in override_components:
            self._append_component_override_macros(lines, comp, entity, schema)

    def _append_component_override_macros(
        self, lines: list[str], comp: ComponentRef, parent: HardwareEntity, parent_schema: HardwareSchema
    ) -> None:
        child_schema = self.library.schema(comp.entity.schema_id)
        parent_prefix = self.prefix(parent, parent_schema)
        slot_prefix = f"{parent_prefix}_{macro_name(comp.slot)}"
        child_prefix = self.prefix(comp.entity, child_schema)
        lines.append(f"// Local overrides for {comp.slot}")
        for pname, pspec in child_schema.parameters.items():
            macro = f"{slot_prefix}_{pspec.c_name}"
            found_override, override_value = self._parameter_mapping_value(comp.overrides, pname, pspec.c_name)
            if found_override:
                value = self._format_parameter_value(override_value, pspec.value_format, parent, parent_prefix)
            else:
                target = f"{child_prefix}_{pspec.c_name}"
                value = target
            lines.append(f"#define {macro} {value}")
        for item in child_schema.derived_macros:
            macro = f"{slot_prefix}_{item.name}"
            expr = self._format_expr(item.expr, slot_prefix)
            lines.append(f"#define {macro} {expr}")
        lines.append("")

    def _append_export_comments(self, lines: list[str], schema: HardwareSchema, prefix: str) -> None:
        if not schema.exports:
            return
        lines.append("// Logical exports")
        for name, export in schema.exports.items():
            lines.append(f"// {name}: {self._format_expr(export.macro, prefix)}")
        lines.append("")

    def _format_expr(self, expr: str, prefix: str) -> str:
        return expr.replace("{PREFIX}", prefix)

    def _format_parameter_value(
        self, value: Any, value_format: str, entity: HardwareEntity, prefix: str
    ) -> str:
        if isinstance(value, dict):
            if "literal" in value:
                return str(value["literal"])
            if "macro" in value:
                return str(value["macro"])
            if "ref" in value:
                return self._resolve_entity_symbol(entity, prefix, str(value["ref"]))
            if "export" in value:
                return self._resolve_entity_symbol(entity, prefix, str(value["export"]))
            if "expr" in value:
                return self._format_local_expr(str(value["expr"]), entity, prefix)
            raise SDPEError(f"Unsupported parameter value object: {value!r}")
        return c_literal(value, value_format)

    def _format_local_expr(self, expr: str, entity: HardwareEntity, prefix: str) -> str:
        def replace(match: re.Match[str]) -> str:
            token = match.group(1)
            if token == "PREFIX":
                return prefix
            return self._resolve_entity_symbol(entity, prefix, token)

        return re.sub(r"\{([A-Za-z0-9_][A-Za-z0-9_.]*)\}", replace, expr)

    def prefix(self, entity: HardwareEntity, schema: HardwareSchema) -> str:
        """Resolve macro prefix for an entity."""

        if entity.macro_prefix:
            return entity.macro_prefix
        if schema.header_prefix:
            return f"{schema.header_prefix}_{macro_name(entity.id)}"
        return macro_name(entity.id)

    def _component_effective_prefix(
        self, parent: HardwareEntity, parent_schema: HardwareSchema, comp: ComponentRef
    ) -> str:
        child_schema = self.library.schema(comp.entity.schema_id)
        if not comp.overrides:
            return self.prefix(comp.entity, child_schema)
        return f"{self.prefix(parent, parent_schema)}_{macro_name(comp.slot)}"

    def generate_project(self, project_path: Path) -> list[GeneratedFile]:
        """Generate a project binding header."""

        data = read_json(project_path)
        generated: list[GeneratedFile] = []
        seen: set[Path] = set()
        included_entities = self._project_entity_ids(data)
        for entity_id in included_entities:
            for item in self.generate_entity_tree(entity_id):
                if item.path not in seen:
                    seen.add(item.path)
                    generated.append(item)

        header_name = data.get("output_header", "sdpe_project_bindings.h")
        out_path = self.out_dir / "project" / header_name
        changed = write_if_changed(out_path, self.render_project_header(data))
        generated.append(GeneratedFile(out_path, changed))
        return generated

    def render_project_header(self, data: dict[str, Any]) -> str:
        """Render project requirement binding header."""

        project_id = data.get("id", "sdpe_project")
        guard = header_guard(f"project/{data.get('output_header', 'sdpe_project_bindings.h')}")
        hardware_ids = self._project_entity_ids(data)
        includes = [self.entity_include_path(self.library.entity(entity_id)) for entity_id in hardware_ids]

        lines = [
            "/**",
            f" * @file {data.get('output_header', 'sdpe_project_bindings.h')}",
            f" * @brief SDPE project bindings for {data.get('display_name', project_id)}.",
            " */",
            "",
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
        ]
        for inc in sorted(dict.fromkeys(includes)):
            lines.append(f"#include <{inc}>")
        if includes:
            lines.append("")

        lines.extend(["// Project metadata", f"#define SDPE_PROJECT_ID \"{project_id}\""])
        if "suite" in data:
            lines.append(f"#define SDPE_PROJECT_SUITE \"{data['suite']}\"")
        lines.append("")

        lines.append("// Requirement bindings")
        for req in data.get("requirements", []):
            macro = req["macro"]
            value = self._resolve_binding_value(req["binding"])
            desc = req.get("description", req.get("role", macro))
            lines.extend(["/**", f" * @brief {desc}", " */", f"#define {macro} {value}", ""])

        if data.get("peripheral_bindings"):
            lines.append("// Board peripheral mapping")
            for macro, value in data["peripheral_bindings"].items():
                lines.append(f"#define {macro} {value}")
            lines.append("")

        if data.get("global_macros"):
            lines.append("// Global project macros")
            for macro, value in data["global_macros"].items():
                lines.append(f"#define {macro} {value}")
            lines.append("")

        lines.extend([f"#endif // {guard}", ""])
        return "\n".join(lines)

    def _project_entity_ids(self, data: dict[str, Any]) -> list[str]:
        ids = [item["entity"] for item in data.get("hardware", [])]
        for req in data.get("requirements", []):
            binding = req.get("binding")
            export_path = None
            if isinstance(binding, dict):
                export_path = binding.get("export")
            elif isinstance(binding, str) and "." in binding:
                export_path = binding
            if export_path:
                root_id = export_path.split(".", 1)[0]
                if root_id in self.library.entity_files:
                    ids.append(root_id)
        return list(dict.fromkeys(ids))

    def _resolve_binding_value(self, binding: Any) -> str:
        if isinstance(binding, dict):
            if "literal" in binding:
                return str(binding["literal"])
            if "macro" in binding:
                return str(binding["macro"])
            if "export" in binding:
                return self._resolve_export(binding["export"])
        if isinstance(binding, str):
            if "." in binding:
                return self._resolve_export(binding)
            return binding
        raise SDPEError(f"Unsupported binding: {binding!r}")

    def _resolve_export(self, export_path: str) -> str:
        parts = export_path.split(".")
        if len(parts) < 2:
            raise SDPEError(f"Export binding must look like entity.export or entity.slot.export: {export_path}")
        entity = self.library.entity(parts[0])
        current = entity
        current_schema = self.library.schema(current.schema_id)
        current_prefix = self.prefix(current, current_schema)
        for slot in parts[1:-1]:
            if slot not in current.components:
                raise SDPEError(f"Entity {current.id} has no component slot '{slot}' in binding {export_path}")
            comp = current.components[slot]
            current_prefix = self._component_effective_prefix(current, self.library.schema(current.schema_id), comp)
            current = comp.entity
        export_name = parts[-1]
        schema = self.library.schema(current.schema_id)
        if export_name in schema.exports:
            export = schema.exports[export_name]
            return self._format_expr(export.macro, current_prefix)
        pspec = self._parameter_spec_by_symbol(schema, export_name)
        if pspec is not None:
            return f"{current_prefix}_{pspec.c_name}"
        for item in schema.derived_macros:
            if export_name == item.name or export_name.lower() == item.name.lower():
                return f"{current_prefix}_{item.name}"
        raise SDPEError(f"Schema {schema.id} has no export or parameter '{export_name}' in binding {export_path}")

    def _resolve_entity_symbol(self, entity: HardwareEntity, root_prefix: str, path: str) -> str:
        parts = path.split(".")
        if not parts:
            raise SDPEError(f"Empty entity symbol path for {entity.id}")
        current = entity
        current_prefix = root_prefix
        for slot in parts[:-1]:
            if slot not in current.components:
                raise SDPEError(f"Entity {current.id} has no component slot '{slot}' in symbol {path}")
            comp = current.components[slot]
            current_prefix = self._component_effective_prefix(current, self.library.schema(current.schema_id), comp)
            current = comp.entity
        name = parts[-1]
        schema = self.library.schema(current.schema_id)
        if name in schema.exports:
            return self._format_expr(schema.exports[name].macro, current_prefix)
        pspec = self._parameter_spec_by_symbol(schema, name)
        if pspec is not None:
            return f"{current_prefix}_{pspec.c_name}"
        for item in schema.derived_macros:
            if name == item.name or name.lower() == item.name.lower():
                return f"{current_prefix}_{item.name}"
        raise SDPEError(f"Schema {schema.id} has no export, parameter, or derived macro '{name}' in symbol {path}")

    def _entity_parameter_value(self, entity: HardwareEntity, pname: str, c_name: str) -> tuple[bool, Any]:
        return self._parameter_mapping_value(entity.parameters, pname, c_name)

    def _parameter_mapping_value(self, values: dict[str, Any], pname: str, c_name: str) -> tuple[bool, Any]:
        if pname in values:
            return True, values[pname]
        c_key = c_name.lower()
        if c_key in values:
            return True, values[c_key]
        normalized = c_key.replace("__", "_")
        for key, value in values.items():
            if key.lower() == normalized:
                return True, value
        return False, None

    def _parameter_spec_by_symbol(self, schema: HardwareSchema, name: str):
        if name in schema.parameters:
            return schema.parameters[name]
        key = name.lower()
        for pspec in schema.parameters.values():
            if pspec.c_name.lower() == key:
                return pspec
        return None
