/**
 * @file xplt.peripheral.c
 * @brief Portable C2000 LaunchPad binding for UART, ADC ISR and user LED.
 */

#include <gmp_core.h>

#include "user_main.h"
#include <xplt.peripheral.h>
#include <launchpad_board.h>

#ifndef XPLT_DL_BAUD_RATE
#define XPLT_DL_BAUD_RATE 115200UL
#endif

#define XPLT_DL_RX_FIFO_LEVEL SCI_FIFO_RX8
#define XPLT_DL_LOCAL_RX_SIZE 16U

#if XPLT_DL_BAUD_RATE > 500000UL
#define XPLT_DL_LSPCLK_HZ (DEVICE_SYSCLK_FREQ / 2UL)
#else
#define XPLT_DL_LSPCLK_HZ DEVICE_LSPCLK_FREQ
#endif

static gmp_datalink_t* bound_datalink;
#if LAUNCHPAD_CAN_CLASSIC
static volatile uint16_t can_last_rx[8];
static volatile uint32_t can_rx_count;
#endif

/** @brief SCIA receive FIFO interrupt handler. */
__interrupt void xplt_scia_rx_isr(void);

/** @brief ADC control interrupt generated by SysConfig. */
__interrupt void MainISR(void);

/**
 * @brief Drain all currently buffered SCIA characters into the Data Link FIFO.
 * @details Each C28x character occupies one native 16-bit data unit while only
 * the low eight bits are part of the wire protocol.
 */
static void xplt_dl_drain_rx_fifo(void)
{
    byte_gt local_buffer[XPLT_DL_LOCAL_RX_SIZE];
    size_gt count;
    size_gt index;

    if (bound_datalink == NULL)
    {
        while (SCI_getRxFIFOStatus(LAUNCHXL_UART_USB_BASE) != SCI_FIFO_RX0)
            (void)SCI_readCharNonBlocking(LAUNCHXL_UART_USB_BASE);
        return;
    }

    do
    {
        count = (size_gt)SCI_getRxFIFOStatus(LAUNCHXL_UART_USB_BASE);
        if (count > XPLT_DL_LOCAL_RX_SIZE)
            count = XPLT_DL_LOCAL_RX_SIZE;
        for (index = 0U; index < count; ++index)
            local_buffer[index] = (byte_gt)(SCI_readCharNonBlocking(LAUNCHXL_UART_USB_BASE) & 0x00FFU);
        if (count > 0U)
            gmp_dev_dl_push_str(bound_datalink, local_buffer, count);
    } while (SCI_getRxFIFOStatus(LAUNCHXL_UART_USB_BASE) != SCI_FIFO_RX0);
}

/** @brief Configure SCIA for the LaunchPad XDS110 Application/User UART. */
static void xplt_configure_scia(void)
{
#if XPLT_DL_BAUD_RATE > 500000UL
    /* A 50 MHz LSPCLK minimizes the F280049C divider error at 921600 baud. */
    SysCtl_setLowSpeedClock(SYSCTL_LSPCLK_PRESCALE_2);
#endif

    SCI_performSoftwareReset(LAUNCHXL_UART_USB_BASE);
    SCI_setConfig(LAUNCHXL_UART_USB_BASE, XPLT_DL_LSPCLK_HZ, XPLT_DL_BAUD_RATE,
                  SCI_CONFIG_WLEN_8 | SCI_CONFIG_STOP_ONE | SCI_CONFIG_PAR_NONE);
#if XPLT_DL_BAUD_RATE == 921600UL
    /* Force BRR=6: 50 MHz / (8 * (6 + 1)) = 892857 baud. */
    HWREGH(LAUNCHXL_UART_USB_BASE + SCI_O_HBAUD) = 0U;
    HWREGH(LAUNCHXL_UART_USB_BASE + SCI_O_LBAUD) = 6U;
#endif
    SCI_resetChannels(LAUNCHXL_UART_USB_BASE);
    SCI_enableFIFO(LAUNCHXL_UART_USB_BASE);
    SCI_setFIFOInterruptLevel(LAUNCHXL_UART_USB_BASE, SCI_FIFO_TX0, XPLT_DL_RX_FIFO_LEVEL);
    SCI_clearInterruptStatus(LAUNCHXL_UART_USB_BASE, SCI_INT_RXFF | SCI_INT_TXFF | SCI_INT_RXERR);
    SCI_enableInterrupt(LAUNCHXL_UART_USB_BASE, SCI_INT_RXFF | SCI_INT_RXERR);
    SCI_enableModule(LAUNCHXL_UART_USB_BASE);
    SCI_performSoftwareReset(LAUNCHXL_UART_USB_BASE);
}

void setup_peripheral(void)
{
    debug_uart = NULL;
    bound_datalink = NULL;

    GPIO_writePin(LAUNCHPAD_USER_LED_GPIO, 1U);

    xplt_configure_scia();
    Interrupt_register(INT_LAUNCHXL_UART_USB_RX, &xplt_scia_rx_isr);
    Interrupt_enable(INT_LAUNCHXL_UART_USB_RX);
    Interrupt_clearACKGroup(INT_LAUNCHXL_UART_USB_RX_INTERRUPT_ACK_GROUP);
}

void xplt_dl_bind(gmp_datalink_t* datalink)
{
    bound_datalink = datalink;
}

void xplt_dl_poll_rx(void)
{
    Interrupt_disable(INT_LAUNCHXL_UART_USB_RX);
    xplt_dl_drain_rx_fifo();
    SCI_clearInterruptStatus(LAUNCHXL_UART_USB_BASE, SCI_INT_RXFF);
    Interrupt_enable(INT_LAUNCHXL_UART_USB_RX);
}

void xplt_dl_start_tx(gmp_datalink_t* datalink)
{
    SCI_writeCharArray(LAUNCHXL_UART_USB_BASE,
                       (const uint16_t*)gmp_dev_dl_get_tx_hw_hdr_ptr(datalink),
                       (uint16_t)gmp_dev_dl_get_tx_hw_hdr_size(datalink));
    if (gmp_dev_dl_get_tx_hw_pld_size(datalink) > 0U)
    {
        SCI_writeCharArray(LAUNCHXL_UART_USB_BASE,
                           (const uint16_t*)gmp_dev_dl_get_tx_hw_pld_ptr(datalink),
                           (uint16_t)gmp_dev_dl_get_tx_hw_pld_size(datalink));
    }
    while (SCI_isTransmitterBusy(LAUNCHXL_UART_USB_BASE))
    {
    }
    gmp_dev_dl_tx_state_done(datalink);
}

void xplt_start_sample_timer(void)
{
    Interrupt_enable(INT_BOOSTXL_ADCA_1);
}

void xplt_toggle_user_led(void)
{
    GPIO_togglePin(LAUNCHPAD_USER_LED_GPIO);
}

void xplt_can_service(void)
{
#if LAUNCHPAD_CAN_CLASSIC
    static time_gt last_tx_tick;
    time_gt now = gmp_base_get_system_tick();

    if ((time_gt)(now - last_tx_tick) >= 100U)
    {
        uint16_t payload[4];
        uint16_t pwm_value = (uint16_t)((float)launchpad_output_pu * 4095.0F);
        payload[0] = launchpad_adc_raw & 0x00FFU;
        payload[1] = (launchpad_adc_raw >> 8U) & 0x00FFU;
        payload[2] = pwm_value & 0x00FFU;
        payload[3] = (pwm_value >> 8U) & 0x00FFU;
        CAN_sendMessage(LAUNCHPAD_CAN_BASE, 4U, 4U, payload);
        last_tx_tick = now;
    }
#elif LAUNCHPAD_CAN_MCAN
    /* MCAN targets bind the same service contract in their board-specific port. */
#endif
}

/** @brief Drain the receive FIFO whenever at least eight characters are ready. */
__interrupt void xplt_scia_rx_isr(void)
{
    xplt_dl_drain_rx_fifo();
    if ((SCI_getRxStatus(LAUNCHXL_UART_USB_BASE) & SCI_RXSTATUS_OVERRUN) != 0U)
    {
        SCI_clearOverflowStatus(LAUNCHXL_UART_USB_BASE);
        SCI_resetRxFIFO(LAUNCHXL_UART_USB_BASE);
    }
    SCI_clearInterruptStatus(LAUNCHXL_UART_USB_BASE, SCI_INT_RXFF | SCI_INT_RXERR);
    Interrupt_clearACKGroup(INT_LAUNCHXL_UART_USB_RX_INTERRUPT_ACK_GROUP);
}

#if LAUNCHPAD_CAN_CLASSIC
/** @brief Receive command frame 0x101 and acknowledge classic CAN interrupts. */
__interrupt void INT_LAUNCHXL_CAN_0_ISR(void)
{
    uint32_t cause = CAN_getInterruptCause(LAUNCHPAD_CAN_BASE);
    if (cause == 1U)
    {
        CAN_readMessage(LAUNCHPAD_CAN_BASE, 1U, (uint16_t*)can_last_rx);
        CAN_clearInterruptStatus(LAUNCHPAD_CAN_BASE, 1U);
        can_rx_count++;
    }
    else if (cause != 0U && cause != CAN_INT_INT0ID_STATUS)
    {
        CAN_clearInterruptStatus(LAUNCHPAD_CAN_BASE, cause);
    }
    CAN_clearGlobalInterruptStatus(LAUNCHPAD_CAN_BASE,
                                   CAN_GLOBAL_INT_CANINT0);
    Interrupt_clearACKGroup(INT_LAUNCHXL_CAN_0_INTERRUPT_ACK_GROUP);
}

__interrupt void INT_LAUNCHXL_CAN_1_ISR(void)
{
    CAN_clearGlobalInterruptStatus(LAUNCHPAD_CAN_BASE,
                                   CAN_GLOBAL_INT_CANINT1);
    Interrupt_clearACKGroup(INT_LAUNCHXL_CAN_1_INTERRUPT_ACK_GROUP);
}
#endif

/** @brief Run the portable control path from the ePWM-triggered ADC interrupt. */
__interrupt void MainISR(void)
{
    gmp_base_ctl_step();
    user_dsa_timer_step();
    gmp_step_system_tick();
    ADC_clearInterruptStatus(BOOSTXL_ADCA_BASE, ADC_INT_NUMBER1);
    if (ADC_getInterruptOverflowStatus(BOOSTXL_ADCA_BASE, ADC_INT_NUMBER1))
    {
        ADC_clearInterruptOverflowStatus(BOOSTXL_ADCA_BASE, ADC_INT_NUMBER1);
        ADC_clearInterruptStatus(BOOSTXL_ADCA_BASE, ADC_INT_NUMBER1);
    }
    Interrupt_clearACKGroup(INT_BOOSTXL_ADCA_1_INTERRUPT_ACK_GROUP);
}
