/**
 * @file bsc040n10ns5.h
 * @brief SDPE hardware preset for BSC040N10NS5.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _POWER_SWITCH_BSC040N10NS5_H_
#define _POWER_SWITCH_BSC040N10NS5_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_bsc040n10ns5 BSC040N10NS5
 * @{
 */

// Identification
#define BSC040N10NS5_ID "bsc040n10ns5"
#define BSC040N10NS5_SCHEMA "power_switch"
#define BSC040N10NS5_NAME "BSC040N10NS5"

// Tags: infineon, mosfet, power_device, switch

/*
 * Schema: Power switch device used by bridge modules.
 * Vendor: Infineon
 * Datasheet: https://www.infineon.com/assets/row/public/documents/24/49/infineon-bsc040n10ns5-datasheet-en.pdf
 */

// Parameter macros
/**
 * @brief Power device part number.
 */
#define BSC040N10NS5_PART_NUMBER "BSC040N10NS5"

/**
 * @brief MOSFET, IGBT, GaN, SiC, etc.
 */
#define BSC040N10NS5_DEVICE_TYPE "MOSFET"

/**
 * @brief Drain-source or collector-emitter voltage rating.
 * @unit V
 */
#define BSC040N10NS5_VOLTAGE_RATING_V (100.0f)

/**
 * @brief Current rating.
 * @unit A
 */
#define BSC040N10NS5_CURRENT_RATING_A (120.0f)

/**
 * @brief On resistance.
 * @unit ohm
 */
#define BSC040N10NS5_RDSON_OHM (0.0034f)

/**
 * @brief Single switch, dual switch, half bridge power block, etc.
 */
#define BSC040N10NS5_CONFIGURATION "single"

/**
 * @brief Maximum on resistance at the documented gate voltage.
 * @unit ohm
 */
#define BSC040N10NS5_RDSON_MAX_OHM (0.004f)

/**
 * @brief Gate voltage associated with the resistance value.
 * @unit V
 */
#define BSC040N10NS5_GATE_VOLTAGE_V (10.0f)

/**
 * @brief Typical total gate charge.
 * @unit nC
 */
#define BSC040N10NS5_GATE_CHARGE_NC (0.0f)

/**
 * @brief Manufacturer package name.
 */
#define BSC040N10NS5_PACKAGE "SuperSO8"

// Logical exports
// voltage_rating: BSC040N10NS5_VOLTAGE_RATING_V
// current_rating: BSC040N10NS5_CURRENT_RATING_A

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _POWER_SWITCH_BSC040N10NS5_H_
