/**
 * @file csd18533q5a.h
 * @brief SDPE hardware preset for CSD18533Q5A.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _POWER_SWITCH_CSD18533Q5A_H_
#define _POWER_SWITCH_CSD18533Q5A_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_csd18533q5a CSD18533Q5A
 * @{
 */

// Identification
#define CSD18533Q5A_ID "csd18533q5a"
#define CSD18533Q5A_SCHEMA "power_switch"
#define CSD18533Q5A_NAME "CSD18533Q5A"

// Tags: mosfet, power_device, switch, ti

/*
 * Schema: Power switch device used by bridge modules.
 * Vendor: Texas Instruments
 * Datasheet: https://www.ti.com/lit/ds/symlink/csd18533q5a.pdf
 */

// Parameter macros
/**
 * @brief Power device part number.
 */
#define CSD18533Q5A_PART_NUMBER "CSD18533Q5A"

/**
 * @brief MOSFET, IGBT, GaN, SiC, etc.
 */
#define CSD18533Q5A_DEVICE_TYPE "MOSFET"

/**
 * @brief Drain-source or collector-emitter voltage rating.
 * @unit V
 */
#define CSD18533Q5A_VOLTAGE_RATING_V (60.0f)

/**
 * @brief Current rating.
 * @unit A
 */
#define CSD18533Q5A_CURRENT_RATING_A (100.0f)

/**
 * @brief On resistance.
 * @unit ohm
 */
#define CSD18533Q5A_RDSON_OHM (0.0047f)

/**
 * @brief Single switch, dual switch, half bridge power block, etc.
 */
#define CSD18533Q5A_CONFIGURATION "single"

/**
 * @brief Maximum on resistance at the documented gate voltage.
 * @unit ohm
 */
#define CSD18533Q5A_RDSON_MAX_OHM (0.0059f)

/**
 * @brief Gate voltage associated with the resistance value.
 * @unit V
 */
#define CSD18533Q5A_GATE_VOLTAGE_V (10.0f)

/**
 * @brief Typical total gate charge.
 * @unit nC
 */
#define CSD18533Q5A_GATE_CHARGE_NC (29.0f)

/**
 * @brief Manufacturer package name.
 */
#define CSD18533Q5A_PACKAGE "SON 5x6"

// Logical exports
// voltage_rating: CSD18533Q5A_VOLTAGE_RATING_V
// current_rating: CSD18533Q5A_CURRENT_RATING_A

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _POWER_SWITCH_CSD18533Q5A_H_
