/**
 * @file csd88584q5dc.h
 * @brief SDPE hardware preset for CSD88584Q5DC Half-Bridge Power Block.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _POWER_SWITCH_CSD88584Q5DC_H_
#define _POWER_SWITCH_CSD88584Q5DC_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_csd88584q5dc CSD88584Q5DC Half-Bridge Power Block
 * @{
 */

// Identification
#define CSD88584Q5DC_ID "csd88584q5dc"
#define CSD88584Q5DC_SCHEMA "power_switch"
#define CSD88584Q5DC_NAME "CSD88584Q5DC Half-Bridge Power Block"

// Tags: half_bridge, mosfet, power_block, power_device, switch, ti

/*
 * Schema: Power switch device used by bridge modules.
 * Vendor: Texas Instruments
 * Datasheet: https://www.ti.com/lit/ds/symlink/csd88584q5dc.pdf
 */

// Parameter macros
/**
 * @brief Power device part number.
 */
#ifndef CSD88584Q5DC_PART_NUMBER
#define CSD88584Q5DC_PART_NUMBER "CSD88584Q5DC"
#endif // CSD88584Q5DC_PART_NUMBER

/**
 * @brief MOSFET, IGBT, GaN, SiC, etc.
 */
#ifndef CSD88584Q5DC_DEVICE_TYPE
#define CSD88584Q5DC_DEVICE_TYPE "MOSFET"
#endif // CSD88584Q5DC_DEVICE_TYPE

/**
 * @brief Drain-source or collector-emitter voltage rating.
 * @unit V
 */
#ifndef CSD88584Q5DC_VOLTAGE_RATING_V
#define CSD88584Q5DC_VOLTAGE_RATING_V (40.0f)
#endif // CSD88584Q5DC_VOLTAGE_RATING_V

/**
 * @brief Current rating.
 * @unit A
 */
#ifndef CSD88584Q5DC_CURRENT_RATING_A
#define CSD88584Q5DC_CURRENT_RATING_A (50.0f)
#endif // CSD88584Q5DC_CURRENT_RATING_A

/**
 * @brief On resistance.
 * @unit ohm
 */
#ifndef CSD88584Q5DC_RDSON_OHM
#define CSD88584Q5DC_RDSON_OHM (0.0017f)
#endif // CSD88584Q5DC_RDSON_OHM

/**
 * @brief Single switch, dual switch, half bridge power block, etc.
 */
#ifndef CSD88584Q5DC_CONFIGURATION
#define CSD88584Q5DC_CONFIGURATION "half_bridge_power_block"
#endif // CSD88584Q5DC_CONFIGURATION

/**
 * @brief Maximum on resistance at the documented gate voltage.
 * @unit ohm
 */
#ifndef CSD88584Q5DC_RDSON_MAX_OHM
#define CSD88584Q5DC_RDSON_MAX_OHM (0.0f)
#endif // CSD88584Q5DC_RDSON_MAX_OHM

/**
 * @brief Gate voltage associated with the resistance value.
 * @unit V
 */
#ifndef CSD88584Q5DC_GATE_VOLTAGE_V
#define CSD88584Q5DC_GATE_VOLTAGE_V (10.0f)
#endif // CSD88584Q5DC_GATE_VOLTAGE_V

/**
 * @brief Typical total gate charge.
 * @unit nC
 */
#ifndef CSD88584Q5DC_GATE_CHARGE_NC
#define CSD88584Q5DC_GATE_CHARGE_NC (0.0f)
#endif // CSD88584Q5DC_GATE_CHARGE_NC

/**
 * @brief Manufacturer package name.
 */
#ifndef CSD88584Q5DC_PACKAGE
#define CSD88584Q5DC_PACKAGE "DualCool SON 5x6"
#endif // CSD88584Q5DC_PACKAGE

// Logical exports
// voltage_rating: CSD88584Q5DC_VOLTAGE_RATING_V
// current_rating: CSD88584Q5DC_CURRENT_RATING_A

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _POWER_SWITCH_CSD88584Q5DC_H_
