/**
 * @file stl180n6f7.h
 * @brief SDPE hardware preset for STL180N6F7.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _POWER_SWITCH_STL180N6F7_H_
#define _POWER_SWITCH_STL180N6F7_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_stl180n6f7 STL180N6F7
 * @{
 */

// Identification
#define STL180N6F7_ID "stl180n6f7"
#define STL180N6F7_SCHEMA "power_switch"
#define STL180N6F7_NAME "STL180N6F7"

// Tags: mosfet, power_device, st, switch

/*
 * Schema: Power switch device used by bridge modules.
 * Vendor: STMicroelectronics
 * Datasheet: https://www.st.com/resource/en/datasheet/stl180n6f7.pdf
 */

// Parameter macros
/**
 * @brief Power device part number.
 */
#ifndef STL180N6F7_PART_NUMBER
#define STL180N6F7_PART_NUMBER "STL180N6F7"
#endif // STL180N6F7_PART_NUMBER

/**
 * @brief MOSFET, IGBT, GaN, SiC, etc.
 */
#ifndef STL180N6F7_DEVICE_TYPE
#define STL180N6F7_DEVICE_TYPE "MOSFET"
#endif // STL180N6F7_DEVICE_TYPE

/**
 * @brief Drain-source or collector-emitter voltage rating.
 * @unit V
 */
#ifndef STL180N6F7_VOLTAGE_RATING_V
#define STL180N6F7_VOLTAGE_RATING_V (60.0f)
#endif // STL180N6F7_VOLTAGE_RATING_V

/**
 * @brief Current rating.
 * @unit A
 */
#ifndef STL180N6F7_CURRENT_RATING_A
#define STL180N6F7_CURRENT_RATING_A (120.0f)
#endif // STL180N6F7_CURRENT_RATING_A

/**
 * @brief On resistance.
 * @unit ohm
 */
#ifndef STL180N6F7_RDSON_OHM
#define STL180N6F7_RDSON_OHM (0.0019f)
#endif // STL180N6F7_RDSON_OHM

/**
 * @brief Single switch, dual switch, half bridge power block, etc.
 */
#ifndef STL180N6F7_CONFIGURATION
#define STL180N6F7_CONFIGURATION "single"
#endif // STL180N6F7_CONFIGURATION

/**
 * @brief Maximum on resistance at the documented gate voltage.
 * @unit ohm
 */
#ifndef STL180N6F7_RDSON_MAX_OHM
#define STL180N6F7_RDSON_MAX_OHM (0.0024f)
#endif // STL180N6F7_RDSON_MAX_OHM

/**
 * @brief Gate voltage associated with the resistance value.
 * @unit V
 */
#ifndef STL180N6F7_GATE_VOLTAGE_V
#define STL180N6F7_GATE_VOLTAGE_V (10.0f)
#endif // STL180N6F7_GATE_VOLTAGE_V

/**
 * @brief Typical total gate charge.
 * @unit nC
 */
#ifndef STL180N6F7_GATE_CHARGE_NC
#define STL180N6F7_GATE_CHARGE_NC (79.5f)
#endif // STL180N6F7_GATE_CHARGE_NC

/**
 * @brief Manufacturer package name.
 */
#ifndef STL180N6F7_PACKAGE
#define STL180N6F7_PACKAGE "PowerFLAT 5x6"
#endif // STL180N6F7_PACKAGE

// Logical exports
// voltage_rating: STL180N6F7_VOLTAGE_RATING_V
// current_rating: STL180N6F7_CURRENT_RATING_A

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _POWER_SWITCH_STL180N6F7_H_
