/**
 * @file stl160n10f8.h
 * @brief SDPE hardware preset for STL160N10F8.
 * @details Generated by tools/SDPE_v2. Do not edit generated macros directly.
 */

#ifndef _POWER_SWITCH_STL160N10F8_H_
#define _POWER_SWITCH_STL160N10F8_H_

// User code after includes
// SDPE extension point: add after_includes code in the Entity Instance Code page if needed.

#ifdef __cplusplus
extern "C"
{
#endif

/**
 * @defgroup sdpe_stl160n10f8 STL160N10F8
 * @{
 */

// Identification
#define STL160N10F8_ID "stl160n10f8"
#define STL160N10F8_SCHEMA "power_switch"
#define STL160N10F8_NAME "STL160N10F8"

// Tags: mosfet, power_device, st, switch

/*
 * Schema: Power switch device used by bridge modules.
 * Vendor: STMicroelectronics
 * Datasheet: https://www.st.com/resource/en/datasheet/stl160n10f8.pdf
 */

// Parameter macros
/**
 * @brief Power device part number.
 */
#ifndef STL160N10F8_PART_NUMBER
#define STL160N10F8_PART_NUMBER "STL160N10F8"
#endif // STL160N10F8_PART_NUMBER

/**
 * @brief MOSFET, IGBT, GaN, SiC, etc.
 */
#ifndef STL160N10F8_DEVICE_TYPE
#define STL160N10F8_DEVICE_TYPE "MOSFET"
#endif // STL160N10F8_DEVICE_TYPE

/**
 * @brief Drain-source or collector-emitter voltage rating.
 * @unit V
 */
#ifndef STL160N10F8_VOLTAGE_RATING_V
#define STL160N10F8_VOLTAGE_RATING_V (100.0f)
#endif // STL160N10F8_VOLTAGE_RATING_V

/**
 * @brief Current rating.
 * @unit A
 */
#ifndef STL160N10F8_CURRENT_RATING_A
#define STL160N10F8_CURRENT_RATING_A (158.0f)
#endif // STL160N10F8_CURRENT_RATING_A

/**
 * @brief On resistance.
 * @unit ohm
 */
#ifndef STL160N10F8_RDSON_OHM
#define STL160N10F8_RDSON_OHM (0.0027f)
#endif // STL160N10F8_RDSON_OHM

/**
 * @brief Single switch, dual switch, half bridge power block, etc.
 */
#ifndef STL160N10F8_CONFIGURATION
#define STL160N10F8_CONFIGURATION "single"
#endif // STL160N10F8_CONFIGURATION

/**
 * @brief Maximum on resistance at the documented gate voltage.
 * @unit ohm
 */
#ifndef STL160N10F8_RDSON_MAX_OHM
#define STL160N10F8_RDSON_MAX_OHM (0.0032f)
#endif // STL160N10F8_RDSON_MAX_OHM

/**
 * @brief Gate voltage associated with the resistance value.
 * @unit V
 */
#ifndef STL160N10F8_GATE_VOLTAGE_V
#define STL160N10F8_GATE_VOLTAGE_V (10.0f)
#endif // STL160N10F8_GATE_VOLTAGE_V

/**
 * @brief Typical total gate charge.
 * @unit nC
 */
#ifndef STL160N10F8_GATE_CHARGE_NC
#define STL160N10F8_GATE_CHARGE_NC (0.0f)
#endif // STL160N10F8_GATE_CHARGE_NC

/**
 * @brief Manufacturer package name.
 */
#ifndef STL160N10F8_PACKAGE
#define STL160N10F8_PACKAGE "PowerFLAT 5x6"
#endif // STL160N10F8_PACKAGE

// Logical exports
// voltage_rating: STL160N10F8_VOLTAGE_RATING_V
// current_rating: STL160N10F8_CURRENT_RATING_A

// User code before footer
// SDPE extension point: add before_footer code in the Entity Instance Code page if needed.

/** @} */

#ifdef __cplusplus
}
#endif

#endif // _POWER_SWITCH_STL160N10F8_H_
