"""Generate a fixed-size Eigen C++ circuit class from circuit-data JSON."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Mapping, Sequence

from circuit_data import load_circuit_data


def _identifier(value: str, default: str = "Circuit") -> str:
    result = re.sub(r"[^A-Za-z0-9_]", "_", value).strip("_") or default
    if result[0].isdigit():
        result = "Circuit_" + result
    return result


def _default_class_name(data_path: str | Path, document: Mapping) -> str:
    source_file = document.get("circuit", {}).get("source", {}).get("file")
    stem = Path(source_file).stem if source_file else Path(data_path).stem
    words = re.findall(r"[A-Za-z0-9]+", stem)
    base = "".join(word[:1].upper() + word[1:].lower() for word in words) or "Circuit"
    return _identifier(base + "Circuit")


def _number(value: float) -> str:
    text = format(float(value), ".17g")
    return text if any(char in text for char in ".eE") else text + ".0"


def _cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def _matrix_expression(type_name: str, values: Sequence[Sequence[float]] | Sequence[float]) -> str:
    flattened: list[float] = []
    for item in values:
        if isinstance(item, (list, tuple)):
            flattened.extend(float(value) for value in item)
        else:
            flattened.append(float(item))
    assignments = ", ".join(_number(value) for value in flattened)
    return f"([] {{ {type_name} value; value << {assignments}; return value; }}())"


def _topology_initializer(topology: Mapping) -> str:
    normal = topology["discrete"]["normal"]
    short = topology["discrete"]["short"]
    values = [
        _matrix_expression("StateMatrix", normal["A"]),
        _matrix_expression("InputMatrix", normal["B"]),
        _matrix_expression("StateVector", normal["bias"]),
        _matrix_expression("StateMatrix", short["A"]),
        _matrix_expression("InputMatrix", short["B"]),
        _matrix_expression("StateVector", short["bias"]),
        _matrix_expression("SignalMatrix", normal["C"]),
        _matrix_expression("SignalInputMatrix", normal["D"]),
        _matrix_expression("SignalVector", normal["output_bias"]),
    ]
    return "Topology{\n                " + ",\n                ".join(values) + "\n            }"


def render_header(document: Mapping, class_name: str) -> str:
    state_count = len(document["state"]["names"])
    signal_count = len(document["signals"]["names"])
    input_ports = [port for port in document["ports"]["inputs"] if port["data_type"] == "double"]
    outputs = document["ports"]["outputs"]
    input_count = len(input_ports)
    switching = document["switching"]
    terminal = document["signals"]["switch_terminal_indices"]
    input_fields = [_identifier(port["name"], "input") for port in input_ports]
    output_fields = [_identifier(port["field"], "output") for port in outputs]
    topology_values = ",\n            ".join(_topology_initializer(item) for item in document["topologies"])
    input_vector = ", ".join(f"inputs.{name}" for name in input_fields)
    input_parameters = ", ".join(f"double {name}" for name in input_fields)
    input_arguments = ", ".join(input_fields)
    output_updates = "\n".join(
        f"        output.{field} = signals_({port['signal_index']});"
        for field, port in zip(output_fields, outputs)
    )
    output_members = "\n".join(f"        double {field}{{0.0}};" for field in output_fields)
    output_lookup = "\n".join(
        f"            if (name == {_cpp_string(port['name'])} || name == {_cpp_string(field)}) return {field};"
        for field, port in zip(output_fields, outputs)
    )
    input_members = "\n".join(
        f"        double {field}{{{_number(port['default'])}}};"
        for field, port in zip(input_fields, input_ports)
    )
    default_arguments = ", ".join(_number(port["default"]) for port in input_ports)
    source_name = document["circuit"]["source"].get("file") or "<unknown>"
    source_hash = document["circuit"]["source"].get("sha256") or "<unknown>"
    return f'''#pragma once

// Generated by GMP mna_solver/cpp_codegen.py from {source_name}.
// Source SHA-256: {source_hash}
// Do not hand-edit; regenerate from the circuit-data JSON file.

#include <Eigen/Dense>

#include <array>
#include <cstddef>
#include <cstdint>
#include <stdexcept>
#include <string>
#include <string_view>

class {class_name} {{
public:
    static constexpr std::size_t state_count = {state_count};
    static constexpr std::size_t signal_count = {signal_count};
    static constexpr std::size_t analog_input_count = {input_count};
    static constexpr double normal_step_s = {_number(document['solver']['normal_step_s'])};
    static constexpr double short_step_s = {_number(document['solver']['short_step_s'])};

    struct Inputs {{
        std::uint32_t PWM{{0U}};
{input_members}
    }};

    struct Outputs {{
{output_members}

        double operator[](std::string_view name) const {{
{output_lookup}
            throw std::out_of_range("unknown circuit output: " + std::string(name));
        }}
    }};

    Outputs output{{}};

    {class_name}() {{ reset(); }}

    void reset() {{
        state_.setZero();
        signals_.setZero();
        diode_on_ = false;
        body_on_ = false;
        last_topology_index_ = 0;
        output = Outputs{{}};
    }}

    const Outputs& step_short(const Inputs& inputs) {{ return step(inputs, true); }}
    const Outputs& step_normal(const Inputs& inputs) {{ return step(inputs, false); }}

    const Outputs& step_short(std::uint32_t PWM, {input_parameters}) {{
        return step_short(Inputs{{PWM, {input_arguments}}});
    }}

    const Outputs& step_normal(std::uint32_t PWM, {input_parameters}) {{
        return step_normal(Inputs{{PWM, {input_arguments}}});
    }}

    const Outputs& run(std::uint32_t PWM, {input_parameters}) {{
        return step_normal(PWM, {input_arguments});
    }}

    const Outputs& operator()(std::uint32_t PWM, {input_parameters}) {{
        return run(PWM, {input_arguments});
    }}

    double operator[](std::string_view name) const {{ return output[name]; }}
    const auto& state() const noexcept {{ return state_; }}
    std::size_t last_topology_index() const noexcept {{ return last_topology_index_; }}

private:
    using StateMatrix = Eigen::Matrix<double, {state_count}, {state_count}>;
    using InputMatrix = Eigen::Matrix<double, {state_count}, {input_count}>;
    using StateVector = Eigen::Matrix<double, {state_count}, 1>;
    using SignalMatrix = Eigen::Matrix<double, {signal_count}, {state_count}>;
    using SignalInputMatrix = Eigen::Matrix<double, {signal_count}, {input_count}>;
    using SignalVector = Eigen::Matrix<double, {signal_count}, 1>;
    using InputVector = Eigen::Matrix<double, {input_count}, 1>;

    struct Topology {{
        StateMatrix normal_A;
        InputMatrix normal_B;
        StateVector normal_bias;
        StateMatrix short_A;
        InputMatrix short_B;
        StateVector short_bias;
        SignalMatrix C;
        SignalInputMatrix D;
        SignalVector output_bias;
    }};

    static const std::array<Topology, 6>& topologies() {{
        static const std::array<Topology, 6> value{{{{
            {topology_values}
        }}}};
        return value;
    }}

    std::size_t select_topology(std::uint32_t PWM) {{
        const double diode_voltage = signals_({terminal['diode_anode']}) - signals_({terminal['diode_cathode']});
        const double reverse_mosfet_voltage = signals_({terminal['mosfet_source']}) - signals_({terminal['mosfet_drain']});
        constexpr double hysteresis = {_number(switching['voltage_hysteresis_V'])};
        constexpr double diode_threshold = {_number(switching['diode_forward_threshold_V'])};
        constexpr double body_threshold = {_number(switching['body_forward_threshold_V'])};
        diode_on_ = diode_voltage >= diode_threshold + (diode_on_ ? -hysteresis : hysteresis);
        std::size_t path = 0;
        if (PWM != 0U) {{
            body_on_ = false;
            path = 1;
        }} else {{
            body_on_ = reverse_mosfet_voltage >= body_threshold + (body_on_ ? -hysteresis : hysteresis);
            path = body_on_ ? 2 : 0;
        }}
        return (diode_on_ ? 3U : 0U) + path;
    }}

    const Outputs& step(const Inputs& inputs, bool use_short_step) {{
        last_topology_index_ = select_topology(inputs.PWM);
        const auto& topology = topologies()[last_topology_index_];
        InputVector input_vector;
        input_vector << {input_vector};
        if (use_short_step) {{
            state_ = topology.short_A * state_ + topology.short_B * input_vector + topology.short_bias;
        }} else {{
            state_ = topology.normal_A * state_ + topology.normal_B * input_vector + topology.normal_bias;
        }}
        signals_ = topology.C * state_ + topology.D * input_vector + topology.output_bias;
{output_updates}
        return output;
    }}

    StateVector state_{{StateVector::Zero()}};
    SignalVector signals_{{SignalVector::Zero()}};
    bool diode_on_{{false}};
    bool body_on_{{false}};
    std::size_t last_topology_index_{{0}};
}};
'''


def render_testbench(document: Mapping, class_name: str, header_name: str) -> str:
    analog = [port for port in document["ports"]["inputs"] if port["data_type"] == "double"]
    if len(analog) != 1:
        raise ValueError("the generated reference testbench currently requires exactly one analog input")
    outputs = document["ports"]["outputs"]
    if not outputs:
        raise ValueError("the generated reference testbench requires at least one probe output")
    measured = next((port for port in outputs if port["name"].upper().startswith("V(")), outputs[0])
    measured_field = _identifier(measured["field"], "output")
    output_header = ",".join(port["name"] for port in outputs)
    output_values = " << ',' << ".join(
        f"output.{_identifier(port['field'], 'output')}" for port in outputs
    )
    source_file = document["circuit"]["source"].get("file") or class_name
    csv_stem = _identifier(Path(source_file).stem, "circuit").lower()
    supply = _number(analog[0]["default"])
    normal_dt = _number(document["solver"]["normal_step_s"])
    short_dt = _number(document["solver"]["short_step_s"])
    return f'''#include "{header_name}"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>

int main() {{
    {class_name} circuit;
    constexpr double supply = {supply};
    constexpr double pwm_frequency = 10000.0;
    constexpr double duty = 0.5;
    constexpr double duration = 0.05;
    constexpr double normal_dt = {normal_dt};
    constexpr double short_dt = {short_dt};
    constexpr std::size_t startup_short_steps = 200;
    constexpr std::size_t normal_steps = static_cast<std::size_t>(duration / normal_dt);
    const double period = 1.0 / pwm_frequency;

    double startup_time = 0.0;
    for (std::size_t index = 0; index < startup_short_steps; ++index) {{
        const std::uint32_t pwm = std::fmod(startup_time, period) < duty * period ? 1U : 0U;
        circuit.step_short(pwm, supply);
        startup_time += short_dt;
    }}

    std::ofstream csv("{csv_stem}_cpp_50pct.csv");
    if (!csv) {{
        std::cerr << "cannot create {csv_stem}_cpp_50pct.csv\\n";
        return 2;
    }}
    csv << "time_s,PWM,{output_header},topology_index\\n";
    csv << std::setprecision(17);
    double tail_sum = 0.0;
    double tail_min = std::numeric_limits<double>::infinity();
    double tail_max = -std::numeric_limits<double>::infinity();
    std::size_t tail_count = 0;
    for (std::size_t index = 0; index < normal_steps; ++index) {{
        const double time = static_cast<double>(index) * normal_dt;
        const std::uint32_t pwm = std::fmod(time, period) < duty * period ? 1U : 0U;
        const auto& output = circuit(pwm, supply);
        if (index % 100U == 0U || index + 1U == normal_steps) {{
            csv << time + normal_dt << ',' << pwm << ',' << {output_values} << ','
                << circuit.last_topology_index() << '\\n';
        }}
        if (index >= normal_steps * 9U / 10U) {{
            tail_sum += output.{measured_field};
            tail_min = std::min(tail_min, output.{measured_field});
            tail_max = std::max(tail_max, output.{measured_field});
            ++tail_count;
        }}
    }}
    const double mean = tail_sum / static_cast<double>(tail_count);
    std::cout << std::setprecision(12)
              << "50% PWM tail mean={measured['name']}: " << mean
              << ", min=" << tail_min << ", max=" << tail_max << '\\n';
    std::cout << "string access {measured['name']}=" << circuit[{_cpp_string(measured['name'])}] << '\\n';
    if (!std::isfinite(mean) || mean <= 0.0) {{
        std::cerr << "Circuit output is not finite and positive\\n";
        return 3;
    }}
    return 0;
}}
'''


def render_cmake(class_name: str) -> str:
    target = _identifier(class_name.lower() + "_testbench")
    return f'''cmake_minimum_required(VERSION 3.21)
project(gmp_generated_{target} LANGUAGES CXX)

find_package(Eigen3 CONFIG REQUIRED)

add_executable({target} {target}.cpp)
target_compile_features({target} PRIVATE cxx_std_17)
target_link_libraries({target} PRIVATE Eigen3::Eigen)

enable_testing()
add_test(NAME {target} COMMAND {target})
'''


def generate_cpp_project(data_path: str | Path, output_directory: str | Path, class_name: str | None = None) -> dict[str, Path]:
    document = load_circuit_data(data_path)
    selected_class = _identifier(class_name) if class_name else _default_class_name(data_path, document)
    stem = _identifier(selected_class.lower())
    output = Path(output_directory)
    output.mkdir(parents=True, exist_ok=True)
    header = output / f"{stem}.hpp"
    testbench = output / f"{stem}_testbench.cpp"
    cmake = output / "CMakeLists.txt"
    vcpkg = output / "vcpkg.json"
    header.write_text(render_header(document, selected_class), encoding="utf-8")
    testbench.write_text(render_testbench(document, selected_class, header.name), encoding="utf-8")
    cmake.write_text(render_cmake(selected_class), encoding="utf-8")
    vcpkg.write_text(
        json.dumps(
            {"name": f"gmp-generated-{stem.lower()}", "version-string": "1.0.0", "dependencies": ["eigen3"]},
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return {"header": header, "testbench": testbench, "cmake": cmake, "vcpkg": vcpkg}


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate an Eigen C++ circuit class")
    parser.add_argument("data")
    parser.add_argument("output_directory")
    parser.add_argument("--class-name")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        generated = generate_cpp_project(args.data, args.output_directory, args.class_name)
        for kind, path in generated.items():
            print(f"{kind}: {path}")
    except (OSError, ValueError, KeyError) as error:
        print(f"error: {error}")
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
